Gemfile.lock, app/helpers/playbook/pb_kit_helper.rb, lib/playbook/version.rb, package.json
While adding `playbook_ui` into Nitro, @markiearnold @jasperfurniss and I ran into an `ActionView::MissingTemplate` error. Here is the full message:
```
ActionView::MissingTemplate at /
Missing partial dev_docs/pb_caption/_caption with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :slim, :coffee, :prawn, :prawn_dsl]}. Searched in:
* "/Users/garettarrowood/Power/nitro-web/components/ux_prototypes/app/views"
* "/Users/garettarrowood/Power/nitro-web/components/user_profile/app/views"
* "/Users/garettarrowood/Power/nitro-web/components/travel/app/views"
* "/Users/garettarrowood/Power/nitro-web/components/talkbox_client/app/views"
* "/Users/garettarrowood/Power/nitro-web/components/support/app/views"
* …
```
=> Look for playbook partials outside of controller namespace

package.json
Storybook is named `nitro_sg` as a Ruby gem, and `nitro-sg` as a npm package.
Playbook is named `playbook_ui` as a Ruby gem, and this change will make it `playbook-ui` as a npm package.
No version raise is necessary. The first release as a npm package will match its version as a Ruby gem.
=> Consistent name for Playbook library in npm & rubygems

Gemfile.lock, lib/playbook/version.rb, package.json
TLDR: I had to bump to a minor version because of an accidental gem push from my own branch, instead of Master. That resulted in me "gem yanking" the version from the ruby gems registry, which in turn meant needing to cut a new version.
=> Bumped Minor Version

lib/generators/kit/kit_generator.rb, lib/generators/kit/templates/kit_ruby.erb.tt
Before this change, generating a rails kit came with 16 rubocop offenses. After this change, a newly generated kit comes with 0 rubocop offenses.
=> Update generators to adhere to rubocop

Dockerfile, docker-compose.yml
Prevent common errors when running Playbook locally
Addresses 2 common errors defined in [Common Errors & Solutions](https://github.com/powerhome/playbook/wiki/Common-Errors-&-Solutions)
* Already running server.pid
* Node-sass bindings
=> Prevent common errors when running Playbook locally

app/pb_kits/playbook/packs/application.js, app/pb_kits/playbook/packs/pb_image.js, app/pb_kits/playbook/pb_dashboard/pbChartsLightTheme.js, app/pb_kits/playbook/plugins/pb_chart_plugin.js, app/pb_kits/playbook/vendor.js, app/views/layouts/playbook/application.html.slim, package.json, yarn.lock
This adds `vendor.js` which is to be consumed the same way in PB as in PG and Nitro. 
Lib tree in vendor:
- lazysizes
- pb_chart_plugin.js
- Highcharts
=> Create vendor.js for exporting 

app/pb_kits/playbook/pb_table/styles/_structure.scss
Fix for [Issue #111](https://github.com/powerhome/playbook/issues/111)
For all table sizes, the table header should be medium.
=> BUG FIX: All table headers should be medium size

app/pb_kits/playbook/pb_title_count/_title_count.scss, app/pb_kits/playbook/pb_title_count/title_count.rb
Changes:
* Adds missing space between title and count
Resolves Issue #242
=> Bug: Title Count spacing

app/pb_kits/playbook/pb_toggle/_toggle.html.erb, app/pb_kits/playbook/pb_toggle/docs/_toggle_custom.html.erb, app/pb_kits/playbook/pb_toggle/docs/_toggle_custom_radio.html.erb, app/pb_kits/playbook/pb_toggle/docs/_toggle_name.html.erb, app/pb_kits/playbook/pb_toggle/docs/example.yml, app/pb_kits/playbook/pb_toggle/toggle.rb
Allow Toggle to accept custom inputs through the block syntax
**Custom checkbox**
```erb
<%= pb_rails("toggle", props: { size: "sm" }) do %>
<input class="my_custom_input" type="checkbox" name="custom_checkbox" value="ABC" />
<% end %>
```
**Custom radio**
```erb
<%= pb_rails("toggle", props: { size: "sm" }) do %>
<input type="radio" name="gender" value="male">
<% end %>
```
---
Or allow for default functionality of a checkbox input, but just passing in `name`, `value` and `checked`
```erb
<%= pb_rails("toggle", props: {
size: "sm",
checked: false,
name: "vehicle",
value: "car"
}) %>
```
---
=> Enhance Toggle to accept custom inputs

app/pb_kits/playbook/pb_date/date.rb, app/pb_kits/playbook/pb_date/docs/_date_default.html.erb
Allow for date to have optional icon.
Currently date has 2 sizes (lg, sm).  I added xs for the non-icon version. This is now consistent with the Time kit.
=> Enhance Date optional icon

app/pb_kits/playbook/pb_pill/_pill.jsx, app/pb_kits/playbook/pb_pill/_pill.scss, app/pb_kits/playbook/pb_pill/pill.rb
Changes include
* Pill to use Title 4 instead of Body (bold text)
* Updated Pill react kit syntax
---
=> Enhance Pill font weight

app/pb_kits/playbook/pb_date/date.rb, app/pb_kits/playbook/pb_date/docs/_date_default.html.erb, app/pb_kits/playbook/pb_kit/pb_date_time.rb, app/pb_kits/playbook/pb_time/docs/_time_default.html.erb, app/pb_kits/playbook/pb_time/docs/_time_timestamp.html.erb, app/pb_kits/playbook/pb_time/time.rb
Changes include:
* Extract all date related methods to its own class PbDateTime
* Update both Date and Time kits to use PbDateTime class
* Update Date Kit to accept prop `date` instead of `timestamp` (Both are available, but date is documented)
* Update Time Kit to accept prop `time` instead of `timestamp` (Both are available, but time is documented)
---
`timezone` arg is optional.  It allows the stored date or time passed in to be converted and displayed to a different timezone.  Timezone defaults to Eastern (America/New_York)
```ruby
date = Playbook::PbKit::PbDateTime.new(date, timezone)
date.to_day_of_week  # thu
date.to_day  # 2
```
```ruby
time = Playbook::PbKit::PbDateTime.new(time, timezone)
time.to_hour  # 11
time.to_meridian  # p
time.to_timeszone  # edt
```
=> PbDateTime Class

Dockerfile
Fix from [this](https://github.com/sass/node-sass/issues/1918) issue.
Suggested running `npm rebuild node-sass` within DockerFile **after** `yarn install`.
The first attempted fix in Playbook was incorrectly running this before `yarn install`, which did not fix the problem.
---
Unknown if this should use the force option: `npm rebuild node-sass --force`
=> Node-sass bugfix

app/pb_kits/playbook/pb_caption/caption.rb, app/pb_kits/playbook/pb_checkbox/_checkbox.html.erb, app/pb_kits/playbook/pb_checkbox/checkbox.rb, app/pb_kits/playbook/pb_checkbox/docs/_checkbox_checked.html.erb, app/pb_kits/playbook/pb_checkbox/docs/_checkbox_dark.html.erb, app/pb_kits/playbook/pb_checkbox/docs/_checkbox_default.html.erb, app/pb_kits/playbook/pb_checkbox/docs/_checkbox_default.jsx, app/pb_kits/playbook/pb_checkbox/docs/example.yml, app/pb_kits/playbook/props.rb, spec/pb_kits/playbook/kits/caption_spec.rb, spec/pb_kits/playbook/kits/checkbox_spec.rb, spec/pb_kits/playbook/props_spec.rb, spec/support/playbook/rspec.rb
1. Migrate Checkbox Kit to new format
1. Add a checked example to the docs.
1. Adjust base classname default (see change in test expectation in `caption_spec.rb`).
1. Add more custom matchers.
1. Add `partial` helper method.
1. Add `generate_classname` helper method.
=> Migrate Checkbox Kit

app/pb_kits/playbook/pb_card/_card.html.erb, app/pb_kits/playbook/pb_card/card.rb, app/pb_kits/playbook/pb_card/card_body.rb, app/pb_kits/playbook/pb_card/child_kits/_card_body.html.erb, app/pb_kits/playbook/props.rb, app/pb_kits/playbook/props/enum.rb, spec/pb_kits/playbook/kits/caption_spec.rb, spec/pb_kits/playbook/kits/card_body_spec.rb, spec/pb_kits/playbook/kits/card_spec.rb, spec/pb_kits/playbook/kits/checkbox_spec.rb, spec/pb_kits/playbook/props_spec.rb, spec/support/playbook/rspec.rb
1. Migrate `card` kit and `card_body` subkit.
1. Extend base initialization of kit to capture a `block` if yielded one.
1. Add `#with_values` matcher for `Enum` prop assertions.
=> Migrate card kit

app/pb_kits/playbook/pb_distribution_bar/_distribution_bar.html.erb, app/pb_kits/playbook/pb_distribution_bar/_distribution_bar.jsx, app/pb_kits/playbook/pb_distribution_bar/_distribution_bar.scss, app/pb_kits/playbook/pb_distribution_bar/distribution_bar.rb, app/pb_kits/playbook/pb_distribution_bar/docs/_distribution_bar_default.html.erb, app/pb_kits/playbook/pb_distribution_bar/docs/_distribution_bar_default.jsx, app/pb_kits/playbook/props.rb, app/pb_kits/playbook/props/number_array.rb, spec/pb_kits/playbook/kits/distribution_bar_spec.rb, spec/pb_kits/playbook/props/number_array_spec.rb
Modernize the distribution bar kit and add spec file.
When trying to find what `values` represents dug deeper to see that it represents the `widths` which is a array of numbers. Also the distribution bar kit has not been used in Nitro anywhere, so we changed prop to a name that makes more sense. Also added the number array type.
=> modernize playbook distribution bar kit

config/webpack/environment.js, config/webpack/loaders/fast-sass-loader.js, package.json, yarn.lock
Currently, in both Playbook and Nitro-Web, CSS declarations relating to kits are duplicated `n` times for each kit. This is very bad bloat and an artifact of the `sass-loader` webpack loader.  
`fast-sass-loader` solves this by de-duping simply by using the loader in place of `sass-loader`. A slight compilation speed-up can also be noted.
=> Swap sass-loader for fast-sass-loader to de-dupe CSS declarations

app/pb_kits/playbook/index.js, app/pb_kits/playbook/pb_bar_graph/barGraphSettings.js, app/pb_kits/playbook/pb_dashboard/commonSettings.js, app/pb_kits/playbook/pb_line_graph/lineGraphSettings.js
This adds `dataColors` as a main export in `index.js` for use in Nitro (and beyond). Currently affects any graph that uses data colors. Color order was changed per https://github.com/powerhome/playbook/pull/349
=> Allow re-ordered data colors export

app/pb_kits/playbook/props.rb, spec/pb_kits/playbook/props_spec.rb
Some kits do not connect each part of their unique classnames with an underscore (the default), and instead use whitespace. This addition allows `#generate_classname` to take a custom `separator`. It also adds some test support to this method which demonstrates its functionality.
=> Allow Props#generate_classname to take a custom delimiter

spec/pb_kits/playbook/props_spec.rb, spec/support/playbook/rspec.rb
When this matcher is used on a `string_prop` that is not required:
```
1) Playbook::Props required props should define string prop :required_prop that is required
Failure/Error: it { is_expected.to define_string_prop(:test_prop).that_is_required }
expected test_prop to be required
```
When this matcher is used on a `prop` that is not required:
```
1) Playbook::Props required props should define string prop :required_prop that is required
Failure/Error: it { is_expected.to define_prop(:test_prop).that_is_required }
expected test_prop to be required
```
=> Add required custom matcher

app/pb_kits/playbook/pb_label_pill/label_pill.rb
The Label Pill kit was using the pill kit in it and it was being passed an empty string for the variant, which broke the code. We passed it neutral as the default which fixed the issue.
=> Fix bug where variant was passed an empty string

app/pb_kits/playbook/pb_home_address_street/_home_address_street.html.erb, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_dark.html.erb, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_default.html.erb, app/pb_kits/playbook/pb_home_address_street/home_address_street.rb
Currently, if house_style is left blank, it will not appear which is what we want; however, the dash between street and house_style will still appear. Step one is to make this dash dependent on existence of house_style. Dark mode is nil, showing no dash or house_style, while light mode is standard with Col style present, separated by a dash. 
Second, our addresses do not have a prop for a second address line such as an apartment number, which exists in Nitro. We want this to only appear with the existence of a second address line, otherwise there should be no white space. This is opposite, with light mode showing nil for second address line, to show no extra white space; Dark mode is set with the value "Apt M18" to show a second address line present.
=> Create Optional House Style and Second Address Line for Home Address Street Playbook kit

app/pb_kits/playbook/pb_home_address_street/_home_address_street.html.erb, app/pb_kits/playbook/pb_home_address_street/_home_address_street.jsx, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_dark.html.erb, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_dark.jsx, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_default.html.erb, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_default.jsx, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_modified.html.erb, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_modified.jsx, app/pb_kits/playbook/pb_home_address_street/docs/example.yml, app/pb_kits/playbook/pb_home_address_street/docs/index.js, app/pb_kits/playbook/pb_home_address_street/home_address_street.rb
Originally, the zipcode was an accepted prop that was not displayed anywhere in the kit. Also the territory was not an accepted prop, and the position the territory would take was filled in by the state. In Nitro there is a difference between state and territory (example: Delaware state is PHL territory) so prop added and also displayed. 
This was the original pbkit without Zip or proper territory:
Compared to old Nitro with correct fields: 
This is the new kit with proper values and displays:
=> Show Zipcode and Add Territory to Home Address Street Playbook

app/pb_kits/playbook/pb_icon_value/_icon_value.html.erb, app/pb_kits/playbook/pb_icon_value/icon_value.rb, spec/pb_kits/playbook/kits/icon_value_spec.rb
Modernizes the Icon Value kit, also makes the icon and text within required. Adds a spec to the kit as well.
=> Modernize Icon Value pbkit

app/pb_kits/playbook/pb_dashboard_value/docs/_dashboard_value_align.html.erb, app/pb_kits/playbook/pb_dashboard_value/docs/_dashboard_value_default.html.erb, app/pb_kits/playbook/pb_stat_value/_stat_value.html.erb, app/pb_kits/playbook/pb_stat_value/docs/_stat_value_unit.html.erb, app/pb_kits/playbook/pb_stat_value/stat_value.rb, spec/pb_kits/playbook/kits/stat_value_spec.rb
Common modernization to the Stat Value kit to match our current formatting.
Additional Information:
This kit originally accepted strings or integers where it was displaying values. The values were always an integer, but it was formatted this way in the examples if the end user typed in a string. To better stream line, we made the prop always a number, however this may effect previous uses that contained strings. With that in mind, we should watch any previous Stat Value pbkit or Dashboard Value kit (which inherits Stat Value in it) for backwards compatibility issues. It will be an easy fix of adjusting the value to an integer.
=> Modernize Stat Value Playbook Kit

app/pb_kits/playbook/pb_icon/_icon.html.erb, app/pb_kits/playbook/pb_icon/icon.rb, spec/pb_kits/playbook/kits/icon_spec.rb, spec/support/playbook/rspec.rb
Modernize Icon kit to match new formatting
Additional Information:
Commit 5d69785 adjusts the Enum specs to coerce array into strings for comparison. This allows the default to be nil.
=> Modernize Icon Playbook Kit

app/pb_kits/playbook/pb_date_range_inline/_date_range_inline.html.erb, app/pb_kits/playbook/pb_date_range_inline/date_range_inline.rb, app/pb_kits/playbook/props.rb, app/pb_kits/playbook/props/date.rb, spec/pb_kits/playbook/kits/date_range_inline_spec.rb, spec/pb_kits/playbook/props/date_spec.rb, spec/spec_helper.rb
Modernizes the DateRangeInline kit to our new method. 
Additional information:
Also adds a Date prop to playbook.
=> Modernize DateRangeInline Playbook kit

app/pb_kits/playbook/pb_home_address_street/_home_address_street.html.erb, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_modified.html.erb, app/pb_kits/playbook/pb_home_address_street/home_address_street.rb
Currently if a Home Address Street kit was not passed an home_id, a bubble would still appear with H#. This wraps that prop in a conditional that will only display if home_id is not nil. If no home_id is passed, territory will simply fill the space. 
Additional information:
The H# is currently not using the Hashtag kit, but instead a badge kit. I made an initial attempt to migrate this to the Hashtag kit so we dont have to hardcode "H#" before the home_id, however the Hashtag kit requires a url prop taking this out of the scope of this card. This is something I will bring up to Garett as a possibly follow up card.
=> Adjust HomeAddressStreet kit to have optional H#

app/pb_kits/playbook/pb_contact/_contact.html.erb, app/pb_kits/playbook/pb_contact/_contact.jsx, app/pb_kits/playbook/pb_contact/contact.rb, app/pb_kits/playbook/pb_contact/docs/_contact_default.html.erb, app/pb_kits/playbook/pb_contact/docs/_contact_default.jsx, app/pb_kits/playbook/pb_person_contact/_person_contact.html.erb, app/pb_kits/playbook/pb_person_contact/_person_contact.jsx, app/pb_kits/playbook/pb_person_contact/docs/_person_contact_default.html.erb, app/pb_kits/playbook/pb_person_contact/docs/_person_contact_default.jsx, app/pb_kits/playbook/pb_person_contact/docs/_person_contact_single_person.html.erb, app/pb_kits/playbook/pb_person_contact/docs/_person_contact_single_person.jsx, spec/pb_kits/playbook/kits/contact_spec.rb
Added a new prop to contact kit so we can show who's contact info the specific entries belong to. ex: John's Cell, Home, Pauline's Work.
=> Add contact_details prop to contact kit

app/pb_kits/playbook/pb_dashboard_value/_dashboard_value.html.erb, app/pb_kits/playbook/pb_dashboard_value/_dashboard_value.jsx, app/pb_kits/playbook/pb_dashboard_value/dashboard_value.rb, app/pb_kits/playbook/pb_dashboard_value/docs/_dashboard_value_align.html.erb, app/pb_kits/playbook/pb_dashboard_value/docs/_dashboard_value_align.jsx, app/pb_kits/playbook/pb_dashboard_value/docs/_dashboard_value_default.html.erb, app/pb_kits/playbook/pb_dashboard_value/docs/_dashboard_value_default.jsx, spec/pb_kits/playbook/kits/dashboard_value_spec.rb
BAB-181: Modernize DashboardValue Playbook Kit
Note: This modernization changes the prop type of `:stat_label` in rails from a hash `stat_label: { label: "This is the label" }` to a string `stat_label: "This is the label"`. 
Backwards breaking changes: 
components/dev_docs/app/views/dev_docs/playbook/index.html.erb
components/solar_roofing/app/views/solar_roofing/solar_proposals/_overview.html.erb
=> Modernize dashboard value

app/pb_kits/playbook/pb_toggle/_toggle.jsx
https://github.com/powerhome/playbook/blob/master/app/pb_kits/playbook/pb_toggle/_toggle.jsx#L34
refs:
https://stackoverflow.com/questions/54282836/object-rest-spread-is-not-allowed-trailing-commas-in-babel-7
https://github.com/tc39/proposal-object-rest-spread/issues/47
=> Fix object rest syntax error

app/pb_kits/playbook/pb_home_address_street/_home_address_street.jsx, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_dark.html.erb, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_dark.jsx, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_default.jsx, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_modified.jsx, app/pb_kits/playbook/pb_home_address_street/home_address_street.rb, app/pb_kits/playbook/utilities/text.js
This will titleize the Address and City props.
Additional Information:
I had only placed a safety navigator on the address_cont since this is the only field that needs to be titleized but also optional. Street and City will always exist.
=> Titleize Home Address Street Playbook Kit

app/pb_kits/playbook/pb_card/_card.jsx, app/pb_kits/playbook/pb_card/_card.scss, app/pb_kits/playbook/pb_card/card.rb, app/pb_kits/playbook/pb_card/docs/_card_highlight.jsx, app/pb_kits/playbook/pb_card/docs/example.yml, app/pb_kits/playbook/pb_card/docs/index.js, spec/pb_kits/playbook/kits/card_spec.rb
Changes:
* Added highlight prop to react kit
* Extended React Card kit to take a custom classname
---
* Updated SCSS to use pseudo element instead of border for highlight
---
* Updated docs to make consistent between Rails and React
---
* Updated Card Spec test to account for new highlight prop, as well as class name changes highlight adds
=> Card Highlight - Support Branch

app/pb_kits/playbook/packs/site_styles/docs/_color_utilities.scss, app/pb_kits/playbook/tokens/_colors.scss, app/views/playbook/pages/utilities.html.slim
Changes to the view: [https://playbook.powerapp.cloud/utilities](https://playbook.powerapp.cloud/utilities)
* Primary Action color was broken
* Data colors was missing `$data_8`
* Dark Card color was missing `dark: true` for the color to be visible
=> Update Color Utility View

app/pb_kits/playbook/pb_dashboard_value/_dashboard_value.jsx, app/pb_kits/playbook/pb_dashboard_value/docs/_dashboard_value_align.jsx, app/pb_kits/playbook/pb_dashboard_value/docs/_dashboard_value_default.jsx
- Removes props with `_` in `DashboardValue kit
- tested in Nitro to ensure label appears for React version
=> Fix underscored DashboardValue

Dockerfile
Adds the same node [binding found for Huddle](https://github.com/powerhome/huddle/pull/101), which resolves error between different OS versions in Docker env.
=> Add node binding for node-sass

Jenkinsfile
Uses `ci-kubed` to set the image ready status check.
=> [GOG-24] Sets image ready build status for milano compatibility

Gemfile
Make sure that simple form will be available in the production mode
of the playbook web app. This is needed so we can show the example of
how to use playbook with simple form. The previous code only had a
development dependency defined in the gemspec, moving this to the
Gemfile will make it available in the production web app.
=> Fix form kit dependencies

app/pb_kits/playbook/pb_stat_value/_stat_value.html.erb, app/pb_kits/playbook/pb_stat_value/stat_value.rb
This PR adds [`number_with_delimiter`](https://api.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html#M001972) to `stat_value` Rails kit so that `5567` is always represented as `5,567`
=> Use number_with_delimiter for stat_value.value

package.json
The eslint version used here depends on a newer version of node when comparing to nitro-web.
Moving this dep to the `devDependencies` is a short term solution to allow playbook_ui to be used with nitro-web.
Long term solution should be to upgrade nitro node version since [it's not gonna be supported anymore](https://nodejs.org/en/about/releases/).
We tested this pointing my nitro-web to my playbook on my local machine and it worked fine. Is there any other test I should do?
=> Eslint is a dev dependency

app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_dark.html.erb, app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_dark.jsx
There was bug found in the code example of Selectable Card Kit. In the dark versions of both Rails and React, when the disabled card is clicked, it would make the adjacent card turn off or on. This was due to having the same name for both cards in the code example when they should've been different.
To fix this bug, the input_id, name, and value were changed so that the clicking would be affecting the correct card.
=> Selectable Card Kit Bug - Error in Code Example

CHANGELOG.md, app/pb_kits/playbook/pb_contact/contact.rb, app/pb_kits/playbook/pb_person_contact/_person_contact.html.erb, app/pb_kits/playbook/pb_person_contact/_person_contact.scss, app/pb_kits/playbook/pb_person_contact/docs/_person_contact_with_wrong_numbers.html.erb, app/pb_kits/playbook/pb_person_contact/docs/example.yml, app/pb_kits/playbook/pb_person_contact/person_contact.rb, spec/pb_kits/playbook/kits/contact_spec.rb
Currently, the kit wasn't displaying the wrong number caption, wasn't arranging the contacts with valid contacts above incorrect contacts, nor documenting this functionality in the kit. 
This PR adds that documentation referenced above, it detects valid contacts, then displays them above a wrong number caption and displays the wrong numbers beneath with the correct icon. 
**This in no way is a backward breaking change to the Nitro repo, as it isn't implemented there yet.**
=> Display wrong contacts correctly

lib/tasks/pb_release.rake
Upon running the command `bin/rails app:pb_release:version` you will now see:
=> Update `pb_release:version` task to include confirmation and versioning info

CHANGELOG.md, app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb, app/pb_kits/playbook/pb_form/docs/_form_simple_form.html.erb, app/pb_kits/playbook/pb_form/form_builder.rb, app/pb_kits/playbook/pb_form/form_builder/form_field_builder.rb, app/pb_kits/playbook/pb_text_input/_text_input.html.erb, app/pb_kits/playbook/pb_text_input/_text_input.scss
Tickets: [BOP-309]
Extend the form builder for the form kit to add in a text area.
Previously the form builder used the default text area method provided
by ActionView::Helpers::FormBuilder and SimpleForm::FormBuilder. This
new version uses the text area element built buy these implementations,
but wraps them using the pb_textarea kit.
Generalize the text input builder to allow a kit name to be passed in.
This allows us to reuse the builder for the text_area field as well as
the existing text type inputs fields.
**Form With Example**
**Simple Form Example**
=> Add textarea kit to form kit

CHANGELOG.md, app/pb_kits/playbook/pb_user/_user.html.erb, app/pb_kits/playbook/pb_user/user.rb
The territory was removed inadvertently to the rails kit. This PR brings it back.
No Breaking Changes
=> Added territory back to the kit

CHANGELOG.md, app/pb_kits/playbook/pb_icon_circle/_icon_circle.jsx
Add support to the existent but unused `className` prop on the React version of the icon circle kit.
There are no breaking changes.
1. Usages of the react version of the icon circle component should allow for additional styles to be applied via the `className` prop.
=> Add className support to React version of icon circle kit

CHANGELOG.md, app/pb_kits/playbook/pb_card/_card.jsx, app/pb_kits/playbook/pb_card/_card.scss
It seems that the highlight position values (`side` vs `top`) have their implementations inverted (see screenshots below).
This PR makes it so that setting the highlight position to `side`, causes the highlight to be actually rendered on the side of the card rather than on the top. Similarly, the highlight position set to `top` will render the highlight on the top of the card rather than on its side.
This PR **could** introduce some regression on apps using the `position` prop of the `Card` kit. As of this writing, it seems that at least `nitro-web` **would not** experience any changes to the behavior of card components since there's no usage instance of the position prop.
**Before**
**Rails** Version:
**React** Version:
**After**
**Rails** Version:
**React** Version:
=> Pb Card: Swap implementation of highlight position values.

CHANGELOG.md, app/pb_kits/playbook/pb_text_input/_text_input.scss, app/pb_kits/playbook/pb_textarea/_textarea.html.erb, app/pb_kits/playbook/pb_textarea/_textarea.jsx, app/pb_kits/playbook/pb_textarea/_textarea.scss, app/pb_kits/playbook/pb_textarea/docs/_textarea_dark_error.html.erb, app/pb_kits/playbook/pb_textarea/docs/_textarea_dark_error.jsx, app/pb_kits/playbook/pb_textarea/docs/_textarea_error.html.erb, app/pb_kits/playbook/pb_textarea/docs/_textarea_error.jsx, app/pb_kits/playbook/pb_textarea/docs/example.yml, app/pb_kits/playbook/pb_textarea/docs/index.js, app/pb_kits/playbook/pb_textarea/textarea.rb, spec/pb_kits/playbook/kits/textarea_spec.rb
Based on https://github.com/powerhome/playbook/pull/554
https://nitro.powerhrg.com/runway/backlog_items/NUX-559
=> Add error state to TextArea kit

CHANGELOG.md, app/pb_kits/playbook/pb_home_address_street/_home_address_street.html.erb, app/pb_kits/playbook/pb_home_address_street/_home_address_street.jsx, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_dark.html.erb, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_dark.jsx, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_default.html.erb, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_default.jsx, app/pb_kits/playbook/pb_home_address_street/home_address_street.rb, spec/pb_kits/playbook/kits/home_address_street_spec.rb
Adds url support to the `Home Address Street` kit. Defaults to "#" if prop is not used. 
There are no breaking changes. 
The home_id link should direct to the link given to the `home_url` prop.
=> Add home_url prop to home_address_street kit

CHANGELOG.md, app/pb_kits/playbook/packs/site_styles/docs/_kit_doc.scss, app/pb_kits/playbook/packs/site_styles/docs/_markdown.scss, app/pb_kits/playbook/packs/site_styles/docs/_spacing_tokens.scss, app/pb_kits/playbook/pb_card/card.rb, app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss, app/pb_kits/playbook/tokens/_colors.scss, app/pb_kits/playbook/tokens/_shadows.scss, app/views/playbook/pages/utilities.html.slim, spec/pb_kits/playbook/kits/card_spec.rb
- There is now one shadow color for both light and dark eliminating the need for shadow_light & shadow_dark.
- Shadow values shallow and default removed and all files with those values were changed.
- shadow_shallow removed
-shadow_default removed
-shadow_dark removed
-shadow_light renamed to shadow
- ✅ **SPECS** Please cover your changes with specs
- ✅ **CHANGELOG** Please add an entry on `[Unreleased]` section to every functionality `ADDED`/`CHANGED`/`DEPRECATED`/`REMOVED`/`FIXED`
=> Shadow Shallow, Default & Dark Deprecation

CHANGELOG.md, app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.html.erb, app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.jsx, app/pb_kits/playbook/pb_circle_icon_button/circle_icon_button.rb
None..
Previously, a circle icon button's type is set to the default `submit`, which always causes forms with circle icon buttons to be submitted. There was no way to prevent this by setting type to `button`.
This PR adds a `type` prop to the circle icon button kit to allow users to set a button type. This also changes the circle icon button's default type to `button`, a more reasonable default since circle icon buttons are not primarily used for form submissions (is it?).
It will break forms that use circle icon buttons for submission.
=> Set circle icon button type to `button`

CHANGELOG.md, app/pb_kits/playbook/pb_hashtag/_hashtag.jsx, app/pb_kits/playbook/pb_hashtag/docs/_hashtag_dark.html.erb, app/pb_kits/playbook/pb_hashtag/docs/_hashtag_dark.jsx, app/pb_kits/playbook/pb_hashtag/docs/_hashtag_default.html.erb, app/pb_kits/playbook/pb_hashtag/docs/_hashtag_default.jsx, app/pb_kits/playbook/pb_hashtag/hashtag.rb, spec/pb_kits/playbook/kits/hashtag_spec.rb
No ticket URL. This PR has been opened to follow up on SpotNitro additions during Create. Our team was informed to use the Appointment hashtag for viewing Estimate Appointments in SpotNitro. Unfortunately, we could only get the hashtag to appear as `#A123456` instead of `A#123456`.
With this addition, we can align SpotNitro's representation of an  Estimate Appointment with that of a Home.
As it looks like now.
There are no breaking changes in this PR.
=> Add Appointment to Hashtag kit

app/pb_kits/playbook/pb_select/_select.jsx, app/pb_kits/playbook/pb_select/docs/_select_blank.jsx, app/pb_kits/playbook/pb_select/docs/_select_dark.jsx, app/pb_kits/playbook/pb_select/docs/_select_dark_error.jsx, app/pb_kits/playbook/pb_select/docs/_select_default.jsx, app/pb_kits/playbook/pb_select/docs/_select_disabled.jsx, app/pb_kits/playbook/pb_select/docs/_select_disabled_options.jsx, app/pb_kits/playbook/pb_select/docs/_select_error.jsx, app/pb_kits/playbook/pb_select/docs/_select_required.jsx, app/pb_kits/playbook/pb_select/docs/_select_value_text_same.jsx, app/pb_kits/playbook/pb_selectable_card/_selectable_card.jsx, app/pb_kits/playbook/pb_textarea/_textarea.jsx, app/pb_kits/playbook/pb_toggle/_toggle.jsx, app/pb_kits/playbook/types.js
https://nitro.powerhrg.com/runway/backlog_items/BOLT-71
Fixes the following warning:
1. Renamed the option `valueText` attribute to `text` for a more concise API.
1. Removed the ability to directly mark an option as `selected` in favor of the `value` prop on the `select` element.
There seems to be only one usage of the `Select` kit in `nitro-web` in the installation crews profile page which will need to be updated to meet the new `Select` API and be regression tested.
=> [BOLT-71] Select Kit: Fix misuse of selected vs value props

CHANGELOG.md, app/pb_kits/playbook/pb_date_stacked/_date_stacked.jsx, app/pb_kits/playbook/pb_date_stacked/docs/_date_stacked_not_current_year.jsx
Without these changes a usage like this
```
<DateStacked
date="2018-03-20"
size="md"
/>
```
would create different results depending on the timezone, it could say that the date is "March 19th, 2018", for instance. 
Since this is a Date only kit my assumption is that timezones are not desired.
This should not break anything. This kit still accepts `new Date` or formatted date strings like `"2020-08-30"` as a valid date.
The `/compliance` page in Nitro uses this Kit, so we can verify that it's still working as expected:
- If the date is in the same year as the current year, it should only show day and month
- If the date is NOT in the same year as the current year, it should show the year as well.
=> Ignore timezone on DateStacked

app/pb_kits/playbook/packs/site_styles/docs/_flex_examples.scss, app/views/playbook/pages/kit_show.html.slim
Removes the gray backgrounds for other kits using `flex` / `flex/flex-item` kit. 
N/A
None
N/A
=> Remove flex kit doc highlighting for other kits

CHANGELOG.md, app/pb_kits/playbook/pb_date_stacked/_date_stacked.jsx, app/pb_kits/playbook/pb_date_stacked/docs/_date_stacked_not_current_year.jsx, app/pb_kits/playbook/pb_kit/dateTime.js
Without these changes a usage like this
```
<DateStacked
date="2018-03-20"
size="md"
/>
```
would create different results depending on the timezone, it could say that the date is "March 19th, 2018", for instance. 
Since this is a Date only kit my assumption is that timezones are not desired.
This should not break anything. This kit still accepts `new Date` or formatted date strings like `"2020-08-30"` as a valid date.
The `/compliance` page in Nitro uses this Kit, so we can verify that it's still working as expected:
- If the date is in the same year as the current year, it should only show day and month
- If the date is NOT in the same year as the current year, it should show the year as well.
=> Ignore timezone on date stacked

Jenkinsfile
See https://github.com/powerhome/ci-kubed/pull/29
This played out on https://github.com/powerhome/playbook/pull/621 where the merge commit f2b0c81 had its image build reported against the previous commit 092039f in the CI job at https://ci.powerhrg.com/blue/organizations/jenkins/powerhome%2Fplaybook/detail/PR-621/6/pipeline/15
=> Upgrade ci-kubed for bugfixes

CHANGELOG.md, Jenkinsfile, app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_context.html.erb, app/pb_kits/playbook/pb_typeahead/docs/example.yml, app/pb_kits/playbook/pb_typeahead/index.js
Allow the typeahead to use a context to make searches distinct when
using the same typeahead to provide results with different
conditions.
The typeahead has a cache, but that might not be the best name for
it. This structure was primarily added to provide coordination for
asynchronous searches. We can get the benefits of a cache,
and always provide the user with fresh results. We change the search
to always show the cached values when results are present but also
always issuing a event to get new results.
[BOP-357](https://nitro.powerhrg.com/runway/backlog_items/BOP-357)
=> Add a context option for the typeahead

CHANGELOG.md, app/pb_kits/playbook/pb_typeahead/_typeahead.html.erb, app/pb_kits/playbook/pb_typeahead/_typeahead.scss, app/pb_kits/playbook/pb_typeahead/index.js
=> [BOP-368] Typeahead/add loading indicator

CHANGELOG.md, app/pb_kits/playbook/packs/examples.js, app/pb_kits/playbook/vendor.js
Move popover and typeahead initialize to vendor.js. This was in the wrong area for Nitro and should not exist in examples.js since application.js imports vendor.js. This may have prevented popover from working in Playbook and Typeahead from working in Nitro. 
N/A
1. Ensure both Popover and Typeahead kits work on dev docs page
2. Ensure typeahead works on Corp Directory
3. Ensure popover works on Corp Directory
=> Move popover and typeahead initialize to vendor.js

CHANGELOG.md, app/pb_kits/playbook/kits/pb_flex.js, app/pb_kits/playbook/kits/pb_highlight.js, app/pb_kits/playbook/packs/examples.js, app/pb_kits/playbook/vendor.js, lib/generators/kit/kit_generator.rb, lib/generators/kit/templates/kit_pack.erb.tt
Based on https://github.com/powerhome/playbook/pull/651
https://nitro.powerhrg.com/runway/backlog_items/NUX-680
Removes invalid kits folder and updates the generator 
None
N/A
=> Update kit generator

app/pb_kits/playbook/pb_home_address_street/_city_emphasis.html.erb, app/pb_kits/playbook/pb_home_address_street/_home_address_street.html.erb, app/pb_kits/playbook/pb_home_address_street/_home_address_street.jsx, app/pb_kits/playbook/pb_home_address_street/_home_address_street.scss, app/pb_kits/playbook/pb_home_address_street/_street_emphasis.html.erb, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_emphasis.html.erb, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_emphasis.jsx, app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_emphasis.md, app/pb_kits/playbook/pb_home_address_street/docs/example.yml, app/pb_kits/playbook/pb_home_address_street/docs/index.js, app/pb_kits/playbook/pb_home_address_street/home_address_street.rb, spec/pb_kits/playbook/kits/home_address_street_spec.rb
https://github.com/powerhome/playbook/issues/210
Currently, none. The display **defaults** to the street being emphasized, which is how they currently are in Nitro-- so nothing from this PR would break any of the kit occurrences in Nitro. 
If we want to make the emphasis prop **required**, this would require a small change to this PR and _would_ result in breaking changes and a new major release of Playbook.
=> Emphasis Prop Added

config/deploy/templates/deployment.yaml.erb, config/deploy/templates/ingress.yaml.erb
We are preparing to upgrade to Kubernetes v1.16 and to do that we need to remove deprecated API endpoints. In the Repo the only issue was with the deployment:
* Deployment in the **extensions/v1beta1**, **apps/v1beta1**, and **apps/v1beta2** API versions is no longer served
* Migrate to use the **apps/v1** API version, available since v1.9. Existing persisted data can be retrieved/updated via the new version.
* Notable changes:
* `spec.rollbackTo` is removed
* `spec.selector` is now required and immutable after creation
* `spec.progressDeadlineSeconds` now defaults to 600 seconds
* `spec.revisionHistoryLimit` now defaults to 10
* `maxSurge` and `maxUnavailable` now default to 25%
The kubernetes `v1.20` release will stop serving the following deprecated API versions in favor of newer and …
=> Upgrade deprecated api to prepare for kubernetes v1.16

CHANGELOG.md, app/pb_kits/playbook/pb_form/form_builder/form_field_builder.rb, app/pb_kits/playbook/pb_select/_select.html.erb
https://nitro.powerhrg.com/runway/backlog_items/NUX-730
None
1. Test a form kit that uses placeholders such as Owner Referrals view. Form should show placeholders in the input field when no value is present.
=> Allow form field placeholder + select kit id

Gemfile.lock, playbook_ui.gemspec
Uses newer version of webpacker. This is required in order to also upgrade webpacker on `nitro-web` so we can get a fix for the `webpacker:clean` rake task that was buggy in previous versions.
=> Update webpacker to version 4.2.2

app/pb_kits/playbook/tokens/_colors.scss, app/views/playbook/pages/utilities.html.slim
Renames the `roofs` color to `roofing` to align with the industry standard naming convention.
=> Rename roofs to roofing

app/pb_kits/playbook/pb_form_pill/_form_pill.jsx, app/pb_kits/playbook/pb_form_pill/docs/_form_pill_tag.jsx, app/pb_kits/playbook/pb_form_pill/docs/_form_pill_user.jsx
@gmfvpereira I was running your branch for a PR that I need to create regarding cleanup of `onClick` handlers across the board. Upon testing, I noticed that the `<i onClick=...` does not actually fire at all (which is sort of surprising - sorta not). Since it isn't doing anything, I moved the prop to the wrapping `<div>` within `FormPill`. This time, the `onClick` is fired as seen here in the doc examples for React. Let me know if you have any questions or concerns. I would like to know if you had this working for you locally and perhaps there is some strange delta I am seeing here.. Thanks!
BTW - I did create the [revert PR](https://github.com/powerhome/playbook/pull/693)
=> Move onClick prop out of Icon and in to FormPill

config/deploy/templates/deployment.yaml.erb
Attempting to help prevent evictions. At least 50Mi are needed just
for logs and the playbook pods themselves seem to be running around
150MB. This gives us a bit of headroom to play with for now.
=> [GOG-146] Add ephemeral-storage quota

CHANGELOG.md, config/webpack/loaders/erb.js, docker-compose.yml, package.json, yarn.lock
Playbook will currently run with as much resource as it possibly can which can potentially cause over-allocation and all of the not-so-happy side effects that come along (hanging, unresponsiveness and even crashing). For this reason, I created this PR which adds resource restrictions to the Docker `webpacker` instance during local development (based on the fairly standard Power-issued dev Macbook Pro):
- CPU: min 2 / max 4
- Memory: min 2G / max 6G (~4-5G is normal w/ no latency)
This first pass is more lenient than perhaps we may end up settling on. 
¯\\\_(ツ)_/¯
=> Limit webpacker CPU & memory on local dev

CHANGELOG.md, app/pb_kits/playbook/pb_text_input/_text_input.html.erb, app/pb_kits/playbook/pb_text_input/_text_input.jsx, app/pb_kits/playbook/pb_text_input/docs/_text_input_default.html.erb, app/pb_kits/playbook/pb_text_input/docs/_text_input_default.jsx, app/pb_kits/playbook/pb_text_input/text_input.rb
Originally started in #798 
Removes duplicate custom class name from Ruby input element.
#791
=> Aria data id fixes for text input

CHANGELOG.md, app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.html.erb, app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.jsx, app/pb_kits/playbook/pb_circle_icon_button/circle_icon_button.rb, app/pb_kits/playbook/pb_circle_icon_button/docs/_circle_icon_button_link.html.erb, app/pb_kits/playbook/pb_circle_icon_button/docs/_circle_icon_button_link.jsx, app/pb_kits/playbook/pb_circle_icon_button/docs/example.yml, app/pb_kits/playbook/pb_circle_icon_button/docs/index.js, spec/pb_kits/playbook/kits/circle_icon_button_spec.rb
Added link and newWindow prop to circle icon button
=> Added link & new window props to circle icon button

CHANGELOG.md, app/pb_kits/playbook/pb_table/_table.scss, app/pb_kits/playbook/pb_table/docs/_table_side_highlight.html.erb, app/pb_kits/playbook/pb_table/docs/_table_side_highlight.jsx, app/pb_kits/playbook/pb_table/docs/_table_side_highlight.md, spec/pb_kits/playbook/kits/table_row_spec.rb
No breaking changes.
https://nitro.powerhrg.com/runway/backlog_items/NUX-1028
=> Added category colors to table side highlight kit

CHANGELOG.md, app/pb_kits/playbook/pb_progress_pills/_progress_pills.html.erb, app/pb_kits/playbook/pb_progress_pills/_progress_pills.jsx
React Progress Pills kit was missing aria, className, data, and id props. Rails Progress Pills kit was missing aria props. 
REACT
RAILS
None
=> Add aria, className, data, id props to React Progress Pills kit

CHANGELOG.md, app/pb_kits/playbook/pb_section_separator/_section_separator.html.erb, app/pb_kits/playbook/pb_section_separator/_section_separator.jsx, app/pb_kits/playbook/pb_section_separator/docs/_section_separator_text.jsx
React Section Separator kit was missing aria, data, id props. Rails Section Separator kit was missing aria props.
RAILS
REACT
None
=> Add aria, id, data props to React Section Separator kit; Add aria props to Rails

CHANGELOG.md, app/pb_kits/playbook/pb_message/_message.html.erb, app/pb_kits/playbook/pb_message/_message.jsx, app/pb_kits/playbook/pb_message/docs/_message_default.jsx, app/pb_kits/playbook/pb_message/message.rb
React Message kit did not contain aria, className, id, data props and Rail Message kit did not contain aria props.
RAILS: 
REACT: 
None
=> Add aria, className, data, id props to React Message kit

CHANGELOG.md, app/pb_kits/playbook/pb_person/_person.html.erb, app/pb_kits/playbook/pb_person/_person.jsx, app/pb_kits/playbook/pb_person/docs/_person_default.html.erb
React Person kit was missing aria, data, id props and Rails Person kit was missing aria props.
RAILS 
REACT
None
=> Add aria, data, id props to React Person kit, add aria props to Rails

CHANGELOG.md, app/pb_kits/playbook/pb_label_value/_label_value.html.erb, app/pb_kits/playbook/pb_label_value/_label_value.jsx
Aria, data, id props were missing from React Label Value kit; aria props were missing from Rails Label Value kit.
NOTE: This PR will replace #842. 
I added in examples of data, aria, id to make sure the props were working correctly and took screenshots of the html. Before I pushed up the PR, I removed the examples.
REACT
RAILS
None
=> Add aria, data, id props to React LabelValue kit

CHANGELOG.md, app/pb_kits/playbook/pb_bar_graph/_bar_graph.jsx, app/pb_kits/playbook/pb_bar_graph/bar_graph.rb, app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_legend_non_clickable.html.erb, app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_legend_non_clickable.jsx, app/pb_kits/playbook/pb_bar_graph/docs/example.yml, app/pb_kits/playbook/pb_bar_graph/docs/index.js, app/pb_kits/playbook/pb_line_graph/_line_graph.jsx, app/pb_kits/playbook/pb_line_graph/docs/_line_graph_legend_nonclickable.html.erb, app/pb_kits/playbook/pb_line_graph/docs/_line_graph_legend_nonclickable.jsx, app/pb_kits/playbook/pb_line_graph/docs/example.yml, app/pb_kits/playbook/pb_line_graph/docs/index.js, app/pb_kits/playbook/pb_line_graph/line_graph.rb, app/pb_kits/playbook/plugins/pb_chart.js, spec/pb_kits/playbook/kits/bar_graph_spec.rb, spec/pb_kits/playbook/kits/line_graph_spec.rb
This PR allows for the legend's click functionality on the Bar and Line graph to be toggled on and off.
I have set the default to true because it is being used in several places around Nitro and I don't want to have to change them all.
=> Add ability to toggle if the legend is clickable

CHANGELOG.md, app/pb_kits/playbook/pb_title/_title.html.erb, app/pb_kits/playbook/pb_title/_title.jsx, app/pb_kits/playbook/pb_title/title.rb, lib/playbook/version.rb, package.json, spec/pb_kits/playbook/kits/title_spec.rb, yarn.lock
React Title kit was missing aria, data, id props and Rails Title kit was missing aria props.
RAILS
REACT
None
=> Add aria, data, id props to React Title kit and aria to Rails Title kit

config/deploy/templates/ingress.yaml.erb
No GUI change.
Merge of this PR will prevent certs from being issued until cert-manager is updated on the cluster. Lack of merge of this PR will prevent certs from being issued after cert-manager is updated on the cluster.
Certificates are issued with a 90 day validity, renewed whenever there's less than 15 days to expire, and we plan on updating cert-manager on the cluster on the first half of this week, so this shouldn't be an issue.
https://nitro.powerhrg.com/runway/backlog_items/WTWR-149
All functional tests have already been performed by the Watchtower team.
=> Migrate cert-manager annotations to new version

CHANGELOG.md, app/pb_kits/playbook/pb_radio/_radio.scss
When the radio text is very long, it will squish the radio button. Also, the border color for radio dark needs to be updated.
_Radio before_
_Radio after_
Note: The doc example in the PR just says "Custom Power." The extra long radio option in the screenshots is to just demonstrate that the radio button gets squished.
_Updated border color for dark version_
n/a
n/a
=> Radio kit fixes

app/pb_kits/playbook/pb_typeahead/docs/_typeahead_default.html.erb
Old View of Typeahead kit docs:
New View of Typeahead kit docs:
No breaking changes. Only affects the example shown in the docs.
No related ticket.
- ~~**CHANGELOG** Please add an entry on `[Unreleased]` section to every functionality `ADDED`/`CHANGED`/`DEPRECATED`/`REMOVED`/`FIXED`~~
=> Fix bug displaying user kit in "typeahead" kit docs

CHANGELOG.md, app/pb_kits/playbook/pb_badge/_badge.html.erb, app/pb_kits/playbook/pb_badge/_badge.jsx
The React Badge kit didn't have aria, data props; the Rails Badge kit didn't have aria props. I also alphabetized a few lists.
None
=> Add aria, data props to React Badge kit

CHANGELOG.md, app/pb_kits/playbook/pb_caption/_caption.scss
I tested this on both React & Rails, with spacing props added in the docs example. The conflicts are now gone. 🎉
https://nitro.powerhrg.com/runway/backlog_items/NUX-1228
=> Fixes Spacing Conflicts with Caption Sizing Props

CHANGELOG.md, app/pb_kits/playbook/pb_legend/_legend.html.erb, app/pb_kits/playbook/pb_legend/_legend.jsx, app/pb_kits/playbook/pb_legend/docs/_legend_default.jsx
#269
Added className prop as well as aria, data, id props to React Legend kit. Added aria props to Rails Legend kit.
=> Add props to legend

CHANGELOG.md, app/pb_kits/playbook/pb_popover/_popover.html.erb, app/pb_kits/playbook/pb_popover/_popover.jsx, app/pb_kits/playbook/pb_popover/_popover.scss, app/pb_kits/playbook/pb_popover/popover.rb
N/A, preserves default behavior and accounts for all situations in which a scroll bar would appear (using max width/height).
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/NUX-1120)
Double check Popovers with max widths/heights in Nitro
=> Popover Overflow Fix

CHANGELOG.md, app/pb_kits/playbook/pb_dashboard_value/_dashboard_value.html.erb, app/pb_kits/playbook/pb_dashboard_value/_dashboard_value.jsx
React Dashboard Value kit was missing aria, data props; Rails kit was missing aria props. There were also some minor inconsistencies between the default values on the React versus the Rails.
None
=> Add aria, data props to Dashboard Value kit

CHANGELOG.md, app/pb_kits/playbook/pb_button/_button.jsx
Before disabled `true` was adding only a disabled class but it was missing to add the disabled attribute to button which was letting the key "Enter" to execute an action. 
In this PR fix, we added the disabled attribute to button when disabled `true` to solve the problem. 
https://nitro.powerhrg.com/runway/backlog_items/LGA-232
```
import React, { useState } from 'react'
import { Button } from '../../'
const ButtonDefault = () => {
const [ myButton, setMyButton ] = useState(false)
const handleError = () => {
setMyButton(true)
window.setTimeout(() => {
setMyButton(false)
}, 15000)
console.log('Hello there')
}
return (
<div>
<Button
disabled={myButton}
onClick={handleError}
text="Button Disabled"
/>
</div>
)
}
export default ButtonDefault
```
=> Adds disabled attribute to button

CHANGELOG.md, app/pb_kits/playbook/pb_kit/dateTime.js, app/pb_kits/playbook/pb_time/_time.jsx, app/pb_kits/playbook/pb_time/_time.scss, app/pb_kits/playbook/pb_time/docs/_time_align.jsx, app/pb_kits/playbook/pb_time/docs/_time_dark.jsx, app/pb_kits/playbook/pb_time/docs/_time_default.jsx, app/pb_kits/playbook/pb_time/docs/_time_timestamp.jsx, app/pb_kits/playbook/pb_time/docs/example.yml, app/pb_kits/playbook/pb_time/docs/index.js, app/pb_kits/playbook/pb_title/_title.jsx
Not breaking, but of note, running into a weird bug where the Rails version of this kit adds 'invisible' spacing between the icon and time.
https://github.com/powerhome/playbook/issues/616
Checkout the branch.
=> Add React Version of Time Kit

CHANGELOG.md, app/pb_kits/playbook/pb_title/_title.jsx, app/pb_kits/playbook/pb_title/_title.scss, app/pb_kits/playbook/pb_title/title.rb, spec/pb_kits/playbook/kits/title_spec.rb
NUX-1287
Dark prop was removed from Rails and React side of kit.
=> Edit dark mode in Title kit to reflect globalProps changes

CHANGELOG.md, app/pb_kits/playbook/pb_caption/_caption.jsx, app/pb_kits/playbook/pb_caption/_caption.scss, app/pb_kits/playbook/pb_caption/caption.rb, spec/pb_kits/playbook/kits/caption_spec.rb
NUX-1287
Removed dark prop from Rails and React Caption kits
=> Edit dark mode in Caption kit to reflect globalProps changes

app/pb_kits/playbook/pb_typeahead/_typeahead.html.erb, app/pb_kits/playbook/pb_typeahead/_typeahead.scss, app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_context_dark.html.erb, app/pb_kits/playbook/pb_typeahead/typeahead.rb
This is a composite kit that should show dark components once its children components are updated.
None I'm aware of.
https://nitro.powerhrg.com/runway/backlog_items/NUX-1286
Playbook Docs or Nitro Docs
=> NUX-1286 - Global Props for Dark on typeahead

app/pb_kits/playbook/pb_textarea/_textarea.jsx, app/pb_kits/playbook/pb_textarea/_textarea.scss, app/pb_kits/playbook/pb_textarea/docs/_textarea_dark.jsx, app/pb_kits/playbook/pb_textarea/docs/_textarea_dark_error.jsx, app/pb_kits/playbook/pb_textarea/textarea.rb, spec/pb_kits/playbook/kits/textarea_spec.rb
**Rails**
**React**
[https://nitro.powerhrg.com/runway/backlog_items/NUX-1286](https://nitro.powerhrg.com/runway/backlog_items/NUX-1286)
=> NUX-1286 - Update dark props for Textarea kit

app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.html.erb, app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_dark.html.erb, app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_dark.jsx, app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_multi_line_dark.html.erb, app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_multi_line_dark.jsx, app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/example.yml, app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/index.js, spec/pb_kits/playbook/kits/fixed_confirmation_toast_spec.rb
=> Add dark mode to Fixed Confirmation Toast

app/pb_kits/playbook/pb_table/_table.html.erb, app/pb_kits/playbook/pb_table/_table.jsx, app/pb_kits/playbook/pb_table/_table_row.html.erb, app/pb_kits/playbook/pb_table/_table_row.jsx, app/pb_kits/playbook/pb_table/table.rb, spec/pb_kits/playbook/kits/table_spec.rb
NUX-1326
I also added aria, data, id props.
Removed dark prop from both sides of kit.
=> Table dark mode

app/pb_kits/playbook/pb_date/date.rb, app/pb_kits/playbook/pb_date/docs/_date_default.html.erb, app/pb_kits/playbook/pb_date/docs/_date_timezone.html.erb, app/pb_kits/playbook/pb_date/docs/_date_timezone.md, app/pb_kits/playbook/pb_date/docs/_description.md, app/pb_kits/playbook/pb_date/docs/example.yml, spec/pb_kits/playbook/kits/date_spec.rb
The Date kit wasn't supporting Timezones. When you added a strict `Date` class it's not a concern but `DateTime` would have problems and default all days to adhere to EST timezone.
- This PR updates the method to leverage existing functionality, the kit just needed a Timezone prop.
- Also, since Dates, Time, Timezones are confusing as is, we needed to add a little more documentation around how our kits leverage those classes in RoR to render dates, times, and timezones.
**Updated details**
**Default Example**
**Timezone Examples**
Should be ok. New timezone props is optional.
https://nitro.powerhrg.com/runway/backlog_items/NUX-1370
Use kit, enter various dates and timezones.
=> [NUX-1370] - Date Kit Timezone Props

app/pb_kits/playbook/pb_text_input/_text_input.scss
I don't believe so. The selector is quite specific.
https://nitro.powerhrg.com/runway/backlog_items/NUX-1347
I'm not quite sure actually.
=> [NUX-1347] - Reduce input css specificity

app/pb_kits/playbook/pb_filter/_filter.scss
Closes #1032 
Nope
NUX-1379
Resize the browser to generate scrollbars on the filter displays. Confirm the filters scroll properly
=> Attempting to fix scrollbars on Windows

app/pb_kits/playbook/pb_date/date.rb, app/pb_kits/playbook/pb_date/docs/_date_default.html.erb, app/pb_kits/playbook/pb_date/docs/_date_timezone.html.erb, app/pb_kits/playbook/pb_date/docs/_date_timezone.md, app/pb_kits/playbook/pb_date/docs/_description.md, app/pb_kits/playbook/pb_date/docs/example.yml, spec/pb_kits/playbook/kits/date_spec.rb
The Date kit wasn't supporting Timezones. When you added a strict `Date` class it's not a concern but `DateTime` would have problems and default all days to adhere to EST timezone.
- This PR updates the method to leverage existing functionality, the kit just needed a Timezone prop.
- Also, since Dates, Time, Timezones are confusing as is, we needed to add a little more documentation around how our kits leverage those classes in RoR to render dates, times, and timezones.
**Updated details**
**Default Example**
**Timezone Examples**
Should be ok. New timezone props is optional.
https://nitro.powerhrg.com/runway/backlog_items/NUX-1370
Use kit, enter various dates and timezones.
=> Add timezone prop to date, expand docs

app/pb_kits/playbook/pb_time/_time.html.erb, app/pb_kits/playbook/pb_time/_time.jsx, app/pb_kits/playbook/pb_time/_time.scss, app/pb_kits/playbook/pb_time/docs/_time_align.html.erb, app/pb_kits/playbook/pb_time/docs/_time_align.jsx, app/pb_kits/playbook/pb_time/docs/_time_dark.html.erb, app/pb_kits/playbook/pb_time/docs/_time_dark.jsx, app/pb_kits/playbook/pb_time/docs/_time_default.html.erb, app/pb_kits/playbook/pb_time/docs/_time_default.jsx, app/pb_kits/playbook/pb_time/docs/_time_sizes.html.erb, app/pb_kits/playbook/pb_time/docs/_time_sizes.jsx, app/pb_kits/playbook/pb_time/docs/_time_timestamp.html.erb, app/pb_kits/playbook/pb_time/docs/_time_timestamp.jsx, app/pb_kits/playbook/pb_time/docs/_time_timezone.html.erb, app/pb_kits/playbook/pb_time/docs/_time_timezone.jsx, app/pb_kits/playbook/pb_time/docs/example.yml, app/pb_kits/playbook/pb_time/docs/index.js, app/pb_kits/playbook/pb_time/time.rb, app/pb_kits/playbook/tokens/_typography.scss, spec/pb_kits/playbook/kits/time_spec.rb
**React** - No, there is no reference to the `<Time />` component in Nitro.
**Rails** - Yes, there are 14 references to `<%= pb_rails("time") %>`.
- "Lg" size is not used in any kits.
- "Sm" is referenced and has an icon if that's the case. Therefore we need to add the `show_icon` prop to those instances.
- "Xs" references needs to be changed to "sm"
[https://nitro.powerhrg.com/runway/backlog_items/NUX-639](https://nitro.powerhrg.com/runway/backlog_items/NUX-639)
- Check Implementation in Playbook
- Testing in Playground
- Specs Updated
=> [NUX-639] - Time Kit Redesign / Update

app/pb_kits/playbook/pb_time/docs/_time_dark.html.erb, app/pb_kits/playbook/pb_time/docs/_time_default.html.erb, app/pb_kits/playbook/pb_time/docs/_time_timestamp.html.erb, app/pb_kits/playbook/pb_time/docs/_time_timezone.html.erb, app/pb_kits/playbook/pb_time/time.rb
**Note**: 1 Logic Change - Other changes are just the documentation.
Logic swap here:
https://github.com/powerhome/playbook/compare/hotfix/timezone-show?expand=1#diff-956141a959c897010749a84f9ce34bf7R21
No - This is a fix to adopt a previous behavior.
Bug Fix
=> Bug Fix - Swap show_timezone to be false by default

app/pb_kits/playbook/pb_stat_value/_stat_value.jsx, app/pb_kits/playbook/pb_stat_value/docs/_stat_value_default.jsx
When we pass a numeric `0` to the `value` prop of the `StatsValue` kit  (i.e. `<StatValue value={0} />`) in React, the value is not being displayed. This PR is to fix this issue.
Before
After
No.
https://nitro.powerhrg.com/runway/backlog_items/NOVA-596
I've added an example of that usage into the documentation. Thus, it can be tested asserting that the 0 value is being shown.
=> Display numeric zero in StatsValue Kit

app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.html.erb, app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.jsx, app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.scss, app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_close.html.erb, app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_close.jsx, app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_default.jsx, app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_multi_line.html.erb, app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_multi_line.jsx, app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_multi_line_dark.html.erb, app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_multi_line_dark.jsx, app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/example.yml, app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/index.js, app/pb_kits/playbook/pb_fixed_confirmation_toast/fixed_confirmation_toast.rb, app/pb_kits/playbook/pb_fixed_confirmation_toast/index.js, app/pb_kits/playbook/vendor.js, spec/pb_kits/playbook/kits/fixed_confirmation_toast_spec.rb
No - New prop that is optional and defaults to existing state. 
_Please double check though : )_
[NUXE-80](https://nitro.powerhrg.com/runway/backlog_items/NUXE-80)
Click toast examples in docs.
=> [NUXE-80] - Add 'close' option to kit, with examples

app/pb_kits/playbook/pb_toggle/docs/_toggle_options.html.erb, app/pb_kits/playbook/pb_toggle/docs/example.yml, app/pb_kits/playbook/pb_toggle/toggle.rb, spec/pb_kits/playbook/kits/toggle_spec.rb
No. This PR adds the input_options prop to the toggle kit so PlayBook users can pass every single kind of HTML element option to the input element. This PR does not remove any props as to not break any existing usages of the toggle kit.
Read this [RFC](https://github.com/powerhome/rfcs/blob/master/0052-playbook-html-attribute-standards.md) for more details.
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/CMPN-18)
=> [CMPN-18] Allow all HTML options on input in PbToggle Rails kit.

app/pb_kits/playbook/pb_section_separator/_section_separator.jsx, app/pb_kits/playbook/pb_section_separator/_section_separator.scss, app/pb_kits/playbook/pb_section_separator/_section_separator_mixin.scss, app/pb_kits/playbook/pb_section_separator/docs/_section_separator_line.jsx, app/pb_kits/playbook/pb_section_separator/docs/_section_separator_text.jsx, app/pb_kits/playbook/pb_section_separator/docs/_section_separator_text_background.jsx, app/pb_kits/playbook/pb_section_separator/docs/_section_separator_vertical.jsx, app/pb_kits/playbook/pb_section_separator/section_separator.rb, spec/pb_kits/playbook/kits/section_seperator_spec.rb
No breaking changes. This PR consist of taking dark_class off of classname and other css changes.
https://nitro.powerhrg.com/runway/backlog_items/NUXE-158
Test this by making the page dark and checking that it looks like how it's supposed to.
https://pr1146.playbook.beta.gm.powerapp.cloud/kits/section_separator/react
=> [NUXE-158] Section separator dark mode (WIP)

README.md, app/pb_kits/playbook/props.rb, app/pb_kits/playbook/props/base.rb, spec/pb_kits/playbook/props/array_spec.rb, spec/pb_kits/playbook/props/base_spec.rb, spec/pb_kits/playbook/props/boolean_spec.rb, spec/pb_kits/playbook/props/date_spec.rb, spec/pb_kits/playbook/props/enum_spec.rb, spec/pb_kits/playbook/props/hash_array_spec.rb, spec/pb_kits/playbook/props/hash_spec.rb, spec/pb_kits/playbook/props/number_array_spec.rb, spec/pb_kits/playbook/props/number_spec.rb, spec/pb_kits/playbook/props/numeric_spec.rb, spec/pb_kits/playbook/props/percentage_spec.rb, spec/pb_kits/playbook/props_spec.rb
See added tests and updated error messages. Specifically the additions to `props_spec.rb` and `props/base_spec.rb`. The other changes in prop type tests are simply to keep them working.
No breaking changes.
[CMPN-143](https://nitro.powerhrg.com/runway/backlog_items/CMPN-143)
Consider merging with the next major release if you like. Should be a nice developer experience enhancement.
1. Make sure milano envs loads normally. (It does)
2. After it's merged, see the error become more informative locally and caught in sentry. [Here is an example of what the error message looked like before this change](https://sentry.io/organizations/power-home-remodeling-group/issues/1918768597/?query=is%3Aunresolved+%22required+prop+and+needs+to+be+provided+a+value%22&statsPeriod=14d) .  
``` …
```
=> Better error messages, and more test coverage

app/pb_kits/playbook/pb_pill/_pill.scss
**Before:**
**New:**
No, style fix to prevent the pill text from breaking into two lines.
[NUXE-104](https://nitro.powerhrg.com/runway/backlog_items/NUXE-104)
Set the browser to a smaller size that would enforce the break. Saw the pill text was breaking. Applied the `white-space: nowrap` and retested to make sure the pill text did not break. Images above.
=> Pill Kit double line fix

package.json, yarn.lock
Fixes issue [defined here](https://github.com/JedWatson/react-select/issues/3452#issuecomment-633421878) relating to a bug in the particular version of the library.
N/A
None
https://nitro.powerhrg.com/runway/backlog_items/NUXE-190
- View dev_docs pages and ensure that Typeahead with pills works and does not disappear on focus
=> Downgrade react-select lib

app/pb_kits/playbook/pb_date/_date.html.erb, app/pb_kits/playbook/pb_date/_date.jsx, app/pb_kits/playbook/pb_date/_date.scss, app/pb_kits/playbook/pb_date/date.rb, app/pb_kits/playbook/pb_date/docs/_date_alignment.html.erb, app/pb_kits/playbook/pb_date/docs/_date_alignment.jsx, app/pb_kits/playbook/pb_date/docs/_date_default.html.erb, app/pb_kits/playbook/pb_date/docs/_date_default.jsx, app/pb_kits/playbook/pb_date/docs/_date_variants.html.erb, app/pb_kits/playbook/pb_date/docs/_date_variants.jsx, app/pb_kits/playbook/pb_date/docs/example.yml, app/pb_kits/playbook/pb_date/docs/index.js, lib/playbook/version.rb, spec/pb_kits/playbook/kits/date_spec.rb
No (Will verify as well) - The kit will gracefully deprecate size by accepting the `:size` prop but not leveraging it.
Lost in transition to two boards..but here's the issue:
https://github.com/powerhome/playbook/issues/615
Milano testing, QA Review in Nitro
=> [NUX-638] - Date Kit Refactor/Design

app/pb_kits/playbook/pb_home_address_street/home_address_street.rb
No visual changes.
No.
[BOP-726](https://nitro.powerhrg.com/runway/backlog_items/BOP-726)
No changes should be visible. Errors in Nitro becomes subdued.
=> [BOP-726] Add safe navigator to address home's without addresses

app/pb_kits/playbook/pb_tooltip/_tooltip.scss, app/pb_kits/playbook/pb_tooltip/docs/_tooltip_default.html.erb, app/pb_kits/playbook/pb_tooltip/docs/_tooltip_white.html.erb, app/pb_kits/playbook/pb_tooltip/tooltip.rb
No - These are CSS updates.
https://nitro.powerhrg.com/runway/backlog_items/NUXE-23
Hover
=> [NUXE-23] - Fix tooltip with CSS

milano.production.yml
Move automated deployments of playbook production to the 
`app-prod-hq` cluster.
This requires coordination with @powerhome/watchtower to change
the routing of `playbook.powerapp.cloud` to the the instance running in
`app-prod-hq`'s  `playbook-production` namespace. 
References
------------
https://nitro.powerhrg.com/runway/backlog_items/GOG-313
=> Deploy playbook production to app-prod-hq

milano.production.yml
Playbook production has moved to the new app-prod-hq cluster. As such,
its telemetry is now being reported to the Kibana and Grafana
instances in the new cluster. Here we update the links so consumers
can still use the Milano UI to get to the relevant information for
playbook-production.
=> Fix production links to logs and metrics in the Milano UI

yarn.lock
The JS console error: `TypeError: Cannot read property 'inputValue' of undefined` is still appearing even after attempting to downgrade `react-select` as mentioned in the issue below:
As it relates to [this issue](https://github.com/JedWatson/react-select/issues/3452#issuecomment-633421878), the SHA that was given originally from NPM was `06ff764e29db843bcec439ef13e196865242e0c1`, but if you look at [the official version on Github](), you will see that this is incorrect and should be `1c002f04997401a11bede0852fea0807c6aebe41` instead which will actually apply the previous downgrade from `react-select@3.1.0` to `react-select@3.0.8`. 
No
N/A
This must be tested in Nitro to confirm that the bug listed in the GH issue above no longer remains. Currently @idanzonshein is working with PO …
=> Fix Bad SHA in react-select Version

app/pb_kits/playbook/pb_typeahead/_typeahead.jsx, app/pb_kits/playbook/pb_typeahead/components/ClearIndicator.jsx, app/pb_kits/playbook/pb_typeahead/components/MultiValue.jsx, app/pb_kits/playbook/pb_typeahead/components/Option.jsx, app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills.html.erb, app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills.md, app/pb_kits/playbook/pb_typeahead/typeahead.rb, spec/pb_kits/playbook/pb_typeahead/typeahead_spec.rb, yarn.lock
https://github.com/powerhome/playbook/pull/1172
No
N/A
View the Playbook doc example for testing. Ensure that the default "Windows" pill shows for the first Typeahead with Pills example.
=> Add default pre-selected options to Typeahead with Pills

config/deploy/production/values.yaml, config/deploy/prs/values.yaml, config/deploy/staging/values.yaml, config/deploy/templates/ingress.yaml.erb
Each APP cluster has a wildcard cert issued for playbook-prs which is provisioned into each review namespace. This avoids having to issue a new cert for each review environment, which results in regular notifications of cert expiry for these discarded certs.
=> Don't issue new certs for review envs

playbook/app/pb_kits/playbook/pb_background/_background.html.erb, playbook/app/views/playbook/pages/home.html.erb
1. Fixes rails background kit image bug.
2. Reintroduces hero background svg to landing page.
n/a
[Link to Runway Story](https://nitro.powerhrg.com/runway/backlog_items/NUXE-272)
Double check that the Rails background kit is pulling in an image in the doc examples (last example on page).
=> [NUXE-272] Fixed background kit Rails image bug

playbook/app/pb_kits/playbook/pb_image/_image.scss, playbook/app/views/playbook/samples/news_magazine/index.html.erb, playbook/app/views/playbook/samples/news_magazine/index.jsx
**Rails**
**React**
No, we are fixing issues on the sample news magazine with Javascript.
https://nitro.powerhrg.com/runway/backlog_items/NUXE-260
Go into samples and select the news magazine example. Make sure to see the page loading with images and that the images fit the card body.
=> [NUXE-260] SAMPLE PAGE - Image aspect ratio on News View

playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.jsx, playbook/app/pb_kits/playbook/pb_typeahead/components/Option.jsx, playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async.html.erb, playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async.jsx, playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_async.md, playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb
Fixes #1242 
N/A
none
https://nitro.powerhrg.com/runway/backlog_items/NUXE-342
See https://playbook.powerapp.cloud/kits/typeahead examples
=> Allow getOption[Label|Value] props in Typeahead

playbook/app/pb_kits/playbook/packs/site_styles/_scaffold.scss, playbook/app/pb_kits/playbook/packs/site_styles/_site-style.scss
Nope, style for doc site only
NA
Try this out in Milano on Mobile
=> Improve navigation overflow for mobile

playbook/lib/playbook/props/base.rb
Adds the ruby work from https://github.com/powerhome/playbook/pull/1203 back. It was removed by accident during `7.7.0` or some time after.
=> Add deprecation back

playbook/app/pb_kits/playbook/pb_filter/Filter/SortMenu.jsx
No
https://nitro.powerhrg.com/runway/backlog_items/NUXE-299
Sort menu on React of look the same as the Rails implementation. Icon on the right of the sort button and no icons in the drop down. 
=> Improve consistency of the react filter kit sort icon to match rails

playbook/lib/playbook.rb
Removes methods from the Playbook API which are not used.
No UI change
There's no Runway ticket, this work tracks back to the proposition of [RFC 0056](https://github.com/powerhome/rfcs/blob/master/0056-playbook-project-organization.md).
Smoke testing the deployed playbook-docs
=> Remove unused methods from Playbook api

playbook/app/pb_kits/playbook/pb_radio/_radio.jsx, playbook/app/pb_kits/playbook/pb_radio/docs/_radio_default.jsx, playbook/app/pb_kits/playbook/pb_radio/docs/index.js, playbook/app/pb_kits/playbook/pb_radio/radio.test.js, playbook/app/pb_kits/playbook/pb_select/_select.jsx, playbook/app/pb_kits/playbook/pb_select/select.test.js, playbook/app/pb_kits/playbook/pb_text_input/_text_input.jsx, playbook/app/pb_kits/playbook/pb_text_input/docs/_description.md, playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_custom.jsx, playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_default.jsx, playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_error.jsx, playbook/app/pb_kits/playbook/pb_text_input/text_input.test.js, playbook/app/pb_kits/playbook/pb_textarea/_textarea.jsx
1. Adds `React.forwardRef` implementation to Text Input React kit 
2. Adds basic test coverage (matching Rails kit) to Text Input kit
N/A
none
- Forward Ref: https://nitro.powerhrg.com/runway/backlog_items/NUXE-303
- Test Coverage: https://nitro.powerhrg.com/runway/backlog_items/NUXE-326
- See Playbook website #1 example for `ref` prop. 
- Ensure that no JavaScript errors occur in website example 
- Ensure CI goes green + `yarn run test` locally
=> Forward refs within Text Input, Radio, & Select React kits

playbook/app/pb_kits/playbook/packs/site_styles/_landing-page.scss, playbook/app/views/playbook/pages/home.html.erb
1. Adjusts a media query applied margin to account for the snoggle's new fixed width.
2. Adds background color `$bg_dark` to the homepage hero to make text readable when background image is slow or fails to load.
<br />
n/a
[Link to Runway Story](https://nitro.powerhrg.com/runway/backlog_items/NUXE-369)
Checkout homepage.
=> Fix snoggle margin, homepage hero background color

playbook/lib/playbook/engine.rb
fixes broken generator kit from [this darkmode pr](https://github.com/powerhome/playbook/pull/1238/files#)
[NUXE-378](https://nitro.powerhrg.com/runway/backlog_items/NUXE-378)
Run the kit generator command, possibly check dark-mode on some kits?
=> Fixes kit generator error

playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss, playbook/lib/playbook/engine.rb
No 
[Runway URL](https://nitro.powerhrg.com/runway/backlog_items/NUXE-367)
No tests
=> [NUXE-367] Fix typeahead cursor position (REACT)

playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss, playbook/lib/playbook/engine.rb
No 
[Runway URL](https://nitro.powerhrg.com/runway/backlog_items/NUXE-315)
No tests
=> [NUXE-315] UX - KIT DEV - Remove extra Margin from selectable cards

playbook/app/pb_kits/playbook/docs_components/KitSearch.jsx, playbook/app/pb_kits/playbook/packs/site_styles/_site-style.scss, playbook/app/views/layouts/playbook/_nav.html.erb, playbook/app/views/layouts/playbook/_sidebar.html.erb, playbook/app/views/layouts/playbook/kits.html.erb, playbook/app/views/playbook/pages/visual_guidelines.html.erb, playbook/lib/playbook/engine.rb
1. Adds search to mobile screen sizes.
2. Fixes extra scroll bar on kit pages (`body.kits { scroll-y: hidden; }`).
3. Fixes small bug in KitSearch by adding null value handling.
4. Fixes dark text issue on Visual Guidelines page.
5. Unifies top nav and side bar page links.
n/a
[Link to Runway Story](https://nitro.powerhrg.com/runway/backlog_items/NUXE-346)
Test out mobile search in Milano deploy.
=> Add mobile search

playbook/lib/playbook/engine.rb
Reopened after reverting. We need to confirm this is not affecting Nitro. For example, slim rails is not used in Nitro so requiring it here might have unexpected problems.
fixes broken generator kit from [this darkmode pr](https://github.com/powerhome/playbook/pull/1238/files#)
[NUXE-378](https://nitro.powerhrg.com/runway/backlog_items/NUXE-378)
Run the kit generator command, possibly check dark-mode on some kits?
=> Fixes genrator error

.github/workflows/coverage.yml
This fixes the CI errors we were encountering by having the Node version too loose.
=> Specifying Node Version for Github Actions

playbook/app/pb_kits/playbook/pb_image/_image.scss
No
[Runway URL](https://nitro.powerhrg.com/runway/backlog_items/NUXE-396)
No testing
=> Add Object-fit: cover to Image Kit

playbook/app/pb_kits/playbook/pb_card/_card.scss
No
[Runway URL](https://nitro.powerhrg.com/runway/backlog_items/NUXE-380)
No testing
=> [NUXE-308] Set Overflow to be Auto on the Card Kit

playbook/app/pb_kits/playbook/pb_select/_select.scss
No
https://nitro.powerhrg.com/runway/backlog_items/NUXE-432
You can add CSS to select to make it smaller than the content.
=> Adds truncation for select kit

playbook/app/pb_kits/playbook/pb_distribution_bar/_distribution_bar.jsx, playbook/app/pb_kits/playbook/pb_distribution_bar/_distribution_bar.scss, playbook/app/pb_kits/playbook/pb_distribution_bar/distribution_bar.rb, playbook/app/pb_kits/playbook/pb_distribution_bar/docs/_distribution_bar_custom_colors.html.erb, playbook/app/pb_kits/playbook/pb_distribution_bar/docs/_distribution_bar_custom_colors.jsx, playbook/app/pb_kits/playbook/pb_distribution_bar/docs/_distribution_bar_custom_colors.md, playbook/app/pb_kits/playbook/pb_distribution_bar/docs/example.yml, playbook/app/pb_kits/playbook/pb_distribution_bar/docs/index.js, playbook/app/pb_kits/playbook/pb_select/_select.scss
No
https://nitro.powerhrg.com/runway/backlog_items/NUXE-414
https://nitro.powerhrg.com/runway/backlog_items/NUXE-415
1. You can add just 1 data and see that the bar is still rounded
2. You can add color props to customize colors.
=> Fixed Distribution Bar Cuttoff + added custom color props

playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.jsx, playbook/app/pb_kits/playbook/pb_typeahead/components/MultiValue.jsx
The reason you don't see this behavior on the examples on the [react-select homepage](https://react-select.com/home) examples is because they spread ALL the remove props ([here](https://github.com/JedWatson/react-select/blob/5bee3f40e74c165117a6765588ae906f07ad76f9/packages/react-select/src/components/MultiValue.js#L160)) to the default value label.
One of these props is "onMouseDown", which stops the event from propagating
([defined here ](https://github.com/JedWatson/react-select/blob/500398d93b8e2924ae49f6c786259cfd40dc0405/packages/react-select/src/Select.js#L1553))
So because we were just passing down the onclick prop, the mousedown event was propagating from our multivalue implementation to the control (the text input area) and triggering the menu
My first approach was to just add …
=> Prevent Typeahead menu opening on FormPill removal

playbook/app/pb_kits/playbook/pb_image/_image.jsx
No
N/A
1. View http://playbook.powerapp.cloud/kits/image/react
2. Open inspector and ensure the error above does not occur
=> Fix Image kit rounded prop warning

playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.html.erb, playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.jsx, playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss, playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_error.html.erb, playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_error.jsx, playbook/app/pb_kits/playbook/pb_selectable_card/docs/example.yml, playbook/app/pb_kits/playbook/pb_selectable_card/docs/index.js, playbook/app/pb_kits/playbook/pb_selectable_card/selectable_card.rb
This is not a breaking change. This PR simply adds an example variant to Selectable Card kit that displays what an error state would look like in both Rails and React (also included dark mode.)
https://nitro.powerhrg.com/runway/backlog_items/CMPN-379
=> [CMPN-379] Add Error State to Selectable Card

playbook/app/pb_kits/playbook/pb_flex/_flex_item.jsx, playbook/app/pb_kits/playbook/pb_flex/_flex_item.scss, playbook/app/pb_kits/playbook/pb_flex/flex_item.rb, playbook/app/pb_kits/playbook/pb_gauge/docs/_gauge_sizing.html.erb, playbook/app/pb_kits/playbook/pb_gauge/docs/_gauge_sizing.jsx, playbook/app/pb_kits/playbook/pb_gauge/docs/_gauge_sizing.md, playbook/app/pb_kits/playbook/pb_gauge/docs/example.yml, playbook/spec/pb_kits/playbook/kits/flex_item_spec.rb
Charts were not behaving correctly when nested inside of a flex item. The best remedy seemed to be adding "overflow: true" to the flex item, so that it would shrink its width and not keep the width of its child, when the screen was made smaller. This allows the highcharts javascript to detect the change in size and redraw the chart appropriately.
To accomplish this, the FlexItem kit has a new prop of `overflow` which takes any of the available values for overflow as a string, and by default does nothing.
https://user-images.githubusercontent.com/28073714/106659743-24501200-656d-11eb-8953-866ca50ba10b.mov
No - prop added that by default has no effect
[NUXE-349](https://nitro.powerhrg.com/runway/backlog_items/NUXE-349)
Check docs at 
/kits/gauge/rails
/kits/gauge/react
*The normal release …
=> [NUXE-349] Update gauge examples using overflow in flex item

playbook/app/pb_kits/playbook/_playbook.scss, playbook/app/pb_kits/playbook/utilities/_positioning.scss, playbook/app/pb_kits/playbook/utilities/globalProps.js, playbook/app/views/playbook/pages/visual_guidelines.html.erb, playbook/app/views/playbook/pages/visual_guidelines_partials/_pb_doc_positioning.html.slim, playbook/app/views/playbook/pages/visual_guidelines_partials/_positioning.html.slim, playbook/lib/playbook/props.rb
No 
[Runway URL](https://nitro.powerhrg.com/runway/backlog_items/NUXE-82)
No testing
=>  Add `zIndex` as a global prop

playbook/app/pb_kits/playbook/pb_select/_select.scss
NO
NA
Switch to dark mode and shrink the select till truncation appears on the select
=> fixup dark mode select truncation

playbook/app/pb_kits/playbook/pb_distribution_bar/_distribution_bar.scss, playbook/app/pb_kits/playbook/pb_distribution_bar/docs/_distribution_bar_custom_colors.html.erb, playbook/app/pb_kits/playbook/pb_distribution_bar/docs/_distribution_bar_custom_colors.jsx, playbook/app/pb_kits/playbook/pb_distribution_bar/docs/_distribution_bar_custom_colors.md
No
NA
See the docs under custom colors. The last option `Neutral` is new
=> Added status colors to the distribution bar

playbook/app/pb_kits/playbook/pb_card/card.rb, playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.jsx, playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_attributes.html.erb, playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_attributes.jsx, playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/example.yml, playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/index.js, playbook/app/pb_kits/playbook/pb_rich_text_editor/rich_text_editor.html.erb, playbook/app/pb_kits/playbook/pb_rich_text_editor/rich_text_editor.test.js
No - This add additional props with optional props.
[NUXE-447](https://nitro.powerhrg.com/runway/backlog_items/NUXE-447)
Has tests, attributes in new example as well.
=> Add data, aria, & name props to RichTextEditor

playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb
Above: The name prop is missing...
No, bug fix.
[NUXE-489](https://nitro.powerhrg.com/runway/backlog_items/NUXE-489)
Add name to kit.
=> Add name prop to typeahead with pills options

playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.scss
No
https://nitro.powerhrg.com/runway/backlog_items/NUXE-453
Check If the tooltip is centered
=> Fix tooltip - Center Arrows

playbook/app/pb_kits/playbook/pb_docs/kit_example.rb
Before...
After...
n/a
[Link to Runway Story](https://nitro.powerhrg.com/runway/backlog_items/NUXE-515)
Double check Milano deploy to see if markdown is displaying.
=> Reintroduce missing kit description markdown

playbook/app/pb_kits/playbook/pb_progress_simple/_progress_simple.jsx, playbook/app/pb_kits/playbook/pb_progress_simple/_progress_simple.scss, playbook/app/pb_kits/playbook/pb_progress_simple/docs/_progress_simple_variants.html.erb, playbook/app/pb_kits/playbook/pb_progress_simple/docs/_progress_simple_variants.jsx, playbook/app/pb_kits/playbook/pb_progress_simple/docs/_progress_simple_variants.md, playbook/app/pb_kits/playbook/pb_progress_simple/progress_simple.rb, playbook/spec/pb_kits/playbook/kits/progress_simple_spec.rb
RAILS
REACT
None -- only additive changes.
https://nitro.powerhrg.com/runway/backlog_items/CHMN-35
The easiest way is to go to the Progress Simple docs and look at the "Variants" example.
=> [CHMN-35] Add yellow as option to progress simple kit

playbook/app/pb_kits/playbook/pb_nav/_item.jsx, playbook/app/pb_kits/playbook/pb_nav/_nav.jsx, playbook/app/pb_kits/playbook/pb_nav/item.html.erb, playbook/app/pb_kits/playbook/pb_nav/nav.html.erb
Replaces `div` with `nav` html tags in nav kit.  Adds an `aria-label` to nav icons.
No visual changes
n/a
[Link to Runway Story](https://nitro.powerhrg.com/runway/backlog_items/NUXE-494)
Check nav html in Milano deploy.
=> Nav Kit - Accessibility Improvements (#1361)

playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb, playbook/app/pb_kits/playbook/pb_form/form.html.erb, playbook/app/pb_kits/playbook/pb_form/form.rb, playbook/app/pb_kits/playbook/pb_form/form_builder.rb, playbook/app/pb_kits/playbook/pb_form/form_builder/action_area.html.erb, playbook/app/pb_kits/playbook/pb_form/form_with.html.erb, playbook/app/pb_kits/playbook/pb_form/form_with.rb
Each playbook kit runs in its own view context, with a block that carries a context in itself. The way the form is setup, the context in which the block code is executed is ran within the kit context, not the same context it was created. This PR fixes this issue and simplify the form kit setup.
=> Fix form kit view context

playbook/app/pb_kits/playbook/pb_button/_button.jsx, playbook/app/pb_kits/playbook/pb_button/button.test.js, playbook/app/pb_kits/playbook/pb_button/docs/_button_default.jsx, playbook/app/pb_kits/playbook/pb_button_toolbar/button_toolbar.test.js, playbook/app/pb_kits/playbook/pb_circle_icon_button/circle_icon_button.test.js, playbook/app/pb_kits/playbook/utilities/test-utils.js
1. Adds React tests for Button, Button Toolbar, and Circle Icon Button kits.
2. Adds a test utility method that can be used to test click functionality.
n/a
[Link to Runway Story](https://nitro.powerhrg.com/runway/backlog_items/NUXE-325)
Pull locally and run `docker-compose run web yarn test`
=> Add React tests for Button, Button Toolbar, Circle Icon Button

playbook/app/pb_kits/playbook/pb_form/form_builder.rb, playbook/app/pb_kits/playbook/pb_form/form_builder/action_area.html.erb, playbook/app/pb_kits/playbook/pb_form/form_builder/action_area.rb, playbook/app/pb_kits/playbook/pb_form/simple_form.html.erb, playbook/app/pb_kits/playbook/pb_form/simple_form.rb
Form builders manipulate their view contexts and makes it hard to maintain the expected flow. This PR standardizes that across form with and simple form in Playbook and fixes the rendering of Action area buttons.
=> Fix forms and action area rendering context

playbook/app/pb_kits/playbook/pb_caption/_caption.jsx, playbook/app/pb_kits/playbook/pb_caption/caption.rb, playbook/spec/pb_kits/playbook/kits/caption_spec.rb
1. Adds `<caption>` html tag to Caption kit.
No visual changes.
n/a
[Link to Runway Story](https://nitro.powerhrg.com/runway/backlog_items/NUXE-498)
Try passing "caption" to tag prop in Caption kit.
=> Add caption html tag to Caption kit

playbook/app/pb_kits/playbook/pb_avatar/_avatar.jsx, playbook/app/pb_kits/playbook/pb_avatar/avatar.html.erb, playbook/app/pb_kits/playbook/pb_avatar/avatar.rb, playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_default.html.erb, playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_default.jsx, playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_status.html.erb, playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_status.jsx, playbook/app/pb_kits/playbook/pb_avatar_action_button/_avatar_action_button.jsx, playbook/app/pb_kits/playbook/pb_avatar_action_button/avatar_action_button.html.erb, playbook/app/pb_kits/playbook/pb_avatar_action_button/avatar_action_button.rb, playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/_avatar_action_button_actions.html.erb, playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/_avatar_action_button_actions.jsx, playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/_avatar_action_button_default.html.erb, playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/_avatar_action_button_default.jsx, playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/_avatar_action_button_on_click.jsx, playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/_avatar_action_button_onclick.html.erb, playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/_avatar_action_button_placement.html.erb, playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/_avatar_action_button_placement.jsx, playbook/app/pb_kits/playbook/pb_avatar_action_button/docs/_avatar_action_button_tooltip.html.erb, playbook/app/pb_kits/playbook/pb_avatar_action_button/pb_avatar_action_button.test.js, playbook/spec/pb_kits/playbook/kits/avatar_action_button_spec.rb, playbook/spec/pb_kits/playbook/kits/avatar_spec.rb
No - Added prop and it's variable and has a default
https://nitro.powerhrg.com/runway/backlog_items/NUXE-491
Add image alt prop and check render. Tests added.
=> Add image alt attributes as props to avatar kits

playbook/app/pb_kits/playbook/data/menu.yml, playbook/app/pb_kits/playbook/pb_online_status/_online_status.jsx, playbook/app/pb_kits/playbook/pb_online_status/online_status.html.erb
1. Adds an `aria-label` to the Online Status kit matching it's status prop (i.e. online, offline, away)
2. Removes Online Status kit from `menu.yml` (no longer visible in the docs)
No visual changes
No
[Story 1](https://nitro.powerhrg.com/runway/backlog_items/NUXE-529)
[Story 2](https://nitro.powerhrg.com/runway/backlog_items/NUXE-499)
Check the `aria-label` on the Avatar kit's online status (both React and Rails).  Confirm that the Online Status kit no longer appears in the docs.
=> Online Status Accessibility Improvements

playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb, playbook/app/pb_kits/playbook/pb_form/form_with.rb, playbook/spec/pb_kits/playbook/pb_form/form_with_spec.rb
Fixes the FormWith kit to allow the user to not set `url`.
None
`form/form_with` should allow the user to only set the `model` and let rails figure out the route.
=> Allow url to be empty so form_with can generate a url based on the model

playbook/package.json
Playbook shouldn't care about the versions of these tools because they are only used to install it, and playbook doesn't depend on them at runtime.
This unblocks things like https://github.com/powerhome/tempo/pull/142.
=> Don't specify compatible versions of npm/yarn

playbook/Makefile
Removes build flag on `make start` to speed up dev startup
=> Do not build everything on every start up

playbook/app/pb_kits/playbook/tokens/_colors.scss
No
https://nitro.powerhrg.com/runway/backlog_items/NUXE-500
Inspect the Caption kit or Body Light and see that the color being used is #687887
=> Update body light & lighter to a more accessible color

playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
No
https://nitro.powerhrg.com/runway/backlog_items/NUXE-586
Check focus state on sticky rich text editor
=> Fix Rich text Focus State

playbook/app/pb_kits/playbook/pb_dialog/dialog_header.rb, playbook/app/pb_kits/playbook/pb_select/_select.jsx, playbook/app/pb_kits/playbook/pb_select/_select.scss, playbook/app/pb_kits/playbook/pb_select/select.rb, playbook/spec/pb_kits/playbook/kits/select_spec.rb
No - Sets defaults, new margin bottom 
[NUXE-479](https://nitro.powerhrg.com/runway/backlog_items/NUXE-479)
Playbook Select margin should look identical but expand if new margin is added.
=> [NUXE-479] - Add margin overrides to select

playbook/app/pb_kits/playbook/pb_flex/_flex_item.jsx
No
https://nitro.powerhrg.com/runway/backlog_items/NUXE-609[INSERT URL]
right click on any flex item kit and inspect element check the flex item kit class. If undefined does not appear this PR has resolved the issue.
=> Set a default value for flex items

playbook/app/pb_kits/playbook/pb_date/_date.jsx, playbook/app/pb_kits/playbook/pb_date/date.html.erb, playbook/app/pb_kits/playbook/pb_date/docs/_date_variants.html.erb, playbook/app/pb_kits/playbook/pb_date/docs/_date_variants.jsx
No, breaking changes. Icon for md is being handled by an < if else > statement.
[NUXE-585](https://nitro.powerhrg.com/runway/backlog_items/NUXE-585)
Visually assessed that the icon was the correct size for size small. Checked to verify that size md (default) icon was not affected.
=> Date variant small with icon

playbook/app/pb_kits/playbook/pb_nav/_vertical_nav.scss, playbook/app/pb_kits/playbook/pb_nav/docs/_block_nav.html.erb, playbook/app/pb_kits/playbook/pb_nav/docs/_block_nav.jsx, playbook/app/pb_kits/playbook/pb_user/_user.scss
*Before*
*After*
*Old NavItem Block  doc example*
*New NavItem Block doc example*
No –– this PR only affects the CSS class in User Kit.
https://nitro.powerhrg.com/runway/backlog_items/NUXE-584
I tested this bug by updating the doc example so that a User Kit is in Nav/NavItem to confirm that the styling is behaving as expected.
=> Updated user css file

playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.jsx, playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.scss, playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_multi_line.html.erb, playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_multi_line.jsx, playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_multi_line.md, playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/fixed_confirmation_toast.rb, playbook/spec/pb_kits/playbook/kits/fixed_confirmation_toast_spec.rb
No, this should not affect any current uses of the kit.
https://nitro.powerhrg.com/runway/backlog_items/CHMN-64
Open up PB and go to the multi-line Fixed Confirmation Toast doc. Resize your screen and watch the text stack!
=> [CHMN-64] Playbook - Fixed Confirmation Toast Responsive

playbook/hot.sh
Just a simple shell script for hot loading a local distribution into another repo's `node_modules` for local testing.
Useage: `./hot.sh $OTHER_LOCAL_REPO`
=> Add 🥵 script

playbook/app/pb_kits/playbook/pb_passphrase/useZxcvbn.js
By trying to rely on a value set in a use state hook, the logic for which color to show was one input behind, and therefore showing the wrong color when thresholds are crossed.
No, fixes an issue
[CHMN-78](https://nitro.powerhrg.com/runway/backlog_items/CHMN-78)
https://playbook.powerapp.cloud/kits/popover/react
Look at the example kit on the Passphrase page in playbook that shows the strength on the page. This number is right, the meter should match. (0,1 are red, 2 is yellow, 3,4 is green the default settings)
=> [CHMN-78] Hotfix passphrase strength bar display

playbook/app/pb_kits/playbook/pb_button/_button.jsx, playbook/app/pb_kits/playbook/pb_button/button.rb, playbook/app/pb_kits/playbook/pb_button/docs/_button_accessibility.html.erb, playbook/app/pb_kits/playbook/pb_button/docs/_button_accessibility.jsx, playbook/app/pb_kits/playbook/pb_button/docs/_button_link.html.erb, playbook/app/pb_kits/playbook/pb_button/docs/_button_link.jsx, playbook/app/pb_kits/playbook/pb_button/docs/_button_loading.html.erb, playbook/app/pb_kits/playbook/pb_button/docs/_button_loading.jsx
Code speaks for itself but here is one just in case:
No - Handling of `aria` props is still accepting an object.
[NUXE-490](https://nitro.powerhrg.com/runway/backlog_items/NUXE-490)
View Button and code in the console in Playbook
=> [NUXE-490] - Update Button for A11y (OKR)

playbook/.sops.yaml, playbook/config/deploy/production/secrets.yaml, playbook/config/deploy/prs/secrets.yaml, playbook/config/deploy/staging/secrets.yaml
This causes SOPS to assume the UX role when accessing these secrets, which is necessary based on the new permissions model which grants selective access to KMS keys. Use of the key without a role is also retained for Milano's access.
Previously, all members of the Developers group had access to all KMS keys. We're moving toward access only to those keys which protect secrets that are within the remit of specific groups.
Only UX need access to Playbook secrets.
https://nitro.powerhrg.com/runway/backlog_items/GOG-421
=> [GOG-421] Use UX AWS role for SOPS decryption

playbook/app/pb_kits/playbook/pb_passphrase/_passphrase.jsx
"passphrase-tips" is the new classname 
No, additive changes to the passphrase kit. Other kits not affected. Passphrase kit not used yet (but will be soon)
As a Nitro developer I want a way to specifically target the passphrase tips popover so that I can safely apply custom styles in Nitro without affecting other popover elements. 
[RunwayT URL](https://nitro.powerhrg.com/runway/backlog_items/CHMN-98)
/kits/passphrase/react
/kits/passphrase/
See that the popover has a classname - "passphrase-tips"
=> [CHMN-98] Add classname to popover on passphrase kit 

playbook/app/pb_kits/playbook/pb_select/_select.jsx
Fixes a bug related to positioning of Icon kit in Select kit. 
No
https://nitro.powerhrg.com/runway/backlog_items/NUXE-655
View under "Select w/ Error Toggle" section 
=> [NUXE-655] Move error text

playbook/app/pb_kits/playbook/pb_date_time/docs/_date_time_default.jsx
PROBLEM
FIX
None. This is just a slight change to the docs to make sure that the date and time are showing up correctly in firefox.
https://nitro.powerhrg.com/runway/backlog_items/LGA-719
Go to `kits/date_time/react` in your browser and check the default docs. You MUST do this in *firefox* because the bug only exists in firefox.
=> [LGA-719] Fix invalid date in Date Time docs for Firefox

playbook/app/pb_kits/playbook/pb_passphrase/_passphrase.jsx
No new visuals.
No, additive changes to the passphrase kit. Other kits not affected. Passphrase kit not used yet (but will be soon)
We had an issue where clicking on the "eye" icon would trigger the "info" icon to open its popover. 
[Runway URL](https://nitro.powerhrg.com/runway/backlog_items/CHMN-101)
/kits/passphrase/react
/kits/passphrase/
See that clicking on the eye icon inside the tips example does not open the info icon popover 
=> [CHMN-101] Don't allow popover to open when clicking on eyeball in the passphrase kit

playbook/app/pb_kits/playbook/pb_dialog/_dialog.jsx, playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_default.jsx
This PR takes the value of a Dialog's `portalClassName` prop:
and adds it to the React Modal portal's `div` class attribute:
This will allow a specific Dialog's modal to be targeted for CSS or JavaScript purposes.
No breaking changes. If the `className` prop isn't present then it's not added to the list of CSS class names.
https://nitro.powerhrg.com/runway/backlog_items/BOP-968
=> Add the value of a Dialog's portalClassName prop to the React Modal portal DIV class attribute

playbook/app/pb_kits/playbook/pb_message/_message.jsx, playbook/app/pb_kits/playbook/pb_message/_message_mixins.scss, playbook/app/pb_kits/playbook/pb_message/docs/_message_default.html.erb, playbook/app/pb_kits/playbook/pb_message/docs/_message_default.jsx, playbook/app/pb_kits/playbook/pb_message/docs/_message_timestamp.html.erb, playbook/app/pb_kits/playbook/pb_message/docs/_message_timestamp.jsx, playbook/app/pb_kits/playbook/pb_message/docs/example.yml, playbook/app/pb_kits/playbook/pb_message/docs/index.js, playbook/app/pb_kits/playbook/pb_message/message.html.erb, playbook/app/pb_kits/playbook/pb_message/message.rb
https://app.abstract.com/share/00ce8869-748b-4ac2-9d38-07083137a6a6?collectionId=afd8ed52-e16b-4afd-b503-f8bc6cf2e80b&collectionLayerId=76a6e707-0640-4352-a903-b37714f4be41&present=true&preview=false&sha=32ff4fbf2dce3bedb52ab8f7e2261e3479cdb658
Normal:
On hover:
No breaking changes. A change was made that you can now pass this kit a `timestamp_object`, which is like `DateTime.current`. When this is present, the hover effect will work, otherwise it will not.
https://nitro.powerhrg.com/runway/backlog_items/BOP-979
=> [BOP-979] Enhance message kit to accept timestamp object for hover

playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.jsx, playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_async_createable.jsx, playbook/app/pb_kits/playbook/pb_typeahead/docs/example.yml, playbook/app/pb_kits/playbook/pb_typeahead/docs/index.js
Adds `AsyncCreatable` as an option if `async` prop is provided. 
None
No
None
See the documentation for an example. New feature enhancement.
=> Typeahead AsyncCreatable

playbook/package.json, playbook/private/tasks/pb_release.rake, playbook/webpack.config.js, yarn.lock
The pb_release task is responsible for releasing playbook, but it also cleans up some of the extra files generated by webpack. This doesn't work when we're in development mode because we need the dist directory to always have up-to-date, release-ready files.
No visual change
No
[NUX-2012](https://nitro.powerhrg.com/runway/backlog_items/NUX-2012)
Test development mode changing CSS.
=> [NUX-2012] Move dist cleanup to webpack

playbook-website/bin/deployer
This gets us a newer version of krane (1.1.3 -> 2.2.0) which we think handles mismatched CRD versions within an apiGroup better.
See:
* https://github.com/Shopify/krane/issues/804
* https://github.com/powerhome/nitro-web/pull/21909
* https://github.com/powerhome/portal/pull/125
* https://github.com/powerhome/incidents/pull/8
* https://github.com/powerhome/APP/pull/1180
=> Use recent deployer image

Dockerfile
This changeset applies the suggestion https://github.com/phusion/passenger-docker/issues/322#issuecomment-932263996 to fix an issue with an expired certificate (https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/).
[INSERT URL]
=> Update image to fix certificate issue

playbook/app/pb_kits/playbook/pb_home_address_street/home_address_street.rb
The kit was causing an error whenever a "city" was `nil` because of the use of `titleize`. The other fields (address, addresscont, etc) in the kit have the `&` operator when using `titleize` to prevent errors, but "city" got overlooked. This PR remedies that problem.
EXAMPLE:
ERROR:
No only additive changes.
https://nitro.powerhrg.com/runway/backlog_items/LGA-1009
Try putting `nil` in for the "city" field in the examples already created for the kit.
=> Add & operator to guard against nil

playbook/app/pb_kits/playbook/pb_caption/_caption.scss, playbook/app/pb_kits/playbook/pb_caption/_caption_mixin.scss
BEFORE: 
AFTER: 
No. This PR is fixing a bug on dark mode colors setup in Caption kit. 
https://nitro.powerhrg.com/runway/backlog_items/PLAY-98
Turn on dark mode and open the dev tools in a browser. `dark` should be added inside the class name , and the color should be white.
=> [PLAY-98] fIxed dark mode colors

playbook/app/pb_kits/playbook/pb_popover/docs/_popover_scroll_height.jsx, playbook/app/pb_kits/playbook/pb_popover/docs/_popover_z_index.jsx
BEFORE DESKTOP VIEW: 
AFTER DESKTOP VIEW:
https://nitro.powerhrg.com/runway/backlog_items/PLAY-80
Go to the popover kit page in playbook, then click on "Click Me" for the Z INDEX & the SCROLL AND HEIGHT SETTINGS
=> [Play-80] Updating padding prop to popover kit

playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss
BEFORE:
AFTER:
No, this was a bug that is being fixed by overriding the padding inherited from the card kit when creating an add on.
[https://nitro.powerhrg.com/runway/backlog_items/PLAY-44](url) (Original story)
1. Use a text input kit with an add-on in React
2. Make sure that the input and add-on are in line with eachother
=> [PLAY] Override add on padding for text input

playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.scss, playbook/app/pb_kits/playbook/pb_section_separator/_section_separator_mixin.scss
No. This PR is fixing margin default on section separator kit with vertical orientation.. Default remains the same- 8px margin left and 8px margin right. Developer can pass a margin prop to overwrite the default.
[[Runway ticket]](https://nitro.powerhrg.com/runway/backlog_items/PLAY-103)
Add a margin left or right to overwrite the default.
=> [PLAY-103] Section separator: Add ability to remove margin from vertical orentation

playbook/app/pb_kits/playbook/pb_date/_date.jsx, playbook/app/pb_kits/playbook/pb_date/date.html.erb
BEFORE PIC DESKTOP VIEW: 
AFTER PIC DESKTOP VIEW: 
No breaking change 
https://nitro.powerhrg.com/runway/backlog_items/PLAY-62
Go to the date kit, scroll down to the variants option.... notice the icon size change. (reference pictures)
=> [Play-62] Updating size for icon on variant prop

playbook/app/pb_kits/playbook/pb_body/_body.jsx, playbook/app/pb_kits/playbook/pb_caption/_caption.jsx, playbook/app/pb_kits/playbook/pb_caption/_caption.scss, playbook/app/pb_kits/playbook/pb_caption/caption.rb, playbook/app/pb_kits/playbook/pb_title/_title.jsx, playbook/app/pb_kits/playbook/pb_title/title.rb
A patch fix for a breaking change that removed variant prop on title and caption kit that was being used in Nitro.
=> Added back variant prop and tested for Title and Caption

playbook/app/pb_kits/playbook/pb_popover/_popover.jsx, playbook/app/pb_kits/playbook/pb_popover/docs/_popover_close.html.erb, playbook/app/pb_kits/playbook/pb_popover/index.js, playbook/app/pb_kits/playbook/pb_popover/popover.html.erb
Yes, this change affects how the popover is closed, so this could possibly be breaking when sensitive data or edits/updates that need to be confirmed are rendered inside of a popover tooltip. Alpha testing is needed.
[https://nitro.powerhrg.com/runway/backlog_items/PLAY-82](url)
- Create a React or Rails page and use 2 or more pop over kits on the same page
- Set at least one of the `close_on_click` values to "any"
- Click between the buttons (not outside, or in the popover itself. The actual trigger elements), to make sure that when a new popover is rendered, any open popover on the page will disappear.
=> [Play-82]Bug Popover close on any

playbook/app/pb_kits/playbook/pb_file_upload/_file_upload.jsx, playbook/app/pb_kits/playbook/pb_file_upload/fileupload.test.js
BEFORE:
https://user-images.githubusercontent.com/82796889/152414334-9ba8e405-43b0-4a0b-a1b5-93c5da41cd58.mov
AFTER: 
https://user-images.githubusercontent.com/82796889/152415131-547a72f4-e08f-4ce9-b1ec-1de488300e11.mov
No. This PR is fixing a bug that was causing File Upload kit to not accept all file types. Setting accept prop default as null will fix the issue. 
[[INSERT URL](https://nitro.powerhrg.com/runway/backlog_items/PLAY-16)]
Open a browser, go to File Upload kit and try adding different types of files.
=> [PLAY-16] File Upload Kit: Can't upload Pages, Numbers, and Keynote files [#1575]

playbook/app/pb_kits/playbook/pb_avatar/_avatar.jsx, playbook/app/pb_kits/playbook/pb_avatar/_avatar.scss, playbook/app/pb_kits/playbook/pb_avatar/avatar.rb, playbook/app/pb_kits/playbook/pb_avatar/avatar.test.js, playbook/spec/pb_kits/playbook/kits/avatar_spec.rb
BEFORE
AFTER
BELOW: ALL SCREENSHOTS ARE FROM ALPHA TEST
SALES REPS 
USER PROFILE
POWER STORY
RUNWAY
Video Showcasing how adding a size props no longer changes that avatar kit size. Test done in alpha:
https://user-images.githubusercontent.com/92755007/152423540-60d3b209-286c-4181-bdb6-bb5d1fa6b9ca.mov
This will add word `size` on avatar kits but the actual size will remain the same. The only thing we need to do is make sure avatar kits with size on are not being targeted anywhere in Nitro so we can safely update the classname.
[INSERT URL]
Add a margin or padding prop to the avatar kit and see if image size will change.
=> [PLAY-111] Size Prop styling needs to be corrected: Avatar

playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.jsx
BEFORE
SEE VIDEO:
[Reproducing bug- editor does not update when value change ](https://user-images.githubusercontent.com/82796889/152073557-147ef5b9-4aa6-4cb6-a961-cfe88a2b8f91.mov)
AFTER
SEE VIDEO: 
https://user-images.githubusercontent.com/82796889/152073624-332cfaf0-dcc2-4d6f-adab-734070010c47.mov
No. This PR is fixing a bug on React Rich Text Editor kit. The problem was when value prop  is changed externally editor content will not update, meaning if we set a value as a state and we attempt to change state value editor will not reflect those changes. 
[[INSERT URL](https://nitro.powerhrg.com/runway/backlog_items/PLAY-17)]
To reproduce this we need to pass value as a state, and have an external button change this state onClick. When this state is changed, the trix editor content should …
=> [PCA-17] React Rich Text Editor Kit: Field doesn't update with an external value update [#1579]

playbook/app/pb_kits/playbook/pb_image/_image.jsx, playbook/app/pb_kits/playbook/pb_image/_image.scss, playbook/app/pb_kits/playbook/pb_image/image.rb, playbook/app/pb_kits/playbook/pb_image/image.test.js, playbook/spec/pb_kits/playbook/kits/image_spec.rb
BEFORE
AFTER
This will add word `size` on image kits but the actual size will remain the same. The only thing we need to do is make sure image kits with size on are not being targeted anywhere in Nitro so we can safely update the  classname.
[[INSERT URL](https://nitro.powerhrg.com/runway/backlog_items/PLAY-112)]
Add a margin or padding prop to the image kit and see if image size will change.
=> [PLAY-112] Size Prop styling needs to be corrected: Image Kit

playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss, playbook/app/pb_kits/playbook/pb_text_input/text_input.test.js, playbook/spec/pb_kits/playbook/kits/text_input_spec.rb
Breaking Changes
No. The default `margin-bottom` small  was removed from the `text_input_wrapper`, but added to the `pb_text_input_kit` class (by default). Visually, any existing implementations of the text input kit will remain the same.
Runway Ticket URL
https://nitro.powerhrg.com/runway/backlog_items/PLAY-76
How to test this
The text input kit should have a small margin on the bottom by default. Developer can pass a margin-bottom prop to text input kit and the default margin-bottom will be overridden.
=> [PLAY-76]Text Input kit spacing fixed

playbook/app/pb_kits/playbook/pb_text_input/_text_input.jsx
No. A unique key prop was added to the actual input element of the Text Input kit, clearing the error message that usually persists in the console when working with this kit in React.
[https://nitro.powerhrg.com/runway/backlog_items/PLAY-91](url)
1. Navigate to http://localhost:3000/kits/text_input/react
2. Open console log
3. Check to make sure error is not there anymore
=> [PLAY-91] Add unique key prop to text input

playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_height.jsx
BEFORE: 
AFTER: 
No. This PR is fixing a bug on React Line Graph kit. One of the doc examples is showing a graph when height is fixed(`height="300px"`) but the height prop is missing which shows incorrect kit example. 
https://nitro.powerhrg.com/runway/backlog_items/NUX-2724
Open a browser and go to Line Graph kit. Under the `Height` section there's a fixed height graph. Open a code example and see `height="300px"` being passed to the kit.
=> React Line Graph - line graph height doc example missing a fixed height prop

playbook/app/pb_kits/playbook/pb_icon/icon.rb
No. Should address a single Deprecation Warning.
[HFH-705](https://nitro.powerhrg.com/runway/backlog_items/HFH-705)
=> Addressing deprecation warning in order to avoid using Kernel.open

playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss
BEFORE: 
AFTER:
No. This PR is fixing an alignment on the form group kit. 
[[INSERT URL](https://nitro.powerhrg.com/runway/backlog_items/PLAY-127)]
Open a a browser and inspect form group kit. All kits inside the form group should be aligned correctly.
=> Form Group Kit alignment bug fixed

playbook/app/pb_kits/playbook/pb_button/_button.scss
BEFORE:
AFTER:
No. This PR is fixing a button's min-height bug. 
[[INSERT URL](https://nitro.powerhrg.com/runway/backlog_items/PLAY-126)]
Open a browser and inspect a button kit styles. Only `sm` size button should have `min-height: 0`. Every other size, including the default, should have `min-height: 40`
=> Button's min-height bug fix

playbook/app/pb_kits/playbook/pb_dialog/_dialog.scss
Sometimes for some people the dialog kit has a border on the right and bottom sides. I have changed the scss from `overflow: scroll` to `overflow:auto` and this fixed the problem for me.
PROBLEM:
SOLUTION:
No. This change shouldn't break anything.
Check to make sure the dialog kit is working without the strange border. For some people this bug was not reproducible and we're not sure why.
=> Dialog Kit shows a strange border intermittently

playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.jsx, playbook/app/pb_kits/playbook/pb_pill/_pill.jsx, playbook/app/pb_kits/playbook/pb_title/_title.tsx, playbook/app/pb_kits/playbook/pb_title/title.test.js
WIP
No
https://nitro.powerhrg.com/runway/backlog_items/PLAY-146
Test in Milano enviroment
=> [PLAY-146]Title Kit Convert to Typescript

playbook/app/pb_kits/playbook/tokens/_colors.scss
[[PLAY-123]](https://nitro.powerhrg.com/runway/backlog_items/PLAY-123)
=> [PLAY-123] Added red_dark color and updated error_dark value

playbook-website/app/javascript/site_styles/_site-style.scss, playbook-website/app/views/pages/kit_show.html.erb, playbook/app/pb_kits/playbook/pb_table/_table.jsx, playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky.html.erb, playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky.jsx, playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky.md, playbook/app/pb_kits/playbook/pb_table/docs/example.yml, playbook/app/pb_kits/playbook/pb_table/docs/index.js, playbook/app/pb_kits/playbook/pb_table/styles/_all.scss, playbook/app/pb_kits/playbook/pb_table/styles/_sticky_header.scss, playbook/app/pb_kits/playbook/pb_table/table.rb, playbook/app/pb_kits/playbook/pb_table/table.test.js, playbook/spec/pb_kits/playbook/kits/table_spec.rb
https://user-images.githubusercontent.com/84343331/166304855-2b881d65-e8b6-4b8b-a123-89d2cf1936e2.mov
No, this adds a new prop with a `false` default value so nothing in Nitro will be affected until the prop is passed a `true` value.
[PLAY-67](https://nitro.powerhrg.com/runway/backlog_items/PLAY-67)
Add the `sticky` prop with a value of `true` and see if the table header sticks when you scroll down.
=> Add Sticky Header Prop for Table Kit

playbook-website/config/deploy/production/values.yaml, playbook-website/config/deploy/prs/values.yaml, playbook-website/config/deploy/staging/values.yaml
Because of this type the `certificate` resource wasn't being created and because of that cert-manager didn't know that it needed to manage that certificate.
____
[INSERT URL]
=> fix issuerCert typo prod

playbook-website/app/views/pages/kit_show.html.erb
Before: 
After:
No, fixing a bug.
[Play-198](https://nitro.powerhrg.com/runway/backlog_items/PLAY-198)
=> [PLAY-198] Fix Title Bug

playbook/lib/playbook/pb_kit_helper.rb
When using Playbook with Rails 7, the `pb_rails` method attempts to call `render_component` which does not work in later versions of Rails.
Output:
```
undefined method `render_component' for #<ActionView::Base:0x00000000010a68>
Did you mean?  react_component
```
For later Rails versions, `render` should be used instead. Using `respond_to?` should prevent any breaking changes.
=> [Rails 7 fix] Conditionally use render_component method in PbKitHelper

playbook/app/pb_kits/playbook/pb_card/_card.tsx, playbook/app/pb_kits/playbook/utilities/props.ts
=> Fix Incorrect Type Declaration and Card Kit buildCss for Highlight Class

playbook/app/pb_kits/playbook/pb_stat_value/docs/_stat_value_default.md, playbook/app/pb_kits/playbook/pb_stat_value/docs/_stat_value_precision.html.erb, playbook/app/pb_kits/playbook/pb_stat_value/docs/_stat_value_precision.md, playbook/app/pb_kits/playbook/pb_stat_value/docs/example.yml, playbook/app/pb_kits/playbook/pb_stat_value/stat_value.rb, playbook/spec/pb_kits/playbook/kits/stat_value_spec.rb
**Pay attention to your PR titles and use Title Case!**
Here is a bad 👎 example: "Updates kit props and children"
_Why is it bad? Indistinct title which is not using title case._
Here is a good 👍 example: "Updates Props and Children in Body Kit"
_Why is it good? Distinct title which is using title case._
____
I dont think there should be. For places already using the kit its okay if they dont specify the precision so it shouldnt break existing usage
https://nitro.powerhrg.com/runway/backlog_items/FINC-1393
make sure you see the precision prop (?) and it shows the right about of decimals specifies
=> [FINC-1393] Add Precision to Stat Value Kit

playbook/app/pb_kits/playbook/pb_contact/_contact.jsx, playbook/app/pb_kits/playbook/pb_contact/contact.rb, playbook/app/pb_kits/playbook/pb_contact/contact.test.js, playbook/app/pb_kits/playbook/pb_contact/docs/_contact_with_detail.html.erb, playbook/app/pb_kits/playbook/pb_contact/docs/_contact_with_detail.jsx, playbook/spec/pb_kits/playbook/kits/contact_spec.rb
No breaking changed.  Added a new `extention` option to the prop `contactType`, making it possible to display 4-digit phone extensions.
[PLAY-194](https://nitro.powerhrg.com/runway/backlog_items/PLAY-194)
=> [PLAY-194] Contact Kit Update: Extension Variant

playbook/app/pb_kits/playbook/pb_bread_crumbs/docs/_description.md
The description for the `BreadCrumbs` component used "there" instead of "their." This PR fixes that typo.
**Note**: I don't think I have permissions to add labels, but this PR is ready for review.
____
No
run locally
=> Fix Minor Typo

playbook/app/pb_kits/playbook/pb_icon_circle/_icon_circle.tsx
No, PR just converts all .jsx files in Icon Circle kit to .tsx
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-260)
Review in Milano environment
=> [PLAY-260]-TS-Conversion of Icon Circle Kit

playbook/app/pb_kits/playbook/pb_date_picker/date_picker.test.js, playbook/jest.config.js
No
https://nitro.powerhrg.com/runway/backlog_items/PLAY-297
Passes CI = good to go.
=> [PLAY-297] Fixing Jest Test that Breaks CI Intermittently

playbook/app/pb_kits/playbook/pb_form_group/_form_group.tsx, playbook/app/pb_kits/playbook/pb_form_group/form_group.test.js, playbook/app/pb_kits/playbook/utilities/props.ts
T]
No breaking changes. I had to also change a typing in `props.ts` regarding the `buildCss` function, it should accept booleans as well.
[[PLAY-257]
](https://nitro.powerhrg.com/runway/backlog_items/PLAY-257)
Open the localhost and try the kit with different props. Check if the console has any error.
=> [PLAY-257] Typescript Conversion: Form Group

playbook/app/pb_kits/playbook/pb_lightbox/lightbox.test.jsx
Lightbox Jest Tests are failing for the last two which make use of keyboard events to remove the lightbox from the view.
The problem is: we are writing tests to check for non-existence of the subject (kit)
✅ Solution: mock the `api.onClose` function in the Jest test. Then, instead of checking for the subject to be removed, check for the aforementioned function to have been called.
N/A
No
[INSERT URL]
`(cd playbook; yarn run jest playbook/app/pb_kits/playbook/pb_lightbox/lightbox.test.jsx)`
=> Fix Lightbox Jest Tests

playbook/app/pb_kits/playbook/pb_layout/_layout.tsx, playbook/app/pb_kits/playbook/pb_layout/layout.test.js, playbook/app/pb_kits/playbook/utilities/props.ts
No breaking changes. Typescript conversion of the layout Kit and Jest test.
[[PLAY-266]](https://nitro.powerhrg.com/runway/backlog_items/PLAY-266)
Create multiple versions of the Layout Kit. 
Run `yarn test`.
Check for console or visual errors.
=> [PLAY-266] Typescript Conversion: Layout

playbook-website/app/controllers/pages_controller.rb, playbook-website/app/javascript/components/ReactSidebar/index.tsx, playbook-website/app/javascript/components/Sidebar/index.tsx, playbook-website/app/javascript/components/VisualGuidelines/Templates/Example.tsx, playbook-website/app/javascript/components/VisualGuidelines/index.tsx, playbook-website/app/javascript/packs/application.js, playbook-website/app/javascript/packs/react_sidebar.js, playbook-website/app/views/layouts/_sidebar.html.erb, playbook-website/app/views/pages/visual_guidelines_react.html.erb
No breaking changes, adding to playbook website only
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-311)
Test in milano env
=> [Play-311] - Add Sidebar For Visual Guidelines React Page

playbook-website/app/javascript/components/VisualGuidelines/Examples/LineHeight.tsx, playbook-website/app/javascript/components/VisualGuidelines/Examples/Positioning.tsx, playbook-website/app/javascript/components/VisualGuidelines/Examples/Spacing.tsx, playbook-website/app/javascript/components/VisualGuidelines/Templates/SpacingProps.tsx, playbook-website/app/javascript/site_styles/_visual_guidelines.scss
No breaking changes, edits to visual guidelines react styling
Screenshots of what screens looked like before changes can be seen on linked runway ticket: 
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-317)
Review in milano env at /visual_guidelines_react 
Changes to Spacing, Positioning and Line Height examples
=> [PLAY-317] - Visual Guidelines Improvements

playbook/app/pb_kits/playbook/pb_timestamp/_timestamp.jsx, playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed.html.erb, playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed.jsx, playbook/app/pb_kits/playbook/pb_timestamp/timestamp.rb, playbook/app/pb_kits/playbook/pb_timestamp/timestamp.test.js
No breaking changes, added a new optional prop that allows users to not display 'Last Updated' text on elapsed variant. Default is set to display the text.
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-301)
Review Timestamp Kit in milano env, example titled 'Time Ago'. Last item in example should display timestamp without 'Last updated' Text prefixing it.
=> [Play-301]- Timestamp Kit Last Updated Text as Optional Prop

playbook/app/pb_kits/playbook/pb_layout/layout.test.js
Removes noise from jest output
=> Remove console.log from Layout Kit

playbook/app/pb_kits/playbook/pb_text_input/_text_input.tsx
No breaking changes. Fixed the bug that was causing the input to not display in full-width.
[[PLAY-332]](https://nitro.powerhrg.com/runway/backlog_items/PLAY-332)
Use Text Input kit sending the `addOn` prop. Test in multiple forms.
=> [PLAY-332] Bug - Text Input not full-width with addOn prop

playbook/app/pb_kits/playbook/pb_icon_stat_value/_icon_stat_value.tsx, playbook/app/pb_kits/playbook/pb_icon_stat_value/icon_stat_value.test.js
No breaking changes, converted .jsx to .tsx and added jest test
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-261)
review in milano env, make sure kit functions as expected in each example
=> PLAY-261-TS Conversion Icon Stat Value Kit + Jest Test

playbook/jest.config.js
Often playbook builds use a large amount of memory, and are constantly sitting right up against their limits. We've seen OOMKills when there just aren't enough resources to go around. This will reduce the amount of memory used.
=> Limit Number of Jest Workers

playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_flatpickr_styles.scss
No breaking changes, fixes to SCSS that were breaking date pickr with time variant in Nitro
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-343)
Test in milano env as well as in nitro in dev_docs. Check to make sure 'Time Selection' version of date Pickr renders as expected and SCSS functions properly.
=> [PLAY-343]- Date Pickr SCSS Bug Fix

playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.tsx
No breaking changes. The kit was obligating the user to declare props, but the `line separator` doesn't need any to work.
[[PLAY-331]
](https://nitro.powerhrg.com/runway/backlog_items/PLAY-331)
- Run tests locally
- Try implementing the kit in different ways with and without props.
=> [PLAY-331] Section Separator Type Bug

playbook-website/app/javascript/components/VisualGuidelines/Examples/Spacing.tsx, playbook/app/pb_kits/playbook/tokens/_spacing.scss, playbook/app/pb_kits/playbook/utilities/_spacing.scss, playbook/lib/playbook/spacing.rb
No breaking changes, adds a new size for spacing tokens (xxs)
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-344)
Review in milano env.
=> [PLAY-344]- Add XXS Spacing Token

playbook/app/pb_kits/playbook/pb_date_range_stacked/_date_range_stacked.tsx, playbook/app/pb_kits/playbook/pb_date_range_stacked/date_range_stacked.test.js
No breaking changes, converted .jsx file to .tsx and added Jest test
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-217)
Review in milano env, confirm that kit example functions as expected.
=> [PLAY-217]- Convert Date Range Stacked to TS + Added Jest Test

playbook/app/pb_kits/playbook/pb_lightbox/Carousel/Slides.tsx, playbook/app/pb_kits/playbook/pb_lightbox/Carousel/Thumbnails.tsx, playbook/app/pb_kits/playbook/pb_lightbox/Carousel/index.tsx, playbook/app/pb_kits/playbook/pb_lightbox/Header/_lightbox_header.tsx, playbook/app/pb_kits/playbook/pb_lightbox/Header/_lightbox_header_icon.tsx, playbook/app/pb_kits/playbook/pb_lightbox/_lightbox.tsx, playbook/app/pb_kits/playbook/pb_lightbox/lightbox.scss
No, fixes bug where thumbnails at bottom of screen were not visible on chrome and safari on mobile + adds swiping functionality to slides on mobile
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-330)
- On Browser: Test Lightbox kit 'Multiple', make sure thumbnails on bottom of screen scroll + active thumbnail stays centered on screen
- On Mobile: Test Lightbox kit 'Multiple', make sure thumbnails show up on bottom of screen, are scrollable and active thumbnail stays centered on screen. Test to make sure slides are swipeable.
=> [PLAY-330]-Lightbox Kit Responsive on Mobile

playbook/app/pb_kits/playbook/pb_filter/docs/_filter_close_popover.jsx, playbook/app/pb_kits/playbook/pb_filter/docs/_filter_default.html.erb, playbook/app/pb_kits/playbook/pb_filter/docs/_filter_default.jsx, playbook/app/pb_kits/playbook/pb_filter/docs/_filter_min_width.html.erb, playbook/app/pb_kits/playbook/pb_filter/docs/_filter_min_width.jsx, playbook/app/pb_kits/playbook/pb_filter/docs/_filter_no_background.html.erb, playbook/app/pb_kits/playbook/pb_filter/docs/_filter_no_background.jsx, playbook/app/pb_kits/playbook/pb_filter/docs/_filter_no_sort.html.erb, playbook/app/pb_kits/playbook/pb_filter/docs/_filter_no_sort.jsx, playbook/app/pb_kits/playbook/pb_filter/docs/_filter_only.html.erb, playbook/app/pb_kits/playbook/pb_filter/docs/_filter_only.jsx, playbook/app/pb_kits/playbook/pb_filter/docs/_filter_placement.html.erb, playbook/app/pb_kits/playbook/pb_filter/docs/_filter_placement.jsx, playbook/app/pb_kits/playbook/pb_filter/docs/_filter_single.html.erb, playbook/app/pb_kits/playbook/pb_filter/docs/_filter_single.jsx
* If you add a max width, then the dropdown select will grow to the designated size, but will not truncate the actual items in the menu
* 
NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-347)
N/A
=> [PLAY-347] Filter Kit Dropdown updates

playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_sizes.jsx, playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.jsx, playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_status.jsx
____
No breaking changes, just add `wrap` and `rowGap` props.
[[PLAY-371]](https://nitro.powerhrg.com/runway/backlog_items/PLAY-371)
Check milano building and simulate different screen resolutions. Check if the buttons are not overflowing its container.
=> [PLAY-371] Dialog kit docs examples not containing contents

playbook/app/pb_kits/playbook/pb_list/docs/_description.md
No breaking changes, just removing a `li` with flex display that was breaking the code responsiveness.
[[PLAY-368]](https://nitro.powerhrg.com/runway/backlog_items/PLAY-368) 
Open milano environment and resize your screen.
=> [PLAY-368] Lists kit docs are broken

playbook/app/pb_kits/playbook/pb_table/docs/_table_icon_buttons.html.erb, playbook/app/pb_kits/playbook/pb_table/docs/_table_icon_buttons.jsx, playbook/app/pb_kits/playbook/pb_table/docs/_table_one_action.html.erb, playbook/app/pb_kits/playbook/pb_table/docs/_table_one_action.jsx, playbook/app/pb_kits/playbook/pb_table/docs/_table_two_actions.html.erb, playbook/app/pb_kits/playbook/pb_table/docs/_table_two_actions.jsx, playbook/app/pb_kits/playbook/pb_table/docs/_table_two_plus_actions.html.erb, playbook/app/pb_kits/playbook/pb_table/docs/_table_two_plus_actions.jsx
____
No breaking changes, just add change the flex alignment of last column.
[[PLAY-378]](https://nitro.powerhrg.com/runway/backlog_items/PLAY-378)
Check milano and see if the buttons are right aligned. Resize your screen to see if it looks good in different resolutions
=> [PLAY-378] Table kit doc example buttons should be right aligned

playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_data.jsx
NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-376)
N/A
=> [PLAY-376] Table kit missing space between doc examples

playbook-website/app/views/pages/kit_category_show.html.erb, playbook-website/app/views/pages/kits.html.erb
No breaking changes, fixes UI issue on playbook website kits page.
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-389)
review in milano env
=> [PLAY-389]-Page Title Spacing Bug Fix

playbook-website/app/javascript/site_styles/_getting_started.scss
NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-369)
N/A
=> [PLAY-369] Getting Started markdown code background styling is the wrong color

playbook/app/pb_kits/playbook/pb_dialog/_dialog.scss
Bug fix: border-radius should only be `0` in the `full-height` variant of the Dialog Kit.
No breaking changes, css fix for the dialog kit.
[INSERT URL]
Check milano build. Resize your screen simulating different resolutions. Only the full height variant should not have `border-radius`.
=> Fix dialog kit border-radius

playbook/app/pb_kits/playbook/pb_table/_table.jsx
NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-354)
N/A
=> [PLAY-354] Table Kit (React) doesn’t have responsive js code

playbook/app/pb_kits/playbook/pb_text_input/_text_input.tsx
No, fixed issue where a null class was rendering in dom
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-427)
Review i n milano env. inspect each typeahead and make sure the null class is not rendering in DOM (see story for screenshot of issue)
=> [PLAY-427]-Fixed Issue Where Typeahead Kit Was Returning Null Classes

playbook/app/pb_kits/playbook/pb_checkbox/_checkbox.scss, playbook/app/pb_kits/playbook/pb_radio/_radio.scss
Before: 
After: 
NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-396)
N/A
=> [PLAY-396]  Selectable List Radios have extra padding

playbook/app/pb_kits/playbook/pb_collapsible/_collapsible.tsx, playbook/app/pb_kits/playbook/pb_collapsible/child_kits/CollapsibleMain.tsx, playbook/app/pb_kits/playbook/pb_collapsible/collapsible_main.html.erb, playbook/app/pb_kits/playbook/pb_collapsible/collapsible_main.rb, playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_color.html.erb, playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_color.jsx, playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_color.md, playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_default.html.erb, playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_size.html.erb, playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_size.jsx, playbook/app/pb_kits/playbook/pb_collapsible/docs/_collapsible_size.md, playbook/app/pb_kits/playbook/pb_collapsible/docs/example.yml, playbook/app/pb_kits/playbook/pb_collapsible/docs/index.js
NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-411)
N/A
=> [PLAY-411] Collapsible kit icon size and color

playbook/app/pb_kits/playbook/pb_legend/_legend.jsx, playbook/app/pb_kits/playbook/pb_legend/_legend.scss, playbook/app/pb_kits/playbook/pb_legend/docs/_legend_custom_colors.html.erb, playbook/app/pb_kits/playbook/pb_legend/docs/_legend_custom_colors.jsx, playbook/app/pb_kits/playbook/pb_legend/docs/_legend_custom_colors.md, playbook/app/pb_kits/playbook/pb_legend/docs/example.yml, playbook/app/pb_kits/playbook/pb_legend/docs/index.js, playbook/app/pb_kits/playbook/pb_legend/legend.html.erb, playbook/app/pb_kits/playbook/pb_legend/legend.rb
No, adds functionality that allows color prop to accept hex values. 
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-391)
In milano env check to make sure 'custom color' example functions as expected for react as well as rails
=> [PLAY-391] - Legend Kit to Take Custom Colors

playbook/app/pb_kits/playbook/pb_radio/_radio.scss
NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-423)
Check the react version of the radio kit and make sure the alignment section is aligned properly, with the caption below the radio button instead of next to it. Make sure all other cards work as intended
=> [PLAY-423] Radio kit (React) alignment error

playbook/app/pb_kits/playbook/pb_button/_button.scss, playbook/app/pb_kits/playbook/pb_button/docs/_button_default.html.erb, playbook/app/pb_kits/playbook/pb_button/docs/_button_default.jsx
Adds hover to the button with the link variant.
It mimics the same style we have inside of Playbook's sidebar that shows our components. 
No
[Runway story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-385)
Hover that link button, yo!
~- [ ] **SPECS** Please cover your changes with specs.~
=> [PLAY-385] Added Hover State to Buttons with Link Variant

playbook/app/pb_kits/playbook/pb_date_picker/date_picker.test.js, playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_time.jsx, playbook/app/pb_kits/playbook/pb_date_picker/plugins/timeSelect.ts, playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_time_selection_styles.scss
AM/PM toggle
AM/PM toggle on hover
No, see runway story for full details. 
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-489)
Test in review env. Scroll down to 'Time Selection' doc example and click on calendar to show Date Picker. Make sure thev Am/PM toggle works to change the Am/PM in the display. 
There are 2 Date Pickers in that example, make sure toggle works correctly on each and does not interfere with the other Date Picker's toggle (see story for details)
=> [PLAY-489] Reinstated Flatpickr Default AM/PM Toggle

playbook/app/pb_kits/playbook/pb_button/_button.scss
No Hover:
With Hover:
Yes, Changes hover state for link variant of Button to only change text color NOT background color
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-501)
=> [PLAY-501] Fix Button Hover Bug

playbook/app/pb_kits/playbook/pb_enhanced_element/element_observer.ts, playbook/app/pb_kits/playbook/pb_enhanced_element/index.ts
No. We converted the Enhanced Element to Typescript, but we did not change any signature or behavior.
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-227)
We can test the kits that make use of the Enhanced Element. They are PbCollapsible, PbFixedConfirmationToast, PbFormValidation, PbPopover, PbTable, PbTextarea, PbTooltip, PbTypeahead.
=> [PLAY-227] Converting Enhanced Element to Typescript

playbook-website/Gemfile.lock, playbook/app/pb_kits/playbook/pb_date_picker/date_picker_helper.ts, playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_time.jsx
Story TBD 
I was recently talking with @kellyeryan about issues with Datepicker closing on date selection before being able to select the time in her working view. We noticed that state mutations will trigger the datepicker instance to close and that Flatpickr has a `closeOnClick` config prop that you can pass to prevent this behavior. In a normal vanilla JS UI, this config prop alone would do the trick, however, in a stateful React app we must add one more thing to prevent unnecessary re-drawing of the datepicker instance: add `useMemo` hook. 
____
No
TBD
See the time example. The Datepicker should not close on date or time selection. Only on click outside should it close.
=> Datepicker closeOnSelect Prop

playbook/app/pb_kits/playbook/pb_date_picker/date_picker.test.js, playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_time.html.erb, playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_time.jsx, playbook/app/pb_kits/playbook/pb_date_picker/plugins/timeSelect.ts, playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_time_selection_styles.scss
No, replaces the flatpicker native toggle for AM/PM with custom built component
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-486)
In milano env scroll down to 'time selection' doc example. Click to open the datepicker and make sure it looks like the image above and that the AM/PM buttons change the value in the input field. There are 2 date pickers in that example, make sure the AM/PM buttons do not interfere with each other and only toggle Am/PM for their own date Picker's input
=> [PLAY-486] Date Picker AM/PM Buttons Instead of Toggle

playbook-website/Gemfile.lock, playbook/app/pb_kits/playbook/pb_selectable_list/_item.jsx, playbook/app/pb_kits/playbook/pb_selectable_list/_selectable_list.jsx, playbook/app/pb_kits/playbook/pb_selectable_list/_selectable_list.scss, playbook/app/pb_kits/playbook/pb_selectable_list/docs/_selectable_list_radio.jsx, playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list.html.erb, playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list.rb, playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list_item.html.erb, playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list_item.rb
No
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-414)
Go to Selectable List kit.
Select any item.
Its background color should change.
=> [PLAY-414] Change bg color when selectable list item is selected

playbook-website/app/controllers/pages_controller.rb, playbook-website/app/javascript/components/KitDocs/index.tsx, playbook-website/app/javascript/packs/application.js, playbook-website/app/views/pages/kit_show_new.html.erb, playbook-website/app/views/pages/kit_show_react.html.erb
NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-518)
In the URL type in /kits/:name/new and check to see that the correct kit name is being rendered as a title
=> Updating new kit architecture names

playbook-website/config/deploy/templates/deployment.yaml.erb
The namespace quota is sufficiently sized for 3 replicas of this pod. The default parameters (25% capacity flux either way) would cause an attempt to execute 4 pods concurrently. These parameters allow rollouts to operate within the quota of 3 pods concurrently.
=> Allow deployments to proceed smoothly within quota

playbook/app/pb_kits/playbook/tokens/_colors.scss
No Breaking changes, PR only changes hex color for tokens.
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-519)
Compare tokens in review env to ones on prod to see changes to red color.
=> [PLAY-519] Update Error Color Token

playbook/app/pb_kits/playbook/pb_popover/docs/_popover_list.html.erb, playbook/app/pb_kits/playbook/pb_popover/docs/_popover_list.jsx
With dropdown closed:
With dropdown open:
No Breaking changes, updates to DOCs only
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-520)
Test in review env to make sure icon on dropdown example changes when clicked
=> [PLAY-520] Popover Kit Updates for Dropdown Doc Example

playbook/package.json, yarn.lock
No.
Runway: https://nitro.powerhrg.com/runway/backlog_items/PLAY-543
PR from Stephen Greer that they had to do as a workaround until THIS playbook PR is released: https://github.com/powerhome/nitro-id/pull/283
Check that everything still works and the vulnerability is now gone from our dependabot.
=> [PLAY-543] Fixes loader-utils security vulnerability

playbook/app/pb_kits/playbook/pb_file_upload/_file_upload.tsx, playbook/app/pb_kits/playbook/pb_file_upload/docs/_description.md, playbook/app/pb_kits/playbook/pb_file_upload/docs/_file_upload_custom_message.jsx, playbook/app/pb_kits/playbook/pb_file_upload/docs/example.yml, playbook/app/pb_kits/playbook/pb_file_upload/docs/index.js, playbook/app/pb_kits/playbook/pb_file_upload/fileupload.test.js
- Adds the capability to pass a custom message to the `FileUpload` kit
- Adds documentation and test coverage
No.
[PLAY-566](https://nitro.powerhrg.com/runway/backlog_items/PLAY-566)
- Pass a `string` into the `FileUpload` component like so:
```js
<FileUpload customMessage="Hello world!">
```
=> [PLAY-566] Add Custom Message to FileUpload kit

playbook/app/pb_kits/playbook/pb_stat_value/_stat_value.tsx, playbook/app/pb_kits/playbook/pb_stat_value/docs/_stat_value_unit.jsx, playbook/app/pb_kits/playbook/pb_stat_value/stat_value.test.js
NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-529)
Check to make sure all stat changes kits still render properly
=> [Play-529] Typescript Conversion Stat Value

playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.tsx, playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_default_react.jsx, playbook/app/pb_kits/playbook/pb_tooltip/tooltip.test.jsx
NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-499)
Add a custom class name using the className prop and inspect to make sure the className was passed
=> [PLAY-499] Added ClassName prop to Tooltip Kit

playbook/app/pb_kits/playbook/pb_timestamp/_timestamp.tsx, playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_align.jsx, playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_default.jsx, playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed.jsx, playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_timezones.jsx, playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated.jsx
NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-586)
Check that the Timestamp kit still works as expected and has no errors in console.
=> [PLAY-586] Typescript Conversion: TimeStamp

playbook/app/pb_kits/playbook/pb_bar_graph/_bar_graph.tsx, playbook/app/pb_kits/playbook/pb_dashboard/pbChartsDarkTheme.ts, playbook/app/pb_kits/playbook/tokens/_colors.scss
NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-412)
Check Bar graph to make sure borders are transparent
=> [PLAY-412] Bar Graph borders don't match theme

playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss, playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_add_on.html.erb, playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_add_on.jsx
NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-415)
Use the Text Input `LEFT-ALIGNED ADD ON WITH NO BORDER` variant and ensure that the blinking cursor is visible.
=> [PLAY-415] Text Input kit Left-Aligned Add On With No Border padding missing

playbook/app/pb_kits/playbook/tokens/_colors.scss
NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-619)
Try to override playbooks color tokens
=> [PLAY-619] Color tokens need default property

playbook/app/pb_kits/playbook/pb_selectable_list/_selectable_list.scss
NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-620)
Check an item in selectable list and inspect to make sure it is using $active_light
=> [PLAY-620] Selectable List kit active background color is wrong

playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
No
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-370)
- Go to the Typeahead component.
- Click on the "search" input to trigger the dropdown.
=> [PLAY-370] Fixing Typeahead off spacing on dropdown

playbook/app/pb_kits/playbook/pb_passphrase/_passphrase.tsx, playbook/app/pb_kits/playbook/pb_popover/_popover.tsx
No
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-634)
Use the Passphrase kit and ensure it works as expected after the Typescript conversion.
=> [PLAY-634] Converting Passphrase kit to Typescript

playbook/app/pb_kits/playbook/pb_person_contact/_person_contact.tsx, playbook/app/pb_kits/playbook/pb_person_contact/person_contact.test.js
No
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-635)
Use the Person Contact kit and ensure it works as expected after the Typescript conversion.
=> [PLAY-635] Converting Person Contact kit to Typescript

playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.tsx
=> Fixed classname order in tooltip

.github/workflows/github-actions-alpha-version.yml
I spotted a bug occurring on all PRs that get opened against our master branch. 
They are generating alphas every time someone adds a label. 
This fix will resolve that issue, only triggering the alpha is someone adds the specific `alpha` label.
=> Fix for Alphas

playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.jsx, playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.test.jsx
No
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-671)
=> [PLAY-671] Adding classname prop to Typeahead kit

playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.scss, playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.tsx, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_default.jsx, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_initial_country.jsx, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_only_countries.jsx, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_preferred_countries.jsx, playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.rb
No
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-625)
Go to the Phone Number Input kit on Playbook and check the dark mode.
=> [PLAY-625] Implementing Phone Number Input kit dark mode

playbook/app/pb_kits/playbook/pb_circle_chart/_circle_chart.tsx, playbook/app/pb_kits/playbook/pb_circle_chart/circle_chart.rb, playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_custom_tooltip.html.erb, playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_custom_tooltip.jsx, playbook/app/pb_kits/playbook/pb_circle_chart/docs/_circle_chart_custom_tooltip.md, playbook/app/pb_kits/playbook/pb_circle_chart/docs/example.yml, playbook/app/pb_kits/playbook/pb_circle_chart/docs/index.js
No
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-514)
=> [PLAY-514] Custom Tooltip Prop for Circle Chart

playbook-website/app/helpers/application_helper.rb, playbook-website/app/javascript/components/KitDocs/index.tsx, playbook-website/app/javascript/site_styles/docs/_kit_doc.scss, playbook-website/app/views/pages/kit_show_new.html.erb
No
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-697)
Go to any kit/sandpack page on Playbook.
=> [PLAY-697] Updating Sandpack docs styles

playbook/app/pb_kits/playbook/pb_card/_card.scss, playbook/app/pb_kits/playbook/pb_card/_card.tsx, playbook/app/pb_kits/playbook/pb_card/card_header.rb, playbook/app/pb_kits/playbook/pb_card/docs/_card_header.html.erb, playbook/app/pb_kits/playbook/pb_card/docs/_card_header.jsx
This PR allows applying striped (aka hashed) colors to Card kit headers.
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-700)
1. Go to Card Kit on Playbook doc
2. Go to the Header Card variant
3. Check the Striped Colors section
=> [PLAY-700] Adding Card Header support to striped colors

playbook/app/pb_kits/playbook/pb_avatar/_avatar.tsx, playbook/app/pb_kits/playbook/pb_avatar/avatar.html.erb, playbook/app/pb_kits/playbook/pb_avatar/avatar.rb, playbook/app/pb_kits/playbook/pb_avatar/avatar.test.js, playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_default.html.erb, playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_default.jsx, playbook/spec/pb_kits/playbook/kits/avatar_spec.rb
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-729)
This PR reconfigured the way the alt attribute is passed into the Image kit from the Avatar kit. Previously it would use the prop `imageAlt` or `image_alt` to pass into the alt attribute. Therefore if a user did not pass in an `imageAlt` prop the alt attribute would be left empty. I've created a conditional that checks for an `imageAtl` prop, if there is none, it passes the `name` prop as the alt attribute.
1. Go to [the User Kit](https://playbook.powerapp.cloud/kits/user/react) and inspect the page
2. Notice how even though there is no `imageAlt` prop being passes in the …
=> [PLAY-729]  🛠️ Update Avatar kit imageAlt default

playbook/app/pb_kits/playbook/pb_docs/kit_example.html.erb, playbook/app/pb_kits/playbook/pb_docs/kit_example.rb, playbook/app/pb_kits/playbook/pb_image/docs/_default_image.jsx
=> Fix for broken datepicker page

playbook/app/pb_kits/playbook/pb_body/_body.scss, playbook/app/pb_kits/playbook/pb_body/docs/_body_styled.html.erb, playbook/app/pb_kits/playbook/pb_body/docs/_body_styled.jsx, playbook/app/pb_kits/playbook/pb_body/docs/_body_styled.md, playbook/app/pb_kits/playbook/pb_body/docs/example.yml
Adding styles to <em> and <small> tags in Playbook.
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-764)
1. Go to Body kit on Playbook
2. Scroll down to the **Style Tags** example
=> [PLAY-764] Adding styles tags to Body kit

playbook/app/pb_kits/playbook/tokens/_colors.scss
[PLAY-747](https://nitro.powerhrg.com/runway/backlog_items/PLAY-747)
This PR changes the values for the `$border_dark` and `$card_dark` tokens. It also creates a new `$shadow_dark` token
N/A
1. Go the color tokens file
2. Check the changed and new tokens
3. Confirm they have the correct values
=> [PLAY-747]  🪙 Add/Update tokens for Card (dark)

playbook-website/Gemfile, playbook-website/Gemfile.lock
This reverts commit c4c9b3d7709752db737783909206f3c85e8a514e.
1. Go to '...'
=> Revert "Update dependency better_errors to v2.10.0 (#2537)"

playbook-website/app/javascript/packs/application.js, playbook-website/app/javascript/site_styles/_changelog.scss, playbook-website/app/javascript/site_styles/docs/_all.scss, playbook-website/app/javascript/site_styles/docs/_links.scss, playbook-website/app/views/pages/kit_show.html.erb, playbook-website/package.json, yarn.lock
Adds anchor links to all kit card examples on hover.
Also updates the size of the anchors on the changelog page. 
1. Go to a card example.
2. Hover near the caption and see a clickable anchor link icon.
~- [ ] **TESTS** I have added test coverage to my code.~
=> [PLAY-753] Anchors Linking 

playbook/app/pb_kits/playbook/pb_weekday_stacked/_weekday_stacked.tsx, playbook/app/pb_kits/playbook/pb_weekday_stacked/weekday_stacked.test.jsx
Converts WeekdayStacked to TS + adds jest tests
[Runway story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-816)
1. Go to '...'
=> [PLAY-816] Convert WeekdayStacked to TS + Jest Tests

playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss
This PR fixes broken dark mode styling for TextInput with icon add on.
[PLAY-834](https://nitro.powerhrg.com/runway/backlog_items/PLAY-834)
1. Go to TextInput in dark mode and scroll to 'Add on' doc example
=> [PLAY-834] Fixes for darkmode Styling of TextInput

playbook/app/pb_kits/playbook/pb_title/_title.scss, playbook/app/pb_kits/playbook/pb_title/docs/_title_light_weight.html.erb, playbook/app/pb_kits/playbook/pb_title/docs/_title_light_weight.jsx, playbook/app/pb_kits/playbook/pb_title/docs/_title_light_weight.md
This sets Title 2 to default to Bold now. 
This can still be turned off manually on an individual kit basis, as an escape hatch if need be. 
Updated the copy as well to reflect the changes. 
1. Go to any title size=2 and see bold for rails/react.
~- [] **TESTS** I have added test coverage to my code.~
=> Title 2 Defaults to Bold

playbook-website/app/components/playbook/pb_docs/kit_api.html.erb
breadcrumbs rails page on the PB website is broken, follow this link to see error msg: https://playbook.powerapp.cloud/kits/bread_crumbs
This PR fixes this be adding the missing props:{} syntax to kit_api.html.erb page
1. Go to '...'
=> Fix for Broken bread_crumb Rails Page on Website

playbook-website/app/javascript/site_styles/docs/_markdown.scss, playbook-website/app/views/guides/design_guidelines/example_markdown_styling.md, playbook/CHANGELOG.md
- [Runway](https://nitro.powerhrg.com/runway/backlog_items/PLAY-878)
- In the changelog's markdown file, use `h5` for the date below the title (see screenshots)
- CSS is the same as the Caption kit
- Add changelog dates to `12.24` and `12.25` and update the Example Markdown Styling page with the `h5` description
- Redcarpet adds a copy link on hover to all headers, but this is a quick ship story
**Add Changelog Dates**
**Add h5 Description to Example Markdown Styling Page**
1. Go to `/changelog`
- In the changelog file, add a `h5` right below the `h1` title.
2. Go to `/guides/design_guidelines/example_markdown_styling`
- View the added `h5` description for changelog dates
=> [PLAY-878] Add CSS for Changelog Dates

playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_default.jsx
Fixes the expanded, so that the database can recall your expanded selections upon page reload. 
https://github.com/powerhome/playbook/assets/9158723/2ab329e3-e89d-4e1c-ba73-1f0dd3541e1d
1. Go to MultiLevel and see the data coming from the tree structure for expanded states.
~- [X] **TESTS** I have added test coverage to my code.~
=> [PLAY-889] Fixed Expanded State to Load From TreeData

playbook/app/pb_kits/playbook/pb_selectable_card_icon/docs/_selectable_card_icon_custom.html.erb, playbook/app/pb_kits/playbook/pb_selectable_card_icon/docs/_selectable_card_icon_custom.jsx, playbook/app/pb_kits/playbook/pb_selectable_card_icon/docs/_selectable_card_icon_custom.md, playbook/app/pb_kits/playbook/pb_selectable_card_icon/docs/example.yml, playbook/app/pb_kits/playbook/pb_selectable_card_icon/docs/index.js, playbook/app/pb_kits/playbook/pb_selectable_card_icon/selectable_card_icon.html.erb, playbook/app/pb_kits/playbook/pb_selectable_card_icon/selectable_card_icon.rb, playbook/app/pb_kits/playbook/pb_selectable_icon/selectable_icon.html.erb, playbook/app/pb_kits/playbook/pb_selectable_icon/selectable_icon.rb
Implementing custom icons for the Selectable Card Icon kit.
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-779)
1. Go to the Selectable Card Icon kit
2. Go to the Custom Icon example
=> [PLAY-779] Implementing custom icons for Selectable Card Icon kit

playbook/app/pb_kits/playbook/pb_multi_level_select/_helper_functions.tsx, playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_selected_ids.html.erb, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_selected_ids.jsx, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_selected_ids.md, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/example.yml, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/index.js, playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.rb
Adds new selectedIds prop so Nitro does not have to map over their tree data to add checked items on re-render. This will allow Nitro to remove several lines of custom code from their implementation
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-906)
1. Go to '...'
=> [PLAY-906] MultiLevel: Added New selectedIds Prop

playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.scss, playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.tsx, playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_children.html.erb, playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_children.jsx, playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_children.md, playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_dashed.html.erb, playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_dashed.jsx, playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_text.html.erb, playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_text.jsx, playbook/app/pb_kits/playbook/pb_section_separator/docs/example.yml, playbook/app/pb_kits/playbook/pb_section_separator/docs/index.js, playbook/app/pb_kits/playbook/pb_section_separator/section_separator.html.erb, playbook/app/pb_kits/playbook/pb_section_separator/section_separator.rb, playbook/spec/pb_kits/playbook/kits/section_seperator_spec.rb
Make the kit accept children, and users are now able to use a dashed separator.
1. Go to the Section Separator kit
=> [PLAY-901] Adding new dashed section separator

playbook/app/pb_kits/playbook/pb_title/_title.scss, playbook/app/pb_kits/playbook/pb_title/_title.tsx, playbook/app/pb_kits/playbook/pb_title/docs/_title_responsive.html.erb, playbook/app/pb_kits/playbook/pb_title/docs/_title_responsive.jsx, playbook/app/pb_kits/playbook/pb_title/docs/_title_responsive.md, playbook/app/pb_kits/playbook/pb_title/docs/example.yml, playbook/app/pb_kits/playbook/pb_title/docs/index.js, playbook/app/pb_kits/playbook/pb_title/title.rb, playbook/app/pb_kits/playbook/pb_title/title.test.js, playbook/spec/pb_kits/playbook/kits/title_spec.rb
It implements responsive Title sizes so that we can dynamically change Title sizes based on screen size.
1. Go to Title Kit on Playbook Website
2. Scroll down to **Responsive** example
=> [PLAY-909] Implementing Responsive Title

playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.tsx, playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_children.html.erb, playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_children.jsx, playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_children.md, playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/example.yml, playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/index.js, playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/fixed_confirmation_toast.html.erb
Implements a children's prop to the Fixed Confirmation Toast kit, so I pass custom content (i.e., links) to my toasts.
1. Go to the Fixed Confirmation Toast kit doc page
2. Scroll down to the children example
=> [PLAY-910] Adding children prop to Fixed Confirmation Toast

playbook/CHANGELOG.md
Updates the Changelog for version 12.32.0
1. Go to '...'
=> 12.32.0 Changelog

playbook-website/app/views/pages/kit_collection.html.erb
Added the Rails kit and global props table to the rails kit mash up page
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-912)
1. Go to https://playbook.powerapp.cloud/kit_collection/title&card&nav
2. Scroll to the bottom
3. Ensure both kit and global prop tables are functioning correctly
4. Change between different kits and ensure that the tables show up as they should for each kit.
=> [PLAY-912]  🌐 kit_collection: add kit + global props table to Rails page

playbook/app/pb_kits/playbook/pb_map/_map.scss
Fix the Map kit's nav buttons that are oversized and breaking their own layout in Safari.
1. Go to Map kit in Safari
2. Check the map buttons
=> [PLAY-881] Fixing the map kit button height for Safari

playbook/app/pb_kits/playbook/pb_dialog/_dialog.scss, playbook/app/pb_kits/playbook/pb_dialog/_dialog.tsx, playbook/app/pb_kits/playbook/pb_dialog/dialog.html.erb
- [Runway](https://nitro.powerhrg.com/runway/backlog_items/PBNTR-65)
- Centers the text for status dialogs by adding a class name: [`dialog_status_text_align`](https://github.com/powerhome/playbook/compare/PBNTR-65-Dialog-Title-Body?expand=1#diff-e0614f355c6addc50e729055d662c40e0486bf3b34ee83d2578a9cff2790ffa4R185)
| Before | After |
|--------|--------|
| ![Screenshot 2023-07-20 at 12 38 20 PM](https://github.com/powerhome/playbook/assets/47684670/5d30d256-eb6c-41c3-8eb0-b67daefde495) | ![Screenshot 2023-07-20 at 12 30 31 PM](https://github.com/powerhome/playbook/assets/47684670/3d526e7b-8936-49eb-8074-3c142c192f6d) |
1. Go to the Dialog kit
2. Open a status Dialog variant
3. Put in some …
=> [PBNTR-65] Center Align Text for Status Dialogs

playbook/app/pb_kits/playbook/pb_dialog/dialogHelper.js
- Refactors the Dialog Rails kit's "click outside to close" feature to not be dependent on the `data-open-dialog` attribute
- If not improved, this could block the SweetAlert replacement ([see POC: PBNTR-62](https://github.com/powerhome/nitro-web/pull/33256))
1. Go to the Dialog Rails kit
2. Open a dialog, then click outside to close
3. Go to the "Overlay Click" example. You should NOT be able to close.
=> Refactor Dialog Kit Close on Outside Click

playbook-website/app/javascript/components/Sidebar/index.tsx, playbook-website/app/javascript/components/VisualGuidelines/Examples/Hover.tsx, playbook-website/app/javascript/components/VisualGuidelines/Templates/Example.tsx, playbook-website/app/javascript/components/VisualGuidelines/index.tsx, playbook-website/app/views/pages/code_snippets/hover_jsx.txt
Create Hover Global Prop docs in our Playbook Wesbite
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-916)
1. Go to Playbook Website
2. Click on Design in the upper right hand corner
3. Click on Hover on the left hand side bar
4. See addition of Hover Global Props
=> [PLAY-916] 🧬📄 Hover global prop docs

playbook-website/app/javascript/site_styles/_kits_show.scss, playbook/app/pb_kits/playbook/pb_badge/docs/_badge_colors_swift.md, playbook/app/pb_kits/playbook/pb_badge/docs/_badge_default_swift.md, playbook/app/pb_kits/playbook/pb_badge/docs/_badge_notification_swift.md, playbook/app/pb_kits/playbook/pb_badge/docs/_badge_props_swift.md, playbook/app/pb_kits/playbook/pb_badge/docs/_badge_rounded_swift.md, playbook/app/pb_kits/playbook/pb_badge/docs/example.yml, playbook/app/pb_kits/playbook/pb_pill/docs/_pill_default_swift.md, playbook/app/pb_kits/playbook/pb_pill/docs/_pill_props_swift.md, playbook/app/pb_kits/playbook/pb_pill/docs/_pill_variants_swift.md, playbook/app/pb_kits/playbook/pb_pill/docs/example.yml, playbook/app/pb_kits/playbook/pb_radio/docs/_radio_alignment_swift.md, playbook/app/pb_kits/playbook/pb_radio/docs/_radio_custom_swift.md, playbook/app/pb_kits/playbook/pb_radio/docs/_radio_default_swift.md, playbook/app/pb_kits/playbook/pb_radio/docs/_radio_error_swift.md, playbook/app/pb_kits/playbook/pb_radio/docs/_radio_orientation_swift.md, playbook/app/pb_kits/playbook/pb_radio/docs/_radio_padding_swift.md, playbook/app/pb_kits/playbook/pb_radio/docs/_radio_props_swift.md, playbook/app/pb_kits/playbook/pb_radio/docs/_radio_spacing_swift.md, playbook/app/pb_kits/playbook/pb_radio/docs/_radio_subtitle_swift.md, playbook/app/pb_kits/playbook/pb_radio/docs/example.yml, playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_align_swift.md, playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_default_swift.md, playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed_swift.md, playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_props_swift.md, playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_timezones_swift.md, playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_updated_swift.md, playbook/app/pb_kits/playbook/pb_timestamp/docs/example.yml
This PR adds swift docs for `badge`, `pill`, `radio`, and `timestamp`
[PBIOS-107](https://nitro.powerhrg.com/runway/backlog_items/PBIOS-107)
[PBIOS-115](https://nitro.powerhrg.com/runway/backlog_items/PBIOS-115)
[PBIOS-116](https://nitro.powerhrg.com/runway/backlog_items/PBIOS-116)
[PBIOS-117](https://nitro.powerhrg.com/runway/backlog_items/PBIOS-117)
1. You will need to pull down locally and go to the `badge`, `pill`, `radio`, and `timestamp` kits
=> [PBIOS-107] Swift Docs: Badge, Pill, Radio and Timestamp Kits

playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_options.html.erb, playbook/app/pb_kits/playbook/pb_text_input/docs/example.yml, playbook/app/pb_kits/playbook/pb_text_input/text_input.rb, playbook/spec/pb_kits/playbook/kits/text_input_spec.rb
https://nitro.powerhrg.com/runway/backlog_items/PLAY-928
We've had the input_options prop for a long time, but it wasn't connected correctly. We just needed a simple merge to be able to leverage any values that the end user passes in. 
✅  Fixed Broken Input Options Prop. 
✅  Simplified Rspec by Using Matcher
**Screenshots:** Screenshot
s to visualize your addition/change
1. Go to Input Options example in the rails docs.
2. Inspect the page, and look directly at the <input />
3. See attributes being added because of the input_options prop fix.
=> [PLAY-928] Fixed Text Input Options Prop

playbook-website/app/javascript/components/Sidebar/index.tsx, playbook-website/app/javascript/components/VisualGuidelines/Examples/Hover.tsx, playbook-website/app/javascript/components/VisualGuidelines/Examples/TextAlign.tsx, playbook-website/app/javascript/components/VisualGuidelines/index.tsx, playbook-website/app/views/pages/code_snippets/text_align_jsx.txt
- [Runway](https://nitro.powerhrg.com/runway/backlog_items/PLAY-937)
- Adds Text Align global prop docs
- Corrects spelling in Hover docs
1. Go to the "Design" tab in Playbook
2. Check out the Text Align docs
=> [PLAY-937] Text Align Global Prop Docs

playbook-website/app/controllers/pages_controller.rb, playbook-website/app/javascript/components/MainSidebar/NestedNavItems.tsx, playbook-website/app/javascript/components/MainSidebar/index.tsx, playbook/app/pb_kits/playbook/pb_nav/_collapsible_nav.scss
**What does this PR do?
[RUNWAY STORY](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1001)
✅ Items should be active immediately when clicked
✅ Top level navItem should not collapse if already on page
✅ Clean up code, separate nav rendering logic to separate file
✅ Fix for navigation where if rails or react page does not exist, redirect to type that does exist
=> [PLAY-1001] Sidebar Collapsible Nav Optimization

playbook-website/app/javascript/components/Sidebar/index.tsx, playbook-website/app/javascript/components/VisualGuidelines/Examples/Overflow.tsx, playbook-website/app/javascript/components/VisualGuidelines/Templates/SpacingProps.tsx, playbook-website/app/javascript/components/VisualGuidelines/index.tsx, playbook-website/app/views/pages/code_snippets/overflow_jsx.txt, playbook-website/app/views/pages/code_snippets/overflow_token.txt, playbook/app/pb_kits/playbook/_playbook.scss, playbook/app/pb_kits/playbook/pb_flex/_flex_item.scss, playbook/app/pb_kits/playbook/pb_flex/_flex_item.tsx, playbook/app/pb_kits/playbook/pb_flex/flex_item.rb, playbook/app/pb_kits/playbook/tokens/_overflow.scss, playbook/app/pb_kits/playbook/utilities/_overflow.scss, playbook/app/pb_kits/playbook/utilities/globalProps.ts, playbook/lib/playbook/classnames.rb, playbook/lib/playbook/kit_base.rb, playbook/lib/playbook/overflow.rb, playbook/spec/pb_kits/playbook/kits/flex_item_spec.rb
- Creates the new overflow global prop
- Caters to overflow, overflowX/overflow_x and overflowY/overflow_y
- Created docs on visual guidelines page
- Removed the overflow prop on flexitem since it was doing same thing our global prop does now and there was no default in the kit
=> [PLAY-823] Global Prop Overflow

playbook-website/bin/deploy, playbook-website/config/deploy/production/values.yaml, playbook-website/config/deploy/templates/deployment.yaml.erb, playbook-website/config/deploy/templates/partials/resources.yaml.erb
Paired with Aaron K. today and this is the result. 
We investigated our CPU resources on grafana, and came to conclusion that for now, we can temporarily request an increase for production env only. Staging is currently sufficient, and we aren't hitting any ceilings there.
We verified that the templates will render by testing locally! 🎉
=> Requesting More CPU

playbook-website/Gemfile, playbook-website/Gemfile.lock, playbook-website/app/controllers/application_controller.rb
This a next step because we are still experiencing 500 errors, and we need a basic profiler added in order to help us look under the hood and see what the bottlenecks are. 
1. Go to '...'
=> Adding Profiler to Debug Performance

playbook-website/config/deploy/templates/ingress.yaml.erb
Part of: https://nitro.powerhrg.com/runway/backlog_items/FVR-77
Address deprecated resource API utilization. This prepares the application for future Kubernetes upgrades in PAC. The upgraded APIs have been available since 1.19.0 and are removed in 1.22.
1. Go to '...'
=> Upgrade deprecated kube resource API versions

playbook-website/app/javascript/components/MainSidebar/NavComponents/KitsNavComponent.tsx, playbook-website/app/javascript/site_styles/_site-style.scss
[Runway story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1033)
This PR:
- Changes kits default to react if no type specified
- Z-index fix for mobile nav:
- Mobile sidebar to pop out from left instead of right:
=> [PLAY-1003] Misc Sidebar fixes

playbook-website/config/deploy/production/values.yaml, playbook-website/config/deploy/templates/deployment.yaml.erb
I made these changes during Create and it seemed to eliminate pod restarts, which are the cause of the 500 errors.
I believe there is some request queueing going on with Puma, and the constrained resources don't allow the queue to be worked fast enough. I recommend implementing some puma metrics to analyze the queue. But these changes should help a  bunch.
=> No CPU Limits + Increase Memory in Production

playbook/app/pb_kits/playbook/pb_image/docs/_default_image_swift.md, playbook/app/pb_kits/playbook/pb_image/docs/_image_props_swift.md, playbook/app/pb_kits/playbook/pb_image/docs/_rounded_image_swift.md, playbook/app/pb_kits/playbook/pb_image/docs/_size_image_swift.md, playbook/app/pb_kits/playbook/pb_image/docs/_size_none_image_swift.md, playbook/app/pb_kits/playbook/pb_image/docs/example.yml
[PBIOS-167](https://nitro.powerhrg.com/runway/backlog_items/PBIOS-167)
1. Pull down branch to your local and navigate to the Image kit.
=> [PBIOS-167] Docs: Image

playbook/app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_default_swift.md, playbook/app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_props_swift.md, playbook/app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_reverse_swift.md, playbook/app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_size_swift.md, playbook/app/pb_kits/playbook/pb_multiple_users/docs/example.yml
[PBIOS-170](https://nitro.powerhrg.com/runway/backlog_items/PBIOS-170)
Adds Multiple Users docs for Swift!
1. Pull branch down locally and navigate to the Multiple Users kit
=> [PBIOS-170] Docs: Multiple Users

playbook/app/pb_kits/playbook/pb_multiple_users_stacked/docs/_multiple_users_stacked_default_swift.md, playbook/app/pb_kits/playbook/pb_multiple_users_stacked/docs/_multiple_users_stacked_props_swift.md, playbook/app/pb_kits/playbook/pb_multiple_users_stacked/docs/_multiple_users_stacked_small_swift.md, playbook/app/pb_kits/playbook/pb_multiple_users_stacked/docs/_multiple_users_stacked_xsmall_swift.md, playbook/app/pb_kits/playbook/pb_multiple_users_stacked/docs/example.yml
[PBIOS-172](https://nitro.powerhrg.com/runway/backlog_items/PBIOS-172)
1. Pull branch locally and navigate to the Multiple users Stacked kit
=> [PBIOS-172] Docs: Multiple Users Stacked

playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_add_on_swift.md, playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_default_swift.md, playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_disabled_swift.md, playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_error_swift.md, playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_props_swift.md, playbook/app/pb_kits/playbook/pb_text_input/docs/example.yml
[PBIOS-182](https://nitro.powerhrg.com/runway/backlog_items/PBIOS-182)
Adds Text Input docs for Swift!
https://github.com/powerhome/playbook/assets/92755007/e32c10de-ca17-4f87-a29d-b5f1914d6e4d
1. Pull branch locally and navigate to the Text Input kit.
=> [PBIOS-182] Docs: Text Input

playbook-website/app/views/pages/kit_show_new.html.erb
[A recent PR broke sandpack experimental feature](https://github.com/powerhome/playbook/pull/2778)
This is an interim fix to check for missing variable def. A follow-up story should be created to fix the underlying missing `type` variable. cc: @nidaqg @jasperfurniss 
N/A
=> Safe check for type var

playbook/changelog.rb, playbook/connect.rb
This adds two scripts that we can run like so:
```
cd playbook
ruby changelog.rb
ruby connect.rb
```
A success message shows and the playbook release team member should copy both separately away and remove the generated new-changelog.md & connect_message_formatted.md.
Next steps: 
- Add more automation for updating the original changelog.md
1. Go to '...'
=> [PLAY-1087] Scripts for Quicker Release Formatting

playbook/app/pb_kits/playbook/pb_filter/docs/_filter_default.md
- [Runway](https://nitro.powerhrg.com/runway/backlog_items/PBNTR-149)
- Update the default filter kit docs instructing devs how to get "No Filter Selected" to appear
- There are areas in Nitro that just have blank text when no filters are selected and the lack of docs could be why
=> [PBNTR-149] Update Filter Docs for "No Filter Selected"

playbook/app/pb_kits/playbook/pb_contact/docs/_contact_default_swift.md, playbook/app/pb_kits/playbook/pb_contact/docs/_contact_props_swift.md, playbook/app/pb_kits/playbook/pb_contact/docs/_contact_with_detail_swift.md, playbook/app/pb_kits/playbook/pb_contact/docs/example.yml
[PBIOS-228](https://nitro.powerhrg.com/runway/backlog_items/PBIOS-228)
Adds swift docs for the Contact kit
1.  pull branch locally and navigate to the Contact kit
=> [PBIOS-228] Docs: Contact

playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_default_swift.md, playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_emphasis_swift.md, playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_link_swift.md, playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_modified_swift.md, playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_props_swift.md, playbook/app/pb_kits/playbook/pb_home_address_street/docs/example.yml
[PBIOS-229](https://nitro.powerhrg.com/runway/backlog_items/PBIOS-229)
Adds Swift docs for the `Home Address Street` kit.
1. Pull branch locally and navigate to the home address street kit.
=> [PBIOS-229] Docs: HomeStreetAddress

playbook/app/pb_kits/playbook/pb_user/docs/_user_horizontal_swift.md, playbook/app/pb_kits/playbook/pb_user/docs/_user_props_table.md, playbook/app/pb_kits/playbook/pb_user/docs/_user_size_swift.md, playbook/app/pb_kits/playbook/pb_user/docs/_user_text_only_swift.md, playbook/app/pb_kits/playbook/pb_user/docs/_user_vertical_size_swift.md, playbook/app/pb_kits/playbook/pb_user/docs/example.yml
[PBIOS-187](https://nitro.powerhrg.com/runway/backlog_items/PBIOS-187)
This PR adds User docs for Swift!
1. Pull branch to your local and navigate to the User kit
=> [PBIOS-187] Docs: User

playbook/app/pb_kits/playbook/pb_button/docs/_button_props_swift.md, playbook/app/pb_kits/playbook/pb_button/docs/_button_reaction_swift.md, playbook/app/pb_kits/playbook/pb_button/docs/example.yml
Adds documentation for the reaction button variant in the button docs
=> [PBIOS-231] Reaction Button Variant Docs

playbook-website/app/javascript/components/VisualGuidelines/Examples/MaxWidth.tsx, playbook-website/app/javascript/components/VisualGuidelines/Templates/Example.tsx, playbook-website/app/javascript/site_styles/_visual_guidelines.scss, playbook-website/app/views/pages/visual_guidelines.html.erb
Adds the `xxl` maxWidth global prop to the Visual guidelines doc examples. 
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1119)
In order to achieve this I had to remove the `Background` kit in the `visual_guidelines.html.erb` file and add it to the `Example.tsx`. I also added a new prop called `backgroundClass` to the Example component which is used to style the background component in the Example component and give it a width of 1320px, so that the `xxl` maxWidth prop value is visible on the page.
1. Go to /visual_guidelines/max_width
2. Check that all maxWidth …
=> [PLAY-1119] Docs: add `xxl` as Max Width value

playbook/app/pb_kits/playbook/pb_detail/_detail.scss, playbook/app/pb_kits/playbook/pb_detail/_detail.tsx, playbook/app/pb_kits/playbook/pb_detail/detail.rb, playbook/app/pb_kits/playbook/pb_detail/detail.test.jsx, playbook/spec/pb_kits/playbook/kits/detail_spec.rb
Fixes bug in detail kit where addition of global responsive display prop overrides our default color
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1109)
n/a
1. Use our detail kit in a codesandbox
2. Add our global responsive display props
3. See that it does not change the default color of the detail kit
=> [PLAY-1109] 🐞 Display prop responsive arguments are blocking font color

playbook/app/pb_kits/playbook/pb_date_picker/_date_picker.tsx, playbook/app/pb_kits/playbook/pb_date_picker/date_picker_helper.ts, playbook/app/pb_kits/playbook/pb_date_picker/plugins/quickPick.tsx
Runway: https://nitro.powerhrg.com/runway/backlog_items/PLAY-1120
1. Go to https://pr2990.playbook.beta.gm.powerapp.cloud/kits/date_picker/react
2. It all works still
- [😈] **TESTS** I have added test coverage to my code.
=> [PLAY-1120] Lint Date Picker kit

milano.production.yml, milano.staging.yml
Fixes the telemetry links displayed in Milano environments for staging and production.
N/A
1. Visit https://milano.powerapp.cloud/powerhome/playbook/staging
2. Click on "More" 
3. Click on "Metrics" 
4. Observe that the linked dashboard does not exist. 
5. Visit https://milano.powerapp.cloud/powerhome/playbook/staging 
6. Click on "More" 
7. Click on "Logs" 
8. Observe that there are no logs
Visit https://milano.powerapp.cloud/powerhome/playbook/production
1. Click on "More"
2. Click on "Metrics"
3. Observe that the linked dashboard does not exist.
4. Visit …
=> [PLAY-1108] Fix Telemetry Links

playbook/app/pb_kits/playbook/pb_passphrase/_passphrase.tsx, playbook/app/pb_kits/playbook/pb_person_contact/_person_contact.tsx, playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.tsx, playbook/app/pb_kits/playbook/pb_popover/_popover.tsx, playbook/app/pb_kits/playbook/pb_progress_pills/_progress_pills.tsx, playbook/app/pb_kits/playbook/pb_progress_simple/_progress_simple.tsx, playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/EditorButton.tsx, playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/EditorTypes.ts, playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/MoreExtensionsDropdown.tsx, playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/Toolbar.tsx, playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/ToolbarDropdown.tsx, playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/ToolbarHistory.tsx, playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/ToolbarNodes.tsx, playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.tsx, playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.tsx, playbook/app/pb_kits/playbook/pb_select/_select.tsx, playbook/app/pb_kits/playbook/pb_selectable_card_icon/_selectable_card_icon.tsx, playbook/app/pb_kits/playbook/pb_selectable_icon/_selectable_icon.tsx, playbook/app/pb_kits/playbook/pb_selectable_list/_selectable_list.tsx, playbook/app/pb_kits/playbook/pb_source/_source.tsx, playbook/app/pb_kits/playbook/types/base.ts, playbook/app/pb_kits/playbook/types/data.ts, playbook/app/pb_kits/playbook/types/index.ts
**Task**
Run our new linter on kits that start with P - T.
**Because**
We've implemented a linter config, but most/all of our library files are still failing its ruleset. We need to update all kits in groups to eventually clean up the entire library to confirm with the new linter configs.
=> [PLAY-1085] Linter implementation: kits P - S

playbook-website/app/controllers/pages_controller.rb, playbook-website/app/helpers/application_helper.rb, playbook-website/app/javascript/components/MainSidebar/NavComponents/KitsNavComponent.tsx, playbook-website/app/javascript/components/MainSidebar/index.tsx, playbook-website/app/views/layouts/_sidebar.html.erb, playbook-website/app/views/pages/kit_show.html.erb, playbook-website/config/menu.yml, playbook-website/lib/pb_doc_helper.rb
[RUNWAY STORY](https://nitro.powerhrg.com/runway/backlog_items/PBNTR-184)
This PR will:
- ✅ Add a 'status' flag to menu.yml file to track kit status ('stable' or 'beta')
- ✅ Create new aggregate_kits method to include kit status
- ✅ Use new method to render sidebar so if 'beta' kit, does not show up in sidebar
- ✅ Edit search_list method to exclude 'beta' kits from typeahead search
- ✅ kit_show page to use new method (call out on top if kit beta)
- ✅ category page to use new method (do not show if kit beta)
- ✅ all kits page to use new method (do not show if kit beta)
1. Test search typeahead
2. Test all kits page
3. Test category page
4. Test kit show pages
5. Check sidebar
=> [PBNTR-184] Add Status Flag to Menu.yml

.github/workflows/github-actions-alpha-version.yml
- Use the exact version `20.11.0` as specified in `.tool-versions` for GH actions workflow.
- Separate NPM build/package/dist task from Ruby Gems.
=> GH Release Workflow Fixes

playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss, playbook/app/pb_kits/playbook/pb_form_group/form_group.rb, playbook/spec/pb_kits/playbook/kits/form_group_spec.rb
Fixes the datepicker margin, when it is used within a form group. 
1. Go to '...'
=> [PLAY-867] Fixed Rails Kit Form Group DatePicker

playbook/app/pb_kits/playbook/pb_bar_graph/_bar_graph.tsx, playbook/app/pb_kits/playbook/pb_bar_graph/bar_graph.rb, playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_custom.html.erb, playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_custom.jsx, playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_custom.md, playbook/app/pb_kits/playbook/pb_bar_graph/docs/example.yml, playbook/app/pb_kits/playbook/pb_bar_graph/docs/index.js, playbook/spec/pb_kits/playbook/kits/bar_graph_spec.rb
Adds a customOptions prop that merges with the current options, allowing for more flexibility in the Highcharts BarGraph when needing to use more flexible/complex use cases. 
Nitro PR to test: https://github.com/powerhome/nitro-web/pull/38055
=> [THOR-93] BarGraph customOptions prop

playbook-website/app/javascript/components/VisualGuidelines/Colors/index.tsx
Fixes layout issue with https://playbook.powerapp.cloud/visual_guidelines/colors
=> Fix colors guidelines layout

playbook-website/app/javascript/components/Website/src/layouts/Footer.tsx, playbook-website/app/javascript/components/Website/src/pages/IconList/index.tsx, playbook-website/app/javascript/packs/app.js, playbook-website/config/routes.rb, playbook-website/config/webpack/environment.js, playbook-website/config/webpacker.yml, playbook-website/package.json, yarn.lock
This PR contains all changes from https://github.com/powerhome/playbook/pull/3182 and intends to:
- Use the latest version of `@powerhome/playbook-icons` and `@powerhome/playbook-icons-react`
- Handle ES modules from the above correctly
https://github.com/powerhome/playbook/compare/play/1141_icon_kit_using_library...PLAY-1241-2
=> [PLAY-1241] rebuild Playbook-Icons-react for use in Nitro

Makefile, playbook-website/bin/cluster_for_review_stack, playbook-website/bin/remote_exec
✅ **This PR does not affect any development or production code!** ⭐️
As a bonus for devs, it would be great to be able to log into PR review environments from our local machines in order to inspect the running file system and debug any issues. 
Usage: `make reviewShell pr=XXXX`
The supporting bin stubs were lifted directly from `nitro-web` and only minor naming `nitro-web -> playbook` was updated within them.
```zsh
make reviewShell pr=3202
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container …
```
=> Enable Remote Shell 

playbook/app/pb_kits/playbook/pb_icon/_icon.tsx, playbook/app/pb_kits/playbook/pb_icon/icon.rb
- Fixes an issue where our own icons appear as vertically mis-aligned. 
1. Go to '...'
=> [PLAY-1265] Add 'svg-inline--fa' class to our icons

playbook/app/pb_kits/playbook/pb_bread_crumbs/_bread_crumbs.scss
[PLAY-1245 ](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1245) makes the border of the Breadcrumbs kit ticket transparent on non-white backgrounds - see Runway ticket for before screenshot and discussion regarding change of scope of ticket to removal of border entirely, and below for after screenshots on Rails/React pages.
TODO:
**Screenshots:** Screenshot with red background shows removed border on React example; screenshot with blue background shows removed border on Rails example; darkmode screenshot shows removed border in darkmode.
**How to test?** Steps to confirm the desired behavior: n/a
~~- [ ] **TESTS** I have added test coverage to my code.~~
=> [PLAY-1245] Make border of Breadcrumbs kit transparent

playbook-website/app/javascript/components/VisualGuidelines/Colors/index.tsx, playbook-website/app/javascript/components/VisualGuidelines/Examples/BorderRadius.tsx, playbook-website/app/javascript/components/VisualGuidelines/Examples/Cursor.tsx, playbook-website/app/javascript/components/VisualGuidelines/Examples/Display.tsx, playbook-website/app/javascript/components/VisualGuidelines/Examples/Hover.tsx, playbook-website/app/javascript/components/VisualGuidelines/Examples/ZIndex.tsx, playbook/app/pb_kits/playbook/pb_flex/docs/_flex_spacing.html.erb
**What does this PR do?** [PLAY-1187](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1187) fixes some layout and page formatting issues on some pages of the Playbook website. See below for before/after screenshots of each affected page.
Colors Page: 
Z-Index Page:
Border Radius Page: 
Display Page:
Cursor Page:
Hover Page (two sets as two spots affected):
Flex Page:
Layout Page (the props floating outside the card in Flex is also fixed futher up on this page)
1. Go to '...'
~~- [ ] **TESTS** I have added test coverage to my code.~~
=> [PLAY-1187] Fix Broken Doc Page Layouts

playbook-website/config/menu.yml, playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_default_date.html.erb, playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_default_date.jsx, playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_range.html.erb, playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_range.jsx, playbook/app/pb_kits/playbook/pb_date_picker/docs/example.yml, playbook/app/pb_kits/playbook/pb_online_status/_online_status.scss, playbook/app/pb_kits/playbook/pb_online_status/_online_status.tsx, playbook/app/pb_kits/playbook/pb_online_status/_online_status_mixins.scss, playbook/app/pb_kits/playbook/pb_online_status/docs/_online_status_default.html.erb, playbook/app/pb_kits/playbook/pb_online_status/docs/_online_status_default.jsx, playbook/app/pb_kits/playbook/pb_online_status/online_status.rb, playbook/spec/pb_kits/playbook/kits/online_status_spec.rb
https://nitro.powerhrg.com/runway/backlog_items/PLAY-1270
https://nitro.powerhrg.com/runway/backlog_items/PLAY-1271
=> [PLAY-1271][PLAY-1270] Enable Online Status & New Colors + Hide Date Range Picker Docs

playbook/app/pb_kits/playbook/pb_toggle/_toggle.scss, playbook/app/pb_kits/playbook/pb_toggle/_toggle.tsx, playbook/app/pb_kits/playbook/pb_toggle/docs/_toggle_disabled.html.erb, playbook/app/pb_kits/playbook/pb_toggle/docs/_toggle_disabled.jsx, playbook/app/pb_kits/playbook/pb_toggle/docs/example.yml, playbook/app/pb_kits/playbook/pb_toggle/docs/index.js, playbook/app/pb_kits/playbook/pb_toggle/toggle.rb, playbook/app/pb_kits/playbook/pb_toggle/toggle.test.js, playbook/spec/pb_kits/playbook/kits/toggle_spec.rb
RUNWAY https://nitro.powerhrg.com/runway/backlog_items/PLAY-1159
Add dedicated disabled prop to the toggle kit,
You can disable with our `input_options` prop, but we want to have disabled styles 
1. Go to https://pr3266.playbook.beta.gm.powerapp.cloud/kits/toggle/react#disabled-prop
2. Whitness greatness
=> [PLAY-1159] Make rails disable prop for toggle kit

playbook/app/pb_kits/playbook/pb_dialog/dialog_footer.html.erb, playbook/app/pb_kits/playbook/pb_dialog/dialog_header.html.erb, playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_compound_components.html.erb
When a form is used to wrap the Rails dialog kit block area content, any unspecified `button` element will submit the form. Only buttons specified with the `type="submit"` attribute should perform this function. 
By defaulting the cancel and close (X) buttons in the Rails version of the kit, we can avoid this unintended side effect. 
- Please see the kits/dialog/rails#complex example
1. Go to the aforementioned path on the review env
2. Activate the modal
3. Click either X or "Cancel"
4. The form should not submit (page should not reload and there should be no `?` at the end of the URL in the browser's address bar)
=> [PLAY-1203] Default cancel and close button type to prevent submission

playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_selected_ids.md, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_selected_ids_react.jsx, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_selected_ids_react.md, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/example.yml, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/index.js
[PLAY-1205](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1205) requests doc changes for the Selected Ids example on the Multi Level Select Kit. Files were edited and created to support differences in markdown text between the Rails and React example that follow a pre-existing but not ideal pattern (that is, appending a `_react` suffix to the .md and .jsx files supporting React and leaving the Rails filenames unaltered) - this will be updated in a [future tech debt ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1274).
Before version of markdown (same for both Rails/React examples):
After version of Rails example markdown:
After version of React example markdown:
1. Go …
=> [PLAY-1205] Update Multilevel React Doc for clarity on selectedIds

playbook-website/app/controllers/pages_controller.rb, playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_default.html.erb
Runway: https://nitro.powerhrg.com/runway/backlog_items/PLAY-1266
This page was broken in prod https://playbook.powerapp.cloud/kit_category/navigation?type=rails
I was broken because the pagination kit needs the `@users` vairable
review env https://pr3296.playbook.beta.hq.powerapp.cloud/kit_category/navigation?type=rails
=> [PLAY-1266] Fix Nav Category Page

playbook-website/app/javascript/site_styles/_samples_show.scss, playbook-website/app/views/samples/show.html.erb
[PBNTR-246](https://nitro.powerhrg.com/runway/backlog_items/PBNTR-246)
Fixes the "Code" icon to show sample code.
Updated copy to say "Show Code"
1.Go to any sample (/samples/crm_client_list)
2. Click "Code" to toggle code
=> [PBNTR-246] fix UI Samples code view

playbook/app/pb_kits/playbook/pb_advanced_table/docs/advanced_table_example_mock_data.rb
`advanced_table_example_mock_data.rb` is causing the site to crash repeatedly. The file isn't being used and is not a module, so Zeitwerk fails to autoload it.
=> [PBNTR-242] Hotfix: Remove advanced_table_example_mock_data.rb

playbook-website/Gemfile.lock, playbook/Gemfile.lock, playbook/playbook_ui.gemspec
- Remove the limit imposed for Rails and friends within the gemspec from [this PR](https://github.com/powerhome/playbook/commit/4d179c672c8fc554a235c34246f1a0dde40ea622#diff-14c9f8391ff13e0125d9abf5439cee7e259fc8da50d8a4ceba7e68ce66aeff03R34-R36)
=> Remove rails upper version limit in gemspec

playbook/app/pb_kits/playbook/pb_avatar/avatar.html.erb, playbook/lib/playbook/kit_base.rb
As a Playbook dev,
I want to provide a content tag helper (playbook_tag),
so that I can dry up kit template code where content_tag is currently being used.
1. Go to kits/avatar
2. See kit renders with expected output
3. Spec test is green
=> [PLAY-1269] DRY up the content_tag portion of Rails kits: Avatar

playbook/app/pb_kits/playbook/pb_body/_body.scss
[PLAY-1297](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1297) adjusts the italic and bold text style in the body kit so they exhibit predictable behavior when used in text editors. See technical details of runway ticket for explicit changes made as interim step before a more comprehensive PBHUB ticket improves upon this (runway ticket also links to the prior investigations that prompted this change).
**Screenshots:** Screenshots from code sandboxes (left = previous version; right = new alpha)
1. Review code sandbox with new alpha provided in runway ticket.
2. Test italicization: italicized/emphasized text should become italicized (but not bold).
3. Test bold links: a link that is then made bold …
=> [PLAY-1297] Update text styles to prevent inconsistent Tiptap output

playbook/app/pb_kits/playbook/pb_background/_background.tsx
[PLAY-998](https://nitro.powerhrg.com/runway/backlog_items/PLAY-998) removes the null alt tag and empty style tag that appeared on the React Background kit (see example screenshot in ticket). The alt tag was a straightforward change, and now only appears when there is purposeful alt text to display for the background. For the style tag, it took some time to fully capture the behavior because this only happens when a page is first loaded: upon page reload, the style tag fills in with relevant style attribute information. The empty tag behavior occurs when the background does not have an image/image URL to display, and the the added conditional to the image-related props in backgroundStyle solve the …
=> [PLAY-998] Background kit remove empty inline styles/attributes

docs/README.md, run.sh
- Adds run script from playgrounds and huddle repo. This script allows quicker startup without the bootstrapping.
Example Usage:
* Working on PLAY-1234 branch, I made changes, committed and pushed. Now I need to checkout another branch to test locally. This requires installation bc dependencies are different. 
+ Simply executing `./run.sh` will install any dependencies (skip if unnecessary) and start the app. 
**References:**
1. https://github.com/powerhome/playgrounds/blob/master/run.sh
2. https://github.com/powerhome/huddle/blob/master/run.sh
**Pre-requisites** 
- You should have run `./setup.sh` at least once since downloading the repo. 
1. …
=> Add run.sh

playbook-website/app/javascript/components/VisualGuidelines/Examples/MaxWidth.tsx
[PLAY-1126](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1126) adds the pixel values for each MaxWidth prop value to the visual guide on the guideline page (see runway ticket for specific designer feedback and context). Pixel values sourced from [here](https://github.com/powerhome/playbook/blob/6508e8593d0ac5b8c85a0e29fdd11c2a488b97fb/playbook/app/pb_kits/playbook/utilities/_max_width.scss).
1. Go to [MaxWidth guidelines page](https://playbook.powerapp.cloud/visual_guidelines/max_width)
2. Scroll down to the visual guide
3. See addition of pixel values in each example XS-XXL. …
=> [PLAY-1126] add px to Max Width global prop values left aligned

playbook-website/app/controllers/pages_controller.rb
[PLAY-1304](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1304) allows for pagination to appear in a kit_collection. This ticket is similar to one noticed on the [Navigation kit_show page](https://playbook.powerapp.cloud/kit_category/navigation?type=rails) due to Pagination which was fixed in [PLAY-1266](https://github.com/powerhome/playbook/pull/3296). 
I have also removed the `kit_collection_show` method from the pages controller as it has been made redundant by `kit_collection_show_rails` and `kit_collection_show_react` (side note: doesn't look like there is the ability to see a swift kit_collection yet on live per my testing [example …
=> [PLAY-1304] fix Kit Collection page when Pagination is present 

playbook/app/pb_kits/playbook/pb_button/_button.scss
[PLAY-761](https://nitro.powerhrg.com/runway/backlog_items/PLAY-761) addresses the reported issue that Buttons with a specified Size prop do not respond to global padding props. We expect global props to take precedence over kit styles, and only Button size kit has this padding size calculation. 
My initial proposed solution is to remove the ```!important``` tag on the padding calculation (which has been there since this line was first written in a [previous PR](https://github.com/powerhome/playbook/pull/1749/files)) so that it functions as expected but allows for modification via global props when necessary. 
**Screenshots:** see CSB links in Testing section below in addition to these screenshots …
=> [PLAY-761] Global padding props don't affect Buttons

playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.scss, playbook/app/pb_kits/playbook/pb_section_separator/_section_separator_mixin.scss
runway https://nitro.powerhrg.com/runway/backlog_items/PLAY-939
the vertical section separator doesn't show up on fire fox because fire fox is rounding down on a 1px width
using width of 1.9 forces the width to be greater than 1 but less than 2 which should result in 1px all the time 
check it out here https://pr3370.playbook.beta.px.powerapp.cloud/kits/section_separator/react#vertical
=> [PLAY-939] Section Separator Vertical Variant Fixes

playbook/app/pb_kits/playbook/pb_progress_simple/docs/_progress_simple_flex.html.erb, playbook/app/pb_kits/playbook/pb_progress_simple/docs/_progress_simple_flex.jsx, playbook/app/pb_kits/playbook/pb_progress_simple/docs/_progress_simple_flex.md, playbook/app/pb_kits/playbook/pb_progress_simple/docs/example.yml, playbook/app/pb_kits/playbook/pb_progress_simple/docs/index.js, playbook/app/pb_kits/playbook/pb_progress_simple/progress_simple.rb
runway https://nitro.powerhrg.com/runway/backlog_items/PLAY-1296
i needed to change the rails classname logic to correctly apply `flex 1` but otherwise this story is just adding a doc
=> [PLAY-1296] Update Progress Simple docs to Use Flex

playbook-website/app/views/guides/getting_started/ruby_on_rails_setup.md
Playbook was usable without the rest, but things were not quite right. I found small things like spacing didn't match what I thought it should. Also, link buttons had the underscore text decoration.
Without reset imported
With reset imported
1. Setup a blank Rails app with playbook imported but without importing the reset first.
2. Make a test page using some rails kits, like the link button.
3. See the kits render wrong, when compared to playbook examples.
4. Import the reset before playbook, and see See the kits render correctly, when compared to playbook examples.
=> Document reset css for Ruby on Rails setup guide

playbook/app/pb_kits/playbook/pb_loading_inline/_loading_inline.tsx, playbook/app/pb_kits/playbook/pb_loading_inline/docs/_loading_inline_custom.html.erb, playbook/app/pb_kits/playbook/pb_loading_inline/docs/_loading_inline_custom.jsx, playbook/app/pb_kits/playbook/pb_loading_inline/docs/_loading_inline_default.html.erb, playbook/app/pb_kits/playbook/pb_loading_inline/docs/_loading_inline_default.jsx, playbook/app/pb_kits/playbook/pb_loading_inline/docs/example.yml, playbook/app/pb_kits/playbook/pb_loading_inline/docs/index.js, playbook/app/pb_kits/playbook/pb_loading_inline/loading_inline.html.erb, playbook/app/pb_kits/playbook/pb_loading_inline/loading_inline.rb, playbook/app/pb_kits/playbook/pb_loading_inline/loading_inline.test.js, playbook/spec/pb_kits/playbook/kits/loading_inline_spec.rb
[PLAY-1307](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1307) adds a text prop with a default value of 'Loading' to the [Loading Inline kit](https://playbook.powerapp.cloud/kits/loading_inline/), and adds a Custom Text kit example showing developers how to customize their Loading Inline components with the new prop. Both the Rails and React versions of the kit have been updated, as have their tests.
In the course of this ticket I also standardized the primary Loading Inline example's name as "default" instead of "light" which was set ~5 years ago - the name is now "default" consistently across Rails and React files and kit example pages.
**Screenshots:** Screenshots of Custom Text kit example …
=> [PLAY-1307] add Loading Inline custom text option

playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.tsx
[PLAY-1249](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1249) addresses an issue on a Nitro page where a react Tooltip is shifting downward slightly when it is in a form. The react Tooltip was given an inline style of "display: inline-flex" when it was first created, but I'm not entirely sure as to it's purpose. Removing this line (or changing the display to inline or block) stops the misalignment from occurring. 
[CSB reproducing issue](https://codesandbox.io/p/sandbox/play-1249-reproduce-issue-v8xw4m)
[CSB with alpha](https://codesandbox.io/p/sandbox/little-fog-nd29j4)
All three inputs are aligned when inline display styling is …
=> [PLAY-1249] Fix Tooltips wrapping form elements causing misalignment

playbook/app/pb_kits/playbook/pb_dropdown/dropdown.html.erb, playbook/app/pb_kits/playbook/pb_dropdown/dropdown_container.html.erb, playbook/app/pb_kits/playbook/pb_dropdown/dropdown_option.html.erb, playbook/app/pb_kits/playbook/pb_dropdown/dropdown_trigger.html.erb
Since we are reverting the PR that created the pb_content_tag [here](https://github.com/powerhome/playbook/pull/3391), we are reverting the dropdown kit to NOT use that pb_content_tag
=> Dropdown to Use Content Tag instead of pb_content_tag

playbook/app/pb_kits/playbook/pb_multiple_users/_multiple_users.scss
[PLAY-1122](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1122) addresses a longstanding bug on the Multiple Users kit wherein the first user badge in the group (the leftmost one on the Default and Size examples, the rightmost one on the Reverse example) overflows out of the expected border. 
This occurred because the token ```pb_multiple_users_overlap``` a negative pixel value which was used to cause the visual overlapping of multiple user avatars, applied this negative to the first avatar which had no neighbor to overlap with. This PR removes this spacing token from the first ```pb_multiple_users_item``` and stops it from shifting "out of bounds" anymore. It does increase the width of …
=> [PLAY-1122] fix Multiple Users padding overflow

playbook-website/app/components/playbook/pb_docs/kit_example.html.erb, playbook/app/pb_kits/playbook/pb_body/_body.scss, playbook/app/pb_kits/playbook/pb_body/_body_mixins.scss, playbook/app/pb_kits/playbook/pb_button/_button_mixins.scss, playbook/app/pb_kits/playbook/pb_caption/_caption_mixin.scss, playbook/app/pb_kits/playbook/pb_detail/_detail_mixins.scss, playbook/app/pb_kits/playbook/pb_docs/kit_example.html.erb, playbook/app/pb_kits/playbook/pb_title/_title.scss, playbook/app/pb_kits/playbook/tokens/_titles.scss
runway https://nitro.powerhrg.com/runway/backlog_items/PLAY-468
changes the color on all buttons and links to active dark when in dark mode 
=> [PLAY-468] Change darkmode button and link color

playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss
[PLAY-1250](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1250) addresses the issue of border radii not lining up flush for text input addons within a form group like they do for default text inputs in a form group. This PR corrects this issue. 
I also discovered and fixed a related bug present in production but not reported by devs/designers regarding this kit: for right-aligned Text Input addon cards with ```border: true```, the border was not appearing unless the card was the last item in the form group.
[CSB reproducing issue](https://codesandbox.io/p/sandbox/play-1250-reproduce-issue-hp7pf7)
[CSB alpha](https://codesandbox.io/p/sandbox/play-1250-alpha-p23m95)
**Screenshots:** Screenshots …
=> [PLAY-1250] fix Text Input addon border radius within a form group

playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss
[PLAY-1115](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1115) corrects the error color for the border of text input addon cards and the error message in dark mode. These currently display as $error color in both light and dark modes but should change to $error_dark in dark (rails + react).
1. Go to [text input](https://playbook.powerapp.cloud/kits/text_input) kit page (in either rails or react) and toggle to dark mode (top right corner).
2. Scroll down to the [with error](https://playbook.powerapp.cloud/kits/text_input#with-error) kit example.
3. See all error borders and text …
=> [PLAY-1115] fix Text input add-on dark mode border and message color

playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb, playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb, playbook/lib/playbook/forms/builder.rb, playbook/lib/playbook/forms/builder/phone_number_field.rb
Making Phone Number Input kit compatible with pb_form_with
1. Go to the Form kit doc page.
=> [PBNTR-48] Making Phone Number Input kit compatible with pb_form_with

playbook/app/pb_kits/playbook/pb_pagination/_pagination.scss
[RUNWAY STORY](https://nitro.powerhrg.com/runway/backlog_items/PBNTR-294)
- old-styles SCSS in Nitro was overriding the padding within pagination kit. 
- adding this important tag should fix the issue
1. Go to '...'
=> [PBNTR-294] Fix for Nitro Style bleed with Pagination kit

playbook/app/pb_kits/playbook/pb_select/_select.scss
This allows the dev more fine-grained control over the elements inside of our Select kit, and enables them to move things around using our global spacing props-- which in turn, fixes a bug where the Select kit is broken when nested inside of a Flex kit. 
https://codesandbox.io/p/sandbox/funny-booth-rqd9dq
=> [PLAY-1178] Fixed Styling when Select Kit is used within a Flex Kit

playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.scss, playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.tsx, playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_display.jsx, playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_display_rails.html.erb, playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_options.jsx, playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_options_rails.html.erb, playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_padding.md, playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_trigger.jsx, playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_with_custom_trigger_rails.html.erb, playbook/app/pb_kits/playbook/pb_dropdown/dropdown.test.jsx, playbook/app/pb_kits/playbook/pb_dropdown/dropdown_option.html.erb, playbook/app/pb_kits/playbook/pb_dropdown/dropdown_option.rb, playbook/app/pb_kits/playbook/pb_dropdown/subcomponents/DropdownOption.tsx
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PBNTR-308)
The Dropdown Option had an additional Flex which was adding padding in addition to the overall padding. This additional padding could not be overridden using global props so devs could not really achieve padding="none" if they needed to.
This PR removes that additional Flex and moves other pieces around to maintain the default UI but allow devs to remove all padding if needed.
[csb with alpha with no padding](https://codesandbox.io/s/edwardtestinglist-forked-r7g4qy)
1. Go to '...'
=> [PBNTR-308] Dropdown Custom Option Padding

playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss
[PLAY-1209](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1209) fixes the border radii of the Date Picker kit in React within a form group so they are flush and visually unified like it is for Rails and for Text Inputs with a form group. When looking at [_form_group.scss](https://github.com/powerhome/playbook/blob/master/playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss) closely there was code in place to address this but the input wrapper classes had not been changed from those of a default text input to those found in date pickers.
[CSB reproducing issue](https://codesandbox.io/p/sandbox/play-1209-reproduce-issue-n2vrkm)
[CSB with …
=> Play 1209 fix form group date picker border radius react

playbook/app/pb_kits/playbook/pb_bar_graph/barGraph.test.js, playbook/app/pb_kits/playbook/pb_circle_chart/circleChart.test.js, playbook/app/pb_kits/playbook/pb_dashboard/pbChartsDarkTheme.ts, playbook/app/pb_kits/playbook/pb_dashboard/pbChartsLightTheme.ts, playbook/app/pb_kits/playbook/pb_gauge/gauge.test.js, playbook/app/pb_kits/playbook/pb_line_graph/lineGraph.test.js, playbook/app/pb_kits/playbook/pb_treemap_chart/treemapChart.test.js, playbook/package.json, yarn.lock
Runway https://nitro.powerhrg.com/runway/backlog_items/PLAY-1351
Upgrades highcharts from version 9 to 10
I added the boiler plate for tests for the graphs because they had nothing. I would have liked to add snapshot testing but was having issues because highcharts generates random ids for different parts of the graphs
your suppose to be able to do things like expect.any(String) https://jestjs.io/docs/snapshot-testing#property-matchers But you need to download other library(s) to get it to work. I bailed because its out of scope
other people have this issue https://github.com/enzymejs/enzyme/issues/1050
```
test('bargraph has right html structure', () => {
const { container } = render(
<BarGraph
data={{ …
```
=> [PLAY-1351] Upgrade Highcharts

playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.tsx
[PLAY-1343](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1343) -  as of right now this PR is for making an alpha that reverts change from [PLAY-1249](https://github.com/powerhome/playbook/pull/3380) in order to truly verify that this change isn't the cause of the runway tooltip misalignment issue.
1. Go to '...'
=> [PLAY-1343] fix Tooltip oversize and misalignment issue

playbook/app/pb_kits/playbook/pb_draggable/_draggable.scss, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_default.jsx, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_default.md, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_multiple_containers.jsx, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_cards.jsx, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_list.jsx, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_list.md, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_selectable_list.jsx, playbook/app/pb_kits/playbook/pb_draggable/docs/example.yml, playbook/app/pb_kits/playbook/pb_draggable/docs/index.js, playbook/app/pb_kits/playbook/pb_list/_list.tsx, playbook/app/pb_kits/playbook/pb_list/_list_item.tsx, playbook/app/pb_kits/playbook/pb_selectable_list/_item.tsx, playbook/app/pb_kits/playbook/pb_selectable_list/_selectable_list.tsx
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PBNTR-328)
✅ Make `<Draggable>` optional for kit to work for fewer nesting requirements
✅ Drag handle styling for Drag Item
✅ dragHandle should be able to be turned off if needed
✅ dragHandle inside specific kits
✅ Build our prop enabled dragging for following kits with Draggable under the hood:
✅ List
✅ SelectableList
✅ Separate code into proper folder structure and finalize all prop names after feedback from V1.
=> [PBNTR-328] Draggable v2

playbook-website/app/javascript/components/MainSidebar/MenuData/GuidelinesNavItems.ts, playbook-website/app/javascript/components/VisualGuidelines/Examples/VerticalAlign.tsx, playbook-website/app/javascript/components/VisualGuidelines/index.tsx, playbook-website/app/views/pages/code_snippets/vertical_align_jsx.txt
Adding Vertical Align global prop doc.
1. Go to /visual_guidelines/vertical_align page.
=> [PBNTR-326] Adding Vertical Align global prop doc

playbook/app/pb_kits/playbook/pb_circle_chart/circle_chart.rb
This PR adds `border_width` prop the the rails circle chart so it matches the React side.
[PBNTR-335](https://nitro.powerhrg.com/runway/backlog_items/PBNTR-335)
1. Go to '...'
=> [PBNTR-335] add border width prop to circle chart

playbook/app/pb_kits/playbook/pb_circle_chart/_circle_chart.tsx
Runway https://nitro.powerhrg.com/runway/backlog_items/PLAY-1361
Change assertion of `itemToMove` to just be an `HTMLElement`
1. Go to https://pr3448.playbook.beta.hq.powerapp.cloud/kits/circle_chart/react
2. Look at props
3. Pary
- [😈] **TESTS** I have added test coverage to my code.
=> [PLAY-1361] Fix kit props in Docs Circle Chart

playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_column_rails.html.erb, playbook/app/pb_kits/playbook/pb_table/table_header.html.erb
[PBNTR-312](https://nitro.powerhrg.com/runway/backlog_items/PBNTR-312)
This PR removed the Flex wrapper when there is no `sorting_style`. Since there is no `sorting_style`, there shouldn't be a need for a flex.
1. Go to the rails Table kit and confirm styling is still correct.  Especially `/kits/table/rails#table-header-11`
2. Check the Table Sorts on the [Alpha](https://pr40246.nitro-web.beta.px.powerapp.cloud/sales/reps?redirect_fallback=/sales/reps)
=> [PBNTR-312] Table_header flex removal

playbook-website/app/helpers/application_helper.rb, playbook-website/config/menu.yml, playbook/lib/generators/kit/kit_generator.rb, playbook/lib/generators/kit/templates/kit_example_react.erb.tt, playbook/lib/generators/kit/templates/kit_html.erb.tt, playbook/lib/generators/kit/templates/kit_jsx_test.erb.tt, playbook/lib/playbook/kit_base.rb
[PLAY-1330](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1330) and this [issue-documentation gist](https://gist.github.com/nidaqg/4519e2f383bf9d5700bd0af71e6f64ac) request a few fixes and a documentation update so the kit generator can function again. 
**Description + Screenshots:** 
- It is now possible to have a sidebar subcategory with only one component in it. The page will load without erroring out. This works whether or not the sole kit is of status beta or stable (there are follow up tickets in place to address beta adding beta status by default and the fact that beta kits show without warning in the kit_category page). 
- It is ideal to leave a blank line at the end of `menu.yml` so that …
=> [PLAY-1330] Fix Kit Generator in Playbook

playbook/app/pb_kits/playbook/pb_dialog/dialog.html.erb
[Story link](https://nitro.powerhrg.com/runway/backlog_items/PBHUB-127)
Adds the `turbo:frame-load` to the Dialog kit so pages using Hotwire don't lose the kit functionalities
=> [PBHUB-127] Add turbo frame event listener to dialog kit

playbook-website/app/components/playbook/pb_docs/kit_example.rb
[PLAY-1274](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1274) looks to update the way playbook parses the markdown files and example files of kit examples in order to streamline naming conventions in order to account for differences between Rails and React versions. This PR adds logic to the `read_kit_file` that displays the markdown description files based on file type. I have tested it against our current file naming conventions and with a trial of our idealized future naming conventions as outlined in the runway ticket - I will go into the specifics of the naming conventions as well below in the screenshot section. 
_**NOTE:**_
This PR makes changes in …
=> [PLAY-1274] Website: Allow Type-Specific Kit Doc Description Markdown

playbook/app/pb_kits/playbook/pb_card/_card.tsx, playbook/app/pb_kits/playbook/pb_draggable/_draggable.scss, playbook/app/pb_kits/playbook/pb_draggable/context/index.tsx, playbook/app/pb_kits/playbook/pb_draggable/context/types.ts, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_default.jsx, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_default.md, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_multiple_containers.jsx, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_cards.jsx, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_cards.md, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_list.jsx, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_list.md, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_selectable_list.jsx, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_selectable_list.md, playbook/app/pb_kits/playbook/pb_draggable/draggable.test.jsx, playbook/app/pb_kits/playbook/pb_draggable/subcomponents/DraggableItem.tsx, playbook/app/pb_kits/playbook/pb_list/_list.tsx, playbook/app/pb_kits/playbook/pb_list/_list_item.tsx, playbook/app/pb_kits/playbook/pb_selectable_list/_item.tsx, playbook/app/pb_kits/playbook/pb_selectable_list/_selectable_list.tsx, playbook/app/pb_kits/playbook/utilities/globalProps.ts
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PBNTR-345)
This PR:
- ✅ Refactors the context to use useReducer and memoization instead of just state for performance improvement
- ✅ Adds all Jest tests
- ✅ Changes prop names based on feedback to make them easier to understand
- ✅ Fixes a bug where it was not working with variant="radio" for SelectableList. 
- TLDR: The DraggableItem requires id to function, but this was interfering with other kits (like the Radio kit) and how it handles id. Best solution was an additional prop called `dragId` in the same way we have pickerId for the datepicker: it is a required prop but will not interfere with how different kits handle id. In the long …
=> [PBNTR-345] Draggable v4 (Beta)

playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.tsx, playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_custom_icon.html.erb, playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/_fixed_confirmation_toast_custom_icon.jsx, playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/example.yml, playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/docs/index.js, playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/fixed_confirmation_toast.rb, playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/fixed_confirmation_toast.test.js, playbook/spec/pb_kits/playbook/kits/fixed_confirmation_toast_spec.rb
[PLAY-1329](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1329) requests the ability to use custom icons in the Fixed Confirmation Toast kit. This PR allows for passing an icon prop to the component along with a status in order to add a new icon while utilizing one of the four style patterns for the confirmation toasts (error, success, neutral, and tip) in Rails and React. Other things of note: 
- Using a custom icon adds `custom_icon` to the classname construction. 
- Custom Icon Rails and React doc examples have been added to playbook (one of which is modeled after the mock provided by the requesting designer in runway). 
- Additionally, this PR adds a jest test file to the fixed confirmation …
=> [PLAY-1329] allow any icon to be used in Fixed Confirmation Toast

playbook-website/app/controllers/pages_controller.rb
Loading Advanced Table mock data in all pages we need.
1. Go to https://pr3480.playbook.beta.px.powerapp.cloud/kits?type=rails#default-required-props or https://pr3480.playbook.beta.px.powerapp.cloud/kit_category/data_visualization?type=rails#default-required-props
=> [PBNTR-343] Loading Advanced Table mock data in all pages we need

playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_beta_sort.html.erb, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_beta_sort.md, playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml, playbook/app/pb_kits/playbook/pb_advanced_table/table_header.html.erb, playbook/app/pb_kits/playbook/pb_table/table_header.html.erb
Adding column sort to Advanced Table kit
1. Go to the Advanced Table kit
2. Scroll down to the Table Sort doc example
=> [PBNTR-331] Adding column sort to Advanced Table kit

playbook/app/pb_kits/playbook/pb_collapsible/index.js, playbook/app/pb_kits/playbook/pb_nav/docs/_collapsible_nav.html.erb, playbook/app/pb_kits/playbook/pb_nav/docs/_collapsible_nav.jsx, playbook/app/pb_kits/playbook/pb_nav/docs/_collapsible_nav.md, playbook/app/pb_kits/playbook/pb_nav/item.html.erb, playbook/app/pb_kits/playbook/pb_nav/item.rb, playbook/spec/pb_kits/playbook/kits/nav_item_spec.rb
- Adds `collapsed` prop to rails side of collapsible nav so you can set initial state for collapsed nav
- Fixes bug where icon was not rendering according to it being open or closed
=> [PBNTR-360] Adding Collapsed Prop to Collapsible Nav on Rails

playbook/app/pb_kits/playbook/pb_date_time_stacked/docs/_date_time_stacked_default_swift.md, playbook/app/pb_kits/playbook/pb_date_time_stacked/docs/_date_time_stacked_props_swift.md, playbook/app/pb_kits/playbook/pb_date_time_stacked/docs/example.yml
A clear and concise description with your runway ticket url.
[PBIOS-442] Date Time Stacked Docs
=> [PBIOS-442] Date Time Stacked Docs

playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.tsx
Remove duplicate "code block" button in Rich Text Editor.
The default Trix "code" button displays code text as a "block", but we want code to display "inline". 
Fix duplicate button as the logic for hiding the "block" button happened on `trix-selection-change`, not at the start. 
Current prod behavior:
If you click the first "code" button, then there is broken "code block" styling:
New behavior:
1. Go to https://pr3501.playbook.beta.hq.powerapp.cloud/kits/rich_text_editor/react
3. The code button in the RTE should show only once
4. Highlight some text
5. Click the code button.
6. The …
=> [PLAY-692] Remove duplicate "block" button in RTE on start, not change

playbook-website/app/javascript/components/Website/src/pages/ComponentList.tsx
[PLAY-1291](https://runway.powerhrg.com/backlog_items/PLAY-1291) requests a way to remove any beta kits from appearing on the beta version of the all kits page. 
Beta all kits page: https://playbook.powerapp.cloud/beta/kits
Current all kits page: https://playbook.powerapp.cloud/kits/
This PR achieves this by filtering through the components list and only displaying those with status "stable". Beta kits have status "beta". The review environment just has one beta kit, Draggable, (which matches current state of kits in production) but when testing locally I made many kits status "beta". 
Next Steps: there is a follow up ticket to address beta kits appearing on the current and beta versions of the …
=> [PLAY-1291] hide beta versions of kits within Beta Index (with menu.yml)

playbook/app/pb_kits/playbook/pb_background/background.html.erb, playbook/app/pb_kits/playbook/pb_body/body.html.erb, playbook/app/pb_kits/playbook/pb_bread_crumbs/bread_crumb_item.html.erb, playbook/app/pb_kits/playbook/pb_bread_crumbs/bread_crumbs.html.erb, playbook/app/pb_kits/playbook/pb_caption/caption.html.erb, playbook/app/pb_kits/playbook/pb_card/card.html.erb, playbook/app/pb_kits/playbook/pb_detail/detail.html.erb, playbook/app/pb_kits/playbook/pb_dialog/dialog.html.erb, playbook/app/pb_kits/playbook/pb_dialog/dialog_body.html.erb, playbook/app/pb_kits/playbook/pb_dialog/dialog_footer.html.erb, playbook/app/pb_kits/playbook/pb_dialog/dialog_header.html.erb, playbook/app/pb_kits/playbook/pb_flex/flex.html.erb, playbook/app/pb_kits/playbook/pb_hashtag/hashtag.html.erb, playbook/app/pb_kits/playbook/pb_highlight/highlight.html.erb, playbook/app/pb_kits/playbook/pb_home_address_street/home_address_street.html.erb
Nitro Alpha https://pr40783.nitro-web.beta.hq.powerapp.cloud/user_requests/new?redirect_fallback=/sales/reps
Runway https://runway.powerhrg.com/backlog_items/PLAY-1367
replace's rails `content_tag' in some of our kits to our wrapper `pb_content_tag`
Only making these changes to a small number of kits because the scope is too large
=> [PLAY-1367] Use new content tag

playbook/app/pb_kits/playbook/pb_date_year_stacked/docs/_date_year_stacked_default.jsx
[Play-1364](https://runway.powerhrg.com/backlog_items/PLAY-1364)
Fixes darkmode conversion with left aligned date year stacked.
1. Go to date year stacked kit, confirm styles/colors are correct
=> [PLAY-1364] Date Year Stacked Left Align Text Color Bug

playbook/app/pb_kits/playbook/pb_background/background.html.erb, playbook/app/pb_kits/playbook/pb_body/body.html.erb, playbook/app/pb_kits/playbook/pb_bread_crumbs/bread_crumb_item.html.erb, playbook/app/pb_kits/playbook/pb_bread_crumbs/bread_crumbs.html.erb, playbook/app/pb_kits/playbook/pb_caption/caption.html.erb, playbook/app/pb_kits/playbook/pb_card/card.html.erb, playbook/app/pb_kits/playbook/pb_detail/detail.html.erb, playbook/app/pb_kits/playbook/pb_dialog/dialog.html.erb, playbook/app/pb_kits/playbook/pb_dialog/dialog_body.html.erb, playbook/app/pb_kits/playbook/pb_dialog/dialog_footer.html.erb, playbook/app/pb_kits/playbook/pb_dialog/dialog_header.html.erb, playbook/app/pb_kits/playbook/pb_flex/flex.html.erb, playbook/app/pb_kits/playbook/pb_hashtag/hashtag.html.erb, playbook/app/pb_kits/playbook/pb_highlight/highlight.html.erb, playbook/app/pb_kits/playbook/pb_home_address_street/home_address_street.html.erb
Reverts powerhome/playbook#3497 for the sole purpose of decreasing our risk in nitro with the Fonts work on the next release. (13.32.0)
=> Revert "[PLAY-1367] Use new content tag"

playbook-website/config/menu.yml, yarn.lock
Fixes kit status that accidentally got put bsck into beta on [this PR](https://github.com/powerhome/playbook/pull/3488)
=> Change Draggable Kit status to Stable

playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.scss, playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.test.jsx, playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.tsx, playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_example.html.erb, playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_example.jsx, playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_size.html.erb, playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_size.jsx, playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_tag.html.erb, playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_tag.jsx, playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_user.html.erb, playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_user.jsx, playbook/app/pb_kits/playbook/pb_form_pill/form_pill.html.erb, playbook/app/pb_kits/playbook/pb_form_pill/form_pill.rb, playbook/spec/pb_kits/playbook/kits/form_pill_spec.rb
[PLAY-882](https://runway.powerhrg.com/backlog_items/PLAY-882) begins the efforts (ticket 1 of 4 at the moment) to match the updated Form Pill/Typeahead [handoff](https://www.figma.com/file/79KJo0Jl8HSNOBQPJo5MSp/Typeahead-Dropdowns?type=design&node-id=240%3A7600&mode=design&t=f7VGtBFjzitLydyF-1) by:
- adding the color prop
- including neutral as an option in addition to the current default primary
- setting up background, hover, and active states for both colors
- setting focus-ability via adding tabIndex prop
- adding jest tests and updating rspec tests (involved adding data prop to react version in order for jest tests to work like other kit tests do)
Here is a [Codesandbox with …
=> [PLAY-882] Form pills: match handoff (primary + default)

playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_default.html.erb
[PLAY-1429](https://runway.powerhrg.com/backlog_items/PLAY-1429)
Updated the default Typeahead variant in the Rails display of Playbook to match the default provided in React.
1. Go to Components in Playbook, Form Inputs, Typehead
2. Click on Rails (if not deafulted) and verify Typehead drop down single selection works. Compare with react default.
=> [PLAY-1429] Improve consistency in docs for default variant of Typeahead

playbook-website/app/controllers/pages_controller.rb, playbook-website/app/javascript/components/Website/src/components/CategoryTitle/index.tsx, playbook-website/app/javascript/components/Website/src/hooks/loaders.ts, playbook-website/app/javascript/components/Website/src/pages/CategoryShow/index.tsx, playbook-website/app/javascript/components/Website/src/pages/ComponentList.tsx, playbook-website/app/javascript/packs/app.js, playbook-website/test/menu_yml_spec.rb
[PLAY-1402](https://runway.powerhrg.com/backlog_items/PLAY-1402) ensures that beta kits are not visible on the kit_category pages of the Playbook website. This includes both PB/kit_category/category_title and PB/beta/kit_category/category_title endpoints. This PR also continues some work started in PLAY-1391 [runway](https://runway.powerhrg.com/backlog_items/PLAY-1391)/[PR](https://github.com/powerhome/playbook/pull/3488) to fully update name -> category for beta website pages based on the change to menu.yml.
The stretch goal 🌟 in the runway ticket was also achieved: `menu_yml_spec.rb` contains some basic tests to confirm the YAML file loads without errors, that categories and components are properly …
=> [PLAY-1402] hide beta versions of kits within Kit Categories (with menu.yml)

playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_custom.md
[PLAY-1431](https://runway.powerhrg.com/backlog_items/PLAY-1431)
Updates Highcharts CustomOption Formatting note discrepancy in docs
New Message:
1. Go to Playbook components, data visualizers, bar graph
2. Scroll down to "CUSTOM OVERRIDES"
=> [PLAY-1431] Update Highcharts CustomOptions Formatting Note

playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/MoreExtensionsDropdown.tsx, playbook/app/pb_kits/playbook/pb_rich_text_editor/TipTap/ToolbarDropdown.tsx
[PLAY-877](https://runway.powerhrg.com/backlog_items/PLAY-877)
The "..." button on the top toolbar of the RTE should toggle its popover dropdown. When clicked again while the dropdown is open, it should close. The same behavior applies to the paragraph formatting dropdown. Although the paragraph formatting dropdown was not mentioned in the provided bug story, the fix involved replicating the functionality of the "..." button in a different file.
1. Go to Playbook Components -> Format Input -> Rich Text Editor
2. Click the "..." extensions button in the RTE toolbar once to verify that the dropdown opens, and click it again to confirm that it closes. Repeat the same process for the paragraph …
=> [PLAY-877] RTE Custom Extenion Dropdown Button Bug Fix

playbook-website/app/javascript/components/VisualGuidelines/Examples/BorderRadius.tsx, playbook-website/app/javascript/components/VisualGuidelines/index.tsx, playbook-website/app/views/pages/code_snippets/border_radius_jsx.txt
[PLAY-1405](https://runway.powerhrg.com/backlog_items/PLAY-1405) updates the [Border Radius](https://playbook.powerapp.cloud/visual_guidelines/border_radius) Tokens and Guidelines page to include more information about how to use this global prop on our kits by including a global prop table and an "example in use." It now also links to the Card kit's border radius [doc example](https://playbook.powerapp.cloud/kits/card/react#border-radius).
1. Go to the Border Radius page in Tokens & Guidelines in the review environment [here](https://pr3534.playbook.beta.hq.powerapp.cloud/visual_guideli …
=> [PLAY-1405] Create a Doc for Border Radius Global Props

playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.scss, playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.test.jsx, playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.tsx, playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_icon.html.erb, playbook/app/pb_kits/playbook/pb_form_pill/docs/_form_pill_icon.jsx, playbook/app/pb_kits/playbook/pb_form_pill/docs/example.yml, playbook/app/pb_kits/playbook/pb_form_pill/docs/index.js, playbook/app/pb_kits/playbook/pb_form_pill/form_pill.html.erb, playbook/app/pb_kits/playbook/pb_form_pill/form_pill.rb, playbook/spec/pb_kits/playbook/kits/form_pill_spec.rb
[PLAY-1454](https://runway.powerhrg.com/backlog_items/PLAY-1454) is part 2 of 5 in the Form Pill/Typeahead [handoff](https://www.figma.com/file/79KJo0Jl8HSNOBQPJo5MSp/Typeahead-Dropdowns?type=design&node-id=240%3A7600&mode=design&t=f7VGtBFjzitLydyF-1). Before altering the form pill size, we needed to allow for the use of icons within the form pill because so much of the pill anatomy, sizing, and future plans for usage depended on this ability. Note: icons are the default text color for now because PLAY-1138 is not merged yet; once that is in the icon color prop should be used. 
The doc examples will look a little funky until the sizing has been corrected - I do wonder if these should be enabled but not …
=> [PLAY-1454] Form pills 2 of 5: add icon prop

playbook/app/pb_kits/playbook/pb_nav/_horizontal_nav.scss
https://runway.powerhrg.com/backlog_items/PLAY-1467
This PR fixes an issue with the default variant for horizontal navigation. When the screen is shrunk to a certain size, the nav items will become mis-aligned due line/text wrapping.
1. Go to '...'
=> [PLAY-1467] Horizontal default nav - fix alignment

playbook-website/package.json, yarn.lock
Bump "axe-core" dependency from 4.9.1 to 4.10.0
1. Go to '...'
=> [PLAY-1475] Bumping "axe-core" dependency from 4.9.1 to 4.10.0

playbook/app/pb_kits/playbook/pb_rich_text_editor/_previewer_mixin.scss, playbook/app/pb_kits/playbook/pb_rich_text_editor/_tiptap_mixin.scss, playbook/app/pb_kits/playbook/pb_rich_text_editor/_tiptap_styles.scss, playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_advanced_preview.jsx, playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/example.yml, playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/index.js
[PBNTR-286](https://runway.powerhrg.com/backlog_items/PBNTR-286) creates a preview doc example for the Advanced editor in React (one already exists for the default editor). It uses a mixin file to incorporate the expected styles into the output on the preview card. The new default content text in the editor serves as instructions for how to use the previewer.
Editor:
Preview Card:
1. Go to the new advanced preview doc example in the milano review environment [here](https://pr3578.playbook.beta.px.powerapp.cloud/kits/rich_text_editor/react#advanced-preview).
2. Alter the text in the …
=> [PBNTR-286] RTE Advanced Previewer + output styles (React)

playbook/app/pb_kits/playbook/pb_badge/_badge.scss, playbook/app/pb_kits/playbook/pb_badge/_badge.tsx, playbook/app/pb_kits/playbook/pb_badge/badge.rb, playbook/app/pb_kits/playbook/pb_badge/badge.test.js, playbook/app/pb_kits/playbook/pb_badge/docs/_badge_notification.html.erb, playbook/app/pb_kits/playbook/pb_badge/docs/_badge_notification.jsx, playbook/spec/pb_kits/playbook/kits/badge_spec.rb
- ✅ Add a notification error variant that's opaque and red
- ✅ Use $error in non-dark mode. Use $error_dark in dark mode. 
- ✅ Update docs and testing
1. Go to kits/badge/react#notification
2. Make sure the error notification badge is the same as a notification badge, but with a different color
3. Turn on dark mode. The badge color should be red, but better suited for dark mode. 
4. Make sure that the normal "colors" are not affected. 
5. Repeat the above, but with Rails
=> [PLAY-1411] Badge Notification Error Variant

playbook/app/pb_kits/playbook/pb_dialog/dialog.html.erb, playbook/app/pb_kits/playbook/pb_dialog/dialog.rb, playbook/app/pb_kits/playbook/pb_dialog/dialogHelper.js, playbook/app/pb_kits/playbook/pb_dialog/dialog_footer.html.erb, playbook/app/pb_kits/playbook/pb_dialog/dialog_footer.rb, playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_loading.html.erb, playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_loading.md, playbook/app/pb_kits/playbook/pb_dialog/docs/example.yml
Runway https://runway.powerhrg.com/backlog_items/PLAY-1490
Adds a prop to the dialog kit that makes the buttons go into a "loading state" when pressed
[screencast-127.0.0.1_3000-2024.08.15-14_05_54.webm](https://github.com/user-attachments/assets/6c9ec27b-d8a8-43cb-8443-fcb0865b2e94)
1. Go to[ /kits/dialog](https://pr3599.playbook.beta.hq.powerapp.cloud/kits/dialog/rails#loading)
2. Click Open Dialog
3. click Okay
4. Notice the loading state of the buttons and admire how nice they communicate that something is loading and that you can't press the buttons again
=> [PLAY-1490] Dialog Kit Loading state buttons

playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.scss, playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.tsx, playbook/app/pb_kits/playbook/pb_form_pill/docs/example.yml, playbook/app/pb_kits/playbook/pb_form_pill/form_pill.html.erb, playbook/app/pb_kits/playbook/pb_form_pill/form_pill.rb, playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx
[PBNTR-416](https://runway.powerhrg.com/backlog_items/PBNTR-416) changes the default and small form pill size to match the pill anatomy and UI specs sections of the [handoff](https://www.figma.com/design/79KJo0Jl8HSNOBQPJo5MSp/Typeahead-Dropdowns?node-id=450-11205&t=0eZQh3tyWdrkedLL-0). The default size of the form pill in the MultiLevelSelect has been changed from `size="small"` to default, which matches the current production appearance (compare the two CSBs below to see this in action). This PR also contains a small follow up to story 2 of 5 re: icon color now that PLAY-1138 is merged - Icons will inherit color from the color given to the Form Pill - and exposes the icon doc example.
[CSB initial …
=> [PBNTR-416] Form pill 3 of 5: Sizes

playbook/app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.tsx, playbook/app/pb_kits/playbook/pb_circle_icon_button/circle_icon_button.html.erb, playbook/app/pb_kits/playbook/pb_circle_icon_button/circle_icon_button.rb, playbook/app/pb_kits/playbook/pb_circle_icon_button/circle_icon_button.test.js, playbook/app/pb_kits/playbook/pb_circle_icon_button/docs/_circle_icon_button_loading.html.erb, playbook/app/pb_kits/playbook/pb_circle_icon_button/docs/_circle_icon_button_loading.jsx, playbook/app/pb_kits/playbook/pb_circle_icon_button/docs/example.yml, playbook/app/pb_kits/playbook/pb_circle_icon_button/docs/index.js, playbook/spec/pb_kits/playbook/kits/circle_icon_button_spec.rb
- ✅ Expose loading prop in Circle Icon kit for underlying Button kit
- ✅ Add examples and tests
1. Go to the Circle Icon Button kit page on Playbook
2. Review the "loading" example
3. There should be a pulse animation
4. Review both Rails and React
=> [PLAY-1420] Add "loading" variant to Circle Icon Button

playbook/app/pb_kits/playbook/pb_timestamp/docs/_timestamp_elapsed.html.erb, playbook/app/pb_kits/playbook/pb_timestamp/timestamp.rb, playbook/spec/pb_kits/playbook/kits/timestamp_spec.rb
https://runway.powerhrg.com/backlog_items/PLAY-1477
Creating private method in the PbTimestamp module to replace the "time_ago_in_words" ruby method to resolve issue in Nitro where the latter method conflicts with our Nitro behavior.
1. Go to '...'
=> [PLAY-1477] Timestamp Kit Rails: Elapsed Time Variant Issue

playbook/app/pb_kits/playbook/pb_pagination/_pagination.scss
[PBNTR-471](https://runway.powerhrg.com/backlog_items/PBNTR-471) addresses the visual stutter observed when going from page to page on the recently developed React Pagination kit. The solution was to alter a line of scss causing an `ease-out` transition too all elements, so that it just affects background-color, color, and border-color. This code was present from back when the kit was Rails only, but the border shaking (aka, "all" elements responding) was never visually apparent since the rails version of the kit has a full page refresh upon each page change (this PR adds additional transition code to preserve current Rails appearance since it is no longer using the catch all `all` in the transition). …
=> [PBNTR-471] React pagination glitchiness

playbook/app/pb_kits/playbook/pb_dialog/dialog.html.erb, playbook/app/pb_kits/playbook/pb_dialog/dialog.rb, playbook/app/pb_kits/playbook/pb_dialog/dialogHelper.js, playbook/app/pb_kits/playbook/pb_dialog/dialog_footer.html.erb, playbook/app/pb_kits/playbook/pb_dialog/dialog_footer.rb, playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_loading.html.erb, playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_loading.md, playbook/app/pb_kits/playbook/pb_dialog/docs/example.yml
Runway https://runway.powerhrg.com/backlog_items/PLAY-1490
The OG PR https://github.com/powerhome/playbook/pull/3599
This was reverted because of multiple data declorations
```<%= pb_rails("button", props: { type: "button", data: {"close-dialog": "#{object.id}" }, id: object.cancel_button_id, variant: "link", data: cancel_loading}) do %>```
**But this is how it works**
Adds a prop to the dialog kit that makes the buttons go into a "loading state" when pressed
[screencast-127.0.0.1_3000-2024.08.15-14_05_54.webm](https://github.com/user-attachments/assets/6c9ec27b-d8a8-43cb-8443-fcb0865b2e94)
1. Go to …
=> [PLAY-1490] Dialog disable rails - Remove duplicate data

playbook/app/pb_kits/playbook/pb_icon/icon.rb
- ✅ Handle custom icon SVGs HTTP errors gracefully- substitute an empty string
- ✅ Fix Nitro test suites from crashing with errors like "Failed to open TCP connection to upload.wikimedia.org:443"
Show blank icons with HTTP errors:
Nav bar custom icons use image tags, so they show broken images:
1. Go to /kits/icon#icon-custom
2. The wrench icon (from wikipedia) should show as normal
3. Go to /kits/selectable_card_icon#custom-icon
4. The wrench icon should show as normal
5. Go to /kits/nav/rails#with-custom-icon
6. The news feed icon should show as normal
I tested HTTP errors on my end (I made 404 icon links), and it shows as empty strings as expected. 
If you want to test to make sure, I can …
=> [PLAY-1519] Return empty string for SVG with HTTP errors (404s, timeouts)

playbook-website/app/javascript/entrypoints/application.js
Runway https://runway.powerhrg.com/backlog_items/PLAY-1458
This issue was discovered when trying to remove font awesome from playbook website 
https://github.com/powerhome/playbook/pull/3547
The icons like grid-2 were not being converted correctly. You can find grid 2 on the main nav on the left for the "Components" nav item
check it out here
https://pr3649.playbook.beta.hq.powerapp.cloud/
=> [PLAY-1458] Fix kebab logic

playbook/CHANGELOG.md
=> Update CHANGELOG.md 14.3.0

playbook-website/lib/markdown_helper.rb, playbook-website/spec/helpers/markdown_helper_spec.rb
https://runway.powerhrg.com/backlog_items/PLAY-1428
1. Go to '...'
=> [PLAY-1428] Fix Undefined Method Error in SamplesController#show

playbook/app/pb_kits/playbook/pb_multiple_users_stacked/_multiple_users_stacked.scss, playbook/app/pb_kits/playbook/pb_multiple_users_stacked/_multiple_users_stacked.test.js, playbook/app/pb_kits/playbook/pb_multiple_users_stacked/_multiple_users_stacked.tsx, playbook/app/pb_kits/playbook/pb_multiple_users_stacked/docs/_multiple_users_stacked_bubble.html.erb, playbook/app/pb_kits/playbook/pb_multiple_users_stacked/docs/_multiple_users_stacked_bubble.jsx, playbook/app/pb_kits/playbook/pb_multiple_users_stacked/docs/example.yml, playbook/app/pb_kits/playbook/pb_multiple_users_stacked/docs/index.js, playbook/app/pb_kits/playbook/pb_multiple_users_stacked/multiple_users_stacked.html.erb, playbook/app/pb_kits/playbook/pb_multiple_users_stacked/multiple_users_stacked.rb, playbook/spec/pb_kits/playbook/kits/multiple_users_stacked_spec.rb
- Add a "Bubble" Multiple Users Stacked variant which can fit four avatars
- Position and size avatars based on the amount of avatars
- Use position and size mixins
- Update spec and jest tests
1. Go to /kits/multiple_users_stacked/react
2. Compare the [handoff](https://huddle.powerapp.cloud/projects/626/handoffs/1337/handoff_items/5655) to the bubble variant
3. Turn on dark mode and compare. Note- the background of the container circle matches the background of the card, so it blends in.
4. Go to https://playbook.powerapp.cloud/kits/multiple_users_stacked/react and make sure the …
=> [PLAY-1412] Bubble Variant to Multiple Users Stacked

playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_page_change.jsx, playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_page_change_react.md
[PBNTR-532](https://runway.powerhrg.com/backlog_items/PBNTR-532) updates the react pagination kit doc example and copy to show a dev how to implement dynamic keys to keep multiple pagination components on a page in sync. 
1. Go to the react pagination kit page [Page Change doc example](https://pr3715.playbook.beta.px.powerapp.cloud/kits/pagination/react#page-change) and see the updated copy.
2. Click on any number or the forward/backward carets in either the top or bottom pagination bar: the table data should update and both pagination bars should update to the new activePage number. …
=> [PBNTR-532] Add multiple pagination components example and dynamic key copy

playbook-website/app/javascript/components/HomepageHero/HeroComponents/TicketsChart.tsx
With the upgrade to Highcharts, using a height of "25%" doesn't work as expected before. 
Set to "150px" to correct. 
1. Go to the home page for Playbook in the test env. Compare to a version of PB's website which works. (e.g., this [older test env](https://pr3739.playbook.beta.gm.powerapp.cloud/))
2. Make sure the "Total Tickets Sold" gauge looks OK.
3. Check on mobile, tablet, and desktop.
4. Note: on mobile, this hero component doesn't show.
=> [PLAY-1599] Set Total Tickets Hero Gauge Height to 150px instead of 25%

playbook-website/bin/deployer, playbook-website/config/deploy/production/secrets.yaml, playbook-website/config/deploy/prs/secrets.yaml, playbook-website/config/deploy/staging/secrets.yaml
Updates the deployer image, and re-encrypts the secrets files to grant the `forever-people` ARN access to the secrets. This unlocks FVR's ability to place MySQL user secrets for https://github.com/powerhome/playbook/pull/3778
=> Re-encrypt secrets for FVR access

playbook-website/config/deploy/production/secrets.yaml, playbook-website/config/deploy/staging/secrets.yaml, playbook-website/config/deploy/templates/deployment.yaml.erb, playbook-website/config/deploy/templates/shell.yaml.erb
Deployments to non-pr environments are broken.
- https://milano.powerapp.cloud/powerhome/playbook/staging/deploys/9880200#
```
key not found: "open_ai"
```
First, https://github.com/powerhome/playbook/pull/3776 only added
values for the `open_ai` value to the `prs` environment - IE review
stacks. The project still needs valaues for staging and production.
Second, even if these values were present, the env var name the
application is looking for and the env var name used by the deployment
are different.
https://github.com/powerhome/playbook/blob/ddf4db1da92383ac58e8c6f17669a0d38629c7c2/playbook-website/config/initializers/openai.rb#L3
=> Fix staging and production deployments

playbook/app/pb_kits/playbook/pb_advanced_table/index.js, playbook/app/pb_kits/playbook/pb_advanced_table/table_header.html.erb, playbook/app/pb_kits/playbook/pb_advanced_table/table_subrow_header.html.erb
[PBNTR-442](https://runway.powerhrg.com/backlog_items/PBNTR-442) address the current incorrect behavior for the "toggle all" icon in the Rails Advanced Table kit. For both headers (see [default doc ex](https://playbook.powerapp.cloud/kits/advanced_table/rails?sort=year_asc#default-required-props)) and subheaders (see [subheader doc ex](https://playbook.powerapp.cloud/kits/advanced_table/rails#subrow-headers)) the toggle all button will just switch the rows that are closed to open and vice versa. 
The desired behavior is to open all rows and close them in sync - if only some are open, the first click should open all of them, and from then on close all/open all in sync (see [React doc …
=> [PBNTR-442] Advanced Table kit "toggle all" is inverted in Rails

playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_reset.html.erb, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_reset.md, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/example.yml
[Runway Story](https://runway.powerhrg.com/backlog_items/PBNTR-606)
This PR:
- ✅ Adds reset functionality to rails side of kit so it can be used within nitro_search_playbook_filter in Nitro
- ✅ Unblocks [this work](https://runway.powerhrg.com/backlog_items/FIRST-1537) for First Contact
- ✅ Creates reset doc example on rails side to showcase how to use exposed function
=> [PBNTR-606] Add Reset Functionality to Rails side of MultiLevelSelect

playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.tsx, playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_clear_selection.jsx, playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_clear_selection.md, playbook/app/pb_kits/playbook/pb_dropdown/docs/example.yml, playbook/app/pb_kits/playbook/pb_dropdown/docs/index.js, playbook/app/pb_kits/playbook/pb_dropdown/subcomponents/DropdownOption.tsx, playbook/app/pb_kits/playbook/pb_dropdown/subcomponents/DropdownTrigger.tsx
Adding React Dropdown cleaning feature
1. Go to the Dropdown kit page
2. Scroll down to the Clear Selection doc
=> [PBNTR-568] Adding React Dropdown cleaning feature

playbook/package.json, yarn.lock
Upgrade react-zoom-pan-pinch from 2.6.1 to 3.6.0
Fix "pinch" bug on mobile and tablet by avoiding [3.6.1 version](https://github.com/BetterTyped/react-zoom-pan-pinch/releases/tag/v3.6.1) which has a bug with "double click" and "two fingers" on zoom.
See discussion in [GitHub issues](https://github.com/BetterTyped/react-zoom-pan-pinch/issues/487). 
Someone made a [PR](https://github.com/BetterTyped/react-zoom-pan-pinch/pull/499) which hasn't been merged yet, so this might be fixed in later versions.
Go through the Lightbox kit for any regressions
=> [PLAY-1601] Bump react-zoom-pan-pinch from 2.6.1 to 3.6.0

playbook/app/pb_kits/playbook/pb_card/_card.tsx, playbook/app/pb_kits/playbook/pb_dialog/_dialog.tsx, playbook/app/pb_kits/playbook/pb_flex/_flex.tsx, playbook/app/pb_kits/playbook/pb_flex/_flex_item.tsx, playbook/app/pb_kits/playbook/pb_flex/flex_item.html.erb, playbook/app/pb_kits/playbook/pb_flex/flex_item.rb, playbook/app/pb_kits/playbook/pb_popover/_popover.tsx, playbook/app/pb_kits/playbook/utilities/globalPropNames.mjs, playbook/app/pb_kits/playbook/utilities/globalProps.ts, playbook/lib/playbook/kit_base.rb
Reverts powerhome/playbook#3749
=> Revert "[PLAY-1581] Height, minHeight, maxHeight for Card, Flex, FlexItem, & Dialog"

playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.scss, playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.tsx, playbook/app/pb_kits/playbook/pb_dropdown/dropdown.rb, playbook/app/pb_kits/playbook/pb_dropdown/dropdown.test.jsx
Fixes dropdown Classname
1. Go to '...'
=> Dropdown ClassName Fix

playbook/CHANGELOG.md
=> Update CHANGELOG.md 14.6.2

playbook-website/app/views/guides/getting_started/dependencies.md, playbook-website/app/views/guides/getting_started/react_setup.md
Runway https://runway.powerhrg.com/backlog_items/PLAY-1610
Added docs to explain the required dependancies to run playbook ui https://pr3885.playbook.beta.px.powerapp.cloud/guides/getting_started/dependencies
=> [PLAY-1610] Add details to dependencies docs 

playbook-website/app/views/guides/getting_started/font_awesome.md
- Use `<details>` and `<summary>` to make collapsibles for different methods to install Font Awesome
- Convert the existing Asset Pipeline docs to html to be used with `<details>` and `<summary>`
- Add a new "With a JavaScript Bundler" section
1. Go to /guides/getting_started/font_awesome
2. There should be two "collapsibles": Default with an Asset Pipeline and With a JavaScript Bundler
3. When you click it, the sections should expand and contract with details
4. Review the new "With a JavaScript Bundler" section
=> [PLAY-1619] Font Awesome Setup Docs: JS Bundle and Asset Pipeline - Phase 2

playbook-website/package.json, yarn.lock
[PLAY-1551](https://runway.powerhrg.com/teams/432/backlog/sprints/active#open-backlog-item-71524)
Bumping dependency to latest version
2.1.12 -> 2.6.6
=> [PLAY-1551] Bump @tiptap/extension-document from 2.1.12 to 2.6.6

playbook/app/pb_kits/playbook/pb_advanced_table/Components/CustomCell.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.test.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_custom_cell.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
[Runway Story](https://runway.powerhrg.com/backlog_items/PBNTR-666)
- This story adds the ability to have custom cells for the first column of the advanced table.
- This functionality was added for the rest of the columns on [this PR](https://github.com/powerhome/playbook/pull/3821)
- To test, scroll down to the last doc example on the React side
[csb here](https://codesandbox.io/p/sandbox/advanced-table-custom-cell-gjzxtw)
=> [PBNTR-666] Custom Cells for Advanced Table First Column 

playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb, playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_loading.html.erb, playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb, playbook/app/pb_kits/playbook/pb_typeahead/index.ts, playbook/app/pb_kits/playbook/pb_typeahead/typeahead.html.erb, playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb, playbook/lib/playbook/forms/builder/typeahead_field.rb
[PBNTR-667](https://runway.powerhrg.com/backlog_items/PBNTR-667) addresses missing functionality from the playbook typeahead used within forms via the `form.typeahead` or `f.typeahead` construction. Specifically, this ticket is in response to an SLA request for accessible label, validation, and reset functionality. 
The results of my investigation were the following: 
- Label click-to-focus functionality was not present in the kit as currently structured. The added label functionality utilizes the recommended Rails form helper `@template.label(@object_name, name)`. It depends on a label's for property matching the text input's id.
- Validation was not present in the kit as currently structured. …
=> [PBNTR-667] Rails Typeahead Form Integration

playbook/app/pb_kits/playbook/pb_date_picker/date_picker_helper.ts, playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_quick_pick_default_date.html.erb, playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_quick_pick_default_date.jsx, playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_quick_pick_default_date.md, playbook/app/pb_kits/playbook/pb_date_picker/docs/example.yml, playbook/app/pb_kits/playbook/pb_date_picker/docs/index.js, playbook/app/pb_kits/playbook/pb_date_picker/plugins/quickPick.tsx
Adding defaultDate prop to Date Picker Quick Pick variant
=> [PBNTR-637] Adding defaultDate prop to Date Picker Quick Pick variant

playbook-website/app/javascript/components/VisualGuidelines/Examples/Hover.tsx, playbook-website/app/views/pages/code_snippets/hover_jsx.txt, playbook/app/pb_kits/playbook/utilities/_hover.scss, playbook/app/pb_kits/playbook/utilities/globalProps.ts, playbook/app/pb_kits/playbook/utilities/test/globalProps/hover.test.js, playbook/lib/playbook/hover.rb, playbook/spec/playbook/global_props/hover_spec.rb
runway https://runway.powerhrg.com/backlog_items/PLAY-1603
Add a "Text Color" hover prop option is the ask in this story 
because color is already a hover option i just used that. The Background and color hover props weren't working because a lot of our kits are listening for classnames that are "_error", "_success" or "_#{any_color_token}"
so i changed the classname to not trigger the pre existing css by making the syntax "hover_color-#{any_color_token}". Doing this to the background kit fixes it too
Checkout the page here https://pr3874.playbook.beta.gm.powerapp.cloud/visual_guidelines/hover
=> [PLAY-1603] Add color hover docs and fix background hover

playbook-website/app/javascript/components/VisualGuidelines/Examples/GroupHover.tsx, playbook-website/app/javascript/components/VisualGuidelines/Examples/Hover.tsx, playbook-website/app/views/pages/code_snippets/group_hover_jsx.txt, playbook-website/app/views/pages/code_snippets/hover_jsx.txt, playbook/app/pb_kits/playbook/pb_card/_card_mixin.scss, playbook/app/pb_kits/playbook/utilities/_hover.scss, playbook/app/pb_kits/playbook/utilities/globalProps.ts
- Create a `visibility` hover prop (like background, shadow, and scale) that hides the component unless it or the group component is hovered over
- Use opacity of 0 for hidden state and animate to 1 when hovered over
- Add to Hover doc
- Refactor Group Hover doc to use background and visibility
1. Review /visual_guidelines/hover
2. Review /visual_guidelines/group_hover
3. Make sure the Card kit's background works as normal
=> [PLAY-1604] Global Hover Visibility Prop

playbook/app/pb_kits/playbook/pb_drawer/_drawer.scss, playbook/app/pb_kits/playbook/pb_drawer/_drawer.tsx, playbook/app/pb_kits/playbook/pb_drawer/drawer.test.jsx
Runway https://runway.powerhrg.com/backlog_items/PLAY-1647
Background: The drawer kit is currently in draft mode. Its similar to the dialog kit, and i used a lot of the same code to make the drawer kit.  
This story removes `react-modal` from the drawer kit. It didn't do as much as i thought it did and we can get away with just using a `div`
1. Go to https://pr3891.playbook.beta.px.powerapp.cloud/kits/drawer/react
2. click all the examples
=> [PLAY-1647] Remove react modal from drawer 

playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb, playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_loading.html.erb, playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb, playbook/app/pb_kits/playbook/pb_typeahead/index.ts, playbook/app/pb_kits/playbook/pb_typeahead/typeahead.html.erb, playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb, playbook/lib/playbook/forms/builder/typeahead_field.rb
Reverts powerhome/playbook#3893
=> Revert "[PBNTR-667] Rails Typeahead Form Integration"

playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.scss, playbook/app/pb_kits/playbook/pb_dropdown/dropdown_container.html.erb, playbook/app/pb_kits/playbook/pb_dropdown/dropdown_container.rb
[Runway Story](https://runway.powerhrg.com/backlog_items/PBHUB-373)
The rails side of the kit did not have the container set to position absolute like the react side
=> [PBNTR-712] Dropdown Rails to have Position Absolute on Container

playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb, playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_loading.html.erb, playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb, playbook/app/pb_kits/playbook/pb_typeahead/index.ts, playbook/app/pb_kits/playbook/pb_typeahead/typeahead.html.erb, playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb, playbook/lib/playbook/forms/builder/typeahead_field.rb
Reverts powerhome/playbook#3916
This PR for [PBNTR-701](https://runway.powerhrg.com/backlog_items/PBNTR-701) contains everything from [PBNTR-667](https://runway.powerhrg.com/backlog_items/PBNTR-667) except for some changes to the Typeahead's PbEnhancedElement `index.ts` file that had caused some form submission issues in nitro. 
Please reference the previous [playbook PR](https://github.com/powerhome/playbook/pull/3893) for thorough description + screenshots, etc. Here is a direct link to the [form kit page](https://pr3917.playbook.beta.gm.powerapp.cloud/kits/form) in the review environment. Here is the new [nitro-web alpha PR](https://github.com/powerhome/nitro-web/pull/44241) used in testing.
=> [PBNTR-701] Revert "Revert "[PBNTR-667] Rails Typeahead Form Integration""

playbook/CHANGELOG.md
=> Update CHANGELOG.md 14.8.0

playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_beta.html.erb, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_beta_sort.html.erb, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_custom_cell_rails.html.erb, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_custom_cell_rails.md, playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml, playbook/app/pb_kits/playbook/pb_advanced_table/table_row.html.erb, playbook/app/pb_kits/playbook/pb_advanced_table/table_row.rb
Allowing kits to be displayed within the advanced table
1. Go to '...'
=> [PBNTR-628] Implementing Rails Advanced Table Custom Cell with kits

playbook/app/pb_kits/playbook/pb_dropdown/utilities/subComponentHelper.tsx
[Runway story](https://runway.powerhrg.com/backlog_items/PBNTR-713)
Issue was related to the Dropdown now being wrapped in a ForwardRef. This ForwardRef is read as the Dropdown being wrapped in proxies or a HOC which means the type does not match the DropdwnTrigger or DropdownContainer. So the separateChildComponents function was returning Trigger and Container as 'null' and pushing all children to otherChildren.
=> [PBNTR-713] Fixes for Custom Trigger not Working

playbook-website/app/javascript/components/MainSidebar/MenuData/GuidelinesNavItems.ts, playbook-website/app/javascript/components/VisualGuidelines/Examples/MaxWidth.tsx, playbook-website/app/javascript/components/VisualGuidelines/Examples/Width.tsx, playbook-website/app/javascript/components/VisualGuidelines/index.tsx, playbook-website/app/javascript/site_styles/_visual_guidelines.scss, playbook-website/app/views/pages/code_snippets/max_width_jsx.txt, playbook-website/app/views/pages/code_snippets/width_jsx.txt, playbook/app/entrypoints/playbook.scss, playbook/app/pb_kits/playbook/pb_progress_simple/_progress_simple.tsx, playbook/app/pb_kits/playbook/pb_progress_simple/progress_simple.html.erb, playbook/app/pb_kits/playbook/pb_progress_simple/progress_simple.rb, playbook/app/pb_kits/playbook/utilities/_max_width.scss, playbook/app/pb_kits/playbook/utilities/_min_width.scss, playbook/app/pb_kits/playbook/utilities/_width.scss, playbook/app/pb_kits/playbook/utilities/globalPropNames.mjs, playbook/app/pb_kits/playbook/utilities/globalProps.ts, playbook/lib/playbook/classnames.rb, playbook/lib/playbook/spacing.rb, playbook/spec/pb_kits/playbook/kits/progress_simple_spec.rb
[PLAY-1680](https://runway.powerhrg.com/backlog_items/PLAY-1680)
Adding new Width Prop to our global props list. Some minor updates to Max and Min Width props.
=> [PLAY-1680] Width Global Prop

playbook/app/pb_kits/playbook/pb_card/_card_mixin.scss, playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss, playbook/app/pb_kits/playbook/pb_selectable_card/selectable_card.html.erb
Updates to dark mode styling based on audit for the Select-able Card component.
[PLAY-1668](https://runway.powerhrg.com/backlog_items/PLAY-1668)
1. Go to 'kits/selectable_card/rails'
2. Scroll down to 'Selected, with icon' -- Border and check circle colors should be changed. 
3. Scroll down to 'Block and With Options' -- All variants should now support dark mode
=> [PLAY-1668] Dark Mode Audit - Selectable Card

playbook/app/pb_kits/playbook/pb_nav/_bold_mixin.scss, playbook/app/pb_kits/playbook/pb_nav/_collapsible_nav.scss, playbook/app/pb_kits/playbook/pb_nav/_vertical_nav.scss
Updates to dark mode styling based on audit for the Nav component. 
[PLAY-1667](https://runway.powerhrg.com/backlog_items/PLAY-1667)
1. Go to kits/nav
2. Turn on Dark Mode
3. Look at Default Variant, bold horizontal and vertical variants, and collapsible variant 
4. Check both react and rails versions for changes mentioned in the story card
=> [PLAY-1667] Dark Mode Audit - Nav

playbook/app/pb_kits/playbook/pb_caption/_caption_mixin.scss, playbook/app/pb_kits/playbook/pb_title/_title.scss, playbook/app/pb_kits/playbook/pb_title/_title_mixin.scss, playbook/app/pb_kits/playbook/tokens/_titles.scss
Updates to dark mode styling based on audit for the Caption and Title components.
[PLAY-1673](https://runway.powerhrg.com/backlog_items/PLAY-1673)
1. Go to 'kits/title'
2. Scroll down to 'Colors' -- Title colors should now be dark mode compatible
3. Go to 'kits/caption
4. Scroll down to 'Colors' -- Caption colors should now be dark mode compatible
=> [PLAY-1673] Dark Mode Audit - Caption and Title

playbook/app/pb_kits/playbook/pb_body/_body.scss, playbook/app/pb_kits/playbook/pb_body/_body_mixins.scss, playbook/app/pb_kits/playbook/pb_stat_change/_stat_change.tsx, playbook/app/pb_kits/playbook/pb_stat_change/stat_change.html.erb
Updates the Rails and React Stat Change Kit to have correct dark mode styling. 
[Play 1666](https://runway.powerhrg.com/backlog_items/PLAY-1666)
1. Go to '/kits/stat_change/rails'
2. Click on 'dark mode toggle
3. Scroll down to 'default, icon, and colors examples
4. dark mode style coloring should be visible for default increasing and decreasing value for body along with dark mode for icon
5. repeat for React kit '/kits/stat_change/react'
=> [PLAY-1666] Dark Mode Audit Stat Change

playbook/app/pb_kits/playbook/pb_bread_crumbs/_bread_crumb_item.tsx, playbook/app/pb_kits/playbook/pb_bread_crumbs/docs/_bread_crumbs_default.jsx
This updates the dark mode styling color for React Kit's inner Title Component. 
[Story 1635](https://runway.powerhrg.com/backlog_items/PLAY-1635)
Before:
After:
1. Go to '/kits/bread_crumbs/react'
2. Click on 'night mode'
3. Scroll down to 'stroll down to to see in Nav colored white'
4. See in inspector tool see span element child have class with dark appended
=> [PLAY-1635] Bread Crumbs Dark Mode Fix

playbook/app/pb_kits/playbook/pb_advanced_table/table_header.html.erb
Fix a bug with the collapsible button and sort button where both functionalities happen when either button is clicked.
[PLAY-1740](https://runway.powerhrg.com/backlog_items/PLAY-1740)
There are no visual changes
1. Go to advanced table kit rails doc page - kits/advanced_table/rails
2. Scroll down to Enable Sorting example on the page
3. Clicking the sort button will refresh and sort the table. 
4. Clicking the collapsible button will expand the table and close the table if pressed again. 
5. Both of the buttons above should act independently of each other now. 
6. Check each collapsible …
=> [PLAY-1740] Fix Sort Function on Rails Advanced Table

playbook-website/app/javascript/components/VisualGuidelines/Examples/Hover.tsx, playbook-website/app/views/pages/code_snippets/hover_jsx.txt, playbook/app/pb_kits/playbook/utilities/_hover.scss, playbook/app/pb_kits/playbook/utilities/globalProps.ts, playbook/app/pb_kits/playbook/utilities/test/globalProps/hover.test.js, playbook/lib/playbook/hover.rb, playbook/spec/playbook/global_props/hover_spec.rb
Runway https://runway.powerhrg.com/backlog_items/PLAY-1605
Adds underline to the global hover prop which is a boolean which adds `text-decoration: underline` on hover
1. Go to https://pr3975.playbook.beta.gm.powerapp.cloud/visual_guidelines/hover
2. Read all the great stuff about the underline option for our global hover prop
=> [PLAY-1605] Add underline hover prop

playbook-website/app/javascript/components/MainSidebar/MenuData/SidebarNavItems.ts
Stops "Warning: Encountered two children with the same key, 'top-nav-item-6'" from appearing in the console when loading playbook. 
[PLAY-1701](https://runway.powerhrg.com/backlog_items/PLAY-1701)
1. Go to [playbook website](https://playbook.powerapp.cloud/), basically any page, with the console open.
2. Check for "Warning: Encountered two children with the same key, 'top-nav-item-6'"
=> [PLAY-1701] Change Playground Key

playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_custom.jsx, playbook/app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_custom_rails.html.erb, playbook/app/pb_kits/playbook/pb_bar_graph/docs/example.yml
Runway https://runway.powerhrg.com/backlog_items/PLAY-1617
Make visual updates to the bar graph doc example for custom overrides
1. Go to https://pr3982.playbook.beta.gm.powerapp.cloud/kits/bar_graph/react#custom-overrides
2. Look at how great the chart is 
3. Rails too https://pr3982.playbook.beta.gm.powerapp.cloud/kits/bar_graph/rails#custom-overrides
=> [PLAY-1617] Change Bar Graph Override Example

playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss, playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_highlight.jsx, playbook/app/pb_kits/playbook/pb_typeahead/typeahead.html.erb
Updates Darkmode styling for the Typeahead component
[PLAY-1670](https://runway.powerhrg.com/backlog_items/PLAY-1670)
1. Go to '/kits/typeahead'
2. Observe improved darkmode styling
=> [PLAY-1670] Dark Mode Audit - Typeahead

playbook/app/pb_kits/playbook/pb_home_address_street/_home_address_street.tsx, playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_emphasis.html.erb, playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_emphasis.jsx, playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_emphasis.md, playbook/app/pb_kits/playbook/pb_home_address_street/home_address_street.rb, playbook/app/pb_kits/playbook/pb_home_address_street/none_emphasis.html.erb, playbook/app/pb_kits/playbook/pb_home_address_street/none_emphasis.rb
Added a "none" option to emphasis prop in Home Address Kit so there can be an emphasized version of the kit. 
[PLAY-1500](https://runway.powerhrg.com/backlog_items/PLAY-1500)
1. kits/home_address_street/
2. Scroll down to emphasis example
3. See new none emphasis example with documentation underneath 
4. Check both react and rails.
=> [PLAY-1500] Home Address Street: "none" Emphasis Prop

playbook-website/app/controllers/pages_controller.rb, playbook-website/app/javascript/components/MainSidebar/NavComponents/OtherNavComponent.tsx, playbook-website/app/views/guides/getting_started/icons.md, playbook-website/app/views/guides/getting_started/icons/font_awesome.md, playbook-website/app/views/layouts/icons.html.erb, playbook-website/app/views/pages/icons.html.erb, playbook-website/app/views/pages/icons_custom.html.erb, playbook-website/app/views/pages/icons_font_awesome.html.erb, playbook-website/app/views/pages/icons_playbook.html.erb, playbook-website/config/initializers/global_variables.rb, playbook-website/config/routes.rb
- Create Icon Integration Doc
- Add a Nav Bar (modeled after the changelog nav bar)
- Move Font Awesome under /icons/font_awesome
- Create blank pages for Playbook Icons and Custom
https://runway.powerhrg.com/backlog_items/PLAY-1623
1. Go to /guides/getting_started/icons/
2. Click Font Awesome
3. Click Playbook Icons and Custom
=> [PLAY-1623] Icon Integration Docs: Nav Bar and About Page

playbook-website/app/javascript/components/VisualGuidelines/index.tsx, playbook-website/config/routes.rb
This fixes the redirection of none sense urls to the parent page if there is one otherwise, it sends the user home. 
[PLAY-1539](https://runway.powerhrg.com/backlog_items/PLAY-1539)
1. Go to links listed on Story card
2. Should see appropriate redirects
=> [PLAY-1539] Playbook Website Redirects - Go to Parent not Home

.github/workflows/github-actions-release-candidate.yml
Skip RC process with 'Inactive RC' label.
After this is merged, RCs should work as normal. 
This PR has the 'Inactive RC' label, so an RC should not be generated.
=> [PLAY-1708] Skip RC process with 'Inactive RC' label

playbook/app/pb_kits/playbook/pb_gauge/_gauge.scss, playbook/app/pb_kits/playbook/pb_gauge/_gauge.tsx, playbook/app/pb_kits/playbook/pb_gauge/docs/_gauge_complex.jsx
Updates Darkmode styling for the Gauge component
1. Go to 'kits/gauge/react/#complex'
2. Observe improved darkmode styling
=> [PLAY-1678] Dark Mode Audit - Gauge

playbook/app/pb_kits/playbook/pb_card/_card.tsx, playbook/app/pb_kits/playbook/pb_card/_card_mixin.scss, playbook/app/pb_kits/playbook/pb_card/docs/_card_header.html.erb, playbook/app/pb_kits/playbook/pb_card/docs/_card_header.jsx, playbook/app/pb_kits/playbook/pb_card/docs/_card_header.md
Makes it so the header in the card kit can accept status colors for the background color. 
[PLAY-1629](https://runway.powerhrg.com/backlog_items/PLAY-1629)
1. Go to card kit page
2. Scroll down to card header section
3. See new status color example
=> [PLAY-1629] Add Status Color to Card Header

playbook/app/pb_kits/playbook/pb_form_group/_error_state_mixin.scss, playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss
Fixes the alignments of the form group items when there are validation errors being displayed on the kit and when a label is used in some of the form group kits. 
[PLAY-1703](https://runway.powerhrg.com/backlog_items/PLAY-1703)
1. Go to 'kits/form_group 
2. Scroll down to the phone number kit
3. Click into the kit and then click out, should see validation error message in red around the kit
4. The form group should still be aligned with and without the error. 
5. Should work for both React and Rails
=> [PLAY-1703 ] Form Group Error State Alignment

playbook/spec/pb_kits/playbook/kits/timestamp_spec.rb
[Runway Story](https://runway.powerhrg.com/backlog_items/PBNTR-782)
Any commit pushed up today is getting this failing spec:
- No issue in kit, issue only in spec test
- The issue was the hard coded value for future_year being 2024 + changes made on [this PR](https://github.com/powerhome/playbook/pull/2977/files#diff-600f6c819a48f07dd029c8b79fc0798daddecaae4e7570da12a5d2a2e43d8348L82) that was removing check for year
- Made future date calculation dynamic to avoid this issue in the future
- Fixes test to expect the correct value
=> [PBNTR-782] Fixes for Timestamp Spec Failing on Year Change

playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.scss
Removes the default padding for all children in the section separator, except for the caption kit. 
Before Change:
After Change:
=> [PLAY-1700] Bug - Remove Default Padding in Section Separator When Children are Passed

playbook/app/pb_kits/playbook/pb_icon_circle/_icon_circle.scss
This PR address sizing of the icon on the xxs variant for the icon circle kit. Adjusted icon to match desired 10px size set by design standards.
[Story 1614](https://runway.powerhrg.com/backlog_items/PLAY-1614)
Before:
After:
1. kits/icon_circle/react
2. Scroll down to size varients
3. Observe that xxs icon is not 10px
4. See both React and Rails Kit
=> [PLAY-1614] Icon Circle Size Bug Fix

playbook/app/pb_kits/playbook/pb_file_upload/_file_upload.tsx, playbook/app/pb_kits/playbook/pb_file_upload/docs/_file_upload_accept.jsx, playbook/app/pb_kits/playbook/pb_file_upload/docs/_file_upload_custom_description.jsx, playbook/app/pb_kits/playbook/pb_file_upload/docs/_file_upload_max_size.jsx, playbook/package.json, yarn.lock
- Upgrade react-dropzone from 10.2.2 to 14.3.5 for React File Upload kit
- Switch `accept` prop from array of strings to object pointing to array of strings. [13.0.0 release notes.](https://github.com/react-dropzone/react-dropzone/releases/tag/v13.0.0)
- Use fileRejections instead of rejectedFiles which includes reason it was rejected. [11.0.0 release notes.](https://github.com/react-dropzone/react-dropzone/releases/tag/v11.0.0)
- Fix TypeScript errors
1. Go to /kits/file_upload/react
2. Test every single doc example
3. Test clicking the box, as well as dragging a file
=> [PLAY-1660] Upgrade react-dropzone to 14.3.5 and File Upload Kit

playbook/app/pb_kits/playbook/pb_avatar_action_button/_avatar_action_button.scss, playbook/app/pb_kits/playbook/pb_badge/_badge.scss, playbook/app/pb_kits/playbook/pb_bread_crumbs/_bread_crumbs.scss, playbook/app/pb_kits/playbook/pb_button/_button.scss, playbook/app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.scss, playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_input_styles.scss, playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_overrides.scss, playbook/app/pb_kits/playbook/pb_date_range_inline/_date_range_inline.scss, playbook/app/pb_kits/playbook/pb_date_time_stacked/_date_time_stacked.scss, playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.scss, playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.scss, playbook/app/pb_kits/playbook/pb_icon_circle/_icon_circle.scss, playbook/app/pb_kits/playbook/pb_label_value/_label_value.scss, playbook/app/pb_kits/playbook/pb_message/_message_mixins.scss, playbook/app/pb_kits/playbook/pb_multiple_users/_multiple_users.scss, playbook/app/pb_kits/playbook/pb_passphrase/_passphrase.scss, playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.scss, playbook/app/pb_kits/playbook/pb_pill/_pill.scss, playbook/app/pb_kits/playbook/pb_progress_simple/_progress_simple.scss, playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss, playbook/app/pb_kits/playbook/pb_select/_select.scss, playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss, playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss, playbook/app/pb_kits/playbook/pb_textarea/_textarea.scss, playbook/app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.scss, playbook/app/pb_kits/playbook/pb_timeline/_timeline.scss, playbook/app/pb_kits/playbook/pb_toggle/_toggle.scss
Updated kits in playbook to address deprecation warning when starting a playbook website server. Used sass math model and updated all divisional operations to use new division syntax. Following in all kits that have been updated: 
- Avatar Action Button
- Badge Kit
- Bread crumbs kit
- Button
- Circle Icon Button
- Date Picker
- Date Range
- Date Time Stacked
- Dropdown
- Form Pill
- Icon Circle
- Pill
- Label value
- Message
- Multiple User
- Prassphrase
- Phone Number Input
- Progress simple
- Rich Text Editor
- Select
- Selectable Card
- Text Input
- Textarea
- Time Range Inline
- Timeline
- Toggle
[Story 1776](https://runway.powerhrg.com/backlog_items/PLAY-1776)
**Screenshots:** Screenshots to …
=> [PLAY-1776] Update Kits To Remove Deprecation Warning With Division

.github/workflows/github-actions-release-candidate.yml
- Fix "Inactive RC" label bug that would show a failed run. Make it so there is a successful run, but an RC is still not made. 
- The RC GitHub action showed an error on the [next "Grab Current Version and Set New RC Version" step](https://github.com/powerhome/playbook/actions/runs/12547084762/job/34983953428) because `exit 0` on the "Get Semver Label" step indicates there is no bug and should still run subsequent steps. But, since the label was never set, this following step fails. 
- Set SKIP_REMAINING_STEPS to true and add a conditional to exit 0 or return for all later steps.
1. Merge this PR
2. The GitHub action should not create an RC
3. It should also run successfully
=> [PLAY-1801] 'Inactive RC' Label: Skip Later Steps

playbook/app/pb_kits/playbook/pb_table/styles/_scroll.scss
Testing a fix for for the templates for [PBNTR-778](https://runway.powerhrg.com/backlog_items/PBNTR-778)
This PR:
- Removes display block from responsive scroll class as it was breaking the table when it did not have enough columns to take up full width
- Makes fixes so that box-shadow on table-responsive-scroll does not appear if the container=false prop is used
=> Scss fixes for Responsive Scroll for Table

playbook/Gemfile.lock, playbook/playbook_ui.gemspec
Adds brakeman as a development dependency. This allows the scanner to work correctly, and developers to scan locally. It does not affect production code. 
This does not contain any functional changes. If you want to run brakeman locally, make sure you're inside of playbook/playbook and have bundled. Then run `brakeman scan .`
=> Add brakeman as a development dependency in playbook

playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_selectable_list_rails.html.erb, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_selectable_list_rails.md, playbook/app/pb_kits/playbook/pb_draggable/docs/example.yml, playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list.html.erb, playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list.rb, playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list_item.html.erb, playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list_item.rb
[PBNTR-718](https://runway.powerhrg.com/backlog_items/PBNTR-718)
As a Playbook dev,
I want a create a simplified version of the Draggable kit for the SelectableList kit,
So that we can ensure parity between our Rails and React Draggable kits.
1. Go to '...'
=> [PBNTR-718] Draggable Kit: Simplified API for SelectableList for Rails

playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_list_rails.html.erb, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_list_rails.md, playbook/app/pb_kits/playbook/pb_list/item.html.erb, playbook/app/pb_kits/playbook/pb_list/item.rb, playbook/app/pb_kits/playbook/pb_list/list.html.erb, playbook/app/pb_kits/playbook/pb_list/list.rb
As a Playbook dev,
I want a create a simplified version of the Draggable kit for the List kit,
So that we can ensure parity between our Rails and React Draggable kits.
1. Go to '...'
=> [PBNTR-719] Draggable Kit: Simplified API for List kit for Rails

playbook/app/pb_kits/playbook/pb_table/_table.tsx, playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_columns.html.erb, playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_columns_rails.md, playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_left_columns_rails.md, playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_right_columns.html.erb, playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_right_columns_rails.md, playbook/app/pb_kits/playbook/pb_table/docs/example.yml, playbook/app/pb_kits/playbook/pb_table/index.ts, playbook/app/pb_kits/playbook/pb_table/table.html.erb, playbook/app/pb_kits/playbook/pb_table/table.rb, playbook/app/pb_kits/playbook/pb_table/utilities/addDataTitle.ts, playbook/spec/pb_kits/playbook/kits/table_spec.rb
Adding sticky right column and refactoring PBTable enhanced element.
**What was done:**
1. Using the class selector (".table-responsive-collapse"), we weren't running the PBTable Enhanced Element for all the tables. What made this work for the other tables was the "document.querySelectorAll".
2. Using "document.querySelectorAll" caused unexpected behaviors (as mentioned above) and performance issues. For each table, we would run the same logic for ALL the tables on the page. This is an On2 code. If we had 10 tables on the page, we would have run it 100 times.
3. I removed the use of ref functions and binds since using arrow functions, we don't need it.
4. The React version was executing PBTable Enhanced Element causing all the issues mentioned above. This code …
=> [PBNTR-768] Adding sticky right column and refactoring PBTable enhanced element

playbook/app/pb_kits/playbook/pb_timeline/_timeline.scss
- Remove 0 height which breaks padding and margin for Timeline labels
- Use flex align-items: center to center step children and connectors
- Remove margin that was centering step children/connectors before
- Correct step children CSS (add ^ "starts with" so you can add global props like "pb_timeline_item_step my_xxs")
1. Go to https://runway.powerhrg.com/backlog_items/PLAY-1774
2. View the code sandbox and make sure
3. Padding works as expected on labels
4. The step "children" (online status and icons) are centered with the "connectors"
=> [PLAY-1774] Fix Timeline Label and Step Spacing

playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.tsx, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_format.html.erb, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_format.jsx, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_format.md, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/example.yml, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/index.js, playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.rb, playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.test.js, playbook/spec/pb_kits/playbook/kits/phone_number_input_spec.rb
- Add `formatAsYouType`/`format_as_you_type` prop to Phone Number Input kit
- Keep most of Phone Number Input logic the same if this prop is false
- Replace `telInputInit` state, `itiInit`, with a ref, `itiRef`, so it's available across renders
- In React, remove formatting (dashes, spaces, parentheses) in the `number` prop in the onChange event
- Make docs and tests
1. Go to /kits/phone_number_input/react#format-as-you-type
2. Type numbers and note that it formats
3. Check other doc examples
4. Review Rails versions
=> [PLAY-1720] Phone Number Input formatAsYouType Prop

playbook/app/pb_kits/playbook/pb_button/button.html.erb, playbook/app/pb_kits/playbook/pb_checkbox/checkbox.html.erb, playbook/app/pb_kits/playbook/pb_date_picker/date_picker.html.erb, playbook/app/pb_kits/playbook/pb_dropdown/dropdown.html.erb, playbook/app/pb_kits/playbook/pb_dropdown/dropdown_container.html.erb, playbook/app/pb_kits/playbook/pb_dropdown/dropdown_option.html.erb, playbook/app/pb_kits/playbook/pb_dropdown/dropdown_trigger.html.erb, playbook/spec/pb_kits/playbook/kits/dropdown_spec.rb
Updated Button, Checkbox, DatePicker, and Dropdown kits to no longer use "content_tag" and use our new "pb_content_tag". Also added test for Dropdown kit.
[Story 1750](https://runway.powerhrg.com/backlog_items/PLAY-1750)
there should be no functional changes to any of these kits. Add Alpha testing locations to story notes
=> [PLAY-1750] Convert Kits to Use Pb_content_tag

playbook/app/pb_kits/playbook/pb_loading_inline/_loading_inline.tsx
Dark mode enabled in React Loading Inline kit page, all text and labels are now using $text_dk_light.
[Story PLAY-1798](https://runway.powerhrg.com/backlog_items/PLAY-1798)
1. Go to '...'
=> [PLAY-1798] Enable Dark Mode in Loading Inline Text and Labels

playbook/app/pb_kits/playbook/pb_radio/_radio.scss, playbook/app/pb_kits/playbook/pb_radio/docs/_radio_custom_children.jsx
[Story 1797](https://runway.powerhrg.com/backlog_items/PLAY-1797)
**Rails-**
With Error doc example - error label now using `$error_Dark`
All selected/checked radio borders now using `$active_dark` instead of `$primary`
**React-**
Custom Children - Typography example now easily visible with a dark background
1. Go to '...'
=> [PLAY-1797 ] DARK MODE AUDIT - Radio

playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_sort_control.md, playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_subtle_variant.md
This PR fixes typos for the Dropdown & Advanced Table docs.
[Story](https://runway.powerhrg.com/backlog_items/PLAY-1832)
1. Go to '...'
=> [PLAY-1832] Fix Doc Typos

playbook-website/app/javascript/site_styles/docs/_markdown.scss, playbook-website/app/views/guides/getting_started/react_setup.md
Removes margin from markdown code blocks to match documentation.
[Story 1715](https://runway.powerhrg.com/backlog_items/PLAY-1715)
1. Go to '...'
=> [PLAY]-1715 Fix Website Markdown Code Indention

playbook/app/pb_kits/playbook/pb_selectable_icon/_selectable_icon.tsx, playbook/app/pb_kits/playbook/pb_selectable_icon/docs/_selectable_icon_default.jsx, playbook/app/pb_kits/playbook/pb_selectable_icon/docs/_selectable_icon_single_select.jsx
This PR enables proper use of dark mode to the selectable icon kit in React.
Before(left) and After(right)
1. Go to the selectable icon kit : /kits/selectable_icon/react
2. Toggle Dark Mode
3. Switch to React
4. See change on each selectable icon kit
=> [PLAY-1787] Selectable Icon - Dark Mode Audit

playbook/app/pb_kits/playbook/pb_advanced_table/Components/CustomCell.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/SubKits/TableBody.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/SubKits/TableHeader.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss, playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_no_subrows.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_pagination.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_pagination_with_props.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows.md, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_actions.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_actions.md, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_header.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_header.md, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_no_subrows.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_selectable_rows_no_subrows.md, playbook/app/pb_kits/playbook/pb_advanced_table/docs/advanced_table_mock_data_no_subrows.json, playbook/app/pb_kits/playbook/pb_advanced_table/docs/advanced_table_mock_data_with_id.json, playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml, playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
[Runway Story](https://runway.powerhrg.com/backlog_items/PBNTR-749)
This PR:
- Creates `selectableRows` props for adding checkboxes
- Creates `onRowSelectionChange` prop for giving devs access to selected items
- Creates `showActionsBar` prop to optionally show actions header
- Creates `actions` prop to pass in custom actions
- Creates selection pattern for expanded and non-expanded tables
=> [PBNTR-749] SelectableRows for AdvancedTable- React

playbook-website/app/javascript/site_styles/map_styles/_map_default.scss
[PLAY-1724](https://runway.powerhrg.com/backlog_items/PLAY-1724)
This PR is a part of the Dark Mode Audit on 'Map'.
We've updated the pop up content, it should display a dark background and white text.
Light mode was also impacted to create this change, the functionality remains the same.
1.  Go to playbook.powerapp.cloud/kits/map/react
2.  Enable 'dark mode'
3.  Check each map
4.  Click on the location icon on the map --> all pop up content should have a dark background and white text
5.  Enable 'light mode', make sure the pop up content behaves the same way as production
=> [PLAY-1724] Dark Mode - Map Audit

playbook/app/pb_kits/playbook/pb_radio/docs/_radio_custom_children.jsx, playbook/app/pb_kits/playbook/pb_select/_select.scss, playbook/app/pb_kits/playbook/pb_select/_select.tsx, playbook/app/pb_kits/playbook/pb_select/select.html.erb
This PR audits the Select component for proper use of dark mode colors.
1. Change all lables to use $text_dk_light
2. Select Inline us updated to have a more visible hover color
3. Error state is using $error_dark for border-color
[Story](https://runway.powerhrg.com/backlog_items/PLAY-1789)
1. Go to [https://pr4128.playbook.beta.gm.powerapp.cloud/kits/select/rails](https://pr4128.playbook.beta.gm.powerapp.cloud/kits/select/rails)
4. Turn on "Dark Mode" and go to the Select Kit
5. Scroll down to 'Select Default'
6. Compare caption text color to prod
7. Scroll down to 'Select w/Error'
8. …
=> [PLAY-1789] Dark Mode Select

playbook/app/entrypoints/playbook-rails.js, playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_mask.html.erb, playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_mask_rails.md, playbook/app/pb_kits/playbook/pb_text_input/docs/example.yml, playbook/app/pb_kits/playbook/pb_text_input/index.js, playbook/app/pb_kits/playbook/pb_text_input/text_input.html.erb, playbook/app/pb_kits/playbook/pb_text_input/text_input.rb, playbook/spec/pb_kits/playbook/kits/text_input_spec.rb
Runway https://runway.powerhrg.com/backlog_items/PLAY-1772
Original Branch had unverified commits https://github.com/powerhome/playbook/pull/4114/commits
Adds input masking to the text input so that there are dashes and commas and all other sorts of patterns in the ui for 
currency 
social security number
zip code
postal code
I put all the javascript for the masking logic in `index.js` in the kit's folder
1. Go to https://pr4127.playbook.beta.px.powerapp.cloud/kits/text_input/rails#mask
2. Type into the text inputs
=> [PLAY-1772] Rails input masking

playbook-website/config/menu.yml, playbook/app/entrypoints/playbook.scss, playbook/app/pb_kits/playbook/pb_icon_button/_icon_button.scss, playbook/app/pb_kits/playbook/pb_icon_button/docs/_icon_button_default.html.erb, playbook/app/pb_kits/playbook/pb_icon_button/docs/example.yml, playbook/app/pb_kits/playbook/pb_icon_button/icon_button.html.erb, playbook/app/pb_kits/playbook/pb_icon_button/icon_button.rb, playbook/spec/pb_kits/playbook/kits/icon_button_spec.rb
Runway https://runway.powerhrg.com/backlog_items/PLAY-1766
Adds a new rails only kit for a square style icon button
Its very similar to the circle icon button
Its still in beta, just made a "default" and "link" variant
Check it out here https://pr4141.playbook.beta.px.powerapp.cloud/kits/icon_button
=> [PLAY-1766] Icon button rails

playbook/app/pb_kits/playbook/pb_multiple_users/_multiple_users.scss, playbook/app/pb_kits/playbook/pb_multiple_users/_multiple_users.tsx, playbook/app/pb_kits/playbook/pb_multiple_users/multiple_users.html.erb
This PR adds dark mode to the number badge that goes along with Multiple Users kit. We change the color of the badges halo from light to dark for both react & rails.
1. Go to the [deployed env](https://pr4139.playbook.beta.gm.powerapp.cloud/)
2. Search for 'Multiple Users
3. For both Rails/React switch to dark mode
4. See the badge '+2' change from a light border to dark.
=> [PLAY-1796] Dark Audit Multiple Users

playbook/app/pb_kits/playbook/pb_card/card.html.erb, playbook/app/pb_kits/playbook/pb_card/card.rb, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_cards_rails.html.erb, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_with_cards_rails.md
As a Playbook dev,
I want a create a simplified version of the Draggable kit for the Card kit,
So that we can ensure parity between our Rails and React Draggable kits. 
1. Go to [Rails Draggable kit](https://pr4161.playbook.beta.px.powerapp.cloud/kits/draggable/rails)
2. Scroll down to the 'Draggable with Cards' example
=> [PBNTR-720] Draggable Kit: Simplified API for Card kit for Rails

playbook/app/pb_kits/playbook/pb_advanced_table/Components/CustomCell.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx
alignment for first column on KPI page is off
=> [PBNTR-843] Alignment Issue for AdvancedTable with Specific Usecases

playbook-website/app/javascript/components/KitSearch.tsx, playbook-website/package.json
This PR adds the match-sorter library to filter the kits that are displayed on the playbook-website as you type.
[Story](https://runway.powerhrg.com/backlog_items/PLAY-372)
1. Go to '...'
=> [PLAY-372] Search Results

playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss, playbook/app/pb_kits/playbook/pb_advanced_table/index.js, playbook/app/pb_kits/playbook/pb_advanced_table/table_row.html.erb
Allows the expanded rows on the Rails Advanced Table to be highlighted, so that the user can visibly tell which rows are expanded and which are not.
[[PLAY]-1741](https://runway.powerhrg.com/backlog_items/PLAY-1741)
1. Go to '...'
=> [PLAY]-1741 Advanced Table Highlight In Rails

playbook/app/pb_kits/playbook/pb_date/_date.tsx, playbook/app/pb_kits/playbook/pb_date/docs/_date_default.jsx, playbook/app/pb_kits/playbook/pb_date/docs/_date_unstyled.jsx
Updates the Unstyled and Default React Doc so that dark mode prop transposes `Title` and `Caption` components.
[Story PLAY-1799](https://runway.powerhrg.com/backlog_items/PLAY-1799)
1. Go to '...'
=> [PLAY-1799] Date Dark Mode Audit

playbook/app/pb_kits/playbook/pb_button/button.rb, playbook/spec/pb_kits/playbook/kits/button_spec.rb
Ruwnay https://runway.powerhrg.com/backlog_items/PLAY-1862
When using the link variant for our button kit, it is not properly applying the disabled prop.
When disabled it is forced to use the button tag
Maddie had the issue and reported it in the playbook room
=> Fix disabled state for link

playbook/app/pb_kits/playbook/pb_file_upload/file_upload.html.erb, playbook/app/pb_kits/playbook/pb_filter/filter.html.erb, playbook/app/pb_kits/playbook/pb_form_group/form_group.html.erb, playbook/app/pb_kits/playbook/pb_form_pill/form_pill.html.erb
Update File Upload, Filter, Form Group, and Form Pill kits to no longer use "content_tag" and use our new "pb_content_tag". 
1. Test Rails File Upload, Filter, Form Group, and Form Pill kits on Playbook website.
2. Test uses on Nitro.
=> [PLAY-1751] Convert Kits to Use pb_content_tag (File Upload, Filter, Form Group, and Form Pill)

playbook/app/pb_kits/playbook/pb_user/_user.tsx, playbook/app/pb_kits/playbook/pb_user/docs/_user_light_weight.html.erb, playbook/app/pb_kits/playbook/pb_user/docs/_user_light_weight.jsx, playbook/app/pb_kits/playbook/pb_user/docs/_user_light_weight.md, playbook/app/pb_kits/playbook/pb_user/docs/example.yml, playbook/app/pb_kits/playbook/pb_user/docs/index.js, playbook/app/pb_kits/playbook/pb_user/user.html.erb, playbook/app/pb_kits/playbook/pb_user/user.rb, playbook/app/pb_kits/playbook/pb_user/user.test.js
Allows user to set user names in `User` kit to lightweight.
[Story 1501](https://runway.powerhrg.com/backlog_items/PLAY-1501)
**Rails:**
**React:**
1. Go to '...'
=> [PLAY-1501] Enable Lightweight User Names in User Kit

playbook-website/package.json, playbook/package.json, yarn.lock
Runway https://runway.powerhrg.com/backlog_items/PLAY-1828
Alpha PR https://github.com/powerhome/nitro-web/pull/45689
Update Vite to 5.3.5 
It was only a couple patch version, but we want to use the same version thats in Nitro
=> [PLAY-1828] Update Vite version

playbook/app/pb_kits/playbook/pb_lightbox/lightbox.scss
- Fix Daily Attendance History Lightbox image's missing close "x" button when viewed on Safari mobile because the Nitro nav bar overlaps visually.
- Bump z-index values for Lightbox.
- In Nitro: remove the wrapping div with a z-index which [changes the stacking context](https://www.joshwcomeau.com/css/stacking-contexts/)
1. Test /kits/lightbox/react
2. Ninja test Nitro lightboxes.
=> [PLAY-1602] Lightbox kit - Nitro Bug

playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_multiple_containers_rails.html.erb, playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_multiple_containers_rails.md, playbook/app/pb_kits/playbook/pb_draggable/docs/example.yml, playbook/app/pb_kits/playbook/pb_draggable/draggable_container.html.erb, playbook/app/pb_kits/playbook/pb_draggable/draggable_container.rb, playbook/app/pb_kits/playbook/pb_draggable/draggable_item.rb, playbook/app/pb_kits/playbook/pb_draggable/index.js
As a Playbook dev, 
I want to implement the "cross container" functionality to our Rails Draggable kit,
so that I can ensure parity between my Rails and React Draggable kits.
1. Go to '[Dragging Across Multiple Containers](https://pr4210.playbook.beta.hq.powerapp.cloud/kits/draggable/rails#dragging-across-multiple-containers)' doc example
=> PBNTR-779 | Draggable kit: Add the "cross-container" functionality to RAILS kit

playbook/app/pb_kits/playbook/pb_home_address_street/_home_address_street.tsx, playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_formatting.html.erb, playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_formatting.jsx, playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_formatting.md, playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_formatting_rails.md, playbook/app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_formatting_react.md, playbook/app/pb_kits/playbook/pb_home_address_street/docs/example.yml, playbook/app/pb_kits/playbook/pb_home_address_street/docs/index.js, playbook/app/pb_kits/playbook/pb_home_address_street/home_address_street.rb
This PR includes all the code from [Story](https://runway.powerhrg.com/backlog_items/PLAY-1821) [PR](https://github.com/powerhome/playbook/pull/4176) plus adds a nil check for custom_titleize so the app does not crash when we don't pass a home address prop
1. Go to '...'
=> [PLAY-1887] Home Address with fix

playbook-website/app/javascript/components/KitSearch.tsx, playbook-website/app/javascript/components/MainSidebar/MenuData/GuidelinesNavItems.ts, playbook-website/app/javascript/components/MainSidebar/NavComponents/OtherNavComponent.tsx
[PLAY-1478](https://runway.powerhrg.com/backlog_items/PLAY-1478)
Everything listed on our "Tokens and Guidelines" page now appears in the Playbook website search bar and brings a user to the respective Playbook page.
Each item in the "Tokens and Guidelines" search has an identifying "Global Props" badge.
1. Go to playbook.powerapp.cloud
2. Search for items listed in the Tokens and Guidelines section
3. Select a Token/Guideline
4. See results in search bar, associated badge -- when clicked, you should be taken to the corresponding tokens page
=> [PLAY-1478] PB Website - Search Global Props

playbook/app/pb_kits/playbook/pb_icon/icon.html.erb, playbook/app/pb_kits/playbook/pb_layout/body.html.erb, playbook/app/pb_kits/playbook/pb_layout/footer.html.erb, playbook/app/pb_kits/playbook/pb_layout/header.html.erb, playbook/app/pb_kits/playbook/pb_layout/item.html.erb, playbook/app/pb_kits/playbook/pb_layout/layout.html.erb, playbook/app/pb_kits/playbook/pb_layout/sidebar.html.erb, playbook/app/pb_kits/playbook/pb_legend/legend.html.erb, playbook/app/pb_kits/playbook/pb_message/message.html.erb, playbook/app/pb_kits/playbook/pb_message/message_mention.html.erb
Update Icon, Layout, Legend, Message kits to no longer use `content_tag` and use our new `pb_content_tag`
There should be no visible changes to the kits.
=> [PLAY-1752] Implement pb_content_tag

playbook/app/pb_kits/playbook/pb_icon_button/docs/_icon_button_default.html.erb, playbook/app/pb_kits/playbook/pb_icon_button/docs/_icon_button_sizes.html.erb, playbook/app/pb_kits/playbook/pb_icon_button/docs/example.yml, playbook/app/pb_kits/playbook/pb_icon_button/icon_button.html.erb, playbook/app/pb_kits/playbook/pb_icon_button/icon_button.rb, playbook/spec/pb_kits/playbook/kits/icon_button_spec.rb
This PR adds the `size` prop to the `icon_button_kit` in Rails and allows the developer to specify the size of an Icon Button.
[Story](https://runway.powerhrg.com/backlog_items/PLAY-1858)
1. Go to '...'
=> [PLAY-1858] Icon Button Sizes

playbook/app/pb_kits/playbook/pb_date_picker/_date_picker.tsx
- Add prop, `initializeOnce`, which uses an empty dependency array in useEffect to React Date Picker kit so flatpickr init runs only on first render. If the prop is false, use undefined so date picker remains unchanged.
- If a form had other inputs and date picker(s), any update to the parent form's state would trigger a reinitialization to the date picker(s). Now date pickers should initialize only once.
1. In Nitro, go to a page with a React form that has the date picker and other inputs in Safari
2. Type and make sure the React Date Picker does not "restart" on every event / slows down other inputs.
=> [PLAY-1888] React Date Picker - initializeOnce - Reinitialization with Other Inputs Bug

playbook/app/pb_kits/playbook/pb_progress_pills/_progress_pills.scss, playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_default.html.erb, playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_default.jsx, playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_default.md
[Story](https://runway.powerhrg.com/backlog_items/PLAY-1884)
This PR makes our Progress Pill kit more responsive by setting the width of the pill to 100% of the container and the `max-width: 45px` which is our current fixed width. This will allow the pills to expand and shrink inside their container. 
1. Go to '...'
=> [PLAY-1884] Responsive Progress Pill

playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_headers_custom_cell.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml, playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
[Support ticket](https://runway.powerhrg.com/backlog_items/PBNTR-883)
When you tried to use the customRenderer to do custom cells while also using the multi-column functionality, the custom cells did not work as expected for the first column in each column group. The issue was that the first column in each column group was being treated like the forst column in the table and getting those styles. This fixes for that.
=> [PBNTR-883] Advanced Table: Multi Column Headers to work with Custom Cells

playbook-website/package.json, playbook/package.json, yarn.lock
Bump axe-core from 4.4.3 to 4.10.2
=> [PLAY-1880] Bump axe-core to 4.10.2

playbook/app/entrypoints/playbook-rails.js, playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb, playbook/app/pb_kits/playbook/pb_overlay/overlay.rb, playbook/app/pb_kits/playbook/pb_select/index.js, playbook/app/pb_kits/playbook/pb_select/select.rb
Adding Select Validity Message
1. Go to '...'
=> [PBNTR-888] Adding Select Validity Message

playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.scss, playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled.html.erb, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled.jsx, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/example.yml, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/index.js, playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.rb
Implementing Multi Level Select disabled
1. Go to '...'
=> [PBNTR-898] Implementing Multi Level Select disabled

playbook/app/pb_kits/playbook/pb_select/select.html.erb, playbook/app/pb_kits/playbook/pb_selectable_card/selectable_card.html.erb, playbook/app/pb_kits/playbook/pb_selectable_card_icon/selectable_card_icon.html.erb, playbook/app/pb_kits/playbook/pb_selectable_icon/selectable_icon.html.erb, playbook/lib/playbook/kit_base.rb
This PR updates the Select, Selectable Card, Selectable Card Icon and Selectable Icon to use the new pb_content_tag.
1. Go to '...'
=> [PLAY-1755] Update pb_content_tag

playbook/app/pb_kits/playbook/pb_popover/_popover.tsx, playbook/app/pb_kits/playbook/pb_popover/popover.test.js
[PBNTR-907](https://runway.powerhrg.com/backlog_items/PBNTR-907) addresses a bug observed first in the React Filter kit with Popover Props used in the React Basic Data Table Template, and then confirmed in the React Filter kit's [Popover Props doc example](https://playbook.powerapp.cloud/kits/filter/react#popover-props). Adding a width property to the filter popover is removing the internal padding. 
The Rails side was unaffected (in doc example and template pages). This PR sets out to address this issue (which was not present when this prop was created, see screenshots in PR for [PBNTR-595](https://github.com/powerhome/playbook/pull/3827)). This PR will also be alpha testing to confirm this fix adjusts …
=> [PBNTR-907] Filter kit: popoverProps width removing internal padding of filter elements

playbook/app/pb_kits/playbook/pb_text_input/inputMask.ts
Allowing zero values on Currency Text Input
1. Go to '...'
=> [PBNTR-894] Allowing zero values on Currency Text Input

playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_react_hook.jsx, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_react_hook.md, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/example.yml, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/index.js
[Story](https://runway.powerhrg.com/backlog_items/PLAY-1854)
In this PR we add `react-hook-form` support to our Multi Level Select kit. Now devs can `...register("name")` any Multi Level Select kit without using `<Controller/>`
1. Go to '...'
=> [PLAY-1854] MultiLevelSelect Kit: React Hook Forms Support 

playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx, playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.rb
[PBNTR-902](https://runway.powerhrg.com/backlog_items/PBNTR-902) requests that we expose the hidden inputs for the default MultiLevelSelect kit option, where returnAllSelected is false and variant is multi. A playbook support inquiry revealed that while we can see the hidden inputs with data populated for returnAllSelected true and the variant = single doc examples, the default case did not have them available for devs. 
Hidden inputs are typically used for rails kits in forms. Because this is a react-rendered-rails kits, the changes made affect both the Rails and React versions of the kit and their doc examples (this bug was technically present in the React side as well). 
This PR also camel cases the …
=> [PBNTR-902] Multi Level Select it - Return All Selected Bug

playbook-website/config/menu.yml, playbook/app/pb_kits/playbook/pb_icon_button/_icon_button.tsx, playbook/app/pb_kits/playbook/pb_icon_button/icon_button.html.erb
[Story](https://runway.powerhrg.com/backlog_items/PLAY-1939)
In this PR we change the Icon Button's border radius from `lg` to `xs` as the default.
We also take the kit out of beta.
1. Go to '...'
=> [PLAY-1939] Icon Button Kit: Border Radius

playbook-website/app/javascript/components/PbKitPlayground/PlaygroundHeader.tsx, playbook-website/app/javascript/components/PbKitPlayground/index.tsx, playbook-website/app/javascript/site_styles/docs/_code_snippet.scss
- Expand clickable area to the full editor space
- Contain code with a scrollbar if the code is longer than 100vh
- Wrap a flex container so entire page is 100vh
- Add padding on left, top, and right in editor
1. Go to /kit_playground_rails.
2. Click on the code editor area (below the first line). 
3. You should be editing even though you didn't click the first line.
4. Type enough code so a scroll bar shows.
5. A scroll bar should appear instead of overflowing.
=> [PLAY-1877] Playground Fixes: Click Anywhere and Scroll

playbook-website/app/javascript/components/VisualGuidelines/Examples/Display.tsx, playbook-website/app/views/pages/code_snippets/display_in_use_jsx.txt, playbook/app/pb_kits/playbook/tokens/_display.scss, playbook/app/pb_kits/playbook/types/display.ts, playbook/app/pb_kits/playbook/utilities/_display.scss, playbook/app/pb_kits/playbook/utilities/test/globalProps/display.test.js, playbook/lib/playbook/display.rb, playbook/spec/playbook/global_props/display_spec.rb
[PBNTR-617](https://runway.powerhrg.com/backlog_items/PBNTR-617) requests the addition of the grid value to Playbook's [Display global prop](https://developer.mozilla.org/en-US/docs/Web/CSS/display). This PR adds it to the code and to the Display visual guidelines example page. 
The property was tested locally in doc examples for Rails and React (screenshots below) and [this CSB with alpha](https://codesandbox.io/p/devbox/pbntr-csb-forked-7g54tx) demonstrates it in a user-testable and inspectable environment.
Display Visual Guidelines page:
Rails doc ex - flex, button, card (responsive)
React doc ex - flex, button, card (responsive)
**How to …
=> [PBNTR-617] Add grid to Display global prop code and example page

playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.scss, playbook/app/pb_kits/playbook/pb_tooltip/docs/_tooltip_sizing.html.erb, playbook/app/pb_kits/playbook/pb_tooltip/docs/example.yml, playbook/app/pb_kits/playbook/pb_tooltip/tooltip.html.erb, playbook/app/pb_kits/playbook/pb_tooltip/tooltip.rb
[PLAY-1907](https://runway.powerhrg.com/backlog_items/PLAY-1907)
https://github.com/user-attachments/assets/e5189372-0c9b-4213-802d-8e76300369eb
1. Go to /kits/tooltip/rails
2. Scroll down to 'Tooltip Sizing'
3. See addition/change
=> [PLAY-1907] Tooltip Kit - Pass Global Props Height and Width to Tooltip - Rails

playbook/app/pb_kits/playbook/pb_textarea/textarea.html.erb, playbook/app/pb_kits/playbook/pb_time/time.html.erb, playbook/app/pb_kits/playbook/pb_title/title.html.erb, playbook/app/pb_kits/playbook/pb_toggle/toggle.html.erb
This PR updates the `content_tag` to use our new `pb_content_tag` inside the Text Area, Time, Title & Toggle kits.
1. Go to '...'
=> [PLAY-1757] Update pb_content_tag

playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list.html.erb, playbook/app/pb_kits/playbook/pb_star_rating/star_rating.html.erb, playbook/app/pb_kits/playbook/pb_table/table.html.erb, playbook/app/pb_kits/playbook/pb_table/table_body.html.erb, playbook/app/pb_kits/playbook/pb_table/table_cell.html.erb, playbook/app/pb_kits/playbook/pb_table/table_head.html.erb, playbook/app/pb_kits/playbook/pb_table/table_header.html.erb, playbook/app/pb_kits/playbook/pb_table/table_row.html.erb, playbook/app/pb_kits/playbook/pb_text_input/text_input.html.erb
This PR DRYs up code by replacing pb_content_tag for Selectable List, Star Rating, Text Input, and Table.
1. Test in Playbook
2. Test cases in Nitro
=> [PLAY-1756] Update pb_content_tag for Selectable List, Star Rating, Text Input, and Table

playbook/app/pb_kits/playbook/pb_multi_level_select/_helper_functions.tsx, playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options.html.erb, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options.jsx, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options.md, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options_default.html.erb, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options_default.jsx, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options_default.md, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options_parent.html.erb, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options_parent.jsx, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options_parent.md, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options_parent_default.html.erb, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options_parent_default.jsx, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_disabled_options_parent_default.md, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/example.yml, playbook/app/pb_kits/playbook/pb_multi_level_select/docs/index.js, playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select_options.tsx
[Runway Story](https://runway.powerhrg.com/backlog_items/PBNTR-899)
Covered in this PR (React and Rails):
- ✅ New logic that allows a user to disable individual options while keeping their parent or top-level option enabled
- ✅ When item disabled, it is not checked when checking cascades from parent
- ✅ Returned array should NOT include disabled option
- ✅ New Logic to disable parent options that will automatically disable all children options for default but not for returnAllSelected
=> [PBNTR-899] MultiLevelSelect Kit: Ability to Disable Options

playbook/app/pb_kits/playbook/pb_icon/_icon.scss, playbook/app/pb_kits/playbook/pb_icon/docs/_icon_color.html.erb, playbook/app/pb_kits/playbook/pb_icon/docs/_icon_color.jsx
Adding the ability to pass the same text color values as the body kit including light and lighter. 
This seemed like the most straightforward and least disruptive way to do it. If more color options are required, there may be a better way. Let me know what you think.
[PLAY-1714](https://runway.powerhrg.com/backlog_items/PLAY-1714)
[Review ENV](https://pr4402.playbook.beta.gm.powerapp.cloud/kits/icon/rails)
=> [PLAY-1714] Add Values to Icon Kit Color Prop

playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss, playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.tsx, playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_disabled.html.erb, playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_disabled.jsx, playbook/app/pb_kits/playbook/pb_typeahead/docs/example.yml, playbook/app/pb_kits/playbook/pb_typeahead/docs/index.js, playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb
[PBNTR-897](https://runway.powerhrg.com/backlog_items/PBNTR-897)
Added `disabled` prop to Typeahead kit.
1. Go to the Typeahead kit and check out the last doc example.
=> [PBNTR-897] Typeahead Kit - Disabled Prop for Rails and React

playbook/app/pb_kits/playbook/pb_icon_button/_icon_button.tsx, playbook/app/pb_kits/playbook/pb_icon_button/docs/_icon_button_click.jsx, playbook/app/pb_kits/playbook/pb_icon_button/docs/example.yml, playbook/app/pb_kits/playbook/pb_icon_button/docs/index.js
Add onClick to Icon Button kit.
1. Go to /kits/icon_button/react
2. Check out the example
=> [PLAY-1963] Icon Button onClick Handler

playbook/app/pb_kits/playbook/pb_button/_button.scss
Moved the disable code further down the file so it overrides the danger styles.
[PLAY-1960](https://runway.powerhrg.com/backlog_items/PLAY-1960)
[Review ENV]()
[CSB](https://codesandbox.io/p/devbox/disabled-button-forked-57vwhq?file=%2Fsrc%2FApp.js&workspaceId=ws_Ni9WCwV5jk56bH746ZU8Ee)
=> [PLAY-1960] Button Kit: Fix Disable Prop on Danger Variant

playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_pagination.jsx
I tried a purely CSS approach, but I ran into issues with the border not displaying due to hidden overflow, as well as the pagination scrolling along with the table. Moving the pagination outside the .pb_advanced_table div seems to fix this. If that’s not an option, let me know, and I can work on a CSS approach that solves the problem.
[PLAY-1956](https://runway.powerhrg.com/backlog_items/PLAY-1956)
[Review ENV](https://pr4421.playbook.beta.px.powerapp.cloud/kits/advanced_table/react)
=> [PLAY-1956] Advance Table Kit: Fix Visible Container on Pagination 

playbook-website/app/views/guides/_docs_index_list.html.erb, playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss
This fixes the links on the Getting Started Page. There is other logic on the page to account for missing token pages and missing global pages. None of that is being triggered currently on the page but I left it as is for now. Let me know if I should remove it.
[PLAY-1950](https://runway.powerhrg.com/backlog_items/PLAY-1950)
[Review ENV](https://pr4432.playbook.beta.px.powerapp.cloud/)
=> [PLAY-1950] Playbook Website: Fix Incorrect Links on Getting Started Page

playbook/app/pb_kits/playbook/pb_layout/_layout.scss, playbook/app/pb_kits/playbook/pb_layout/_layout.tsx, playbook/app/pb_kits/playbook/pb_layout/docs/_layout_bracket.jsx, playbook/app/pb_kits/playbook/pb_layout/docs/_layout_bracket.md, playbook/app/pb_kits/playbook/pb_layout/docs/example.yml, playbook/app/pb_kits/playbook/pb_layout/docs/index.js, playbook/app/pb_kits/playbook/pb_layout/layout.test.js, playbook/app/pb_kits/playbook/pb_layout/subcomponents/_game.tsx, playbook/app/pb_kits/playbook/pb_layout/subcomponents/_round.tsx
- Add a 'bracket' option for `layout` prop in React Layout kit
- Display flex and scroll overflow
- Pass numberOfRounds down to <Layout.Game />
- Add a <Layout.Round /> component
- Flex column, justify-content: space-around
- Add horizontal "right" lines by dividing by 2
- Pass numberOfGames down to <Layout.Game />
- Add a <Layout.Game /> component
- Take first and second child and separate by a section separator in a card
- If there's nothing provided, show "To be determined..."
- If one child or more than two children are provided, fill in
- Add a "half box" based on numberOfRounds and numberOfGames
- Flex grow
- Add a <Layout.RoundLabel /> component
- Fill in any child
- Default: display none, but on mobile, show
- Make responsiveness. On mobile, …
=> [PLAY-1929] Bracket Layout - React

playbook-website/app/components/playbook/pb_docs/kit_example.html.erb, playbook-website/app/components/playbook/pb_docs/kit_example.rb, playbook-website/app/javascript/site_styles/docs/_kit_doc.scss
- Add a fullscreen button that uses `requestFullscreen()`
- Add an id to wrapping card to be targeted for fullscreen
- Add to all Advanced Table and Multi Level Select kits as well as one of the Drawer Menu examples
- Hide the "Show Code" and "Copy HTML" buttons when in fullscreen
- Be able to scroll if the example goes farther than the screen
1. For Advanced Table and Multi Level Select docs:
2. Click Fullscreen
3. Exit
4. Look at rails and react. 
5. Also, look at the drawer kit for the "menu" example
6. Other kit docs should not have the fullscreen button
=> [PLAY-1942] Fullscreen Button - Advanced Table, Multi Level Select, and Drawer Examples

playbook/app/pb_kits/playbook/pb_tooltip/tooltip.html.erb, playbook/app/pb_kits/playbook/pb_typeahead/typeahead.html.erb, playbook/app/pb_kits/playbook/pb_user/user.html.erb, playbook/app/pb_kits/playbook/pb_user_badge/user_badge.html.erb, playbook/lib/playbook/kit_base.rb
Runway https://runway.powerhrg.com/backlog_items/PLAY-1758
Nitro Alpha https://github.com/powerhome/nitro-web/pull/47331
Updates kits to use `pb_content_tag` which is our own take on rail's `content_tag`
these kits: 
typeahead 
tooltip
user
user_badge
=> [PLAY-1758] Typeahead, Tooltip, User, UserBadge Kits: Convert to use Content Tag

playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.test.jsx, playbook/app/pb_kits/playbook/pb_collapsible/__snapshots__/collapsible.test.js.snap, playbook/app/pb_kits/playbook/pb_contact/contact.test.js, playbook/app/pb_kits/playbook/pb_date_range_inline/date_range_inline.test.js, playbook/app/pb_kits/playbook/pb_date_range_stacked/date_range_stacked.test.js, playbook/app/pb_kits/playbook/pb_draggable/draggable.test.jsx, playbook/app/pb_kits/playbook/pb_dropdown/dropdown.test.jsx, playbook/app/pb_kits/playbook/pb_icon/icon.test.js, playbook/app/pb_kits/playbook/pb_icon_circle/icon_circle.test.js, playbook/app/pb_kits/playbook/pb_icon_stat_value/icon_stat_value.test.js, playbook/app/pb_kits/playbook/pb_icon_value/icon_value.test.js, playbook/app/pb_kits/playbook/pb_label_value/label_value.test.js, playbook/app/pb_kits/playbook/pb_link/link.test.jsx, playbook/app/pb_kits/playbook/pb_nav/_nav_item.test.js, playbook/app/pb_kits/playbook/pb_stat_change/stat_change.test.js, playbook/jest.setup.js, playbook/spec/pb_kits/playbook/kits/icon_spec.rb
- In React/Jest tests, add Playbook Icons to window so custom icons are used
- Replace Font Awesome icon classes with Playbook Icon classes
- In Rails/Spec Icon test, test for variations instead of exact Font Awesome class names. 
The build for this PR should pass CI.
=> [PLAY-319] Remove Font Awesome from Tests

playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_vertical.md
[PBNTR-953](https://runway.powerhrg.com/backlog_items/PBNTR-953) requests the addition of clarifying markdown text to the Rails and React vertical section separator doc example. The requirement for `vertical: "stretch"`/`vertical="stretch"` in the parent container is exhibited in the doc example but not explained or highlighted. A Nitro dev expressed confusion figuring out how to get a Vertical Section Separator to work in a Playbook support room and we figured it would make sense to make this "hidden" requirement more explicit.
1. Go to the Vertical Separator doc example …
=> [PBNTR-953] Vertical Section Separator Documentation

playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss, playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_select.html.erb, playbook/app/pb_kits/playbook/pb_form_group/docs/_form_group_select.jsx
[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2063)
Styling fixes for active and error states for the Phone Number Input kit when used in a FormGroup with a Select on the right instead of the left.
=> [PLAY-2063] From Group: Phone Number Input and Select with Select on the Right

playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/Hooks/useTableActions.ts, playbook/app/pb_kits/playbook/pb_advanced_table/Utilities/ExpansionControlHelpers.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss, playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_expand_by_depth.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_expand_by_depth.md, playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml, playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js, playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.tsx, playbook/app/pb_kits/playbook/pb_dropdown/subcomponents/DropdownOption.tsx
[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2054)
This PR:
- Adds a new prop called `expandByDepth`
- This prop enables users to expand or collapse table rows by specific levels of nesting. When provided, it renders a dropdown that appears when the toggle icon in the header is clicked.
- `expandByDepth` accepts an array of objects, where each object defines the depth level to target and the label to display in the dropdown. When a user selects an option:
- Expanding a depth: Expands all rows at the selected depth AND all parent levels above it (if parent levels were closed), ensuring nested content is visible.
- Collapsing a depth: Only collapses rows at the selected depth, keeping parent rows expanded for context.
- Adds the optional `onExpandByDepthClick` prop. This …
=> [PLAY-2054] Advanced Table: Expansion Control by Depth

playbook/app/pb_kits/playbook/pb_overlay/_overlay.scss, playbook/app/pb_kits/playbook/pb_overlay/_overlay.tsx, playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_fullscreen_background.jsx, playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_fullscreen_background.md, playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_fullscreen_opacity.jsx, playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_fullscreen_opacity.md, playbook/app/pb_kits/playbook/pb_overlay/docs/example.yml, playbook/app/pb_kits/playbook/pb_overlay/docs/index.js
[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-1965)
As a Playbook user,
I want to to be able to customize the color and opacity of a non gradient Overlay,
So that I can ensure clarity and legibility of text when over images.
=> [PLAY-1965] Overlay Kit: Add a "Full Screen" prop - React

playbook-website/config/menu.yml, playbook/app/pb_kits/playbook/pb_dialog/dialog.html.erb, playbook/app/pb_kits/playbook/pb_dialog/dialog.rb, playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_turbo_frames.html.erb, playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_turbo_frames_rails.md, playbook/app/pb_kits/playbook/pb_dialog/docs/example.yml, playbook/app/pb_kits/playbook/pb_dialog/index.js
[PLAY-2035](https://runway.powerhrg.com/backlog_items/PLAY-2035) is part of our effort to expand Playbook's Turbo support. It adds a `custom_event_type` prop which can be used as a hook for a dev to get any desired event (e.g. click, keyboard, or Turbo) to re-trigger a DOMContentLoaded event. Nitro devs can use this to update something while interacting with a Rails Dialog kit without reloading the entire page.
[PBNTR-892](https://runway.powerhrg.com/backlog_items/PBNTR-892) updated the Rails Dialog kit to have an enhanced element file, which this PR builds upon. The doc example demonstrates a lot - a custom event to open a dialog, a custom event to close the dialog after clicking confirm, and a third …
=> [PLAY-2035] Dialog kit: Add Turbo support

playbook/app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.scss, playbook/app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.tsx, playbook/app/pb_kits/playbook/pb_circle_icon_button/circle_icon_button.rb, playbook/app/pb_kits/playbook/pb_circle_icon_button/circle_icon_button.test.js, playbook/app/pb_kits/playbook/pb_circle_icon_button/docs/_circle_icon_button_size.html.erb, playbook/app/pb_kits/playbook/pb_circle_icon_button/docs/_circle_icon_button_size.jsx, playbook/app/pb_kits/playbook/pb_circle_icon_button/docs/_circle_icon_button_size.md, playbook/app/pb_kits/playbook/pb_circle_icon_button/docs/example.yml, playbook/app/pb_kits/playbook/pb_circle_icon_button/docs/index.js, playbook/spec/pb_kits/playbook/kits/circle_icon_button_spec.rb
[PLAY-1901](https://runway.powerhrg.com/backlog_items/PLAY-1901) requests a small size for the Circle Icon Button kit. The default kit is 40x40, and the new `size` prop now takes "small" as a value to display a 20x20 button. The icon inside the circle is appropriately centered within it. If additional sizes are requested in the future they can easily be added to the kit via this setup.
1. Go to the Circle Icon Kit "Size" doc example in the review environment ([rails](https://pr4543.playbook.beta.gm.powerapp.cloud/kits/circle_icon_button#size), …
=> [PLAY-1901] Circle Icon Button kit: Add new 20x20 size

playbook-website/config/menu.yml, playbook/app/entrypoints/playbook-rails.js, playbook/app/pb_kits/playbook/pb_copy_button/docs/_copy_button_hook_rails.html.erb, playbook/app/pb_kits/playbook/pb_copy_button/docs/_copy_button_hook_rails.md, playbook/app/pb_kits/playbook/pb_copy_button/docs/example.yml, playbook/app/pb_kits/playbook/pb_copy_button/index.js
- Make the Copy Button Kit live (out of beta)
- In playbook-rails.js, run function, `addCopyEventListeners`, which adds event listeners to any elements with `data-external-copy-value` or `data-external-copy-from`
- Create a "Copy Hook" doc that dispatches an event with the `from` name
https://runway.powerhrg.com/backlog_items/PLAY-2038
1. Go to Playbook
2. You should be able to search for Copy Button kit and also click on it from the menu
3. Go to /kits/copy_button/rails#copy-hook
4. The other Rails kits should not be affected
=> [PLAY-2038] Copy Button Kit Go Live and Rails Copy Hook

playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_error.jsx, playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_error.jsx, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_validation.jsx, playbook/app/pb_kits/playbook/pb_select/docs/_select_error.jsx, playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_error.jsx, playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_error.jsx, playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_error_state.jsx
- Add warning icon next to error docs for accessibility
- Phone Number Input, Text Input, Textarea, Typeahead, Date Picker, Dropdown, and Select
https://runway.powerhrg.com/backlog_items/PLAY-2043
1. Go to these docs and make sure there is a 'warning' icon next to the error message
=> [PLAY-2043] Playbook Website: Add Warning Icon to Error Docs - React

playbook/app/javascript/theme.js, playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_pb_styles.jsx, playbook/app/pb_kits/playbook/pb_line_graph/docs/_line_graph_pb_styles.md, playbook/app/pb_kits/playbook/pb_line_graph/docs/example.yml, playbook/app/pb_kits/playbook/pb_line_graph/docs/index.js, playbook/app/pb_kits/playbook/pb_line_graph/lineGraphTheme.js, playbook/app/pb_kits/playbook/pb_line_graph/lineGraphTheme.ts
[CSB](https://codesandbox.io/p/devbox/busy-cdn-gcxc9p)
[PLAY-1736](https://runway.powerhrg.com/backlog_items/PLAY-1736)
[REVIEW ENV](https://pr4562.playbook.beta.hq.powerapp.cloud/kits/line_graph/react)
This PR allows you to use the Line Graph settings and styles without having to use the Line Graph kit. 
The tick intervals aren't matching for some reason here and I don't know why. That seems to be handled automatically by Highcharts. I'm thinking it's not a huge issue though because the `tickInterval` can be set manually if needed by adding it to the `yAxis` options.
=> [PLAY-1736] Line Graph: Add Ability to Use Line Graph Styles w/o Line Graph

playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss, playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.rb, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_border_color.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_border_color.md, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_border_color_rails.html.erb, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_border_color_rails.md, playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml, playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2056)
As a Playbook user, 
I want provide options for border colors for the vertical borders between Column Groups when using the multi header column logic for the Advanced Table
1. Go to '...'
=> [PLAY-2056] Advanced Table kit: Add Support for Different Column Border Colors for Column Groups - Rails & React

playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.scss, playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.tsx, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_country_search.html.erb, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_country_search.jsx, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_country_search.md, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/example.yml, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/index.js, playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.rb, playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.test.js, playbook/spec/pb_kits/playbook/kits/phone_number_input_spec.rb
[PLAY-2048](https://runway.powerhrg.com/backlog_items/PLAY-2048) prop enables a relatively new-ish feature from the intl-tel-input library, `countrySearch`. `countrySearch` allows a user to search for the country via an input prepended to the country selection dropdown. 
This PR creates a boolean prop to enable this feature for both React and Rails implementations, and adds a doc example demonstrating its use. I also locally tested its look on the [form kit page](https://playbook.powerapp.cloud/kits/form) but did not push this up - see screenshot below from local test. This PR also re-adds a minimum width to the country dropdown - the kit was initially created with this prop, but it was removed in error …
=> [PLAY-2048] Phone Number Input kit: Add Country Search

playbook/app/pb_kits/playbook/pb_select/_select.scss
[PLAY-2037](https://runway.powerhrg.com/backlog_items/PLAY-2037) addresses a visual UX bug (Rails + React) wherein the Select arrow is misaligned when the inline or inline + compact versions of the kit are in an error state. A [previous PR](https://github.com/powerhome/playbook/pull/2253) fixed the same issue for the default kit. 
Can see the update in action comparing these two CSBs:
[CSB Before - Reproduces Initial Issue](https://codesandbox.io/p/devbox/flamboyant-wilson-wv5vmt)
[CSB with Alpha](https://codesandbox.io/p/devbox/play-2037-reproduce-issue-select-inline-error-forked-kc7x6y)
Before: 
After Rails: 
After React:
CSBs side by …
=> [PLAY-2037] Select kit: Inline Error Misaligns Arrow

playbook/app/pb_kits/playbook/pb_table/docs/_table_with_collapsible_with_custom_click.jsx, playbook/app/pb_kits/playbook/pb_table/subcomponents/_table_row.tsx
[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2150)
1. Go to [React Doc Example](https://pr4582.playbook.beta.px.powerapp.cloud/kits/table/react#table-with-collapsible-with-custom-click)
2. Click on far right icon to open/close collapsible
3. Click on icon under column 5. Icon will not affect collapsible.
=> [PLAY-2150] Table kit: Expandable/Collapsible not behaving correctly when multiple icons are present

playbook-website/app/views/pages/kit_collection.html.erb, playbook-website/app/views/pages/kit_variants_collection.html.erb
[PLAY-1556 Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-1556)
1. Go to https://pr4598.playbook.beta.px.powerapp.cloud/kit_collection/title&card&nav/title/react
=> [PLAY-1556]  React Prop table not working on Kit Collection pages

playbook/app/pb_kits/playbook/pb_overlay/_overlay.scss, playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_vertical_dynamic_multi_directional.jsx, playbook/app/pb_kits/playbook/pb_overlay/subcomponents/_overlay_token.tsx
[PLAY-2149](https://runway.powerhrg.com/backlog_items/PLAY-2149)
[CSB](https://codesandbox.io/p/devbox/sad-feistel-c24ftt)
This fixes the hidden scroll for the dynamic variant
Here is the [Nitro Review ENV](https://pr48269.nitro-web.beta.px.powerapp.cloud/powerlife/home) along with a [small nitro fix](https://github.com/powerhome/nitro-web/pull/48269).
To test, shrink browser down and scroll the topics at the top.
=> [PLAY-2149] Overlay Kit: Dynamic Variant Bug Fix - React

.github/PULL_REQUEST_TEMPLATE.md
[PLAY-2004](https://runway.powerhrg.com/backlog_items/PLAY-2004) adds two additional items to our PR checklist. The first is a reminder to add a Semver label (minor, major, or patch) and the second is a reminder to add an Inactive RC label if the PR is being merged as inactive.
1. Go to the PULL_REQUEST_TEMPLATE.md [file on this branch](https://github.com/powerhome/playbook/blob/PLAY-2004-update-PR-template-checklist/.github/PULL_REQUEST_TEMPLATE.md) (PLAY-2004-update-PR-template-checklist).
2. See additional items in checklist in that file.
3. They do not appear on this checklist below …
=> [PLAY-2004] Add Semver and Inactive RC to GitHub PR Checklist

playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.scss, playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss
[PLAY-2125](https://runway.powerhrg.com/backlog_items/PLAY-2125)
[Review ENV](https://pr4610.playbook.beta.px.powerapp.cloud/kits/phone_number_input/react#country-search-1)
This fixes the error styling on the phone input for the country search. 
Here's an example of how it currently looks: [Production](https://playbook.powerapp.cloud/kits/phone_number_input/react)
and the fixed version: [Review ENV](https://pr4610.playbook.beta.px.powerapp.cloud/kits/phone_number_input/react#country-search-1)
=> [PLAY-2125] Phone Number Input: Fix the Error Styles for Country Search - Rails & React

playbook/app/pb_kits/playbook/pb_advanced_table/Components/RegularTableView.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableActionBar.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/Hooks/useTableState.ts, playbook/app/pb_kits/playbook/pb_advanced_table/Utilities/VisibilityTree.ts, playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss, playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility.md, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility_custom.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility_custom.md, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility_multi.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility_multi.md, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility_with_state.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility_with_state.md, playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml, playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js, playbook/app/pb_kits/playbook/pb_advanced_table/scss_partials/advanced_table_sticky_mixin.scss, playbook/app/pb_kits/playbook/pb_dropdown/subcomponents/DropdownContainer.tsx, playbook/app/pb_kits/playbook/pb_section_separator/_section_separator.tsx
[PLAY-2129](https://runway.powerhrg.com/backlog_items/PLAY-2129)
**This PR covers the following:**
Adds `columnVisibilityControl` prop that allows you to toggle visibility of different columns off and on.
Allows devs to manage state for this control if they want so they can set an initial state, etc
allows devs to customize which columns to show as options within the dropdown so they can have a smaller dropdown if they want
Allows for visibility control to work with multi-header columns
For this one, the dropdown shows hierarchy of columns
unchecking and checking cascades up and down similar to MLS
**To be covered in a follow up:**
With the responsiveness set to true, the dropdown is clipped at the bottom where the table ends on smaller screen sizes (only an …
=> [PLAY-2129] Advanced Table: ColumnVisibility Control

playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.scss
[PLAY-1973](https://runway.powerhrg.com/backlog_items/PLAY-1973) requests some adjustments to the size of the Icon,  Avatar, and Close Icon inside the Form Pill kit for the regular size and small size Form Pill. Changes can be compared between [this CSB](https://codesandbox.io/p/sandbox/9qgyfz) from a previous story on Form Pills which has a bunch of different Form Pill permutations and [this CSB](https://codesandbox.io/p/devbox/pbntr-416-form-pill-3-of-5-size-alpha-forked-9jmvms) with alpha from this PR showing size changes.
This PR handles the following:
- Avatar circle is smaller for small Form Pills
- Icon size is larger for default Form Pills
- Close Icon size is larger for default and small Form …
=> [PLAY-1973] Form Pill kit: Icon and Avatar sizing is off

playbook/app/pb_kits/playbook/pb_form_group/_error_state_mixin.scss
It fixes SCSS in the Form Group Kit where a Select input would affect a Passphrase input's error because it would add extra padding. 
We made another fix to Phone Number Input with [PLAY-2107](https://runway.powerhrg.com/backlog_items/PLAY-2107)
https://runway.powerhrg.com/backlog_items/PLAY-2182
is fixed:
1. Go to Credit app and make sure an error doesn't misalign the form group.
=> [PLAY-2182] Form Group Kit: Fix Select and Passphrase Inputs Error Misalignment

playbook-website/package.json, yarn.lock
[PLAY-2139](https://runway.powerhrg.com/backlog_items/PLAY-2139) Bumps [@powerhome/power-fonts](https://github.com/powerhome/power-fonts) from 0.0.1-alpha.6 to 0.0.1 for the Playbook website.
There should be no visual changes - we are just getting off the alpha version of the repo.
1. Go to the [playbook website review env](https://pr4634.playbook.beta.px.powerapp.cloud/).
2. Look at any text/typography. It should still be Power Centra font. Confirm this by: 
- looking at the lowercase t's (these are very visually distinct in Power Centra)
- inspect any text/typography kit and look at the computed font-family - the font should be …
=> [PLAY-2139] Update power-fonts to 0.0.1

playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
Fixes for bug when StickyLeftColumn, Sticky Header and ColumnBorderColor used together, style from the ColumnBorderColor overrode the table container box-shadow
[csb with fix](https://codesandbox.io/p/devbox/advanced-table-multi-column-sticky-forked-52kcyd)
=> [PLAY-2206] Advanced Table: Fix for border when StickyLeftColumn, Sticky Header and ColumnBorderColor used together

playbook/lib/playbook/kit_base.rb
Fix bug where style would be set to nil if inline styles (e.g., height) weren't present
https://runway.powerhrg.com/backlog_items/PLAY-2145
1. Go to /kit_playground_rails
2. Paste the following:
3. `<%= pb_rails("title", props: { text: "Welcome to Playbook", size: 1, html_options: { style: "background-color: blue;" } }) %>
<%= pb_rails("title", props: { text: "Welcome to Playbook", size: 1, height: "50px", html_options: { style: "background-color: blue;" } }) %>`
4. Both should be blue
5. The second should have a height of 50px
=> [PLAY-2145] All Kits: Fix `html_options style` without Inline Styles Bug - Rails

playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableActionBar.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility_with_state.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_visibility_with_state.md
- Replace Visibility Control Dropdown with Popover to solve for all the placement issues. No functionality changes
- Replace expandBy Depth Dropdown with Popover to solve for all the placement issues. No functionality changes
- Additional onChange within VisibilityControl to give access to current state
1. Go to '...'
=> [PLAY-2171] Advanced Table: Replace Dropdown with Popover for ColumnVisibility + expandByDepth Props

renovate.json
Some of these are mandatory for continued functionality, like ci-kubed v9.0.0.
=> Renovate should propose major upgrades

playbook/app/pb_kits/playbook/pb_dropdown/dropdown.test.jsx, playbook/spec/pb_kits/playbook/kits/dropdown_spec.rb
- Adds Jest tests
- Adds Rspec tests
If passes CI, all is well
=> [PLAY-2208] Dropdown Kit: Adding Jest and RSpec Tests

playbook/app/pb_kits/playbook/pb_dropdown/index.js
- Show 'no option' in Rails dropdown like in React for autocomplete
- Add a div with the same classes, `pb_body_kit_light dropdown_no_options pb_item_kit p_xs display_flex justify_content_center`
https://runway.powerhrg.com/backlog_items/PLAY-2161
1. Go to /dropdown/rails
2. Test all the autocomplete docs
=> [PLAY-2161] Dropdown Kit: Display 'no option' with no results in autocomplete - Rails

playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.tsx, playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_close_on_select.jsx, playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_close_on_select.md, playbook/app/pb_kits/playbook/pb_dropdown/docs/example.yml, playbook/app/pb_kits/playbook/pb_dropdown/docs/index.js, playbook/app/pb_kits/playbook/pb_dropdown/subcomponents/DropdownOption.tsx, playbook/app/pb_kits/playbook/pb_dropdown/subcomponents/DropdownTrigger.tsx
[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2127)
1. Go to [Close on Selection](https://pr4681.playbook.beta.px.powerapp.cloud/kits/dropdown/react#close-on-selection) doc example for the React Dropdown kit
=> [PLAY-2127] Dropdown: closeonSelection prop - React only

playbook/app/pb_kits/playbook/pb_advanced_table/Components/CustomCell.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_no_subrows.html.erb, playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
- [Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2239)
- Cell content i n first column should stay left aligned irrespective of whether there are child rows or not
1. Navigate to /kits/advanced_table/react#table-with-no-subrows-or-expansion on milano
=> [PLAY-2239] Advanced Table: Fixes for Cell Alignment when No Subrows

playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
The scrollbar styling scss was overriding the scrollbar none scss, this fixes that.
1. Go to '...'
=> Advanced Table: Scrollbar none scss fixes

playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
[PLAY-2167](https://runway.powerhrg.com/backlog_items/PLAY-2167) is an investigation to figure out why the horizontal rows of the Advanced Table are doubled in Nitro when container is true. 
**Screenshots**
See [Alpha PR](https://github.com/powerhome/nitro-web/pull/48991/) for more screenshots. Compare Headcount over Time borders QA vs. Review env below:
Rails example - setting container: true on Rails Advanced Table to demo this as well Pre-Alpha and Post-Alpha:
1. Go to the [Accrual Report page](https://nitroqa.powerhrg.com/marketing/accrual_report?mt=Accrual%20Report) [Headcount Over Time …
=> [PLAY-2167] Advanced Table Horizontal Rows Double when Container True

playbook/app/pb_kits/playbook/pb_checkbox/checkbox.rb, playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_custom.html.erb, playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_custom_rails.md, playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_form.html.erb, playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_form.md, playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_options.html.erb, playbook/app/pb_kits/playbook/pb_checkbox/docs/example.yml, playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb, playbook/spec/pb_kits/playbook/kits/checkbox_spec.rb
[PLAY-2214](https://runway.powerhrg.com/backlog_items/PLAY-2214) adds a `hidden_input` boolean prop to the rails Checkbox kit so unchecked values can be properly submitted with our base kit `pb_rails("checkbox")` within the `form`/`pb_form_with` context. The logic is set so that it works whether name, value, and other key attributes are passed directly as props or via the `input_options` hash.
Additionally, this update improves documentation for the Form Builder variant (`form.check_box` / `f.check_box`) on the Checkbox and Form kit pages, clarifying how to enable and use hidden inputs in those contexts (by including an `unchecked_value`).
I've also updated the custom checkbox doc example to highlight …
=> [PLAY-2214] Checkbox kit: Add Hidden Input Logic Rails

playbook/app/pb_kits/playbook/pb_table/styles/_table-card.scss
[PLAY-2112](https://runway.powerhrg.com/backlog_items/PLAY-2112) addresses some styling issues that appeared for a one column table. The initial ticket mentioned the one header cell issue, but there is actually one for when there is one table cell in the body as well. Adding the only-child pseudoclass in addition to first-child and last-child in table-card.scss accounts for these situations. 
One column tables will now have: 
- a left border on the table header (currently there is a gap without a border in the header)
- a curved bottom left corner border radius for the last row (currently a right angle)
Compare and contrast: 
[CSB Reproducing Issue](https://codesandbox.io/p/sandbox/elastic-matan-dkzxnc) …
=> [PLAY-2112] Table kit: Styling Issue For One Column Table

playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
[PLAY-2252](https://runway.powerhrg.com/backlog_items/PLAY-2252) re-adds two Rails Advanced Table doc examples. These were created in [PLAY-1893](https://runway.powerhrg.com/backlog_items/PLAY-1893) but not publicized then due to issues with the load time of the Rails doc example page. [PLAY-2255](https://runway.powerhrg.com/backlog_items/PLAY-2255) refactored some code to decrease the page's load time.
1. Go to [Rails Advanced Table doc example page in the review env](https://pr4786.playbook.beta.px.powerapp.cloud/kits/advanced_table/rails). The page should load. Scroll down to the …
=> [PLAY-2252] Advanced Table: Add Rails Header Alignment Docs Examples

playbook/app/pb_kits/playbook/pb_advanced_table/Components/SubRowHeaderRow.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_custom_sort.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_custom_sort.md, playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml, playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2288)
- POC work down on[ this story](https://runway.powerhrg.com/backlog_items/PLAY-2258)
- Sort on the inner dimension cannot be handled by the kit itself without mutating the data so we are only providing the following:
- A button that shows up in the subrow header with a callback function attached
- The callback function will have as an argument an array of the immediate subrows that can be sorted
- Nitro devs will handle the sort itself from the frontend so nothing needed from us there
- Use the 'sort' icon for that button + make it aligned to end of cell so it matches the sort button in the header cell.
doc example …
=> [PLAY-2288] Advanced Table: Custom Sort

playbook-website/app/controllers/pages_controller.rb, playbook-website/app/helpers/application_helper.rb, playbook-website/app/javascript/components/KitSearch.tsx, playbook-website/app/javascript/components/MainSidebar/NavComponents/KitsNavComponent.tsx, playbook-website/app/javascript/components/MainSidebar/index.tsx, playbook-website/app/views/pages/kit_show.html.erb, playbook-website/config/menu.yml, playbook-website/config/routes.rb, playbook-website/lib/pb_doc_helper.rb, playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2295)
Covered in this story:
- ✅ Advanced Table as its own menu item (category)
- ✅ sub menu items as per handoff
- ✅ each submenu item to contain required docs only
- ✅ Advanced Table to still show up in search bar
- ✅ clicking on searchbar item will direct to category page for advanced table
- ✅ dark mode toggle to work
- ✅ rails side: table data to work
- ✅ rails side: sections to contain correct docs
- ✅ routes to be advanced_table/section
1. Go to '...'
=> [PLAY-2295] PB Website: Advanced Table as own Menu Item in Sidebar

playbook/app/pb_kits/playbook/pb_draggable/context/index.tsx, playbook/app/pb_kits/playbook/pb_draggable/context/types.ts
[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2257)
- Dragging drag items between doc examples should not break docs
https://github.com/user-attachments/assets/41386bc9-c68d-466e-bf65-4468d942e5ad
1. Go to React docs for draggable kit and try dragging between doc examples
=> [PLAY-2257] Draggable Kit: Dragging Between Drag Containers to not Break Page

playbook-website/app/helpers/application_helper.rb, playbook-website/app/views/pages/playbook_icons.html.erb
[PLAY-2308](https://runway.powerhrg.com/backlog_items/PLAY-2308) addresses a bug with searching on the Playbook website following code changes in the Advanced Table Docs Restructuring story [PLAY-2295](https://runway.powerhrg.com/backlog_items/PLAY-2295). Changing an and operator to a ternary (matching line 141 right above it) solves the search issue.
When a user tried to navigate from a /rails kit page via the search bar, they would be redirected back to the homepage. 
1. Go to the Playbook website in the review env.
2. Navigate to a Rails kit page. 
3. Search for another kit or different page in the search bar. You should successfully navigate to …
=> [PLAY-2308] Website Search Bug - after Advanced Table Restructuring

playbook/app/entrypoints/playbook-rails-react-bindings.js
[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2307)
The Dialog kit has imports/exports included in this [playbook-rails-react-bindings.js file](https://github.com/powerhome/playbook/blob/master/playbook/app/entrypoints/playbook-rails-react-bindings.js) 
This is a remnant of when this kit was a react rendered rails kit on the rails side. We already did the work to create a Rails only Dialog kit so the imports/exports of Dialog is not longer needed in this bindings file
Test Dialog kit docs on Rails side.
Alpha test in Nitro
=> Dialog Kit: Remove Dialog kit from react bindings file

playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.tsx, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_strict_mode.html.erb, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_strict_mode.jsx, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_strict_mode.md, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/example.yml, playbook/app/pb_kits/playbook/pb_phone_number_input/docs/index.js, playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.rb, playbook/spec/pb_kits/playbook/kits/phone_number_input_spec.rb
Add strictMode prop which only accepts numbers and caps the input at a max length.
This resulted from an exploration into formatAsYouType not working as expected.
https://runway.powerhrg.com/backlog_items/PLAY-2126
1. Go to kits/phone_number_input/react#format-as-you-type
2. Go to rails
=> [PLAY-2126] Phone Number Kit: strictMode Prop Accept Numbers and Max Length

playbook/app/pb_kits/playbook/pb_checkbox/checkbox.rb, playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_indeterminate.html.erb, playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_indeterminate_rails.md, playbook/app/pb_kits/playbook/pb_checkbox/index.js, playbook/app/pb_kits/playbook/pb_table/docs/_table_with_selectable_rows.html.erb, playbook/spec/pb_kits/playbook/kits/checkbox_spec.rb
- Add `indeterminate_main_labels` prop which can be set with ["Check All Label", "Uncheck All Label"]
- If not provided, defaults to "Check All" and "Uncheck All"
- If ["", ""] is provided, no labels are used
- Update "Table with Selectable Rows" doc to match React- remove labels.
https://runway.powerhrg.com/backlog_items/PLAY-2243
1. /kits/checkbox/rails#indeterminate-checkbox-1
2. /kits/table/rails
=> [PLAY-2243] Checkbox Kit: Custom Indeterminate Main Checkbox Labels - Rails

playbook-website/config/menu.yml, playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/Hooks/useTableState.ts, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_with_custom_header_multi_header.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_with_custom_header_multi_header.md, playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml, playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2204)
Custom Header support for multi header tables. 
1. Go to cell behavior tab in the Advanced Table menu to see docs
=> [PLAY-2204] Advanced Table: Support Custom headers with Multi-Header Columns

playbook/app/pb_kits/playbook/pb_select/select.rb, playbook/spec/pb_kits/playbook/kits/select_spec.rb
Fix Select classnames bug by making sure there is a single space between all additional classes (inline, compact, show_arrow).
https://runway.powerhrg.com/backlog_items/PLAY-2148
1. Go to kits/select/rails and compare to prod
=> [PLAY-2148] Select Kit: Classnames Spaces Fix - Rails

playbook/app/pb_kits/playbook/pb_pagination/_pagination.tsx, playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_default_rails.md, playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_default_react.md
- Show the React Pagination Kit only if there are multiple pages to navigate.
- Add note in Rails and React docs. 
- "Note: If the total page count is 0 or 1, the Pagination kit will not be displayed as there aren't multiple pages to navigate."
https://runway.powerhrg.com/backlog_items/PLAY-1985
1. Make sure the descriptions for both React and Rails pagination kits are updated
2. Review the code sandbox attached to the Runway story.
=> [PLAY-1985] Pagination Kit: Show Only with Multiple Pages - React

playbook/app/entrypoints/playbook-rails-react-bindings.js
[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2303)
Currently, when we render Playbook kits via ajax (or Turbo) sometimes we need to call WebpackerReact.mountComponents() to initialize the Playbook kits. This seems to be an issue with all kits listed within [this file](https://github.com/powerhome/playbook/blob/master/playbook/app/entrypoints/playbook-rails-react-bindings.js), most notable being the Typeahead since it is used everywhere.
This workaround of having to call WebpackerReact.mountComponents() has existed for a long time, but with the Vite migration work we want to try and find a better solution for the problem of rendering react rendered rails kits.
The [webpack cleanup work ](https://github.com/powerhome/nitro-web/pull/49189/files) …
=> [PLAY-2303] WebpackerReact Config for Playbook kits to come from Playbook

playbook-website/config/menu.yml, playbook/app/pb_kits/playbook/pb_advanced_table/Components/SortIconButton.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/Hooks/useTableState.ts, playbook/app/pb_kits/playbook/pb_advanced_table/SubKits/TableHeader.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss, playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx, playbook/app/pb_kits/playbook/pb_advanced_table/advanced_table.test.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_sort_per_column.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_sort_per_column.md, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_sort_per_column_for_multi_column.jsx, playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_sort_per_column_for_multi_column.md, playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml, playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js
[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2312)
- This PR adds ability to add sort to any column on the table, not just the first one.
- It retains original functionality for adding sort on first column for backward compatibility. 
- Adds an additional `enableSortingRemoval` prop to allow sort to cycle through 'none' -> 'desc' -> 'asc' -> 'none' -> .. as opposed to just asc and desc so sort can be reset as well 
[Docs under the 'Sorting' menu item](https://pr4945.playbook.beta.gm.powerapp.cloud/kits/advanced_table/sorting/react)
=> [PLAY-2312] Advanced Table: Sort Available on All Columns

playbook/app/pb_kits/playbook/pb_pagination/_pagination.test.jsx, playbook/app/pb_kits/playbook/pb_pagination/_pagination.tsx, playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_external_control.jsx, playbook/app/pb_kits/playbook/pb_pagination/docs/_pagination_external_control_react.md, playbook/app/pb_kits/playbook/pb_pagination/docs/example.yml, playbook/app/pb_kits/playbook/pb_pagination/docs/index.js
[PLAY-2346](https://runway.powerhrg.com/backlog_items/PLAY-2346) adds a useEffect to sync the React Pagination's internal state with the external current prop. There are a couple instances in Nitro with workarounds in place to achieve this result, and this PR will be alpha tested to ensure it works by replacing the workaround on the CD Community Performance Dashboard.
Shoutout to @kangaree's awesome [POC/exploration CSB](https://codesandbox.io/p/sandbox/vigilant-leaf-wrxnrh?file=%2Fsrc%2FApp.js%3A17%2C52) which was a great jumping off point for the doc example used to demonstrate this functionality in use.
This PR also adds a jest test file + tests to the React Pagination kit. …
=> [PLAY-2346] Pagination kit: Sync Pagination's internal state with the external current prop - React

playbook-website/package.json, yarn.lock
[PLAY-2373](https://runway.powerhrg.com/backlog_items/PLAY-2373) adds the Playbook Icon to the playbook-icons repo (woohoo!). This PR is a version bump.
[Playbook-icons PR](https://github.com/powerhome/playbook-icons/pull/43)
1. Icon="Playbook" now works with our Icon kit (React or Rails). See "pb_custom_icon" class in screenshot.
~~- [ ] **TESTS** I have added test coverage to my code.~~
=> [PLAY-2373] Update Playbook Icons

playbook/vite.config.ts
[PLAY-2343](https://runway.powerhrg.com/backlog_items/PLAY-2343) excludes @tiptap/react from Vite's dependency optimization so it is treated as an external dependency during the build. This PR adds it to optimizeDeps.exclude and build.rollupOptions.external in the vite.config.ts. The RichTextEditor kit should function as it currently does on Playbook and in satellite apps with this change.
1. Go to the React RichTextEditor kit page. All doc examples should act the same as they do currently.
2. Go to the RichTextEditor locations in Nitro (in alpha review env) - RTEs in those locations should act the same as they do currently.
~~- [ ] **TESTS** I …
=> [PLAY-2343] Add @tiptap/react to External Dependencies in vite.config.ts

playbook/app/pb_kits/playbook/pb_date/date.test.js
[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2379)
Adds jest tests for the React Date kit to make sure kit functions as expected.
1. Go to '...'
=> [PLAY-2379] Date kit: Add Jest Test Coverage - React

playbook-website/app/assets/icons.json, playbook-website/package.json, yarn.lock
Add new icons from 0.0.1-alpha.44
https://runway.powerhrg.com/backlog_items/PLAY-2402
1. Go to /playbook_icons
=> [PLAY-2402] Playbook Website: Add Missing icons

playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/Opacity.tsx, playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/ScreenSizes.tsx, playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/TextAlign.tsx, playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/TokensExamplesIndex.tsx, playbook-website/config/global_props_and_tokens.yml
https://runway.powerhrg.com/backlog_items/PLAY-2395
This PR adds pages for [Text Align](https://pr5123.playbook.beta.hq.powerapp.cloud/tokens/text_align), [Opacity](https://pr5123.playbook.beta.hq.powerapp.cloud/tokens/opacity) and [Screen Sizes](https://pr5123.playbook.beta.hq.powerapp.cloud/tokens/screen_sizes) tokens on Playbook.
1. Go to /tokens
2. Navigate to the new tokens pages
3. Compare to mockup
=> [PLAY-2395] Playbook Website: Create Text Align, Opacity and Screen Sizes token pages

playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills.html.erb, playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills.jsx, playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_color.html.erb, playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_with_pills_color.jsx, playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_without_pills.html.erb
- Match Rails "With Pills (Custom Color)" doc to React's
- Off-topic: Change label to Products (fka. Colors) for Product Typeaheads
https://runway.powerhrg.com/backlog_items/PLAY-2113
1. Go to /kits/typeahead/rails#with-pills-custom-color
2. It should match /kits/typeahead/react#with-pills-custom-color
=> [PLAY-2113] Typeahead Kit: Fix Clear All Docs - Rails

playbook/lib/playbook/forms/builder/form_field_builder.rb, playbook/spec/playbook/pb_forms_helper_spec.rb
- Add `type`, `value`, `disabled`, `autocomplete`, and `mask` props which change attributes for form field builder. 
- Unlike text input props like `inline` which change the div wrapper (and don't need to be set in `form_field_builder.rb`, these props need to change the nested text input attributes. This is because if content is present, then it's used instead of input_tag which includes these props:
- Combine data attributes so validation and mask can be used together
- Add tests for form.text_field
```
<% if content.present? %>
<%= content %>
<% elsif has_add_on? %>
<%= pb_rails("text_input/add_on", props: object.add_on_props) do %>
<%= input_tag %>
<% end %>
<% elsif mask.present? %>
<%= input_tag %>
<%= tag(:input, data: "sanitized-pb-input", id: …
```
=> [PLAY-2453] Form Kit: Text Field (i.e., Text Input Kit) Attribute Props - Rails

playbook-website/app/assets/icons.json, playbook-website/package.json, playbook/app/pb_kits/playbook/pb_loading_inline/_loading_inline.tsx, playbook/app/pb_kits/playbook/pb_loading_inline/loading_inline.rb, yarn.lock
[PLAY-2511](https://runway.powerhrg.com/backlog_items/PLAY-2511) updates the Playbook Icon Repo 
[Playbook-Icons PR here](https://github.com/powerhome/playbook-icons/pull/48). Adds an alias (more on that below) and a new icon (envelope-slash).
This PR also the internal icon used for the solid variant of [LoadingInline]https://playbook.powerapp.cloud/kits/loading_inline/react#variant) to the spinner-solid's new alias circle-notch to ensure the FA icon appears as a fallback when Playbook Icons are not available. Please reference [this CSB with an alpha of this PR](https://codesandbox.io/p/devbox/amazing-turing-y39z46) showing the particular circumstances we are accounting for with this. …
=> [PLAY-2511] Update Playbook Icons

playbook-website/config/menu.yml, playbook/app/entrypoints/playbook-rails.js, playbook/app/pb_kits/playbook/pb_button/docs/_button_managed_disabled.html.erb, playbook/app/pb_kits/playbook/pb_button/docs/_button_managed_disabled.md, playbook/app/pb_kits/playbook/pb_button/docs/_button_managed_disabled_helper.html.erb, playbook/app/pb_kits/playbook/pb_button/docs/_button_managed_disabled_helper.md, playbook/app/pb_kits/playbook/pb_button/docs/example.yml, playbook/app/pb_kits/playbook/pb_button/index.js, playbook/spec/pb_kits/playbook/kits/button_spec.rb
[Runway story](https://runway.powerhrg.com/backlog_items/PLAY-2512)
This PR creates a config for the Button kit in Rails that will allow devs to toggle the enabled and disabled state within turbo frames or stimulus so they do not have to manually toggle classnames or attributes. 
1. 2 new docs at bottom of Button kit Rails page
2. [Alpha in Nitro](https://github.com/powerhome/nitro-web/pull/52002)
=> [PLAY-2512] Button Kit: Ability to Dynamically Toggle Disabled State in Rails

playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.html.erb, playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_stacked_alert.jsx, playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_status.html.erb, playbook/app/pb_kits/playbook/pb_dialog/docs/_dialog_status.jsx
[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-1995)
This PR adjusts the confirmation button on the 'delete' dialog variant to use the 'danger' variant of the button in the Status Alert and Stack Status Alert doc examples.
1. Go to '...'
=> [PLAY-1995] Dialog kit: Add danger button to the "Delete Status" variants

playbook-website/app/javascript/components/GlobalPropsAndTokens/Data/TokenCards.ts, playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/LetterSpacing.tsx, playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/Shadows.tsx, playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/Titles.tsx, playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/TokensExamplesIndex.tsx, playbook-website/config/global_props_and_tokens.yml
[PLAY-2397](https://runway.powerhrg.com/backlog_items/PLAY-2397)
Adds Letter Spacing, Shadow and Titles token docs
1. Go to '...'
=> [PLAY-2397] Tokens: Create Letter Spacing, Shadow and Titles token pages

playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2525)
- Refactored SCSS for Typeahead to remove partial selectors
- No change to functionality or logic
=> [PLAY-2525] Typeahead: scss refactor

playbook-website/app/javascript/components/GlobalPropsAndTokens/ExamplesPage/Examples/Hover.tsx, playbook-website/app/javascript/components/VisualGuidelines/Examples/GroupHover.tsx, playbook-website/app/views/pages/code_snippets/group_hover_jsx.txt, playbook/app/pb_kits/playbook/pb_card/docs/_card_light.html.erb, playbook/app/pb_kits/playbook/utilities/_hover.scss, playbook/app/pb_kits/playbook/utilities/globalProps.ts, playbook/lib/playbook/hover.rb, playbook/spec/playbook/global_props/hover_spec.rb
[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2246)
This PR: 
- Changes the name of the visibility prop to 'visible' for clarity
- visible:true make the item visible on hover, visible:false does nothing
- Makes fixes to the Rails side so the global prop works on rails side as well
- Makes fixes to the beta global_props/hover page, the visual_guidelines/group_hover page + copy on both to account for the change from visibility to visible
- Added spec tests for visible hover prop
- **NOTE** visible true added to default card doc for review purposes, will be backed out once approved.
https://github.com/user-attachments/assets/4ff096d5-739d-42e0-99d3-0071b82b0280
**How to test?** Steps to …
=> [PLAY-2246] Hover Prop: Updated Visible Hover Prop - React and Rails

playbook/app/pb_kits/playbook/pb_card/docs/_card_light.html.erb
Accidentally shipped a test for a global prop within the doc example, fixing it here.
=> Fixes for Card doc example
