Gemfile.lock
app/assets/config/playbook_manifest.js
lib/playbook/engine.rb
lib/playbook/version.rb
package.json

Finish configuring rails kits to load assets

---

package.json

package_json_must_be_public_to_publish

package_json_must_be_public_to_publish

---

package.json

This shouldn't be here it is copypasta from nitro-storybook repo.

Remove references to storybook in package.json scripts section

---

.eslintrc.json
app/pb_kits/playbook/pb_avatar/_avatar.jsx
app/pb_kits/playbook/pb_avatar/docs/_avatar_default.jsx

This kit represents the ideal React kit pattern.
- Uses es6 class structure 
- Leverages Flow instead of PropTypes
- Is lint-compatible (few or no warnings, no errors) based on `.eslintrc.json`
**Note**: in order to implement in Nitro, https://github.com/powerhome/playbook/pull/158 will need to be merged first!

Avatar React Kit

---

lib/generators/kit/templates/kit_jsx.erb.tt

Update kit generator to generate react kits that match the updated syntax of Avatar.

Kit Generator Update - React JSX Component

---

Gemfile.lock
lib/playbook/version.rb
package.json

* Kit: Avatar React Kit
* Kit: Currency Rails Kit
* Kit: Section Separator Rails Kit
* Kit Update: Dashboard Value Kit
* Enhancement: Playbook Rails JS Imports
* Enhancement: Create vendor.js for exporting
* Enhancement: Update kit generator for react kits
* Bug Fix: Allow vertical nav title to be optional
* Bug Fix: All table headers should be medium size
* Bug Fix: Change date kit bold to title 4
* Bug Fix: Fix Rubocop offenses for kits
* Bug Fix: Remove Highcharts from Plugin
* Bug Fix: Fix Release Script
* Security Fix: Bump mixing-deep version from 1.3.1 to 1.3.2
* `vendor.js` for providing 3rd party global scope JS

Version bump 2.8.7

---

app/pb_kits/playbook/pb_pill/_pill.jsx
app/pb_kits/playbook/pb_pill/docs/_pill_default.jsx

Includes:
* Body react kit
* Pill react kit
Resolves Issue #224

Create Pill react kit

---

app/pb_kits/playbook/pb_body/_body.jsx
app/pb_kits/playbook/pb_dashboard_value/_dashboard_value.jsx
app/pb_kits/playbook/pb_dashboard_value/docs/_dashboard_value_align.jsx
app/pb_kits/playbook/pb_dashboard_value/docs/_dashboard_value_default.jsx
app/pb_kits/playbook/pb_dashboard_value/docs/example.yml
app/pb_kits/playbook/pb_dashboard_value/docs/index.js
app/pb_kits/playbook/pb_icon/_icon.jsx
app/pb_kits/playbook/pb_icon/docs/_icon_animate.jsx
app/pb_kits/playbook/pb_icon/docs/_icon_border.jsx
app/pb_kits/playbook/pb_icon/docs/_icon_default_dark.jsx
app/pb_kits/playbook/pb_icon/docs/_icon_flip.jsx
app/pb_kits/playbook/pb_icon/docs/_icon_pull.jsx
app/pb_kits/playbook/pb_icon/docs/_icon_rotate.jsx
app/pb_kits/playbook/pb_icon/docs/_icon_sizes.jsx
app/pb_kits/playbook/pb_icon/docs/example.yml
app/pb_kits/playbook/pb_icon/docs/index.js
app/pb_kits/playbook/pb_stat_change/_stat_change.jsx
app/pb_kits/playbook/pb_stat_change/docs/_stat_change_default.jsx
app/pb_kits/playbook/pb_stat_value/_stat_value.jsx
app/pb_kits/playbook/pb_stat_value/docs/_stat_value_default.jsx
app/pb_kits/playbook/pb_stat_value/docs/_stat_value_unit.jsx
app/pb_kits/playbook/pb_stat_value/docs/example.yml
app/pb_kits/playbook/pb_stat_value/docs/index.js

* Enables Dashboard Value react kit
* Enables Stat Value react kit
* Enables Stat Change react kit
* Enables Icon react kit
* Bug: Sets PbBody react kit default color to "default" instead of "light"
Also sets all documentation examples 1:1 between Rails and React for the above kits.
---

Enable Dashboard Value react kit

---

app/pb_kits/playbook/pb_button/_button_mixins.scss

Changes include:
* Change font-weight for button
---

Enhance Button font weight

---

app/pb_kits/playbook/packs/examples.js
app/pb_kits/playbook/packs/kits.js
app/pb_kits/playbook/packs/pb_checkbox.js
app/pb_kits/playbook/packs/site_styles/_kit_style_index.scss
app/pb_kits/playbook/pb_checkbox/_checkbox.html.erb
app/pb_kits/playbook/pb_checkbox/_checkbox.jsx
app/pb_kits/playbook/pb_checkbox/_checkbox.scss
app/pb_kits/playbook/pb_checkbox/checkbox.rb
app/pb_kits/playbook/pb_checkbox/docs/_checkbox_dark.html.erb
app/pb_kits/playbook/pb_checkbox/docs/_checkbox_default.html.erb
app/pb_kits/playbook/pb_checkbox/docs/_checkbox_default.jsx
app/pb_kits/playbook/pb_checkbox/docs/example.yml
app/pb_kits/playbook/pb_checkbox/docs/index.js
app/pb_kits/playbook/tokens/_transition.scss
config/data/menu.yml

checkbox kit 
props:
text,
dark

Create Checkbox Kit

---

app/pb_kits/playbook/packs/examples.js
app/pb_kits/playbook/packs/kits.js
app/pb_kits/playbook/packs/pb_loading_inline.js
app/pb_kits/playbook/packs/site_styles/_kit_style_index.scss
app/pb_kits/playbook/pb_loading_inline/_loading_inline.html.erb
app/pb_kits/playbook/pb_loading_inline/_loading_inline.jsx
app/pb_kits/playbook/pb_loading_inline/_loading_inline.scss
app/pb_kits/playbook/pb_loading_inline/docs/_loading_inline_dark.html.erb
app/pb_kits/playbook/pb_loading_inline/docs/_loading_inline_dark.jsx
app/pb_kits/playbook/pb_loading_inline/docs/_loading_inline_light.html.erb
app/pb_kits/playbook/pb_loading_inline/docs/_loading_inline_light.jsx
app/pb_kits/playbook/pb_loading_inline/docs/example.yml
app/pb_kits/playbook/pb_loading_inline/docs/index.js
app/pb_kits/playbook/pb_loading_inline/loading_inline.rb
config/data/menu.yml

This PR is the work done during UX session on 2019.9 Create. It implements Loading Inline kit for Rails.

Loading Inline kit implementation for Rails

---

app/pb_kits/playbook/packs/examples.js
app/pb_kits/playbook/packs/kits.js
app/pb_kits/playbook/packs/pb_home_address_street.js
app/pb_kits/playbook/packs/site_styles/_kit_style_index.scss
app/pb_kits/playbook/pb_home_address_street/_home_address_street.html.erb
app/pb_kits/playbook/pb_home_address_street/_home_address_street.jsx
app/pb_kits/playbook/pb_home_address_street/_home_address_street.scss
app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_dark.html.erb
app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_dark.jsx
app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_default.html.erb
app/pb_kits/playbook/pb_home_address_street/docs/_home_address_street_default.jsx
app/pb_kits/playbook/pb_home_address_street/docs/example.yml
app/pb_kits/playbook/pb_home_address_street/docs/index.js
app/pb_kits/playbook/pb_home_address_street/home_address_street.rb
config/data/menu.yml

Closes https://github.com/powerhome/playbook/issues/209

Create Home Address Street kit

---

app/pb_kits/playbook/index.js
app/pb_kits/playbook/kits/pb_hashtag.js
app/pb_kits/playbook/packs/examples.js
app/pb_kits/playbook/packs/kits.js
app/pb_kits/playbook/packs/pb_hashtag.js
app/pb_kits/playbook/packs/site_styles/_kit_style_index.scss
app/pb_kits/playbook/pb_hashtag/_hashtag.html.erb
app/pb_kits/playbook/pb_hashtag/_hashtag.jsx
app/pb_kits/playbook/pb_hashtag/_hashtag.scss
app/pb_kits/playbook/pb_hashtag/docs/_hashtag_default.html.erb
app/pb_kits/playbook/pb_hashtag/docs/_hashtag_default.jsx
app/pb_kits/playbook/pb_hashtag/docs/example.yml
app/pb_kits/playbook/pb_hashtag/docs/index.js
app/pb_kits/playbook/pb_hashtag/hashtag.rb
config/data/menu.yml

Created Hashtag Kit

---

.gitignore
spec/pb_kits/playbook/kits/caption_spec.rb
spec/pb_kits/playbook/kits/card_body_spec.rb
spec/pb_kits/playbook/kits/card_spec.rb
spec/pb_kits/playbook/kits/checkbox_spec.rb
spec/pb_kits/playbook/props/base_spec.rb
spec/pb_kits/playbook/props/boolean_spec.rb
spec/pb_kits/playbook/props/enum_spec.rb
spec/pb_kits/playbook/props/hash_spec.rb
spec/pb_kits/playbook/props_spec.rb
spec/spec_helper.rb

This PR applies test suite changes from comments proposed in #301 .

Reconfigure spec_helper & test assertions

---

app/pb_kits/playbook/pb_badge/_badge.html.erb
app/pb_kits/playbook/pb_badge/badge.rb
app/pb_kits/playbook/pb_badge/docs/_badge_colors.html.erb
spec/pb_kits/playbook/kits/badge_spec.rb

Live code demo on how to convert a kit into new format.

Modernize badge kit

---

package.json
yarn.lock

Yarn security fixes

---

app/pb_kits/playbook/pb_bar_graph/barGraphSettings.js
app/pb_kits/playbook/pb_dashboard/commonSettings.js
app/pb_kits/playbook/pb_line_graph/lineGraphSettings.js
app/pb_kits/playbook/tokens/_colors.scss

Used with https://github.com/powerhome/nitro-web/pull/12741
Go there for the description

Update Sisense Highcharts Styles and Bug Fixes

---

app/pb_kits/playbook/pb_hashtag/_hashtag.html.erb
app/pb_kits/playbook/pb_hashtag/hashtag.rb
spec/pb_kits/playbook/kits/hashtag_spec.rb

Brings Hashtag pb_kit up to our new standard convention with test spec
BAB 148

Modernize Hashtag

---

app/pb_kits/playbook/pb_home_address_street/_home_address_street.html.erb
app/pb_kits/playbook/pb_home_address_street/home_address_street.rb
app/pb_kits/playbook/props.rb
app/pb_kits/playbook/props/number.rb
spec/pb_kits/playbook/kits/home_address_street_spec.rb
spec/pb_kits/playbook/props/number_spec.rb

BAB149
Modernizes the pb kit to our new style

Modernize Home Address Street Playbook Kit

---

app/pb_kits/playbook/pb_button/_button.jsx
app/pb_kits/playbook/pb_button/docs/_button_default.jsx

Feel free to ignore the last commit from your [code review](https://github.com/powerhome/playbook/pull/329/commits/41066c4ef44f2827ef7ac9ea9a488eb42d476ab7) since it's just formatting changes.

Add on click handler support to React button.

---

app/pb_kits/playbook/pb_input/_input.html.erb
app/pb_kits/playbook/pb_input/_input.jsx
app/pb_kits/playbook/pb_input/_input.scss
app/pb_kits/playbook/pb_input/input.rb
config/data/menu.yml
spec/pb_kits/playbook/kits/input_spec.rb

Brings Input pb_kit up to our new standard convention with test spec
BAB 155

Modernize Input

---

app/pb_kits/playbook/tokens/_colors.scss

[Graph Demo](https://jsfiddle.net/jaot8Lws/)
```scss
$data_1:              $royal;
$data_2:              $yellow;
$data_3:              $purple;
$data_4:              $green;
$data_5:              $orange;
$data_6:              $active_dark;
$data_7:              $teal;
$data_8:              $red;
```
---

Data Color Update

---

lib/generators/kit/kit_generator.rb
lib/generators/kit/templates/kit_html.erb.tt
lib/generators/kit/templates/kit_ruby.erb.tt
lib/generators/kit/templates/kit_ruby_spec.erb.tt

And correct @import paths to match pattern in files they are appended to.

Update rails kit generation

---

app/pb_kits/playbook/pb_online_status/_online_status.html.erb
app/pb_kits/playbook/pb_online_status/online_status.rb
spec/pb_kits/playbook/kits/online_status_spec.rb

Modernize the Online Status Playbook kit

---

app/pb_kits/playbook/pb_pill/_pill.html.erb
app/pb_kits/playbook/pb_pill/pill.rb
spec/pb_kits/playbook/kits/pill_spec.rb

Modernize the pill playbook kit

Modernize Pill Kit

---

app/pb_kits/playbook/pb_toggle/_toggle.jsx
app/pb_kits/playbook/pb_toggle/docs/_toggle_accessibility.jsx
app/pb_kits/playbook/pb_toggle/docs/_toggle_data.jsx
app/pb_kits/playbook/pb_toggle/docs/_toggle_default.jsx
app/pb_kits/playbook/pb_toggle/docs/example.yml
app/pb_kits/playbook/pb_toggle/docs/index.js
app/pb_kits/playbook/types.js
app/pb_kits/playbook/utilities/props.js

**Note**
I've created a [utilities/props.js](app/pb_kits/playbook/utilities/props.js) with some helper functions that hopefully will make it easier to implement common playbook features moving forward (such as aria and data props, building the root css...).

Implement the React version of pb_toggle

---

app/helpers/playbook/pb_doc_helper.rb
app/pb_kits/playbook/pb_title/_title.html.erb
app/pb_kits/playbook/pb_title/title.rb
app/views/playbook/pages/kit_show.html.slim
app/views/playbook/pages/kits.html.slim
app/views/playbook/pages/tokens.html.slim
app/views/playbook/pages/tokens/_pb_doc_spacing.html.slim
app/views/playbook/pages/utilities.html.slim
app/views/playbook/pages/utilities/_pb_doc_color.html.slim
spec/pb_kits/playbook/kits/title_spec.rb

BAB-171
Modernize Title Playbook kit.

Modernize Title Playbook Kit

---

app/pb_kits/playbook/pb_progress_simple/_progress_simple.html.erb
app/pb_kits/playbook/pb_progress_simple/_progress_simple.scss
app/pb_kits/playbook/pb_progress_simple/progress_simple.rb
app/pb_kits/playbook/props.rb
app/pb_kits/playbook/props/percentage.rb
lib/playbook.rb
spec/pb_kits/playbook/kits/progress_simple_spec.rb
spec/pb_kits/playbook/props/percentage_spec.rb
spec/spec_helper.rb

BAB-162
Modernize ProgressSimple Playbook kit

Modernize ProgressSimple Playbook kit

---

app/pb_kits/playbook/pb_person/_person.html.erb
app/pb_kits/playbook/pb_person/person.rb
spec/pb_kits/playbook/kits/person_spec.rb

Modernize the Person Playbook kit
BAB-192

Modernize the Person Playbook Kit

---

app/pb_kits/playbook/pb_table/_table.html.erb
app/pb_kits/playbook/pb_table/_table.jsx
app/pb_kits/playbook/pb_table/docs/_table_container.html.erb
app/pb_kits/playbook/pb_table/docs/_table_container.jsx
app/pb_kits/playbook/pb_table/docs/_table_container_dark.html.erb
app/pb_kits/playbook/pb_table/docs/_table_container_dark.jsx
app/pb_kits/playbook/pb_table/docs/_table_dark.html.erb
app/pb_kits/playbook/pb_table/docs/_table_dark.jsx
app/pb_kits/playbook/pb_table/docs/_table_disable_hover.html.erb
app/pb_kits/playbook/pb_table/docs/_table_disable_hover.jsx
app/pb_kits/playbook/pb_table/docs/_table_lg.html.erb
app/pb_kits/playbook/pb_table/docs/_table_lg.jsx
app/pb_kits/playbook/pb_table/docs/_table_md.html.erb
app/pb_kits/playbook/pb_table/docs/_table_md.jsx
app/pb_kits/playbook/pb_table/docs/_table_multiline.html.erb
app/pb_kits/playbook/pb_table/docs/_table_multiline.jsx
app/pb_kits/playbook/pb_table/docs/_table_single_line.html.erb
app/pb_kits/playbook/pb_table/docs/_table_single_line.jsx
app/pb_kits/playbook/pb_table/docs/_table_sm.html.erb
app/pb_kits/playbook/pb_table/docs/_table_sm.jsx
app/pb_kits/playbook/pb_table/table.rb
app/pb_kits/playbook/props/base.rb
spec/pb_kits/playbook/kits/table_spec.rb

Modernize the table playbook kit

Modernize table kit

---

app/pb_kits/playbook/pb_contact/_contact.html.erb
app/pb_kits/playbook/pb_contact/contact.rb
spec/pb_kits/playbook/kits/contact_spec.rb

Modernize the playbook contact kit, refactor existing code, and add tests.

Modernize contact kit

---

app/pb_kits/playbook/pb_body/_body.html.erb
app/pb_kits/playbook/pb_body/body.rb
app/pb_kits/playbook/pb_person/_person.html.erb
app/pb_kits/playbook/props.rb
spec/pb_kits/playbook/kits/body_spec.rb

BAB-178
Modernize Body Playbook kit.

Modernize Body Playbook kit

---

app/pb_kits/playbook/pb_checkbox/_checkbox.html.erb
app/pb_kits/playbook/pb_checkbox/_checkbox.jsx
app/pb_kits/playbook/pb_checkbox/_checkbox.scss
app/pb_kits/playbook/pb_checkbox/checkbox.rb
app/pb_kits/playbook/pb_checkbox/docs/_checkbox_checked.html.erb
app/pb_kits/playbook/pb_checkbox/docs/_checkbox_dark.html.erb
app/pb_kits/playbook/pb_checkbox/docs/_checkbox_dark.jsx
app/pb_kits/playbook/pb_checkbox/docs/_checkbox_default.html.erb
app/pb_kits/playbook/pb_checkbox/docs/_checkbox_default.jsx
spec/pb_kits/playbook/kits/checkbox_spec.rb

Resolving issue here: https://github.com/powerhome/playbook/issues/341
utilizing Icon and Body Kits within the checkbox component

Fix Checkbox Position

---

app/pb_kits/playbook/pb_icon_circle/_icon_circle.html.erb
app/pb_kits/playbook/pb_icon_circle/icon_circle.rb
spec/pb_kits/playbook/kits/icon_circle_spec.rb

BAB-152 Modernize icon_circle playbook kit

Modernized icon_circle kit

---

app/pb_kits/playbook/pb_toggle/_toggle.html.erb
app/pb_kits/playbook/pb_toggle/toggle.rb
spec/pb_kits/playbook/kits/toggle_spec.rb

Modernizes the playbook toggle kit and adds appropriate specs

Modernize toggle kit

---

Gemfile.lock
lib/playbook/version.rb
package.json

* Modernized Body Kit @darrendc 
* Modernized Contact Kit @eabousaif 
* Modernized Fixed Confirmation Toast Kit @gillianwenhold 
* Modernized Icon Circle Kit @gillianwenhold 
* Modernized Icon Value Kit @KFad11 
* Modernized Image Kit @KFad11 
* Modernized Person Playbook Kit @darrendc 
* Modernized Source Kit @gillianwenhold 
* Modernized Table Kit @eabousaif 
* Modernized Toggle Kit @eabousaif 
* Enhanced Home Address Street Kit @kskilt @KFad11 
* Bug fix for Checkbox Kit @kre8sions

Release 2.9.5

---

app/pb_kits/playbook/pb_title_count/_title_count.html.erb
app/pb_kits/playbook/pb_title_count/docs/_title_count_default.html.erb
app/pb_kits/playbook/pb_title_count/title_count.rb
app/pb_kits/playbook/props.rb
app/pb_kits/playbook/props/numeric.rb
app/pb_kits/playbook/props/percentage.rb
spec/pb_kits/playbook/kits/title_count_spec.rb
spec/pb_kits/playbook/props/number_spec.rb
spec/pb_kits/playbook/props/numeric_spec.rb

Modernize TitleCount Playbook kit
BAB-172

Modernize TitleCount Playbook kit

---

app/pb_kits/playbook/pb_label_pill/_label_pill.html.erb
app/pb_kits/playbook/pb_label_pill/label_pill.rb
spec/pb_kits/playbook/kits/label_pill_spec.rb

Modernizing and creating a spec file for this kit. 
Currently WIP, just needed to get this up to check on my diff's.

Modernize Label Pill kit

---

app/pb_kits/playbook/pb_bar_graph/_bar_graph.html.erb
app/pb_kits/playbook/pb_bar_graph/bar_graph.rb
app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_default.html.erb
app/pb_kits/playbook/pb_line_graph/_line_graph.html.erb
app/pb_kits/playbook/pb_line_graph/docs/_line_graph_default.html.erb
app/pb_kits/playbook/pb_line_graph/line_graph.rb
spec/pb_kits/playbook/kits/bar_graph_spec.rb
spec/pb_kits/playbook/kits/line_graph_spec.rb

BAB-158: Modernize line graph kit
Note: Updated prop `point_start` for bar graph and line graph kits to a Numeric

Modernize line graph kit

---

app/pb_kits/playbook/pb_avatar/_avatar.html.erb
app/pb_kits/playbook/pb_avatar/avatar.rb
spec/pb_kits/playbook/kits/avatar_spec.rb

Modernize Avatar Kit 

---

app/pb_kits/playbook/pb_title_detail/_title_detail.html.erb
app/pb_kits/playbook/pb_title_detail/title_detail.rb
spec/pb_kits/playbook/kits/title_detail_spec.rb

BAB-173: Modernize title detail kit
Note: Title and detail are both required props, may cause backwards compatibility issues

Modernize title-detail kit

---

app/pb_kits/playbook/pb_label_value/_label_value.html.erb
app/pb_kits/playbook/pb_label_value/label_value.rb
spec/pb_kits/playbook/kits/label_value_spec.rb

BAB-157 Modernized label value playbook kit
Note: Label and value are both required props, may cause backwards compatibility issues

Modernize label value kit

---

app/pb_kits/playbook/pb_dashboard_value/docs/_dashboard_value_align.html.erb
app/pb_kits/playbook/pb_dashboard_value/docs/_dashboard_value_align.jsx
app/pb_kits/playbook/pb_dashboard_value/docs/_dashboard_value_default.html.erb
app/pb_kits/playbook/pb_dashboard_value/docs/_dashboard_value_default.jsx
app/pb_kits/playbook/pb_stat_change/_stat_change.html.erb
app/pb_kits/playbook/pb_stat_change/_stat_change.jsx
app/pb_kits/playbook/pb_stat_change/docs/_stat_change_default.html.erb
app/pb_kits/playbook/pb_stat_change/docs/_stat_change_default.jsx
app/pb_kits/playbook/pb_stat_change/stat_change.rb
spec/pb_kits/playbook/kits/stat_change_spec.rb

Modernize StatChange playbook kit

Modernize StatChange playbook kit

---

app/pb_kits/playbook/pb_caption/caption.rb
app/pb_kits/playbook/pb_section_separator/_section_separator.html.erb
app/pb_kits/playbook/pb_section_separator/section_separator.rb
spec/pb_kits/playbook/kits/caption_spec.rb
spec/pb_kits/playbook/kits/section_seperator_spec.rb

Modernize Section Separator playbook kit.

 Modernize SectionSeparator playbook kit

---

app/pb_kits/playbook/pb_button/_button.html.erb
app/pb_kits/playbook/pb_button/button.rb
spec/pb_kits/playbook/kits/button_spec.rb

Modernize the playbook button kit

Modernize button kit

---

app/pb_kits/playbook/pb_vertical_nav/_item.html.erb
app/pb_kits/playbook/pb_vertical_nav/_vertical_nav.html.erb
app/pb_kits/playbook/pb_vertical_nav/item.rb
app/pb_kits/playbook/pb_vertical_nav/vertical_nav.rb
spec/pb_kits/playbook/kits/vertical_nav_item_spec.rb
spec/pb_kits/playbook/kits/vertical_nav_spec.rb

BAB-177: Modernize VerticalNav/VerticalNavItem Playbook kit(s).

Modernize vertical nav

---

app/pb_kits/playbook/pb_list/_item.html.erb
app/pb_kits/playbook/pb_list/_list.html.erb
app/pb_kits/playbook/pb_list/item.rb
app/pb_kits/playbook/pb_list/list.rb
spec/pb_kits/playbook/kits/item_spec.rb
spec/pb_kits/playbook/kits/list_spec.rb

Modernize both the list kit and the item kit and add specs

Modernize List Item kit

---

app/pb_kits/playbook/pb_timestamp/_timestamp.html.erb
app/pb_kits/playbook/pb_timestamp/timestamp.rb
spec/pb_kits/playbook/kits/timestamp_spec.rb

Modernize the Timestamp kit and add spec files

Modernize timestamp kit

---

app/pb_kits/playbook/pb_user_badge/_user_badge.html.erb
app/pb_kits/playbook/pb_user_badge/user_badge.rb
spec/pb_kits/playbook/kits/user_badge_spec.rb

Modernize the User Badge kit and create spec file

Modernize User Badge Kit

---

app/pb_kits/playbook/pb_layout/_body.html.erb
app/pb_kits/playbook/pb_layout/_layout.html.erb
app/pb_kits/playbook/pb_layout/_sidebar.html.erb
app/pb_kits/playbook/pb_layout/body.rb
app/pb_kits/playbook/pb_layout/layout.rb
app/pb_kits/playbook/pb_layout/sidebar.rb
spec/pb_kits/playbook/kits/layout_spec.rb

BAB-235: Modernize Playbook Layout/LayoutBody/LayoutSidebar kit(s)

Modernize layout kit

---

app/pb_kits/playbook/pb_message/_message.html.erb
app/pb_kits/playbook/pb_message/docs/_message_default.html.erb
app/pb_kits/playbook/pb_message/message.rb
app/pb_kits/playbook/pb_user/_user.html.erb
spec/pb_kits/playbook/kits/message_spec.rb

Modernize the message kit and write spec file

Modernize Message Kit

---

app/pb_kits/playbook/pb_contact/_contact.html.erb
app/pb_kits/playbook/pb_contact/_contact.jsx
app/pb_kits/playbook/pb_contact/contact.rb
app/pb_kits/playbook/pb_contact/docs/_contact_default.html.erb
app/pb_kits/playbook/pb_person_contact/_person_contact.html.erb
app/pb_kits/playbook/pb_person_contact/docs/_person_contact_default.html.erb
app/pb_kits/playbook/pb_person_contact/person_contact.rb

Adds a wrong tag to contacts so that we can display them differently than the other contacts.

Add "wrong" tag to contacts

---

app/pb_kits/playbook/pb_time/_time.html.erb
app/pb_kits/playbook/pb_time/time.rb
spec/pb_kits/playbook/kits/time_spec.rb

BAB-169
Modernize Time Playbook kit

Modernize Time Playbook kit

---

app/pb_kits/playbook/pb_date_year_stacked/_date_year_stacked.html.erb
app/pb_kits/playbook/pb_date_year_stacked/date_year_stacked.rb
spec/pb_kits/playbook/kits/date_year_stacked_spec.rb

BAB-234: Modernize DateYearStacked Playbook kit.

Modernize Date Year Stacked 

---

app/pb_kits/playbook/pb_date/_date.html.erb
app/pb_kits/playbook/pb_date/date.rb
spec/pb_kits/playbook/kits/date.rb
spec/pb_kits/playbook/kits/date_spec.rb

Modernize date kit

---

app/pb_kits/playbook/pb_avatar/_avatar.jsx
app/pb_kits/playbook/pb_multiple_users/_multiple_users.html.erb
app/pb_kits/playbook/pb_multiple_users/_multiple_users.jsx
app/pb_kits/playbook/pb_multiple_users/_multiple_users.scss
app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_default.html.erb
app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_default.jsx
app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_reverse.html.erb
app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_reverse.jsx
app/pb_kits/playbook/pb_multiple_users/docs/example.yml
app/pb_kits/playbook/pb_multiple_users/docs/index.js
app/pb_kits/playbook/pb_multiple_users/multiple_users.rb
spec/pb_kits/playbook/kits/multiple_users_spec.rb

Changes:
* Rails and React props are not consistent - **We need to check for breaking changes**
* React prop `url` was updated to `image_url` to match rails.
* React status was `online` by default, Rails is not shown. Updated React Kit to not show status by default.
---
* Moved logic to class level
---
* Created React kit that matches Rails kit
---
* Updated SCSS to use variables
* Updated SCSS to use margin instead of transform to fix spacing issues
* Updated offset to match Sketch design
---
* Updated doc files to be consistent between Rails and React
---
* Created spec test for kit

Multiple Users Kit - Support Branch

---

app/pb_kits/playbook/pb_dashboard_value/_dashboard_value.jsx
app/pb_kits/playbook/pb_dashboard_value/docs/_dashboard_value_align.jsx
app/pb_kits/playbook/pb_dashboard_value/docs/_dashboard_value_default.jsx

- `stat_label` should be `statLabel`
- `stat_change` should be `statChange`

Fix underscored DashboardValue props

---

app/pb_kits/playbook/pb_avatar/_avatar.jsx
app/pb_kits/playbook/pb_avatar/docs/_avatar_default.jsx

Ensures the same prop name is provided with the proper field label format.

Correct prop name format imageUrl

---

app/pb_kits/playbook/pb_message/_message.jsx
app/pb_kits/playbook/pb_message/docs/_message_default.jsx

Message React Kit Created

---

app/pb_kits/playbook/pb_dashboard_value/_dashboard_value.html.erb
app/pb_kits/playbook/pb_dashboard_value/dashboard_value.rb

Fix Dashboard Value Kit

---

app/pb_kits/playbook/index.js
app/pb_kits/playbook/pb_date/_date.jsx
app/pb_kits/playbook/pb_date/docs/_date_default.jsx
app/pb_kits/playbook/pb_kit/dateTime.js

Add jsx support for Date kit

---

app/pb_kits/playbook/pb_card/docs/_card_separator.html.erb
app/pb_kits/playbook/pb_card/docs/example.yml

Need code review to make sure it's legit!!

Created Card Separater as Kit

---

CHANGELOG.md
README.md
docs/upgrade-guide.md
spec/changelog_spec.rb

Adds CHANGELOG as described in https://keepachangelog.com/en/1.0.0/

Add changelog and upgrade_guide

---

app/pb_kits/playbook/pb_card/_card.jsx

Fixes the classname concatenation error that is happening inside the Card kit.

Fix For Null Classname

---

CHANGELOG.md
spec/changelog_spec.rb

I broke CI https://ci.powerhrg.com/blue/organizations/jenkins/powerhome%2Fplaybook/detail/master/323/pipeline

[Fixes CI on master] Don't check for CHANGELOG changes if there aren't changed files

---

CHANGELOG.md
app/pb_kits/playbook/pb_text_input/_text_input.html.erb
app/pb_kits/playbook/pb_text_input/_text_input.jsx
app/pb_kits/playbook/pb_text_input/_text_input.scss
app/pb_kits/playbook/pb_text_input/docs/_text_input_dark.html.erb
app/pb_kits/playbook/pb_text_input/docs/_text_input_dark.jsx
app/pb_kits/playbook/pb_text_input/docs/example.yml
app/pb_kits/playbook/pb_text_input/docs/index.js
app/pb_kits/playbook/pb_text_input/text_input.rb
app/pb_kits/playbook/pb_textarea/_textarea_mixin.scss
spec/pb_kits/playbook/kits/text_input_spec.rb

-Added Dark version of Text Input
-Revised Text Input to use Textarea mixins and follow Sketch design
-Moved over OnChange function from Home Tour React Kits
~~*Currently experiencing an eslint error that needs to be fixed.*~~

Text Input (Dark Mode & Updates)

---

CHANGELOG.md

Updated the changelog to reflect the fixes.

Card kit null class fix

---

CHANGELOG.md
app/pb_kits/playbook/pb_text_input/_text_input.scss

Text Input padding override was removed for input child

---

app/pb_kits/playbook/pb_message/_message.jsx

Change from `class` to `className` in a react component.

Fix class property on react component

---

CHANGELOG.md
app/pb_kits/playbook/tokens/_border_radius.scss
app/pb_kits/playbook/tokens/_colors.scss
app/pb_kits/playbook/tokens/_line_height.scss
app/pb_kits/playbook/tokens/_opacity.scss
app/pb_kits/playbook/tokens/_positioning.scss
app/pb_kits/playbook/tokens/_screen_sizes.scss
app/pb_kits/playbook/tokens/_shadows.scss
app/pb_kits/playbook/tokens/_spacing.scss

Added exports for border-radius, line-height, opacity, z-index, breakpoints, shadows, and spacing  + updated the correct gradient colors
NA
NA

Added exports for Sass exports, and color gradient updates

---

CHANGELOG.md
app/pb_kits/playbook/pb_caption/_caption_mixin.scss
app/pb_kits/playbook/pb_table/_table.jsx
app/pb_kits/playbook/pb_table/docs/_table_container.html.erb
app/pb_kits/playbook/pb_table/docs/_table_container.jsx
app/pb_kits/playbook/pb_table/docs/_table_container_dark.html.erb
app/pb_kits/playbook/pb_table/docs/_table_container_dark.jsx
app/pb_kits/playbook/pb_table/docs/_table_dark.html.erb
app/pb_kits/playbook/pb_table/docs/_table_dark.jsx
app/pb_kits/playbook/pb_table/docs/_table_data_table.html.erb
app/pb_kits/playbook/pb_table/docs/_table_data_table.jsx
app/pb_kits/playbook/pb_table/docs/_table_disable_hover.html.erb
app/pb_kits/playbook/pb_table/docs/_table_disable_hover.jsx
app/pb_kits/playbook/pb_table/docs/_table_lg.html.erb
app/pb_kits/playbook/pb_table/docs/_table_lg.jsx
app/pb_kits/playbook/pb_table/docs/_table_md.html.erb
app/pb_kits/playbook/pb_table/docs/_table_md.jsx
app/pb_kits/playbook/pb_table/docs/_table_multiline.html.erb
app/pb_kits/playbook/pb_table/docs/_table_multiline.jsx
app/pb_kits/playbook/pb_table/docs/_table_single_line.html.erb
app/pb_kits/playbook/pb_table/docs/_table_single_line.jsx
app/pb_kits/playbook/pb_table/docs/_table_sm.html.erb
app/pb_kits/playbook/pb_table/docs/_table_sm.jsx
app/pb_kits/playbook/pb_table/docs/example.yml
app/pb_kits/playbook/pb_table/docs/index.js
app/pb_kits/playbook/pb_table/styles/_hover.scss
app/pb_kits/playbook/pb_table/styles/_structure.scss
app/pb_kits/playbook/pb_table/styles/_table-card.scss
app/pb_kits/playbook/pb_table/table.rb
spec/pb_kits/playbook/kits/table_spec.rb

1. This increases the contrast for captions to improve readability
2. The table docs have been corrected to reflect the default props
3. Fixed broken border-radius for tables
4. Added data-table option for cases where we want to display lots of data with very tight spacing
Test that existing tables function as expected.
See the darker caption-text used throughout all the kits

Table Readability Enhancements

---

Jenkinsfile
bin/deploy
config/deploy/templates/deployment.yaml.erb

https://nitro.powerhrg.com/runway/backlog_items/GOG-19
N/A
N/A

[GOG-19] Upgrades from kubernetes-deploy to krane

---

CHANGELOG.md
app/pb_kits/playbook/pb_icon_value/_icon_value.jsx
app/pb_kits/playbook/pb_icon_value/docs/_icon_value_default.jsx

Implement the React version of the icon value kit.
This PR **has no** breaking changes

Implement React version of IconValue kit

---

.lintstagedrc
CHANGELOG.md
package.json
yarn.lock

Run eslint autofix on pre commit hook

---

CHANGELOG.md
app/pb_kits/playbook/pb_radio/_radio.jsx
app/pb_kits/playbook/pb_radio/docs/_radio_custom.html.erb
app/pb_kits/playbook/pb_radio/docs/_radio_custom.jsx
app/pb_kits/playbook/pb_radio/docs/_radio_dark.jsx
app/pb_kits/playbook/pb_radio/docs/_radio_default.jsx

https://nitro.powerhrg.com/runway/backlog_items/NUX-516

Fixed radio bug in docs

---

CHANGELOG.md
app/pb_kits/playbook/pb_select/_select.scss

https://nitro.powerhrg.com/runway/backlog_items/NUX-520

Select bug fix

---

CHANGELOG.md
app/pb_kits/playbook/pb_card/card.rb
app/pb_kits/playbook/pb_card/docs/_card_highlight.html.erb
app/pb_kits/playbook/pb_card/docs/_card_shadow.html.erb
app/pb_kits/playbook/tokens/_colors.scss
app/pb_kits/playbook/tokens/_shadows.scss
app/views/playbook/pages/utilities.html.slim

- ✅ **SPECS** Please cover your changes with specs
- ✅ **CHANGELOG** Please add an entry on `[Unreleased]` section to every functionality `ADDED`/`CHANGED`/`DEPRECATED`/`REMOVED`/`FIXED`

Shadows Updates

---

CHANGELOG.md
app/pb_kits/playbook/pb_radio/_radio.jsx
app/pb_kits/playbook/pb_radio/_radio.scss
app/pb_kits/playbook/pb_radio/docs/_radio_dark_error.html.erb
app/pb_kits/playbook/pb_radio/docs/_radio_dark_error.jsx
app/pb_kits/playbook/pb_radio/docs/_radio_error.html.erb
app/pb_kits/playbook/pb_radio/docs/_radio_error.jsx
app/pb_kits/playbook/pb_radio/docs/example.yml
app/pb_kits/playbook/pb_radio/docs/index.js
app/pb_kits/playbook/pb_radio/radio.rb
spec/pb_kits/playbook/kits/radio_spec.rb

https://nitro.powerhrg.com/runway/backlog_items/NUX-557
None

Add error state to Radio kit

---

CHANGELOG.md
app/pb_kits/playbook/pb_body/_body_mixins.scss
app/pb_kits/playbook/pb_checkbox/_checkbox.html.erb
app/pb_kits/playbook/pb_checkbox/_checkbox.jsx
app/pb_kits/playbook/pb_checkbox/_checkbox.scss
app/pb_kits/playbook/pb_checkbox/checkbox.rb
app/pb_kits/playbook/pb_checkbox/docs/_checkbox_dark_error.html.erb
app/pb_kits/playbook/pb_checkbox/docs/_checkbox_dark_error.jsx
app/pb_kits/playbook/pb_checkbox/docs/_checkbox_error.html.erb
app/pb_kits/playbook/pb_checkbox/docs/_checkbox_error.jsx
app/pb_kits/playbook/pb_checkbox/docs/example.yml
app/pb_kits/playbook/pb_checkbox/docs/index.js
spec/pb_kits/playbook/kits/checkbox_spec.rb

https://nitro.powerhrg.com/runway/backlog_items/NUX-558
None

Add error state to Checkbox kit

---

app/pb_kits/playbook/_playbook.scss
app/pb_kits/playbook/index.js
app/pb_kits/playbook/packs/examples.js
app/pb_kits/playbook/pb_enhanced_element/element_observer.js
app/pb_kits/playbook/pb_enhanced_element/index.js
app/pb_kits/playbook/pb_list/_item.html.erb
app/pb_kits/playbook/pb_list/_list.html.erb
app/pb_kits/playbook/pb_list/item.rb
app/pb_kits/playbook/pb_list/list.rb
app/pb_kits/playbook/pb_typeahead/_typeahead.html.erb
app/pb_kits/playbook/pb_typeahead/_typeahead.scss
app/pb_kits/playbook/pb_typeahead/docs/_typeahead_default.html.erb
app/pb_kits/playbook/pb_typeahead/docs/example.yml
app/pb_kits/playbook/pb_typeahead/index.js
app/pb_kits/playbook/pb_typeahead/typeahead.rb
config/data/menu.yml
spec/pb_kits/playbook/pb_typeahead/typeahead_spec.rb

[BOP-325](https://nitro.powerhrg.com/runway/backlog_items/BOP-325)
None

Typeahead kit

---

CHANGELOG.md
app/pb_kits/playbook/pb_currency/_currency.html.erb
app/pb_kits/playbook/pb_currency/_currency.jsx
app/pb_kits/playbook/pb_currency/_currency.scss
app/pb_kits/playbook/pb_currency/currency.rb
app/pb_kits/playbook/pb_currency/docs/_currency_default.jsx
app/pb_kits/playbook/pb_currency/docs/_currency_large.html.erb
app/pb_kits/playbook/pb_currency/docs/_currency_large.jsx
app/pb_kits/playbook/pb_currency/docs/_currency_small.html.erb
spec/changelog_spec.rb
spec/pb_kits/playbook/pb_currency/currency_spec.rb

Ticket: https://nitro.powerhrg.com/runway/backlog_items/BOLT-49
By making the component a little smarter, users no longer have to worry about spitting units/decimal parts of the amount value in order to fulfill the props.
Before
After
This PR **does introduce** changes to the component's API (a.k.a props).
**Rails**
**React**
As far as `nitro-web` goes, there won't be breaking changes since no one is using this component yet. @powerhome/ux-team is it possible this component is being used in other applications?

[BOLT-49] Modernize and improve the Currency kit

---

CHANGELOG.md
app/pb_kits/playbook/pb_form/form_builder.rb
app/pb_kits/playbook/pb_form/form_builder/typeahead_field.rb
app/pb_kits/playbook/pb_typeahead/_typeahead.html.erb
app/pb_kits/playbook/pb_typeahead/_typeahead.scss
app/pb_kits/playbook/pb_typeahead/docs/_typeahead_default.html.erb
app/pb_kits/playbook/pb_typeahead/typeahead.rb
spec/pb_kits/playbook/pb_currency/currency_spec.rb
spec/pb_kits/playbook/pb_typeahead/typeahead_spec.rb

Enable label and name for Typeahead kit

---

CHANGELOG.md
app/pb_kits/playbook/pb_typeahead/_typeahead.html.erb
app/pb_kits/playbook/pb_typeahead/typeahead.rb
spec/pb_kits/playbook/pb_typeahead/typeahead_spec.rb

Allow Typeahead to accept value prop

---

CHANGELOG.md
Gemfile.lock
app/pb_kits/playbook/pb_popover/_popover.html.erb
app/pb_kits/playbook/pb_popover/_popover.js
app/pb_kits/playbook/pb_popover/_popover.scss
lib/playbook/version.rb
package.json

Adds instance ref for Popper within Popover kit for calling update on show for proper positioning. 
N/A
None

Call update method on Popper instance

---

CHANGELOG.md
Gemfile.lock
app/pb_kits/playbook/pb_popover/_popover.js
lib/playbook/version.rb
package.json

Fix popover close on body click

---

CHANGELOG.md
app/pb_kits/playbook/pb_form/form/form_with_form.rb
app/pb_kits/playbook/pb_form/form/simple_form_form.rb

Fixes an issue with `form_system_options` merging in `data` props
None
1. Go to dev docs and check form kit is working
1. Visit Runway and ensure form is working as expected

Fix Form kit data prop merge

---

CHANGELOG.md
app/pb_kits/playbook/pb_popover/_popover.scss

N/A
N/A
1. Inspect dev docs for popover
2. View corporate directory search filters

Fix z-index on popover

---

CHANGELOG.md
Gemfile.lock
app/helpers/playbook/redcarpet_helper.rb
app/pb_kits/playbook/config/_kit_ui.html.slim
playbook_ui.gemspec

Bump to latest rouge + officially support React syntax highlight

---

Dockerfile

Fixes the javascript heap memory limit error that is breaking hot-reloading and messing up our compilations.

Fix For Javascript Heap Error

---

CHANGELOG.md
app/pb_kits/playbook/pb_date_stacked/_date_stacked.jsx
app/pb_kits/playbook/pb_date_stacked/docs/_date_stacked_not_current_year.jsx

Reverts powerhome/playbook#592

Revert "Ignore timezone on DateStacked"

---

CHANGELOG.md
Jenkinsfile
app/pb_kits/playbook/index.js
app/pb_kits/playbook/packs/examples.js
app/pb_kits/playbook/packs/kits/pb_popover.js
app/pb_kits/playbook/pb_popover/_popover.html.erb
app/pb_kits/playbook/pb_popover/_popover.js
app/pb_kits/playbook/pb_popover/_popover.jsx
app/pb_kits/playbook/pb_popover/_popover.scss
app/pb_kits/playbook/pb_popover/docs/_popover_default.jsx
app/pb_kits/playbook/pb_popover/docs/_popover_list.jsx
app/pb_kits/playbook/pb_popover/docs/_popover_portal.jsx
app/pb_kits/playbook/pb_popover/docs/_popover_with_button.jsx
app/pb_kits/playbook/pb_popover/docs/example.yml
app/pb_kits/playbook/pb_popover/docs/index.js
app/pb_kits/playbook/pb_popover/popover.rb
app/pb_kits/playbook/vendor.js
package.json
yarn.lock

https://nitro.powerhrg.com/runway/backlog_items/NUX-600
- Renamed vanilla JS version of `Popover` to `PbPopover` to help prevent collision
1. Go to dev docs PB page and ensure that Popover is working
1. Check out the Corporate Directory page and ensure that the search filters popover is working

React Popover kit!

---

CHANGELOG.md
app/helpers/playbook/pb_doc_helper.rb
app/pb_kits/playbook/config/_kit_ui.html.slim

Added a check for rouge in the kit_ui slim file.
Changed the doc helper file to look for menu.yml

Fixes for dev doc kits

---

app/controllers/playbook/application_controller.rb
app/controllers/playbook/pages_controller.rb
app/controllers/playbook/samples_controller.rb
app/helpers/playbook/pb_sample_helper.rb
app/pb_kits/playbook/config/_kit_example.html.slim
app/pb_kits/playbook/config/_kit_samples_list.html.erb
app/pb_kits/playbook/config/_kit_ui.html.slim
app/pb_kits/playbook/data/menu.yml
app/pb_kits/playbook/packs/main.scss
app/pb_kits/playbook/packs/samples.js
app/pb_kits/playbook/packs/site_styles/_samples.scss
app/pb_kits/playbook/packs/site_styles/_site-style.scss
app/pb_kits/playbook/pb_editor/_editor.html.erb
app/views/layouts/playbook/samples.html.erb
app/views/playbook/pages/principles.html.slim
app/views/playbook/samples/dashboards/dashboards.html.erb
app/views/playbook/samples/dashboards/dashboards.jsx
app/views/playbook/samples/sample_show.html.erb
config/routes.rb
config/webpack/environment.js

Full page examples

---

CHANGELOG.md
app/pb_kits/playbook/pb_popover/_popover.html.erb
app/pb_kits/playbook/pb_popover/_popover.js
app/pb_kits/playbook/pb_popover/docs/_popover_with_button.jsx
app/pb_kits/playbook/pb_popover/popover.rb

N/A 
none
1. View popover kits on dev docs in Nitro

Correct popover offset docs

---

CHANGELOG.md
app/pb_kits/playbook/data/menu.yml

Fixed stat change typo in yml file

---

Gemfile.lock
app/pb_kits/playbook/vendor.js
lib/playbook/version.rb
package.json

N/A
N/A
Fixes Popover not working. Inspect dev docs page.

Add PbPopover init back to vendor.js

---

CHANGELOG.md
app/pb_kits/playbook/pb_layout/_layout.scss
app/pb_kits/playbook/pb_layout/_layout_mixin.scss

Fixes [`SassC::SyntaxError: Error: Invalid CSS after ...` error during asset pre-compilation for consuming applications](https://github.com/sass/sassc-rails/issues/97).
No
N/A

Fix Layout Kit SCSS

---

app/pb_kits/playbook/data/menu.yml
app/pb_kits/playbook/pb_editor/_editor.html.erb

This removes a couple of stale files that accidentally made their way into Master.

Removed Stale Editor Kit

---

app/pb_kits/playbook/pb_icon_value/docs/_description.md
app/pb_kits/playbook/pb_image/docs/_description.md
app/pb_kits/playbook/pb_layout/docs/_description.md
app/pb_kits/playbook/pb_list/docs/_description.md
app/pb_kits/playbook/pb_loading_inline/docs/_description.md
app/pb_kits/playbook/pb_multiple_users/docs/_description.md
app/pb_kits/playbook/pb_multiple_users_stacked/docs/_description.md
app/pb_kits/playbook/pb_nav/docs/_description.md
app/pb_kits/playbook/pb_online_status/docs/_description.md
app/pb_kits/playbook/pb_pill/docs/_description.md
app/pb_kits/playbook/pb_popover/docs/_description.md
app/pb_kits/playbook/pb_progress_pills/docs/_description.md

Group 3 docs with picture previews below.

Docs Group 3

---

CHANGELOG.md
app/pb_kits/playbook/config/_kit_ui.html.erb
app/pb_kits/playbook/packs/application.js
app/pb_kits/playbook/packs/site_styles/_samples.scss
app/pb_kits/playbook/packs/site_styles/docs/_kit_doc.scss
app/pb_kits/playbook/pb_typeahead/_typeahead.scss

Fix for filterkit popover and loader position

---

CHANGELOG.md
app/pb_kits/playbook/pb_filter/templates/_default.html.erb
app/pb_kits/playbook/pb_filter/templates/_single.html.erb

Fix Filter variants to look for link prop in sort_menu

---

CHANGELOG.md
app/pb_kits/playbook/pb_currency/_currency.scss

https://nitro.powerhrg.com/runway/backlog_items/NUX-733

Fix line-height in currency.scss for collision with Nitro

---

CHANGELOG.md
app/pb_kits/playbook/pb_table/styles/_reset.scss

Table Header Left Alignment Fix

---

CHANGELOG.md
app/pb_kits/playbook/pb_bar_graph/_bar_graph.jsx
app/pb_kits/playbook/pb_bar_graph/bar_graph.rb
app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_default.html.erb
app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_default.jsx
app/pb_kits/playbook/pb_line_graph/_line_graph.jsx
app/pb_kits/playbook/pb_line_graph/docs/_line_graph_default.html.erb
app/pb_kits/playbook/pb_line_graph/docs/_line_graph_default.jsx
app/pb_kits/playbook/pb_line_graph/line_graph.rb
app/pb_kits/playbook/plugins/pb_chart.js

Add props to bar chart and line chart for :
**x axis:**
_categories_
**y axis:**
_min_
_max_

Add Props to bar & line graph

---

Jenkinsfile

Use the Gotham cluster to run builds if it's available; we're not restricted to just HQ.

Run CI builds on any available cluster

---

CHANGELOG.md
app/pb_kits/playbook/pb_select/_select.scss
app/pb_kits/playbook/pb_text_input/_text_input.scss
app/pb_kits/playbook/pb_textarea/_textarea.jsx
app/pb_kits/playbook/pb_textarea/_textarea.scss
app/pb_kits/playbook/pb_textarea/_textarea_mixin.scss
app/pb_kits/playbook/pb_textarea/docs/_textarea_resize.html.erb
app/pb_kits/playbook/pb_textarea/docs/_textarea_resize.jsx
app/pb_kits/playbook/pb_textarea/docs/example.yml
app/pb_kits/playbook/pb_textarea/docs/index.js
app/pb_kits/playbook/pb_textarea/textarea.rb

Added resize option to textarea

---

CHANGELOG.md
app/pb_kits/playbook/pb_textarea/docs/_textarea_resize.jsx
spec/pb_kits/playbook/kits/textarea_spec.rb
spec/pb_kits/playbook/pb_currency/currency_spec.rb

Fixed Lint Errors So Builds won't Fail

---

CHANGELOG.md
app/pb_kits/playbook/pb_text_input/text_input.rb

https://nitro.powerhrg.com/runway/backlog_items/NUX-738
None
N/A

Prevent empty pattern attribute on Text Input kit

---

CHANGELOG.md
app/pb_kits/playbook/pb_label_value/_label_value.jsx
app/pb_kits/playbook/pb_label_value/_label_value.scss
app/pb_kits/playbook/pb_label_value/docs/_label_value_dark.html.erb
app/pb_kits/playbook/pb_label_value/docs/_label_value_dark.jsx
app/pb_kits/playbook/pb_label_value/docs/example.yml
app/pb_kits/playbook/pb_label_value/docs/index.js
app/pb_kits/playbook/pb_label_value/label_value.rb
spec/pb_kits/playbook/kits/label_value_spec.rb

https://nitro.powerhrg.com/runway/backlog_items/NUX-777

Added react and dark version for Label Value Kit

---

CHANGELOG.md
app/pb_kits/playbook/pb_icon/_icon.jsx

None
There are no usages as of today of this handler in Nitro.

Add onclick handler to icon

---

CHANGELOG.md
app/pb_kits/playbook/pb_icon/_icon.jsx

Reverts powerhome/playbook#691

Revert "Add onclick handler to icon"

---

app/pb_kits/playbook/tokens/_colors.scss
app/views/playbook/pages/utilities.html.slim

1. Added attic insulation and used $red as color.
2. Changed Roofing color to $slate.
3. Changed Doors color to $teal.

Made color changes to products

---

milano.yml

The goal is for Playbook PR's to deploy review instances.

[GOG-162] Adding Milano config to deploy PR environments

---

Gemfile.lock

Use CI supported version of Bundler.

Use supported version of Bundler

---

CHANGELOG.md
app/pb_kits/playbook/pb_online_status/_online_status.jsx
app/pb_kits/playbook/pb_online_status/docs/_online_status_default.jsx
app/pb_kits/playbook/pb_online_status/docs/example.yml
app/pb_kits/playbook/pb_online_status/docs/index.js

#221
No breaking changes because this is an additive change.

Add react online status kit

---

CHANGELOG.md
app/pb_kits/playbook/pb_bar_graph/_bar_graph.jsx
app/pb_kits/playbook/pb_bar_graph/bar_graph.rb
app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_default.html.erb
app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_default.jsx
app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_height.html.erb
app/pb_kits/playbook/pb_bar_graph/docs/_bar_graph_height.jsx
app/pb_kits/playbook/pb_bar_graph/docs/_description.md
app/pb_kits/playbook/pb_bar_graph/docs/example.yml
app/pb_kits/playbook/pb_bar_graph/docs/index.js
app/pb_kits/playbook/pb_line_graph/_line_graph.jsx
app/pb_kits/playbook/pb_line_graph/docs/_description.md
app/pb_kits/playbook/pb_line_graph/docs/_line_graph_default.html.erb
app/pb_kits/playbook/pb_line_graph/docs/_line_graph_default.jsx
app/pb_kits/playbook/pb_line_graph/docs/_line_graph_height.html.erb
app/pb_kits/playbook/pb_line_graph/docs/_line_graph_height.jsx
app/pb_kits/playbook/pb_line_graph/docs/example.yml
app/pb_kits/playbook/pb_line_graph/docs/index.js
app/pb_kits/playbook/pb_line_graph/line_graph.rb
app/pb_kits/playbook/plugins/pb_chart.js

**Bar Graph Kit**
**Line Graph Kit**
No breaking changes.
https://nitro.powerhrg.com/runway/backlog_items/NUX-953

Added height prop to Bar Graph Kit and Line Graph Kit

---

CHANGELOG.md
app/pb_kits/playbook/pb_currency/_currency.html.erb
app/pb_kits/playbook/pb_currency/currency.rb

Fixes https://github.com/powerhome/playbook/issues/797
N/A
https://nitro.powerhrg.com/runway/backlog_items/NUX-999 
~~**SPECS** Please cover your changes with specs~~

Fix currency kit performance (Rails)

---

CHANGELOG.md
app/pb_kits/playbook/pb_source/_source.jsx
app/pb_kits/playbook/pb_source/docs/_source_default.html.erb
app/pb_kits/playbook/pb_source/docs/_source_default.jsx
app/pb_kits/playbook/pb_source/docs/_source_noicon.jsx
app/pb_kits/playbook/pb_source/docs/_source_types.jsx
app/pb_kits/playbook/pb_source/docs/example.yml
app/pb_kits/playbook/pb_source/docs/index.js

Source kit for React

---

README.md

Simple `README.md` update. No `CHANGELOG.md` entry needed.

There is no db in playbook anymore

---

app/pb_kits/playbook/pb_card/_card.jsx

This allow a card to have conditionals within it. I.e.:
```js
<Card>
<If condition={something}>
{'something here'}
</If>
</Card>
```
When the condition is not satisfied, `<If>` produces a `null` child.

Allow null child element on Card kit

---

CHANGELOG.md
app/pb_kits/playbook/pb_logistic/_logistic.html.erb
app/pb_kits/playbook/pb_logistic/_logistic.jsx

React Logistic kit was missing className, data, aria, id props and Rails Logistic kit was missing aria props.
NOTE: This PR replaces #843
REACT
RAILS
None

Add className, id, aria, data props React Logistic kit and aria to Rails Logistic kit

---

CHANGELOG.md
app/pb_kits/playbook/pb_person_contact/_person_contact.html.erb
app/pb_kits/playbook/pb_person_contact/_person_contact.jsx
app/pb_kits/playbook/pb_person_contact/docs/_person_contact_with_wrong_numbers.jsx
app/pb_kits/playbook/pb_person_contact/docs/example.yml
app/pb_kits/playbook/pb_person_contact/docs/index.js

React Person Contact kit was missing data, id, aria props and also missing the _person_contract_with_wrong_numbers.jsx file. Rails Person Contact kit was missing aria props.
REACT
RAILS
None

Add aria, data, id props & wrong number file to React PersonContact kit

---

CHANGELOG.md
renovate.json

No
No
https://nitro.powerhrg.com/runway/backlog_items/NUX-984
You can't.
- ~~**SCREENSHOT** Please add a screen shot or two~~

Renovate config updates

---

CHANGELOG.md
Makefile
README.md
config/initializers/content_security_policy.rb
config/webpacker.yml
docker-compose.yml
spec/dummy/config/webpacker.yml
yarn.lock

Does not break code, but does change how you will start up Playbook and work with it locally. **You will not need to locally run `yarn` or `bundle` again!** With this new workflow, these commands are ONLY to be ran inside of the `web` container. Also, [**PORTS HAVE CHANGED**](https://github.com/powerhome/playbook/pull/873/commits/f51d4f222f2c182815bdce28d342f2dd501bd4e2) for both Puma and Webpacker. See ["Getting Started"](https://github.com/powerhome/playbook/blob/update-dev-ports/README.md#getting-started) for more details.
N/A
1. `make clean`
1. [Follow the directions](https://github.com/powerhome/playbook#getting-started)

Update dev startup

---

CHANGELOG.md
app/pb_kits/playbook/pb_list/_item.html.erb
app/pb_kits/playbook/pb_list/_list.html.erb
app/pb_kits/playbook/pb_list/_list.jsx
app/pb_kits/playbook/pb_list/_list_item.jsx
app/pb_kits/playbook/pb_list/docs/_list_borderless.jsx
app/pb_kits/playbook/pb_list/docs/_list_dark_borderless.jsx
app/pb_kits/playbook/pb_list/docs/_list_dark_lg.jsx
app/pb_kits/playbook/pb_list/docs/_list_dark_ordered.jsx
app/pb_kits/playbook/pb_list/docs/_list_dark_xpadding.jsx
app/pb_kits/playbook/pb_list/docs/_list_layout_left.jsx
app/pb_kits/playbook/pb_list/docs/_list_layout_right.jsx
app/pb_kits/playbook/pb_list/docs/_list_lg.jsx
app/pb_kits/playbook/pb_list/docs/_list_ordered.jsx
app/pb_kits/playbook/pb_list/docs/_list_xpadding.jsx
app/pb_kits/playbook/pb_list/docs/example.yml
app/pb_kits/playbook/pb_list/docs/index.js
lib/playbook/version.rb
package.json
yarn.lock

React List Playbook kit was missing aria, data, id props as well as a great deal of documentation files. It now mirrors the Rails List kit.
None

Add documentation and props to React List Playbook kit

---

config/deploy/templates/ingress.yaml.erb

Migrate annotations to new version

---

CHANGELOG.md
app/pb_kits/playbook/pb_filter/docs/_description.md

https://nitro.powerhrg.com/runway/backlog_items/NUX-1070

Add description to Filter Kit

---

CHANGELOG.md
app/pb_kits/playbook/pb_filter/templates/_default.html.erb
app/pb_kits/playbook/pb_popover/_popover.html.erb
app/pb_kits/playbook/pb_popover/_popover.scss
app/pb_kits/playbook/pb_popover/index.js

Adds the update function back in, so the popover is positioned correctly.

Popover Fixes

---

CHANGELOG.md
Gemfile.lock
app/pb_kits/playbook/pb_filter/docs/_description.md
app/pb_kits/playbook/pb_radio/_radio.scss
app/pb_kits/playbook/pb_typeahead/docs/_typeahead_default.html.erb
config/deploy/templates/ingress.yaml.erb
lib/playbook/version.rb
package.json
yarn.lock

Releasing 5.1.0

---

README.md

Readme Updates.
None.
https://nitro.powerhrg.com/runway/backlog_items/NUX-1066

Added Yarn Link Instructions

---

CHANGELOG.md
app/pb_kits/playbook/data/menu.yml

Add user_badge back to menu.yml

---

CHANGELOG.md
app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.html.erb
app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.jsx
app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.scss
app/pb_kits/playbook/pb_time_range_inline/time_range_inline.rb

Arrow added & icons deemphasized
No Breaking Changes
https://nitro.powerhrg.com/runway/backlog_items/NUX-637

Time Range Inline Update

---

CHANGELOG.md
Gemfile.lock
lib/playbook/version.rb
package.json
spec/pb_kits/playbook/kits/title_spec.rb

Fixup spec

---

CHANGELOG.md
app/pb_kits/playbook/pb_title_detail/_title_detail.html.erb
app/pb_kits/playbook/pb_title_detail/_title_detail.jsx
app/pb_kits/playbook/pb_title_detail/_title_detail.scss
app/pb_kits/playbook/pb_title_detail/docs/_title_detail_dark.html.erb
app/pb_kits/playbook/pb_title_detail/docs/_title_detail_dark.jsx
app/pb_kits/playbook/pb_title_detail/docs/example.yml
app/pb_kits/playbook/pb_title_detail/docs/index.js
spec/pb_kits/playbook/kits/title_detail_spec.rb

Add Title Detail Dark Mode

---

app/pb_kits/playbook/pb_online_status/_online_status.html.erb
app/pb_kits/playbook/pb_online_status/_online_status.jsx
app/pb_kits/playbook/pb_online_status/_online_status_mixins.scss
app/pb_kits/playbook/pb_online_status/docs/_online_status_dark.html.erb
app/pb_kits/playbook/pb_online_status/docs/_online_status_dark.jsx
app/pb_kits/playbook/pb_online_status/docs/example.yml
app/pb_kits/playbook/pb_online_status/docs/index.js
spec/pb_kits/playbook/kits/online_status_spec.rb

NUX-1330
Only additive changes.

Create online status dark mode

---

app/pb_kits/playbook/pb_pill/_pill.html.erb
app/pb_kits/playbook/pb_pill/_pill.jsx
app/pb_kits/playbook/pb_pill/_pill.scss
app/pb_kits/playbook/pb_pill/docs/_pill_dark.html.erb
app/pb_kits/playbook/pb_pill/docs/_pill_dark.jsx
app/pb_kits/playbook/pb_pill/docs/example.yml
app/pb_kits/playbook/pb_pill/docs/index.js
spec/pb_kits/playbook/kits/pill_spec.rb

NUX-1330
Only additive changes.

Create Pill dark mode

---

app/pb_kits/playbook/pb_multiple_users/_multiple_users.html.erb
app/pb_kits/playbook/pb_multiple_users/_multiple_users.jsx
app/pb_kits/playbook/pb_multiple_users/_multiple_users.scss
app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_dark.html.erb
app/pb_kits/playbook/pb_multiple_users/docs/_multiple_users_dark.jsx
app/pb_kits/playbook/pb_multiple_users/docs/example.yml
app/pb_kits/playbook/pb_multiple_users/docs/index.js
spec/pb_kits/playbook/kits/multiple_users_spec.rb

NUX-1328
Only additive changes

Add dark mode to Multiple Users

---

app/pb_kits/playbook/pb_online_status/_online_status.html.erb
app/pb_kits/playbook/pb_online_status/_online_status.jsx
app/pb_kits/playbook/pb_online_status/_online_status_mixins.scss
app/pb_kits/playbook/pb_online_status/docs/_online_status_dark.html.erb
app/pb_kits/playbook/pb_online_status/docs/_online_status_dark.jsx
app/pb_kits/playbook/pb_online_status/docs/example.yml
app/pb_kits/playbook/pb_online_status/docs/index.js
spec/pb_kits/playbook/kits/online_status_spec.rb

a COPY of this one: https://github.com/powerhome/playbook/pull/991
Had to create it to fix a breakage in CI that was merged without going green first: https://ci.powerhrg.com/blue/organizations/jenkins/powerhome%2Fplaybook/detail/PR-988/14/pipeline/#step-83-log-45

Online status

---

app/pb_kits/playbook/pb_user_badge/_user_badge.html.erb
app/pb_kits/playbook/pb_user_badge/_user_badge.jsx
app/pb_kits/playbook/pb_user_badge/docs/_user_badge_dark.html.erb
app/pb_kits/playbook/pb_user_badge/docs/_user_badge_dark.jsx
app/pb_kits/playbook/pb_user_badge/docs/_user_badge_size_dark.html.erb
app/pb_kits/playbook/pb_user_badge/docs/_user_badge_size_dark.jsx
app/pb_kits/playbook/pb_user_badge/docs/example.yml
app/pb_kits/playbook/pb_user_badge/docs/index.js
spec/pb_kits/playbook/kits/user_badge_spec.rb

NUX-1326
None - only additive changes.

Add User Badge dark mode

---

app/pb_kits/playbook/data/menu.yml
app/pb_kits/playbook/pb_badge/docs/_description.md

No breaking changes.
https://nitro.powerhrg.com/runway/backlog_items/NUX-1335

Grouping Badge, Hashtag, and Pill kits

---

app/pb_kits/playbook/pb_progress_step/_progress_step.html.erb
app/pb_kits/playbook/pb_progress_step/_progress_step.jsx
app/pb_kits/playbook/pb_progress_step/_progress_step.scss
app/pb_kits/playbook/pb_progress_step/_progress_step_item.html.erb
app/pb_kits/playbook/pb_progress_step/_progress_step_item.jsx
app/pb_kits/playbook/pb_progress_step/docs/_description.md
app/pb_kits/playbook/pb_progress_step/docs/_progress_step_dark.html.erb
app/pb_kits/playbook/pb_progress_step/docs/_progress_step_default.html.erb
app/pb_kits/playbook/pb_progress_step/docs/_progress_step_default.jsx
app/pb_kits/playbook/pb_progress_step/docs/_progress_step_tracker.html.erb
app/pb_kits/playbook/pb_progress_step/docs/_progress_step_tracker.jsx
app/pb_kits/playbook/pb_progress_step/docs/_progress_step_vertical.html.erb
app/pb_kits/playbook/pb_progress_step/docs/example.yml
app/pb_kits/playbook/pb_progress_step/docs/index.js
app/pb_kits/playbook/pb_progress_step/progress_step.rb
app/pb_kits/playbook/pb_progress_step/progress_step_item.rb
spec/pb_kits/playbook/kits/progress_step_item_spec.rb
spec/pb_kits/playbook/kits/progress_step_spec.rb

Refactor Progress Step & added Tracker variant

---

app/pb_kits/playbook/packs/site_styles/docs/_kit_doc.scss
app/pb_kits/playbook/pb_button/_button_mixins.scss
app/pb_kits/playbook/pb_button_toolbar/_button_toolbar.scss
app/pb_kits/playbook/pb_card/_card_mixin.scss
app/pb_kits/playbook/pb_checkbox/_checkbox.scss
app/pb_kits/playbook/pb_form_pill/_form_pill.scss
app/pb_kits/playbook/pb_icon/docs/_icon_default_dark.html.erb
app/pb_kits/playbook/pb_icon/docs/_icon_default_dark.jsx
app/pb_kits/playbook/pb_nav/_horizontal_nav.scss
app/pb_kits/playbook/pb_nav/_vertical_nav.scss
app/pb_kits/playbook/pb_radio/_radio.scss
app/pb_kits/playbook/pb_select/_select.scss
app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss
app/pb_kits/playbook/pb_selectable_icon/_selectable_icon.scss
app/pb_kits/playbook/pb_table/styles/_hover.scss
app/pb_kits/playbook/pb_table/styles/_mobile.scss
app/pb_kits/playbook/pb_table/styles/_table-dark.scss
app/pb_kits/playbook/pb_typeahead/_typeahead.scss

Disable hovers for mobile

---

app/pb_kits/playbook/pb_toggle/_toggle.scss
app/pb_kits/playbook/pb_toggle/docs/_toggle_size.html.erb
app/pb_kits/playbook/pb_toggle/docs/_toggle_size.jsx
app/pb_kits/playbook/pb_toggle/docs/example.yml
app/pb_kits/playbook/pb_toggle/docs/index.js
app/pb_kits/playbook/pb_toggle/toggle.rb
spec/pb_kits/playbook/kits/toggle_spec.rb

Reverts powerhome/playbook#1039

Revert "Updated Styling for Toggle"

---

package.json
yarn.lock

Update dependency flow-bin to v0.133.0

---

app/pb_kits/playbook/pb_date_picker/_date_picker.scss

Popover Sass Patch

---

CHANGELOG.md
Gemfile.lock
app/pb_kits/playbook/pb_date_picker/_date_picker.scss
lib/playbook/version.rb
milano.production.yml
milano.staging.yml
package.json

removed global popover visibility styling (#1083)

---

app/pb_kits/playbook/pb_popover/_popover.scss
app/pb_kits/playbook/pb_popover/index.js

https://nitro.powerhrg.com/runway/backlog_items/NUXE-22
https://github.com/powerhome/playbook/issues/1033
See github issue above.

Fixing Flash on Popover Initial Page Load

---

app/pb_kits/playbook/pb_date_range_inline/_date_range_inline.html.erb
app/pb_kits/playbook/pb_date_range_inline/_date_range_inline.jsx
app/pb_kits/playbook/pb_date_range_inline/_date_range_inline.scss
app/pb_kits/playbook/pb_date_range_inline/date_range_inline.rb
app/pb_kits/playbook/pb_date_range_inline/docs/_date_range_inline_default.html.erb
app/pb_kits/playbook/pb_date_range_inline/docs/_date_range_inline_default.jsx
app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.scss
spec/pb_kits/playbook/kits/date_range_inline_spec.rb

This is for issue https://github.com/powerhome/playbook/issues/613
No
https://nitro.powerhrg.com/runway/backlog_items/NUX-636

Make updates to the inline date range kit

---

app/pb_kits/playbook/data/menu.yml
app/pb_kits/playbook/pb_progress_step/_progress_step.jsx
app/pb_kits/playbook/pb_progress_step/_progress_step.scss
app/pb_kits/playbook/pb_progress_step/_progress_step_item.html.erb
app/pb_kits/playbook/pb_progress_step/_progress_step_item.jsx
app/pb_kits/playbook/pb_progress_step/docs/_description.md
app/pb_kits/playbook/pb_progress_step/docs/_progress_step_default.html.erb
app/pb_kits/playbook/pb_progress_step/docs/_progress_step_default.jsx
app/pb_kits/playbook/pb_progress_step/docs/_progress_step_tracker.html.erb
app/pb_kits/playbook/pb_progress_step/docs/_progress_step_tracker.jsx
app/pb_kits/playbook/pb_progress_step/docs/_progress_step_vertical.jsx
app/pb_kits/playbook/pb_progress_step/progress_step.rb
app/pb_kits/playbook/pb_progress_step/progress_step_item.rb
spec/pb_kits/playbook/kits/progress_step_item_spec.rb
spec/pb_kits/playbook/kits/progress_step_spec.rb

No
https://nitro.powerhrg.com/runway/backlog_items/NUXE-147

Update Progress Step

---

Gemfile.lock
lib/playbook/version.rb
package.json
playbook_ui.gemspec

Merging the patch into the 7.2.0 branch so we have the latest on Playbook.

Patch for rake dist

---

Gemfile.lock
app/pb_kits/playbook/pb_bar_graph/bar_graph.rb
app/pb_kits/playbook/pb_line_graph/line_graph.rb
lib/playbook/version.rb
package.json

Patch for classnames on line graph and bar graph.

Solar Patch

---

app/pb_kits/playbook/pb_selectable_card/_selectable_card.html.erb
app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_options.html.erb
app/pb_kits/playbook/pb_selectable_card/docs/example.yml
app/pb_kits/playbook/pb_selectable_card/selectable_card.rb
app/pb_kits/playbook/pb_selectable_card_icon/_selectable_card_icon.html.erb
app/pb_kits/playbook/pb_selectable_card_icon/docs/_selectable_card_icon_options.html.erb
app/pb_kits/playbook/pb_selectable_card_icon/docs/example.yml
app/pb_kits/playbook/pb_selectable_card_icon/selectable_card_icon.rb
app/pb_kits/playbook/pb_selectable_icon/_selectable_icon.html.erb
app/pb_kits/playbook/pb_selectable_icon/docs/_selectable_icon_options.html.erb
app/pb_kits/playbook/pb_selectable_icon/docs/example.yml
app/pb_kits/playbook/pb_selectable_icon/selectable_icon.rb
spec/pb_kits/playbook/kits/selectable_card_icon_spec.rb
spec/pb_kits/playbook/kits/selectable_card_spec.rb
spec/pb_kits/playbook/kits/selectable_icon_spec.rb

https://nitro.powerhrg.com/runway/backlog_items/CMPN-22 
Selectable card: 
Selectable Icon: 
Selectable Card Icon: 
[No (Explain)] - Only additive 
Rspec tests have been written to cover changes. 

[CMPN-22] Allow all HTML options on input in PbSelectableIcon, PbSelectableCard and PbSelectableCardIcon Rails kits

---

app/views/layouts/playbook/_ga.html.erb
app/views/layouts/playbook/application.html.erb
yarn.lock

Adding Google Analytics

---

Jenkinsfile

Updates ci-kubed to version 4.0.1

---

Jenkinsfile

Updating our limits per Ben Langfeld and team.

Updated Memory Limits

---

playbook/README.md

Cloned readme file to have ruby gem install correctly 

Move readme inside playbook folder

---

playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_default.jsx
playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_status.jsx

**Before**
**After**
No, this PR just updates doc examples.
n/a
n/a

Progress pills dark doc examples

---

README.md
playbook/Makefile
playbook/app/pb_kits/playbook/index.js
playbook/app/pb_kits/playbook/pb_avatar/_avatar.jsx
playbook/app/pb_kits/playbook/pb_avatar/avatar.test.js
playbook/app/pb_kits/playbook/utilities/test-utils.js
playbook/bin/test
playbook/config/webpack/test.js
playbook/jest.config.js
playbook/lib/generators/kit/kit_generator.rb
playbook/lib/generators/kit/templates/kit_jsx_test.erb.tt
playbook/package.json
playbook/yarn.lock

This PR is the beginning of React kit testing which is based on [Jest](https://jestjs.io/docs/en/getting-started) and leverages [React Testing Library](https://testing-library.com/docs/react-testing-library/intro) along with [Jest DOM custom matchers](https://github.com/testing-library/jest-dom#table-of-contents) to allow testing of various kit UI aspects include, but not limited to: 
- attributes
- contents
- interactions
- and more
See the Runway ticket below for more details on how me will continue to improve on testing React kits beyond this PR.
No
https://nitro.powerhrg.com/runway/backlog_items/NUXE-294
`yarn test`

JavaScript React Kit Testing

---

playbook/app/pb_kits/playbook/pb_table/_table.scss
playbook/app/pb_kits/playbook/pb_table/docs/_description.md
playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_column.html.erb
playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_column.jsx
playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_column.md
playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_row.html.erb
playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_row.jsx
playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_row.md
playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_data.html.erb
playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_data.jsx
playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_data.md
playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_row.html.erb
playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_row.jsx
playbook/app/pb_kits/playbook/pb_table/docs/example.yml
playbook/app/pb_kits/playbook/pb_table/docs/index.js

it does not remove (nor add) props. it adds a custom attribute and doesn't interfere with the class name
https://nitro.powerhrg.com/runway/backlog_items/NUXE-227
[INSERT URL]
see below 
since this does not add any props or change the class name, no new spec test were added. Did play around and see if they can be used with combined with each other and it does seem to work

[NUXE-227] Add alignment properties to tables

---

playbook/app/pb_kits/playbook/data/samples.yml
playbook/app/pb_kits/playbook/packs/site_styles/_kits_show.scss
playbook/app/pb_kits/playbook/packs/site_styles/_samples_index.scss
playbook/app/views/playbook/pages/kit_show.html.erb
playbook/app/views/playbook/samples/samples_index.html.erb

n/a
[Link to Runway Story](https://nitro.powerhrg.com/runway/backlog_items/NUXE-345)
Check sample page index in Milano deploy.

Updated sample page design layout to support categories

---

playbook/app/pb_kits/playbook/packs/site_styles/_landing-page.scss

No
https://nitro.powerhrg.com/runway/backlog_items/NUXE-365
Click the react/rails toggle and ensure on all screens that there is no shaking.
~- [] **SPECS** Please cover your changes with specs.~

Fix for homepage toggle page shake

---

playbook/lib/playbook/engine.rb

Reverts powerhome/playbook#1278

Revert "Fixes kit generator error"

---

playbook/app/pb_kits/playbook/pb_table/docs/_table_lg.jsx
playbook/app/pb_kits/playbook/pb_table/docs/_table_multiline.jsx

1. Fixes prop passing for two React table example components.
n/a

Table prop passing hotfix

---

playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.html.erb
playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.jsx
playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss
playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_default.html.erb
playbook/app/pb_kits/playbook/pb_selectable_card_icon/_selectable_card_icon.scss

Before: 
Fixed
No - fixes a broken example currently on master
[NUXE-427](https://nitro.powerhrg.com/runway/backlog_items/NUXE-427)
Check `/kits/form_group/react` and `/kits/form_group/rails` for selectable card kit groups
- [x
] **DEPLOY** Please add the `Milano` label when you are ready for a review.

[NUXE-427] Fix select card form group

---

playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.jsx
playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss

Fixes for some of the dark mode typeahead stuff.

Fixing some styles for dark mode

---

playbook/app/pb_kits/playbook/pb_card/_card.scss

Reverts powerhome/playbook#1300

Revert "[NUXE-308] Set Overflow to be Auto on the Card Kit"

---

playbook/app/pb_kits/playbook/pb_date_time/_date_time.jsx
playbook/app/pb_kits/playbook/pb_date_time/docs/_date_time_default.jsx

No - Bug fix.
https://nitro.powerhrg.com/runway/backlog_items/NUXE-435
Add your own `new Date`

Fix DateTime kit bug, add more examples

---

playbook/app/pb_kits/playbook/pb_date_range_inline/_date_range_inline.jsx
playbook/app/pb_kits/playbook/pb_fixed_confirmation_toast/_fixed_confirmation_toast.jsx
playbook/app/pb_kits/playbook/pb_layout/docs/_layout_collection_detail.jsx
playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.jsx
playbook/app/pb_kits/playbook/pb_table/docs/_table_alignment_shift_data.jsx

**14 warnings down to 3....**
No, these are code improvements to remove warnings from the console.
https://nitro.powerhrg.com/runway/backlog_items/NUXE-441
None. No interaction required.

Several fixes for kit warnings found on the "all kits" react page.

---

playbook/app/pb_kits/playbook/pb_checkbox/_checkbox.html.erb
playbook/app/pb_kits/playbook/pb_checkbox/_checkbox.jsx
playbook/app/pb_kits/playbook/pb_checkbox/_checkbox.scss
playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_default.html.erb
playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_default.jsx
playbook/app/pb_kits/playbook/pb_radio/_radio.scss
playbook/app/pb_kits/playbook/pb_radio/docs/_radio_default.html.erb
playbook/app/pb_kits/playbook/pb_radio/docs/_radio_default.jsx
playbook/app/pb_kits/playbook/pb_table/styles/_desktop_collapse.scss
playbook/app/pb_kits/playbook/pb_table/styles/_mobile.scss
playbook/app/pb_kits/playbook/pb_table/styles/_mobile_collapse.scss
playbook/app/pb_kits/playbook/pb_table/styles/_tablet_collapse.scss
playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.scss
playbook/app/pb_kits/playbook/tokens/_positioning.scss

No
https://nitro.powerhrg.com/runway/backlog_items/NUXE-442
1.  Visit https://playbook.powerapp.cloud/kits/checkbox
2. Click into the page then tab to the checkbox input
- it should be highlighted
- it should be checked when pressing [spacebar]
- it should be unchecked when pressing [spacebar]

Improved Accessibility by adding focus to Checkbox & Radio Kits

---

playbook/package.json
playbook/yarn.lock

Update webpack dev server

---

playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_flatpickr_styles.scss
playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_header_styles.scss
playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_overrides.scss

_Before_
_After_
n/a, stylings only
[Link to Runway Story](https://nitro.powerhrg.com/runway/backlog_items/NUXE-446)
Check Milano deploy on Safari.  Already alpha tested in Nitro.

Date Picker Safari fixes

---

playbook/renovate.json

N/A
No
https://nitro.powerhrg.com/runway/backlog_items/NUXE-531
Wait and see

Update renovate config

---

playbook/app/pb_kits/playbook/pb_user_badge/_user_badge.jsx

1. Hotfix for User Badge bug.
Check React User Badge in Milano deploy.

React User Badge bug hotfix

---

playbook/Gemfile.lock
playbook/playbook_ui.gemspec

I don't believe so.
More helpful GH issue - [https://github.com/powerhome/playbook/issues/1396](https://github.com/powerhome/playbook/issues/1396)
Config change.

[NUXE-561] - Upgrade max of action pack gem

---

playbook/app/pb_kits/playbook/data/menu.yml
playbook/app/pb_kits/playbook/pb_date_picker/_date_picker.scss
playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_preview.jsx
playbook/app/pb_kits/playbook/pb_select/_select.scss
playbook/app/pb_kits/playbook/pb_select/docs/_select_custom_select.jsx
playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss
playbook/app/pb_kits/playbook/pb_selectable_card/docs/_selectable_card_input.jsx
playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss
playbook/app/pb_kits/playbook/pb_textarea/_textarea.scss
playbook/app/pb_kits/playbook/pb_textarea/_textarea_mixin.scss
playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_character_counter.jsx
playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_custom.jsx
playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss
playbook/dist/tokens/colors.scss

**NO**
https://nitro.powerhrg.com/runway/backlog_items/NUXE-574
*The normal release cut-off deadline is 3p EDT each week. Please reach out to the release team if you have an urgent request or need a release off cycle.*

Accessibility Improvements, Color Fixes, Menu Changes

---

playbook/app/pb_kits/playbook/pb_avatar/_avatar.scss

BEFORE
AFTER
No
[INSERT URL]
*The normal release cut-off deadline is 3p EDT each week. Please reach out to the release team if you have an urgent request or need a release off cycle.*

Correcting z-index bleed on avatar

---

playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss

Fix typahead height

---

playbook/package.json
playbook/yarn.lock

No
No. Fixing changes.
No
1) Go to `/directory` and ensure that Typeahead works
2) Go to runway team settings and ensure Typeahead works

Pins react-select to 3.0.8

---

playbook/app/pb_kits/playbook/data/menu.yml
playbook/app/pb_kits/playbook/pb_badge/_badge.scss
playbook/app/pb_kits/playbook/pb_multiple_users_stacked/_multiple_users_stacked.scss
playbook/app/pb_kits/playbook/pb_pill/_pill.jsx
playbook/app/pb_kits/playbook/pb_pill/pill.html.erb

1. Removed H3 from pill (accessibility)
2. Restructure Menu + alphabetize
3. Fixed broken CSS in Multiple Stacked Users (CSS specificity)
4. Fixed alignment of badge text
5. Corrected badge from breaking to two lines
(1) ^
(2) ^
(3) ^
(4) ^
(5) ^
No
https://nitro.powerhrg.com/runway/backlog_items/NUXE-533
https://nitro.powerhrg.com/runway/backlog_items/NUXE-157
See screens and compare with the latest on Production. This is safe to merge immediately agyer review.

Fixed broken styles in multiple users stacked + pill accessibility, badge alignment, & menu re-organization

---

playbook/app/pb_kits/playbook/pb_timestamp/_timestamp.jsx

No
https://nitro.powerhrg.com/runway/backlog_items/NUXE-673
https://playbook.powerapp.cloud/kits/timestamp/react

[NUXE-673] Fix Timestamp Duplicated Zone

---

playbook/app/pb_kits/playbook/pb_message/_message.jsx
playbook/app/pb_kits/playbook/pb_message/docs/_message_default.html.erb
playbook/app/pb_kits/playbook/pb_message/docs/_message_default.jsx
playbook/app/pb_kits/playbook/pb_message/message.html.erb

No
https://nitro.powerhrg.com/runway/backlog_items/BOP-1014
I've put two examples (one rails and one react) into the examples files to show it working both ways.

[BOP-1014] Add children to message react kit

---

playbook-website/app/controllers/pages_controller.rb
playbook-website/app/views/pages/getting_started.html.erb
playbook-website/app/views/pages/getting_started.html.slim

Fix getting started page

---

playbook/webpack.config.js

This fixes the dev-start from crashing, that forces devs to kill their server and have to re-start.

Fixes the dev-start from Crashing

---

README.md

No - this is changing text in `README.md
https://nitro.powerhrg.com/runway/backlog_items/LGA-824
No need, just read it and see what you think.

[LGA-824] Fix documentation for getting started with PB

---

playbook/app/pb_kits/playbook/pb_file_upload/_file_upload.jsx

The auto-generated message does not handle properly MIME types. The only handled types are image-related where a MIME type like `image/jpeg` gets converted to `jpeg`. That means that `application/pdf` or `application/msword` are not covered, which is probably undesirable. 
Since different MIME types are possible, I'm suggesting accepting `acceptedFilesDescription ` as a prop. That way the user can specify whatever she needs and also will allow us to leverage some cool wildcard features that [react-dropzone](https://react-dropzone.js.org/#section-accepting-specific-file-types) have, which is to use `image/*` to accept any image.
Below there's a screenshot that represents the problem for the given usage:
```
<FileUpload accept={["image/*", "application/pdf"]} ... />
```
With the proposed …

Allow to specify verbiage for selected file types

---

playbook/app/pb_kits/playbook/pb_icon/_icon.scss
playbook/app/pb_kits/playbook/pb_icon/docs/_icon_custom.html.erb
playbook/app/pb_kits/playbook/pb_icon/docs/_icon_custom.md
playbook/app/pb_kits/playbook/pb_icon/docs/example.yml
playbook/app/pb_kits/playbook/pb_icon/icon.html.erb
playbook/app/pb_kits/playbook/pb_icon/icon.rb
playbook/dist/playbook.css
playbook/spec/pb_kits/playbook/kits/icon_spec.rb

No
https://nitro.powerhrg.com/runway/backlog_items/NUXE-740
View the example in Playbook

Rails custom icon

---

playbook/app/pb_kits/playbook/pb_date/docs/_description.md

Add date kit documentation updates

---

playbook/package.json

[NUXE-995] Removed Node version pinning

---

playbook/app/pb_kits/playbook/pb_flex/_flex.jsx
playbook/app/pb_kits/playbook/pb_flex/docs/_description.md
playbook/app/pb_kits/playbook/pb_flex/docs/_flex_align.md
playbook/app/pb_kits/playbook/pb_flex/docs/_flex_justify.md
playbook/app/pb_kits/playbook/pb_flex/docs/_flex_spacing.md

[#### Runway Ticket URL](https://nitro.powerhrg.com/runway/backlog_items/PLAY-6)
[INSERT URL]

Remove deprecated props

---

playbook/app/pb_kits/playbook/pb_flex/_flex.jsx
playbook/app/pb_kits/playbook/pb_flex/docs/_description.md
playbook/app/pb_kits/playbook/pb_flex/docs/_flex_align.md
playbook/app/pb_kits/playbook/pb_flex/docs/_flex_justify.md
playbook/app/pb_kits/playbook/pb_flex/docs/_flex_spacing.md

Reverts powerhome/playbook#1645

Revert "Remove deprecated props"

---

playbook/app/pb_kits/playbook/pb_background/background.test.js
playbook/spec/pb_kits/playbook/kits/background_spec.rb

No
[PLAY-39](https://nitro.powerhrg.com/runway/backlog_items/PLAY-39)

Add tests to cover new colors for the background kit

---

portal.yml

See https://github.com/powerhome/portal/pull/248

Specify System lifecycle in Portal entity

---

playbook/app/pb_kits/playbook/pb_title/title.html.erb

Other kits are sensitive to the extra space being added
[INSERT URL]

Fix title kit spacing 

---

playbook-website/app/views/pages/code_snippets/typography_tokens.txt

Fix typo CSS attribute name

---

playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.jsx
playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_default.html.erb
playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_default.jsx
playbook/package.json
yarn.lock

Use react-trix lib for RTE kit

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/playbook_ui.gemspec

Locks down:
- `react-rails`
- `view_component`

Lock down react-rails and view_component

---

playbook/lib/generators/kit/kit_generator.rb

Fix kit generator (default to JSX)

---

playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.jsx
playbook/app/pb_kits/playbook/pb_pill/_pill.jsx
playbook/app/pb_kits/playbook/pb_title/_title.jsx
playbook/app/pb_kits/playbook/pb_title/title.test.js

Reverts powerhome/playbook#1857

Revert "[PLAY-146]Title Kit Convert to Typescript"

---

playbook/app/pb_kits/playbook/pb_caption/_caption.jsx

Reverts powerhome/playbook#1856

Revert "[PLAY-145]Caption Kit Convert Typescript"

---

playbook/app/pb_kits/playbook/pb_body/_body.tsx
playbook/app/pb_kits/playbook/pb_highlight/_highlight.tsx
playbook/app/pb_kits/playbook/pb_user/_user.tsx

[PLAY-177](https://nitro.powerhrg.com/runway/backlog_items/PLAY-177)

[PLAY-177] Converting User Kit to Typescript

---

playbook/app/pb_kits/playbook/pb_flex/_flex.tsx

[[PLAY-176]](https://nitro.powerhrg.com/runway/backlog_items/PLAY-176)

[PLAY-176] Converted flex kit to TS

---

playbook/app/pb_kits/playbook/pb_background/_background.tsx

[[PLAY-178]](https://nitro.powerhrg.com/runway/backlog_items/PLAY-178)

[PLAY-178] Converted background kit to TS

---

playbook/app/pb_kits/playbook/pb_contact/_contact.tsx

No breaking changes, JSX to TSX conversion.
[PLAY-215](https://nitro.powerhrg.com/runway/backlog_items/PLAY-215)

[PLAY-215]- Typescript conversion of Contact Kit

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/app/pb_kits/playbook/pb_contact/_contact.tsx
playbook/lib/playbook/version.rb
playbook/package.json

No breaking changes, fix a condition that make everything be processed as phone number.
[INSERT URL]

Fix Contact Kit Condition

---

.gitignore
analyse-webpack-bundle.sh
playbook/package.json
yarn.lock

No - just a tool. Does not affect source code or website
`./analyse-webpack-bundle.sh`

Add Webpack Analysis Script

---

Jenkinsfile

https://github.com/powerhome/ci-kubed/pull/85

Upgrades ci-kubed

---

Jenkinsfile

Memory Bump

---

playbook/app/pb_kits/playbook/pb_file_upload/_file_upload.tsx

[[PLAY-226]
](https://nitro.powerhrg.com/runway/backlog_items/PLAY-226)
Try the component with different props. Check the console for errors.

[PLAY-226] Typescript Conversion: File Upload

---

playbook/app/pb_kits/playbook/pb_date_year_stacked/_date_year_stacked.tsx
playbook/app/pb_kits/playbook/pb_date_year_stacked/date_year_stacked.test.js

No breaking changes. Changed .jsx file to .tsx
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-231)
Test in Milano env

[PLAY-231]- TS Conversion of Date Stacked Kit

---

playbook/private/tasks/pb_release.rake

Fixes missing `--tag alpha` on release script

Add --tag alpha to release script when detected

---

playbook/app/pb_kits/playbook/pb_button/button.test.js
playbook/app/pb_kits/playbook/pb_lightbox/lightbox.test.jsx
playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.tsx
playbook/app/pb_kits/playbook/pb_tooltip/tooltip.test.jsx
playbook/app/pb_kits/playbook/utilities/test-utils.js
playbook/global-jest-setup.js
playbook/jest.config.js

Fixing some warnings and noisy logging.
n/a
No
n/a
`(cd playbook; yarn run test)`

Cleanup Jest Tests

---

.gitignore
playbook-website/.gitignore
playbook/.gitignore

Updates all our `.gitignore` files, as to never allow a `.npmrc` file to get pushed.

Updated .gitignore

---

playbook/app/pb_kits/playbook/pb_badge/badge.test.js

From learning session. Adds jest coverage to the badge kit.

Add Jest Tests to Badge Kit

---

playbook-website/app/views/layouts/_nav.html.erb

No, simple UI fix for visual guidelines page
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-379)
review in milano env

[PLAY-379]-Fixed Example Doc Border Issue

---

playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_default.jsx
playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_error.jsx

No breaking changes, doc fix
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-399)
review in milano env

[PLAY-399]-Textarea Doc Bug Fix

---

playbook/app/pb_kits/playbook/pb_timeline/_timeline.scss
playbook/app/pb_kits/playbook/pb_timeline/docs/_timeline_with_date.html.erb
playbook/app/pb_kits/playbook/pb_timeline/docs/_timeline_with_date.jsx
playbook/app/pb_kits/playbook/pb_timeline/docs/_timeline_with_date.md

No, addition to docs and fixed broken scss on 'with date' example
Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-394)
Test on milano env

[PLAY-394]- Timeline Kit Errors Fix

---

playbook/app/pb_kits/playbook/pb_selectable_list/selectable_list_item.rb
playbook/spec/pb_kits/playbook/kits/selectable_list_item_spec.rb

____
No, Fixed wrong classname in Rails version of kit
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-395)
Test in review env

[PLAY-395]-Fixed Hover State on Selectable List Rails Kit

---

playbook/app/pb_kits/playbook/pb_nav/_vertical_nav.scss

No breaking changes, only SCSS fixes
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-405)
test in milano env

[PLAY-405] Nav Title Spacing Fix

---

playbook/app/pb_kits/playbook/pb_filter/_filter.scss

no, fixed style bleed from scss file
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-374)
Test in milano env

[PLAY-374]-Filter Kit Style Bleed Fix

---

playbook/app/pb_kits/playbook/pb_home_address_street/_home_address_street.tsx

No, styling fix
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-407)
review in milano env

[PLAY-407]-Home Address Kit Spacing Bug Fix

---

Jenkinsfile

**Pay attention to your PR titles and use Title Case!**
Here is a bad 👎 example: "Updates kit props and children"
_Why is it bad? Indistinct title which is not using title case._
Here is a good 👍 example: "Updates Props and Children in Body Kit"
_Why is it good? Distinct title which is using title case._
____
[INSERT URL]

Upgrade ci-kubed to 5.8.1

---

playbook/package.json
yarn.lock

NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-445)
Open up milano environment, check the walkthrough kit and make sure all examples still work as they should.

[PLAY-445] Walkthrough kit update Joyride version

---

playbook/app/pb_kits/playbook/pb_nav/_subtle_mixin.scss

No, only scss fixes
[RUNWAY STORY](https://nitro.powerhrg.com/runway/backlog_items/PLAY-530)
test in review env

[PLAY-530] Nav Kit Wiggle Fix

---

playbook/app/pb_kits/playbook/pb_circle_chart/_circle_chart.tsx
playbook/app/pb_kits/playbook/pb_gauge/_gauge.tsx

____
Fixes to bug found on master after merging PLAY-236
[INSERT URL]

Circlechart Fix for Live Update Variant

---

playbook-website/package.json
playbook/app/pb_kits/playbook/pb_popover/_popover.jsx
playbook/app/pb_kits/playbook/pb_popover/docs/_popover_close.jsx
playbook/package.json
yarn.lock

[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-512)
Test in milano env, will need alpha testing in Nitro and Huddle

[PLAY-512] Update React to v17

---

playbook-website/Gemfile.lock
playbook/CHANGELOG.md
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 11.17.0

---

playbook/app/pb_kits/playbook/pb_user_badge/_user_badge.jsx
playbook/app/pb_kits/playbook/pb_user_badge/badges/million-dollar.jsx
playbook/app/pb_kits/playbook/pb_user_badge/badges/veteran.jsx

Fixes for Badges kit svg loader that was broken due to dependency updates.

Fixed SVG-loader Error in Badge Kit

---

playbook-website/Gemfile.lock
playbook/CHANGELOG.md
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump to 11.18.0

---

milano.production.yml
milano.staging.yml
milano.yml

See https://github.com/powerhome/example-rails-app/commit/fc8b53f35679bc9ea296e39cb0011b7ebbc1dfc3

[GOG-749] Allow rollback to previous releases

---

playbook-website/Gemfile.lock
playbook/CHANGELOG.md
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 11.19.0

---

playbook-website/Gemfile.lock
playbook/CHANGELOG.md
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 11.20.0

---

.github/workflows/github-actions-alpha-version.yml

No
[Runway](https://nitro.powerhrg.com/runway/backlog_items/PLAY-576)
Adding label "alpha" to PR.

[PLAY-576] GitHub Actions Alpha

---

playbook/app/pb_kits/playbook/pb_time_stacked/_time_stacked.tsx
playbook/app/pb_kits/playbook/pb_time_stacked/docs/_time_stacked_default.jsx
playbook/app/pb_kits/playbook/pb_time_stacked/docs/index.js

NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-585)
Check Time Stacked kit to insure it works properly and has no errors in console after conversion

[PLAY-585] Time Stacked Typescript Conversion

---

playbook/app/pb_kits/playbook/pb_checkbox/_checkbox.scss

focus:
active and focus:
focus and hover:
No
[Runway story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-596)

[PLAY-596] Checkbox Pseudo Styles

---

playbook/app/pb_kits/playbook/pb_progress_simple/_progress_simple.tsx
playbook/app/pb_kits/playbook/pb_progress_simple/progress_simple.test.js

____
No
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-588)
Test kit page + all kits page

[PLAY-588] TS Conversion of Progress Simple + Jest Tests

---

playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss
playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss

[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-393)
Test form group page + kit pages for Selectable Card and Selectable Card Icon

[PLAY-393]- Fixed Form Group Bug Where content Jumped on Select

---

playbook/app/pb_kits/playbook/pb_date_time_stacked/_date_time_stacked.tsx
playbook/app/pb_kits/playbook/pb_date_time_stacked/docs/_date_time_stacked_default.jsx
playbook/app/pb_kits/playbook/pb_time_stacked/_time_stacked.tsx

NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-232)
Use Date Time Stacked kit and make sure it functions as expected after typescript conversion

[PLAY-232] ♻️ Typescript Conversion: Date Time Stacked

---

playbook/app/pb_kits/playbook/pb_message/_message.tsx
playbook/app/pb_kits/playbook/pb_message/message.test.js

No
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-633)
Use the Message kit and ensure it works as expected after Typescript conversion

[PLAY-633] Converting Message kit to Typescript

---

playbook-website/app/javascript/site_styles/map_styles/_map_default.scss
playbook/app/pb_kits/playbook/index.js
playbook/app/pb_kits/playbook/pb_button/_button.tsx
playbook/app/pb_kits/playbook/pb_map/_map.scss
playbook/app/pb_kits/playbook/pb_map/_map.tsx
playbook/app/pb_kits/playbook/pb_map/docs/_map_default.jsx
playbook/app/pb_kits/playbook/pb_map/docs/_map_default.md
playbook/app/pb_kits/playbook/pb_map/docs/_map_with_plugin.jsx
playbook/app/pb_kits/playbook/pb_map/docs/example.yml
playbook/app/pb_kits/playbook/pb_map/pbMapTheme.ts

[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-553)

[PLAY-553] Map Kit Custom Styles

---

playbook/app/pb_kits/playbook/tokens/_colors.scss

No
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-637)

[PLAY-637] Changing green token color

---

playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.tsx
playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_initial_country.html.erb
playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_only_countries.html.erb
playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_preferred_countries.html.erb
playbook/app/pb_kits/playbook/pb_phone_number_input/docs/example.yml
playbook/app/pb_kits/playbook/pb_phone_number_input/phone_number_input.html.erb

Will post soon...
None
Will post soon....

[PLAY-650] Working Rails Version of Phone Number

---

playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx
playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_default.html.erb
playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_default.jsx
playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_default.md
playbook/app/pb_kits/playbook/pb_multi_level_select/docs/example.yml
playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.html.erb
playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.rb
playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.test.jsx
playbook/app/pb_kits/playbook/playbook-rails-react-bindings.js

No
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-661)

[PLAY-661] MultiLevelSelect in Rails

---

playbook/app/pb_kits/playbook/pb_avatar/_avatar.tsx
playbook/app/pb_kits/playbook/pb_multiple_users_stacked/_multiple_users_stacked.test.js
playbook/app/pb_kits/playbook/pb_multiple_users_stacked/_multiple_users_stacked.tsx

No
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-642)
Use the Multiple Users Stacked kit and ensure it works as it should after TS conversion.

[PLAY-642] Converting Multiple Users Stacked Kit to TS

---

playbook/app/pb_kits/playbook/pb_progress_pills/_progress_pills.tsx
playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_default.jsx
playbook/app/pb_kits/playbook/pb_progress_pills/docs/_progress_pills_status.jsx
playbook/app/pb_kits/playbook/pb_progress_pills/progress_pills.test.js

No
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-644)
Use the Progress Pills kit and ensure it works as it should after TS conversion.

[PLAY-644] Converting Progress Pills kit to TS

---

playbook-website/app/javascript/packs/application.js

No
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-655)

[PLAY-655] Only importing FontAwesome's regular font

---

.github/workflows/github-actions-alpha-version.yml
playbook/private/tasks/pb_action.rake

No
https://nitro.powerhrg.com/runway/backlog_items/PLAY-593
Add an alpha label to our releases and see if it releases to npm and ruby gems.

NPM + Ruby Gem Alpha Release

---

playbook/app/pb_kits/playbook/pb_progress_step/_progress_step.tsx
playbook/app/pb_kits/playbook/pb_progress_step/_progress_step_item.tsx
playbook/app/pb_kits/playbook/pb_progress_step/docs/_progress_step_default.jsx
playbook/app/pb_kits/playbook/pb_progress_step/docs/_progress_step_tracker.jsx
playbook/app/pb_kits/playbook/pb_progress_step/docs/_progress_step_tracker_click_events.jsx
playbook/app/pb_kits/playbook/pb_progress_step/docs/_progress_step_vertical.jsx
playbook/app/pb_kits/playbook/pb_progress_step/progress_step.test.js

NO
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-645)
Ensure progress simple kit works as expected after conversion

[PLAY-645] ♻️ Typescript Conversion: Progress Step Kit

---

playbook/app/pb_kits/playbook/pb_treemap_chart/_treemap_chart.scss

Fixes an import with the Chart failing in our nitro release PR. https://github.com/powerhome/nitro-web/pull/30651

Fix For Chart for Release PR

---

playbook-website/app/views/pages/all_kit_examples.html.erb
playbook-website/config/initializers/global_variables.rb
playbook-website/config/menu.yml
playbook/lib/generators/kit/kit_generator.rb
playbook/lib/playbook/pb_doc_helper.rb
playbook/playbook_ui.gemspec
playbook/webpack.config.js

[PLAY-623] Menu YML Ready for Alpha

---

playbook-website/app/javascript/components/VisualGuidelines/Examples/LineHeight.tsx
playbook-website/app/javascript/components/VisualGuidelines/Examples/MaxWidth.tsx
playbook-website/app/javascript/components/VisualGuidelines/Templates/Example.tsx
playbook/app/pb_kits/playbook/pb_body/docs/_body_articles.html.erb
playbook/app/pb_kits/playbook/pb_body/docs/_body_articles.jsx
playbook/app/pb_kits/playbook/pb_body/docs/_body_articles.md
playbook/app/pb_kits/playbook/pb_body/docs/example.yml
playbook/app/pb_kits/playbook/pb_body/docs/index.js

No
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-682)

[PLAY-682] Add Articles doc to Body kit

---

playbook/app/pb_kits/playbook/pb_avatar/_avatar.tsx
playbook/app/pb_kits/playbook/pb_source/_source.tsx
playbook/app/pb_kits/playbook/pb_source/source.test.js

No
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-680)
Ensure the Source kit works as expected after TS conversion.

[PLAY-680] Converting Source kit to Typescript

---

playbook/app/pb_kits/playbook/pb_flex/_flex.scss
playbook/app/pb_kits/playbook/pb_flex/_flex.tsx
playbook/app/pb_kits/playbook/pb_flex/docs/_flex_gap.html.erb
playbook/app/pb_kits/playbook/pb_flex/docs/_flex_gap.jsx
playbook/app/pb_kits/playbook/pb_flex/docs/_flex_gap.md
playbook/app/pb_kits/playbook/pb_flex/flex.rb
playbook/spec/pb_kits/playbook/kits/flex_spec.rb

No
[RUNWAY STORY](https://nitro.powerhrg.com/runway/backlog_items/PLAY-706)
Made gap xxs on doc example for both react and rails for testing

[PLAY-706] Adding xxs to Flex gap, column gap and row gap

---

playbook-website/Gemfile.lock
playbook/CHANGELOG.md
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump to 12.15.0

---

playbook-website/Gemfile.lock
playbook/CHANGELOG.md
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version bump 12.16.0

---

playbook-website/app/javascript/packs/application.js
playbook-website/app/javascript/site_styles/_changelog.scss
playbook-website/app/javascript/site_styles/_site-style.scss
playbook-website/package.json
yarn.lock

Reverts powerhome/playbook#2480

Revert "[PLAY-753] Added Anchors to Kit Examples and Changelog"

---

playbook-website/Gemfile.lock
playbook/CHANGELOG.md
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump to 12.17.0

---

playbook-website/Gemfile.lock
playbook/CHANGELOG.md
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 12.17.1

---

playbook-website/Gemfile.lock
playbook/CHANGELOG.md
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 12.19.0

---

playbook-website/Gemfile.lock
playbook/CHANGELOG.md
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump to 12.20.0

---

playbook/app/pb_kits/playbook/pb_docs/kit_example.html.erb

Fixed addeventlistner console error by adding conditional

---

renovate.json

This PR adds the encrypted FA auth token, so that renovate doesn't fail on open Pull Requests anymore. 
1. Go to open PRs from renovate, and see that they are passing.
~- [ ] **TESTS** I have added test coverage to my code.~

[PLAY-813] Fix Renovate Failures

---

playbook-website/Gemfile.lock
playbook/CHANGELOG.md
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 12.22.0

---

playbook-website/Gemfile.lock
playbook/CHANGELOG.md
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version bump 12.23.0

---

playbook-website/app/components/playbook/pb_docs/kit_example.html.erb
playbook-website/app/components/playbook/pb_docs/kit_example.rb
playbook-website/app/controllers/pages_controller.rb
playbook-website/lib/pb_doc_helper.rb
playbook/app/pb_kits/playbook/pb_avatar/docs/_avatar_swift.md
playbook/app/pb_kits/playbook/pb_docs/kit_example.html.erb

Correct broken swift markdown docs

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 12.26.0

---

.github/workflows/github-actions-alpha-version.yml

Fixes Alpha Script

---

playbook-website/app/controllers/guides_controller.rb

Correct page name / titleize bug

---

playbook/app/pb_kits/playbook/pb_multi_level_select/_helper_functions.tsx
playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx

Fixes the issues causing breakage in Nitro

Fixes for MultiLevelSelect as tested in Nitro

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump to 12.26.1

---

playbook-website/app/javascript/site_styles/_site-style.scss
playbook-website/app/javascript/site_styles/docs/_code_snippet.scss
playbook-website/app/javascript/site_styles/docs/_color_utilities.scss
playbook-website/app/javascript/site_styles/docs/_kit_doc.scss
playbook-website/app/javascript/site_styles/visual_guidelines/_line_height_guidelines.scss
playbook-website/app/javascript/site_styles/visual_guidelines/_spacing_tokens.scss
playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_flatpickr_styles.scss
playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_month_and_year_styles.scss
playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_week_styles.scss
playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.scss
playbook/app/pb_kits/playbook/pb_rich_text_editor/_trix_styles.scss

[PLAY-865](https://nitro.powerhrg.com/runway/backlog_items/PLAY-865)
This PR updates any `font-weight` that doesn't use one of our tokens
1. Go to any of the kits that got updated
-Date Picker
-Form Pill
-Rich Test Editor
2. Check to see if it still has the correct `font-weight`

[PLAY-865] Font weight tokens updates

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version bump 12.28.0

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump to 12.29.0

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version bump 12.30.0

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version bump to 12.30.1

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 12.31.0

---

playbook/CHANGELOG.md

Update CHANGELOG.md for 12.31.0

---

playbook/app/pb_kits/playbook/pb_date_picker/date_picker_helper.ts

Allows you to pass multiple disabled date types to datepicker

[PLAY-918] DatePicker Disabled Dates Conflict

---

playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.scss
playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx

Implements designs for inputDisplay="none" variant

[PLAY-920] MultiLevelSelect: Designs for no pills Variant

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump to 12.32.0

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version bump 12.33.0

---

playbook/CHANGELOG.md

Update CHANGELOG.md for 12.33.0

---

playbook/app/pb_kits/playbook/pb_date/_date.tsx
playbook/app/pb_kits/playbook/pb_date/docs/_date_alignment.jsx
playbook/app/pb_kits/playbook/pb_date/docs/_date_default.jsx
playbook/app/pb_kits/playbook/pb_date/docs/_date_unstyled.jsx
playbook/app/pb_kits/playbook/pb_date/docs/_date_variants.jsx
playbook/app/pb_kits/playbook/pb_date_range_inline/_date_range_inline.tsx
playbook/app/pb_kits/playbook/pb_date_range_stacked/_date_range_stacked.tsx
playbook/app/pb_kits/playbook/pb_date_stacked/_date_stacked.tsx
playbook/app/pb_kits/playbook/pb_date_time/_date_time.tsx
playbook/app/pb_kits/playbook/pb_date_time/dateTime.test.js
playbook/app/pb_kits/playbook/pb_date_time_stacked/_date_time_stacked.tsx
playbook/app/pb_kits/playbook/pb_date_time_stacked/date_time_stacked.test.js
playbook/app/pb_kits/playbook/pb_date_year_stacked/_date_year_stacked.tsx
playbook/app/pb_kits/playbook/pb_kit/dateTime.ts
playbook/app/pb_kits/playbook/pb_label_value/_label_value.tsx
playbook/app/pb_kits/playbook/pb_logistic/_logistic.jsx
playbook/app/pb_kits/playbook/pb_message/_message.tsx
playbook/app/pb_kits/playbook/pb_time/_time.tsx
playbook/app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.tsx
playbook/app/pb_kits/playbook/pb_time_stacked/_time_stacked.tsx
playbook/app/pb_kits/playbook/pb_timestamp/_timestamp.tsx
playbook/app/pb_kits/playbook/pb_weekday_stacked/_weekday_stacked.tsx

Reverts powerhome/playbook#2627

Revert "[PLAY-814]📦 Remove moment.js"

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump to 12.34.0

---

playbook/CHANGELOG.md

Update CHANGELOG.md for 12.34.0

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 12.35.0

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump to 12.36.0

---

playbook/CHANGELOG.md

Adding missing info for changelog 12.35.0

Missing Info for changelog

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 12.37.0

---

playbook/CHANGELOG.md

Updates Changelog.
1. Go to '...'

12.38.0 CHANGELOG.md

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump

---

playbook/CHANGELOG.md

Update CHANGELOG.md 12.39.0

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version bump to 13.1.0

---

playbook-website/app/components/lg_hp_social_proof_component.erb
playbook-website/app/components/md_hp_social_proof_component.erb
playbook-website/app/components/sm_hp_social_proof_component.html.erb
playbook/app/pb_kits/playbook/pb_select/docs/_select_multiple.md

[PLAY-974](Website/docs copy updates)
This PR:
Updates `Select kit's "Multiple"` docs
updates Social Proof to `1m+`
1. Go to the homepage and select kit page to review changes.

[PLAY-974] Website/docs copy updates

---

playbook/CHANGELOG.md

Update CHANGELOG.md 13.2.0

---

playbook-website/app/javascript/components/MainSidebar/index.tsx
playbook-website/app/javascript/packs/application.js
playbook-website/app/javascript/packs/main_sidebar.js
playbook-website/app/javascript/types.d.ts
playbook-website/app/javascript/utilities/website_sidebar_helper.ts
playbook-website/app/views/layouts/_sidebar.html.erb

Converts Website sidebar to react
[Runway Story](https://nitro.powerhrg.com/runway/backlog_items/PLAY-934)

[PLAY-934] Convert Website Sidebar to React

---

playbook-website/config/deploy/production/secrets.yaml
playbook-website/config/deploy/prs/secrets.yaml
playbook-website/config/deploy/staging/secrets.yaml

See https://nitro.powerhrg.com/support/tickets/735367-TI

Rotate secrets encryption for new owner team

---

playbook-website/app/controllers/pages_controller.rb
playbook-website/app/views/pages/changelog.html.erb
playbook-website/app/views/pages/home.html.erb

Performance Fix Rollback

---

playbook-website/app/controllers/application_controller.rb

Last PR's permissions ended up blocking the site. So removing those that were blocking it. 
1. Go to '...'

Removing blocking permissions

---

playbook/app/pb_kits/playbook/pb_message/_message.scss
playbook/app/pb_kits/playbook/pb_message/_message_mixins.scss

[PLAY-1019](https://nitro.powerhrg.com/runway/backlog_items/PLAY-1019)

[PLAY-1019] Font size for mentions to be 15px

---

playbook/app/pb_kits/playbook/pb_button/_button.tsx
playbook/app/pb_kits/playbook/pb_button/docs/_button_reaction.html.erb
playbook/app/pb_kits/playbook/pb_button/docs/_button_reaction.jsx
playbook/app/pb_kits/playbook/pb_icon/_icon.tsx
playbook/app/pb_kits/playbook/utilities/validEmojiChecker.ts

Number emojis were not being read as emojis by our reaction button kit. Fixed the isValidEmoji function to be more inclusive of all emojis

[PLAY-1016] Reaction Button Emoji Fixes

---

playbook/CHANGELOG.md

Update CHANGELOG.md 13.9.0

---

playbook/app/pb_kits/playbook/pb_button/docs/_button_circle_swift.md
playbook/app/pb_kits/playbook/pb_button/docs/_button_default_swift.md
playbook/app/pb_kits/playbook/pb_button/docs/_button_full_width_swift.md
playbook/app/pb_kits/playbook/pb_button/docs/_button_icon_options_swift.md
playbook/app/pb_kits/playbook/pb_button/docs/_button_props_swift.md
playbook/app/pb_kits/playbook/pb_button/docs/_button_size_swift.md
playbook/app/pb_kits/playbook/pb_button/docs/example.yml

[PBIOS-160](https://nitro.powerhrg.com/runway/backlog_items/PBIOS-160)
Adds swift docs for the Button kit.
1. Pull branch and go to buttons page on local env.

[PBIOS-160] Docs: Button

---

playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_default_swift.md
playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_error_swift.md
playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_indeterminate_swift.md
playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_props_swift.md
playbook/app/pb_kits/playbook/pb_checkbox/docs/example.yml

[PBIOS-164](https://nitro.powerhrg.com/runway/backlog_items/PBIOS-164)
**Screenshots:** Screenshots to visualize
your addition/change
1. Can only be tested in a local environment.
2. Checkout branch and navigate to the Checkbox kit

[PBIOS-164] Docs: Checkbox

---

playbook/app/pb_kits/playbook/pb_icon_circle/docs/_icon_circle_color_props.md
playbook/app/pb_kits/playbook/pb_icon_circle/docs/_icon_circle_color_swift.md
playbook/app/pb_kits/playbook/pb_icon_circle/docs/_icon_circle_defaul_swift.md
playbook/app/pb_kits/playbook/pb_icon_circle/docs/_icon_circle_sizes_swift.md
playbook/app/pb_kits/playbook/pb_icon_circle/docs/example.yml

[PBIOS-166](https://nitro.powerhrg.com/runway/backlog_items/PBIOS-166)
1. Pull branch locally and navigate to the Icon Circle kit

[PBIOS-166] Docs: Icon Circle

---

playbook/app/pb_kits/playbook/pb_dawg/docs/example.yml
playbook/lib/playbook/pb_doc_helper.rb

https://nitroqa.powerhrg.com/dev_docs/playbook
Bug shipped in https://github.com/powerhome/playbook/pull/2778/

Remove Glob code breaking Nitro's Playbook docs

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

13.11.0 Version Bump

---

playbook-website/Gemfile.lock
playbook-website/app/javascript/components/HomepageHero/HeroComponents/SelectPlan.tsx
playbook-website/app/javascript/components/HomepageHero/Pages/Welcome.tsx
playbook-website/app/javascript/components/MainSidebar/TopLevelNavItems.tsx
playbook-website/app/javascript/packs/application.js
playbook-website/app/javascript/packs/main_sidebar.js
playbook-website/app/javascript/packs/samples.js
playbook-website/app/javascript/packs/visual_guidelines.js
playbook-website/lib/generators/sample/sample_generator.rb
playbook/app/pb_kits/playbook/playbook-doc.js
playbook/lib/generators/kit/kit_generator.rb

Fixes console errors related to webpacker in playbook website
[Runway Ticket](https://nitro.powerhrg.com/runway/backlog_items/PLAY-821)
n/a
1. Go to playbook webstite
2. Inspect console and looks for errors related to webpack

[PLAY-821] 🌐 Console error cleanup: site-wide and homepage

---

playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_children_swift.md
playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_dashed_swift.md
playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_line_swift.md
playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_props_swift.md
playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_text_swift.md
playbook/app/pb_kits/playbook/pb_section_separator/docs/_section_separator_vertical_swift.md
playbook/app/pb_kits/playbook/pb_section_separator/docs/example.yml

[PBIOS-180](https://nitro.powerhrg.com/runway/backlog_items/PBIOS-180)
https://github.com/powerhome/playbook/assets/92755007/f4527681-aa0b-490b-ab7e-e5f416800b61
1. Pull branch locally and navigate to the Section Separator kit

[PBIOS-180] Docs: Section Separator

---

playbook/CHANGELOG.md

Update CHANGELOG.md for 13.12.0

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

13.13.0 Version Bump

---

playbook/CHANGELOG.md

13.13.0 Changelog

---

playbook/CHANGELOG.md

Update CHANGELOG.md 13.14.0

---

playbook/app/pb_kits/playbook/pb_select/docs/_select_default_swift.md
playbook/app/pb_kits/playbook/pb_select/docs/_select_error_swift.md
playbook/app/pb_kits/playbook/pb_select/docs/_select_props_table.md
playbook/app/pb_kits/playbook/pb_select/docs/example.yml

Adds documentation for the Select kit

[PBIOS-181] Select docs

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

13.15.0 Version Bump

---

playbook/CHANGELOG.md

13.15.0 Changelog

---

playbook/app/pb_kits/playbook/pb_dashboard/pbChartsDarkTheme.ts
playbook/app/pb_kits/playbook/pb_dashboard/pbChartsLightTheme.ts

Fixes for broken Gauge kit. 
1. Go to '...'

Fixes for Broken Gauge Kit

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

13.16.0 Version Bump

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 13.17.0

---

playbook/app/pb_kits/playbook/pb_popover/popover.test.js

Fix popover test

---

.github/workflows/github-actions-alpha-version.yml

Upgrade Alpha Script's Node Version

---

playbook/CHANGELOG.md

13.17.0 CHANGELOG.md

---

playbook/CHANGELOG.md

13.18.0 Changelog

---

playbook/app/pb_kits/playbook/pb_nav/_subtle_mixin.scss

I changed the css to make active and icon right white 
Runway https://nitro.powerhrg.com/runway/backlog_items/PLAY-1186
https://codesandbox.io/p/sandbox/datepicker-forked-fft3nj?file=%2Fsrc%2FApp.js%3A11%2C71

[PLAY-1186] Fix Bold Nav Icon Color

---

playbook/app/pb_kits/playbook/pb_text_input/_text_input.tsx
playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_add_on.jsx

[PLAY-1237] Fix addon input child

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json
yarn.lock

Version Bump 13.20.0

---

playbook/app/pb_kits/playbook/pb_date/docs/_date_alignment_swift.md
playbook/app/pb_kits/playbook/pb_date/docs/_date_default_swift.md

[PBIOS-300] Date Doc Update
1. Go to '...'

[PBIOS-300] Date Doc Update

---

playbook/app/pb_kits/playbook/pb_message/docs/_description.md

Fixes typos in the Message kit's description.
n/a
1. Go to '.../kits/message'
2. See description under page title

fix Message kit description typos

---

playbook-website/app/views/guides/getting_started/swift_setup.md

[[PBIOS-296] update setup guide](https://nitro.powerhrg.com/runway/backlog_items/PBIOS-296)
1. Go to '...'

[PBIOS-296] update setup guide

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

13.22.0 Playbook Version Bump

---

playbook-website/app/javascript/components/VisualGuidelines/Examples/Position.tsx
playbook/app/pb_kits/playbook/utilities/_positioning.scss
playbook/app/pb_kits/playbook/utilities/globalProps.ts
playbook/lib/playbook/bottom.rb
playbook/lib/playbook/left.rb
playbook/lib/playbook/position_props_css.rb
playbook/lib/playbook/right.rb
playbook/lib/playbook/top.rb

Adds the option to pass in an inset to the global positioning prop to provide for edge cases like the Avatar kit

[PBNTR-243] Global Positioning Props to Allow Inset Value

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

13.23.0 Version Bump

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

13.24.0 Version Bump

---

playbook/CHANGELOG.md

13.23.0 CHANGELOG.md

---

playbook-website/app/javascript/site_styles/docs/_markdown.scss
playbook-website/app/views/guides/design_guidelines/typography_guidelines.md

Verified Version of Typography Guidelines

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

13.25.0 Version Bump

---

playbook/app/pb_kits/playbook/pb_currency/docs/_currency_alignment_swift.md
playbook/app/pb_kits/playbook/pb_currency/docs/_currency_props_swift.md
playbook/app/pb_kits/playbook/pb_currency/docs/_currency_size_swift.md
playbook/app/pb_kits/playbook/pb_currency/docs/example.yml

[PBIOS-339] Currency Docs
1. Go to '...'

[PBIOS-339] Currency Docs

---

milano.production.yml
milano.staging.yml
milano.yml

Updates Milano log links in all envs
1. Go to this deployment
2. Click on the logs link and metrics link
3. Verify both are using the correct env

Update milano links

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

13.26.0 Version Bump

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

13.27.0 Version Bump

---

playbook/app/pb_kits/playbook/pb_date_range_inline/docs/_date_range_inline_default_swift.md
playbook/app/pb_kits/playbook/pb_date_range_inline/docs/_date_range_inline_props_swift.md
playbook/app/pb_kits/playbook/pb_date_range_inline/docs/example.yml

[PBIOS-331] Date Range Inline Docs
1. Go to '...'

[PBIOS-331] Date Range Inline Docs

---

playbook-website/app/javascript/site_styles/docs/_kits_examples.scss
playbook-website/app/views/pages/kit_show.html.erb
playbook/app/pb_kits/playbook/pb_date_time/docs/_date_time_alignment_swift.md
playbook/app/pb_kits/playbook/pb_date_time/docs/_date_time_default_swift.md
playbook/app/pb_kits/playbook/pb_date_time/docs/_date_time_props_swift.md
playbook/app/pb_kits/playbook/pb_date_time/docs/_date_time_size_swift.md
playbook/app/pb_kits/playbook/pb_date_time/docs/example.yml

[PBIOS-338]Date Time Docs
1. Go to '...'

[PBIOS-338]Date Time Docs

---

playbook/CHANGELOG.md

Update CHANGELOG.md for 13.26.0 & 13.27.0

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

13.28.0 Version Bump

---

playbook/app/pb_kits/playbook/pb_tooltip/_tooltip.tsx

Reverts powerhome/playbook#3440

Revert "[PLAY-1343] fix Tooltip oversize and misalignment issue"

---

playbook/app/pb_kits/playbook/pb_icon/icon.rb

https://nitro.powerhrg.com/runway/backlog_items/PLAY-1359
1. Go to '...'

[PLAY-1359] Fix for Icon Rails Kit based on Subdirectory Structure

---

playbook/CHANGELOG.md

Update CHANGELOG.md 13.28.0

---

playbook/CHANGELOG.md

Update CHANGELOG.md 13.29.0

---

playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.scss
playbook/package.json
playbook/webpack.config.js
yarn.lock

Runway: https://nitro.powerhrg.com/runway/backlog_items/PLAY-1355
The story was to try and update to the latest `23` and our current version is `17`
I ran into lots of breaking issues that i just upgraded to `18`. There was a decent amount of css I needed to change because the html structor updated.
1. Go to [/kits/phone_number_input/react](https://pr3453.playbook.beta.px.powerapp.cloud/kits/phone_number_input/react)
2. The kit should not change
- [😈] **TESTS** I have added test coverage to my code.

[PLAY-1355] Upgrade phone number lib

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version bump 13.30.0

---

playbook-website/config/menu.yml
playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_default.html.erb
playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_default.jsx
playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_default.md
playbook/app/pb_kits/playbook/pb_overlay/docs/_overlay_multi_directional.html.erb
playbook/app/pb_kits/playbook/pb_overlay/docs/example.yml
playbook/app/pb_kits/playbook/pb_overlay/overlay.html.erb
playbook/app/pb_kits/playbook/pb_overlay/overlay.rb
playbook/spec/pb_kits/playbook/kits/overlay_spec.rb

[PBNTR-333](https://nitro.powerhrg.com/runway/backlog_items/PBNTR-333)
This PR adds the Overlay kit to the rails side
1. Go to '...'

[PBNTR-333] NEW Overlay kit in Rails

---

playbook/app/pb_kits/playbook/pb_icon/docs/_icon_default.html.erb
playbook/app/pb_kits/playbook/pb_icon/docs/_icon_default.jsx
playbook/app/pb_kits/playbook/pb_icon/types.d.ts

Fixing up docs

---

playbook/CHANGELOG.md

Update CHANGELOG.md for 13.31.0

---

playbook-website/Gemfile.lock
playbook-website/package.json
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

13.32.0 Version Bump

---

playbook/CHANGELOG.md

13.32.0 CHANGELOG.md

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version bump to 13.33.1

---

playbook/CHANGELOG.md

13.33.0 CHANGELOG.md

---

playbook/app/pb_kits/playbook/pb_dropdown/dropdown.html.erb
playbook/app/pb_kits/playbook/pb_dropdown/dropdown.rb
playbook/app/pb_kits/playbook/pb_dropdown/index.js

[Runway Story](https://runway.powerhrg.com/backlog_items/PBNTR-405)
1. Go to '...'

[PBNTR-405] Dropdown Kit in Rails Form Fixes

---

playbook-website/package.json
yarn.lock

Runway https://runway.powerhrg.com/backlog_items/PLAY-1438
Adding Batch 8 of icons 
https://github.com/powerhome/playbook-icons/pull/37

[PLAY-1438] Icons Batch 8

---

playbook/app/pb_kits/playbook/pb_background/background.html.erb
playbook/app/pb_kits/playbook/pb_body/body.html.erb
playbook/app/pb_kits/playbook/pb_bread_crumbs/bread_crumb_item.html.erb
playbook/app/pb_kits/playbook/pb_bread_crumbs/bread_crumbs.html.erb
playbook/app/pb_kits/playbook/pb_caption/caption.html.erb
playbook/app/pb_kits/playbook/pb_card/card.html.erb
playbook/app/pb_kits/playbook/pb_detail/detail.html.erb
playbook/app/pb_kits/playbook/pb_dialog/dialog.html.erb
playbook/app/pb_kits/playbook/pb_dialog/dialog_body.html.erb
playbook/app/pb_kits/playbook/pb_dialog/dialog_footer.html.erb
playbook/app/pb_kits/playbook/pb_dialog/dialog_header.html.erb
playbook/app/pb_kits/playbook/pb_flex/flex.html.erb
playbook/app/pb_kits/playbook/pb_hashtag/hashtag.html.erb
playbook/app/pb_kits/playbook/pb_highlight/highlight.html.erb
playbook/app/pb_kits/playbook/pb_home_address_street/home_address_street.html.erb

A 2nd attempt of https://github.com/powerhome/playbook/pull/3497
Reverts powerhome/playbook#3518

[PLAY-1445] Use New Content Tag

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 13.34.0

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/app/pb_kits/playbook/pb_icon/_icon.scss
playbook/lib/playbook/version.rb
playbook/package.json

Fix For Icon Color SCSS

---

playbook/CHANGELOG.md

[release story](https://runway.powerhrg.com/backlog_items/PLAY-1459)

CHANGELOG for 13.34.1

---

playbook/app/pb_kits/playbook/pb_date_picker/docs/_description.md

https://runway.powerhrg.com/backlog_items/PLAY-1466
Updating documentation for Datepicker to provide clarity on formatting issue
1. Go to '...'

[PLAY-1466] Updating datepicker doc for rails for formatting issue

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

14.0.0 Version Bump

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

14.1.0 Version Bump

---

.github/workflows/github-actions-release-candidate.yml

Adds a new github action for versioning release candidates, when PRs are merged to Master.
1. Merge a PR to master.
2. Check Rubygems & Npm.
~- [ ] **TESTS** I have added test coverage to my code.~

[PLAY-1492] Initial RC Github Action

---

package.json
yarn.lock

Reverts powerhome/playbook#3617

Revert "Testing Dep Update"

---

playbook-website/package.json
yarn.lock

Reverts powerhome/playbook#3598

Revert "[PLAY-1475] Bumping "axe-core" dependency from 4.9.1 to 4.10.0"

---

playbook-website/package.json
yarn.lock

Bumping axecore dependency to 4.10.0

---

playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
playbook/app/pb_kits/playbook/pb_star_rating/index.js
playbook/app/pb_kits/playbook/pb_star_rating/star_rating.html.erb
playbook/app/pb_kits/playbook/pb_star_rating/star_rating.rb

Adding Star Rating form controls
1. Go to the Form kit page
2. Scroll down to the last input (Star Rating kit)

[PBNTR-415] Adding Star Rating form controls

---

playbook/app/javascript/theme.js

Testing exporting highchart themes from PB for a cleaner solution
[Gist here](https://gist.github.com/nidaqg/e7248c888da08d2e596aebdb9796e4da)

Export Highchart Theming Files

---

playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.scss

Fixing Phone Number Input kit flag misalignment
1. Go to the Phone Number Input kit page.

[PBNTR-470] Fixing Phone Number Input kit flag misalignment

---

playbook/CHANGELOG.md

Update CHANGELOG.md 14.1.0

---

.github/workflows/github-actions-release-candidate.yml

[PLAY-1512] Adds New RC Flow

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 14.2.0

---

.github/workflows/github-actions-release-candidate.yml

Testing Fix

---

playbook/SWIFT_CHANGELOG.md

[PBIOS-489] Announce 6.1.0 Release

[PBIOS-489] Announce 6.1.0  Release

---

.github/workflows/github-actions-release-candidate.yml

Testing Incrementing for Github Action RC

---

.github/workflows/github-actions-release-candidate.yml

Implement Error Handling and Additions for Github Action

---

.github/workflows/github-actions-release-candidate.yml

[PLAY-1534] Fix Github Action Bug that Breaks Build

---

playbook/SWIFT_CHANGELOG.md

[PBIOS-535] Update Swift CHANGELOG

[PBIOS-535] Update Swift CHANGELOG

---

playbook/app/pb_kits/playbook/pb_rich_text_editor/_previewer_mixin.scss
playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
playbook/app/pb_kits/playbook/pb_rich_text_editor/_tiptap_styles.scss
playbook/app/pb_kits/playbook/pb_rich_text_editor/_trix_styles.scss
playbook/app/pb_kits/playbook/pb_rich_text_editor/docs/_rich_text_editor_preview.html.erb

[PBNTR-449](https://runway.powerhrg.com/backlog_items/PBNTR-449) involves fixing the [rails previewer doc example](https://playbook.powerapp.cloud/kits/rich_text_editor#preview) (for the default, trix based text editor) so that it 1. works and 2. shows output in the preview card 1:1 with the text editor input (in the same fashion as [PBNTR-286](https://runway.powerhrg.com/backlog_items/PBNTR-286), which did the same thing for the React-only, tiptap based, advanced editor.
I did not abstract out any code that I could not test - specifically, this refers to code referring to attachments or images added to the editor (trix-editor) or the output (trix-content). I also did not touch any of the code involved …

[PBNTR-449] RTE Previewer + Output Rails

---

.github/workflows/github-actions-release-candidate.yml

Fixes Limit for Now

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump to 14.3.0

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Patch update, reverts PBNTR-479

Version Bump 14.3.1

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 14.4.0

---

playbook/CHANGELOG.md

Update CHANGELOG.md 14.4.0

---

.github/workflows/github-actions-release-candidate.yml

Reverts powerhome/playbook#3720

Revert "Rc comment with package links"

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump PR

---

playbook/lib/playbook/pb_doc_helper.rb

[HFH-2454] Support multiple versions of ruby/psych

---

Jenkinsfile

https://ci.powerapp.cloud/blue/organizations/jenkins/powerhome%2Fplaybook/detail/master/996/pipeline/

More storage for CI image builds

---

playbook-website/config/deploy/prs/secrets.yaml

Encrypted OpenAI key using bin/deployer from the playbook-website folder. 
1. Go to '...'

Encrypted OpenAI Key

---

playbook-website/app/javascript/components/AiAssistant/apiService.jsx
playbook-website/app/javascript/components/AiAssistant/index.tsx
playbook-website/package.json
yarn.lock

Adding ChatGPT Api call

---

.gitignore
playbook-website/.gitignore
playbook-website/config/application.rb
playbook-website/config/deploy/prs/secrets.yaml
playbook-website/config/deploy/templates/deployment.yaml.erb
playbook-website/config/deploy/templates/secret.yaml.erb
playbook-website/config/deploy/templates/shell.yaml.erb
playbook-website/config/initializers/openai.rb

Updating Secrets & Git Ignore

---

.gitignore
playbook-website/.gitignore
playbook-website/config/application.rb
playbook-website/config/deploy/prs/secrets.yaml
playbook-website/config/deploy/templates/deployment.yaml.erb
playbook-website/config/deploy/templates/secret.yaml.erb
playbook-website/config/deploy/templates/shell.yaml.erb
playbook-website/config/initializers/openai.rb

Updating Secrets & Git Ignore (#3776)

---

.github/workflows/github-actions-release-candidate.yml

[PLAY-1580](https://runway.powerhrg.com/backlog_items/PLAY-1580)
The RC script should automatically detect the Semver label (Major, Minor, Patch) on each merged PR. Based on the detected Semver target, the script should create the correct versioned RC (e.g., 14.3.0 for Minor, 15.0.0 for Major). This will ensure consistency and reduce manual intervention in the release process.
- The RC script must check for a Semver label on each PR (Major, Minor, Patch). If no label is present, the script should return an error and fail.
- The script should automatically generate the correct RC based on the Semver label:
- Major: Bump the major version (e.g., 2.0.0)
- Minor: Bump the minor version (e.g., 1.1.0)
- …

[PLAY-1580] Automatic Release Improvements - Semver Targets Trigger Correct RCs 

---

.github/workflows/github-actions-release-candidate.yml

Reverts powerhome/playbook#3814

Revert "Fix"

---

.github/workflows/github-actions-release-candidate.yml

Reverts powerhome/playbook#3808

Revert "[PLAY-1580] Automatic Release Improvements - Semver Targets Trigger Correct RCs "

---

.github/workflows/github-actions-check-labels.yml
.github/workflows/github-actions-release-candidate.yml

[PLAY-1580](https://runway.powerhrg.com/backlog_items/PLAY-1580)
Adding a Github action that checks for Semver target labels on the Pull Requests. This action will run whenever a label is added to the PR to ensure that a target label is present.

[PLAY-1580-1] Semver Targets Trigger Correct RCs - Label Check Action

---

playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_custom_cell.jsx
playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_custom_cell.md
playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js

Allowing for custom cells in Advanced Table
[Runway Story](https://runway.powerhrg.com/backlog_items/PBNTR-614)
[CSB here](https://codesandbox.io/p/sandbox/advanced-table-custom-cell-gjzxtw)

[PBNTR-614] Custom Cells for Advanced Table

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 14.6.0

---

playbook-website/config/deploy/production/secrets.yaml
playbook-website/config/deploy/prs/secrets.yaml
playbook-website/config/deploy/staging/secrets.yaml

See https://github.com/powerhome/software/pull/896

Update Sentry DSNs

---

playbook/SWIFT_CHANGELOG.md

[PBIOS-602] Swift Changelog Update
1. Go to '...'

[PBIOS-602] Swift Changelog Update

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version bump 14.7.0

---

playbook/CHANGELOG.md

Update CHANGELOG.md 14.7.0

---

.github/workflows/github-actions-release-candidate.yml

Fixing Github Action Errors

---

playbook/app/pb_kits/playbook/pb_card/docs/_card_light.md

Small Change to Test RC Process

---

.github/workflows/github-actions-release-candidate.yml

Fixed Casing

---

playbook/app/pb_kits/playbook/pb_card/docs/_card_light.md

Testing RC Action

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 14.8.0

---

playbook/SWIFT_CHANGELOG.md

Update playbook-swift changelog file.
1. Go to '...'

[PBIOS-601] Update playbook-swift changelog

---

playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.scss

https://runway.powerhrg.com/backlog_items/PLAY-1625
1. Test the alpha in nitro-web: **https://pr44183.nitro-web.beta.px.powerapp.cloud/referral_portal/candidates/employee_referral?mt=Refer+a+Friend**
2. Test the codesandbox here: **https://codesandbox.io/p/sandbox/typeahead-fixes-zgy482**

[PLAY-1625] Fix For PhoneNumberInput CSS Conflict

---

playbook/package.json
yarn.lock

[PLAY-1658](https://runway.powerhrg.com/backlog_items/PLAY-1658)

[PLAY-1658] Dependency update/upgrade-@tanstack/react-table (8.9.2 -> 8.20.5)

---

playbook/package.json
yarn.lock

[PLAY-1598](https://runway.powerhrg.com/backlog_items/PLAY-1598)

[PLAY-1598] Bump @floating-ui/react from 0.22.2 to 0.26.23

---

playbook/SWIFT_CHANGELOG.md

[PBIOS-638] Update SWIFT_CHANGELOG.md to Reflect 6.5.1 Release
1. Go to '...'

[PBIOS-638] Update SWIFT_CHANGELOG.md to Reflect 6.5.1 Release

---

playbook/CHANGELOG.md

[runway story](https://runway.powerhrg.com/backlog_items/PLAY-1771)

Update CHANGELOG.md with design

---

playbook-website/config/menu.yml
playbook/app/pb_kits/playbook/pb_link/_link.scss

Runway https://runway.powerhrg.com/backlog_items/PLAY-1764 
We are making the link kit go live and im updating the visited color to be a darker primary color rather than purple
Check it out here https://pr3997.playbook.beta.hq.powerapp.cloud/kits/link

[PLAY-1764] Make link live kit

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 14.10.0

---

playbook/CHANGELOG.md

CHANGELOG.md for 14.10.0

---

playbook/app/pb_kits/playbook/pb_advanced_table/Components/TableHeaderCell.tsx
playbook/app/pb_kits/playbook/pb_advanced_table/SubKits/TableBody.tsx
playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss
playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.tsx
playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_headers.jsx
playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_headers.md
playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_headers_multiple.jsx
playbook/app/pb_kits/playbook/pb_advanced_table/docs/_advanced_table_column_headers_multiple.md
playbook/app/pb_kits/playbook/pb_advanced_table/docs/example.yml
playbook/app/pb_kits/playbook/pb_advanced_table/docs/index.js

[Runway Story](https://runway.powerhrg.com/backlog_items/PBNTR-767)

[PBNTR-767] Multi Column Headers for Advanced Table

---

playbook/app/pb_kits/playbook/pb_table/_table.tsx
playbook/app/pb_kits/playbook/pb_table/docs/example.yml
playbook/app/pb_kits/playbook/pb_table/docs/index.js

Fixing gaps between sticky right columns
1. Go to '...'

[PBNTR-784] Fixing gaps between sticky right columns

---

playbook/app/pb_kits/playbook/pb_avatar_action_button/_avatar_action_button.scss
playbook/app/pb_kits/playbook/pb_badge/_badge.scss
playbook/app/pb_kits/playbook/pb_bread_crumbs/_bread_crumbs.scss
playbook/app/pb_kits/playbook/pb_button/_button.scss
playbook/app/pb_kits/playbook/pb_circle_icon_button/_circle_icon_button.scss
playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_input_styles.scss
playbook/app/pb_kits/playbook/pb_date_picker/sass_partials/_overrides.scss
playbook/app/pb_kits/playbook/pb_date_range_inline/_date_range_inline.scss
playbook/app/pb_kits/playbook/pb_date_time_stacked/_date_time_stacked.scss
playbook/app/pb_kits/playbook/pb_dropdown/_dropdown.scss
playbook/app/pb_kits/playbook/pb_form_pill/_form_pill.scss
playbook/app/pb_kits/playbook/pb_icon_circle/_icon_circle.scss
playbook/app/pb_kits/playbook/pb_label_value/_label_value.scss
playbook/app/pb_kits/playbook/pb_message/_message_mixins.scss
playbook/app/pb_kits/playbook/pb_multiple_users/_multiple_users.scss
playbook/app/pb_kits/playbook/pb_passphrase/_passphrase.scss
playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.scss
playbook/app/pb_kits/playbook/pb_pill/_pill.scss
playbook/app/pb_kits/playbook/pb_progress_simple/_progress_simple.scss
playbook/app/pb_kits/playbook/pb_rich_text_editor/_rich_text_editor.scss
playbook/app/pb_kits/playbook/pb_select/_select.scss
playbook/app/pb_kits/playbook/pb_selectable_card/_selectable_card.scss
playbook/app/pb_kits/playbook/pb_text_input/_text_input.scss
playbook/app/pb_kits/playbook/pb_textarea/_textarea.scss
playbook/app/pb_kits/playbook/pb_time_range_inline/_time_range_inline.scss
playbook/app/pb_kits/playbook/pb_timeline/_timeline.scss
playbook/app/pb_kits/playbook/pb_toggle/_toggle.scss

Reverts powerhome/playbook#4089

Revert "[PLAY-1776] Update Kits To Remove Deprecation Warning With Division"

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version 14.12.0

---

playbook/SWIFT_CHANGELOG.md

Update swift changelog file with release 6.6.3 
1. Go to '...'

[PBIOS-672] Update swift changelog

---

examples/rails-react-example/app/assets/stylesheets/application.scss
examples/rails-react-example/app/javascript/components/App.tsx
examples/rails-react-example/app/views/pages/index.html.erb

Update examples/playbook-rails-react-example to work better with tech challenges.

Update example app for Tech challenges

---

examples/rails-react-example/Gemfile
examples/rails-react-example/Gemfile.lock
examples/rails-react-example/package.json
examples/rails-react-example/yarn.lock

puts example repo on alpha to allow for use of Free FA icons

Example repo on Alpha for Free Icons to work

---

playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_mask.html.erb
playbook/app/pb_kits/playbook/pb_text_input/index.js
yarn.lock

Runway [PLAY-1866](https://runway.powerhrg.com/backlog_items/PLAY-1866)
Alpha https://github.com/powerhome/nitro-web/pull/45790
The input mask isn't working in Nitro because Nitro wasn't expecting the JS module to be the new pattern Mark made in
I changed it to use our PbEnhancedElement kit

[PLAY-1866] Mask Use PBenahcnedElement

---

playbook/app/pb_kits/playbook/pb_advanced_table/_advanced_table.scss

[Runway Story](https://runway.powerhrg.com/backlog_items/PBNTR-856)
Make the Action Bar responsive
https://github.com/user-attachments/assets/01ae2ce1-ee93-4371-93dc-185e39884d90

[PBNTR-856] Selectable Rows Action Bar Responsive

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json
yarn.lock

Version Bump 14.13.0

---

playbook/CHANGELOG.md

Update CHANGELOG.md 14.13.0

---

playbook/app/pb_kits/playbook/pb_table/docs/_table_with_selectable_rows.html.erb
playbook/app/pb_kits/playbook/pb_table/docs/_table_with_selectable_rows.jsx
playbook/app/pb_kits/playbook/pb_table/docs/_table_with_selectable_rows.md
playbook/app/pb_kits/playbook/pb_table/docs/example.yml
playbook/app/pb_kits/playbook/pb_table/docs/index.js

Adding Table Selectable Rows doc example
1. Go to '...'

[PBNTR-847] Adding Table Selectable Rows doc example

---

playbook-website/package.json
playbook/app/pb_kits/playbook/pb_checkbox/_checkbox.tsx
playbook/app/pb_kits/playbook/pb_checkbox/checkbox.test.js
playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_react_hook.jsx
playbook/app/pb_kits/playbook/pb_checkbox/docs/_checkbox_react_hook.md
playbook/app/pb_kits/playbook/pb_checkbox/docs/example.yml
playbook/app/pb_kits/playbook/pb_checkbox/docs/index.js
yarn.lock

There were unverified commits in https://github.com/powerhome/playbook/pull/4262

[PLAY-1851] checkbox react hook squash

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 14.14.0

---

playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb
playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
playbook/lib/playbook/forms/builder.rb
playbook/lib/playbook/forms/builder/time_zone_select_field.rb

Adding Form Time Zone Select field
1. Go to '...'

[PBNTR-457] Adding Form Time Zone Select field

---

playbook-website/app/javascript/components/PbKitPlayground/index.tsx

[Story](https://runway.powerhrg.com/backlog_items/PLAY-1875)
This PR changes the cursor/caret in the code editor from a dark color to white. This helps devs see the cursor position more easily leading to a pleasant Playground experience.
1. Go to '...'

[PLAY-1875] Playgound Editor Enhancements 

---

playbook/CHANGELOG.md

Update CHANGELOG.md 14.14.0

---

playbook-website/app/controllers/guides_controller.rb
playbook-website/app/views/guides/global_props.html.md
playbook-website/app/views/guides/global_props/test.md
playbook-website/app/views/guides/tokens.html.md
playbook-website/app/views/guides/tokens/test.md
playbook-website/app/views/layouts/global_props.html.erb

[Story](https://runway.powerhrg.com/backlog_items/PLAY-1843)
This PR sets up the index pages for the new Global Props & Tokens guides that will be on the playbook website.
1. Go to '...'

[PLAY-1843] Global Props & Tokens Index Page

---

playbook/app/pb_kits/playbook/pb_typeahead/_typeahead.tsx
playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_dynamic_options.html.erb
playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_dynamic_options.md
playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_dynamic_options_pure_rails.html.erb
playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_dynamic_options_pure_rails.md
playbook/app/pb_kits/playbook/pb_typeahead/docs/example.yml
playbook/app/pb_kits/playbook/pb_typeahead/index.ts
playbook/app/pb_kits/playbook/pb_typeahead/typeahead.rb

[Runway Story](https://runway.powerhrg.com/backlog_items/PBNTR-890)
This PR:
- Allows for the linking of a rails typeahead (pure rails AND react rendered) to a select to render options dynamically baed on changes in the select selection
https://github.com/user-attachments/assets/2b5d5973-ba22-45e8-a950-d19984d5145f

[PBNTR-890] Typeahead Rails: Dynamic Options

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 14.15.0

---

playbook/CHANGELOG.md

Add CHANGELOG for 14.15.0

---

playbook-website/app/javascript/entrypoints/sample-show.js
playbook-website/app/javascript/site_styles/_samples_show.scss
playbook-website/app/views/samples/news_magazine/index.html.erb
playbook-website/app/views/samples/show.html.erb
playbook-website/app/views/samples/trending_repositories/index.html.erb

[Story](https://runway.powerhrg.com/backlog_items/PLAY-1940)
In this PR we change our "Show Code" logic that way when a user clicks the "Show Code" button we replace the sample with the code and make sure to maintain the view height of the window.
1. Go to '...'

[PLAY-1940] Improve Sample Show Code

---

playbook/app/pb_kits/playbook/pb_draggable/docs/_draggable_default.jsx

Quick fix for error occurring in Draggable document examples.

Fix for Image error in Draggable doc examples

---

playbook/app/pb_kits/playbook/pb_nav/_nav.scss

This makes all nav items have the cursor hover state of pointer even if the link prop isn't set.
[PLAY-1952](https://runway.powerhrg.com/backlog_items/PLAY-1952)
[Review ENV](https://pr4406.playbook.beta.px.powerapp.cloud/kits/nav/react)
https://github.com/user-attachments/assets/8e0e986a-9ec4-4aa9-9b9e-81765dd99901

[PLAY-1952] Nav Kit: Set Default Cursor to Pointer for All Nav Items

---

playbook/app/entrypoints/playbook-rails.js
playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with.html.erb
playbook/app/pb_kits/playbook/pb_form/docs/_form_form_with_validate.html.erb
playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.scss
playbook/app/pb_kits/playbook/pb_multi_level_select/_multi_level_select.tsx
playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_error.html.erb
playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_error.jsx
playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_label.html.erb
playbook/app/pb_kits/playbook/pb_multi_level_select/docs/_multi_level_select_label.jsx
playbook/app/pb_kits/playbook/pb_multi_level_select/docs/example.yml
playbook/app/pb_kits/playbook/pb_multi_level_select/docs/index.js
playbook/app/pb_kits/playbook/pb_multi_level_select/index.js
playbook/app/pb_kits/playbook/pb_multi_level_select/multi_level_select.rb
playbook/lib/playbook/forms/builder/multi_level_select_field.rb

[Runway Story](https://runway.powerhrg.com/backlog_items/PBNTR-910)
This PR:
- ✅ Adds the error prop for the MLS for react and rails
- ✅ Adds required for the rails side for validation

[PBNTR-910] Implementing required Multi Leve Select kit for Forms

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 14.16.0

---

playbook/app/pb_kits/playbook/pb_form_group/_form_group.scss

This fixes the the right border of the errored input that wasn't showing up.
[PLAY-1958](https://runway.powerhrg.com/backlog_items/PLAY-1958)
[Nitro Alpha](https://pr47319.nitro-web.beta.px.powerapp.cloud/referral_portal/candidates/employee_referral)
[CSB](https://codesandbox.io/p/sandbox/dank-voice-fg3gm9)

[PLAY-1958] Form Group Kit: Fix Error Border Styles

---

playbook/CHANGELOG.md

Update CHANGELOG.md 14.17.0

---

playbook/app/javascript/theme.js
playbook/app/pb_kits/playbook/pb_copy_button/_copy_button.tsx
playbook/app/pb_kits/playbook/pb_copy_button/docs/_copy_button_hook.jsx
playbook/app/pb_kits/playbook/pb_copy_button/docs/_copy_button_hook.md
playbook/app/pb_kits/playbook/pb_copy_button/docs/example.yml
playbook/app/pb_kits/playbook/pb_copy_button/docs/index.js
playbook/app/pb_kits/playbook/pb_copy_button/usePBCopy.ts

Runway https://runway.powerhrg.com/backlog_items/PLAY-1889
Adds a hook for the copy javascript from our copy button kit
kinda like how we expose the collapsible logic for the collapsible kit
You can check it out here https://pr4515.playbook.beta.gm.powerapp.cloud/kits/copy_button/react#copy-hook

[PLAY-1889] Add hook and doc example

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 14.18.0

---

playbook/CHANGELOG.md

Update CHANGELOG.md for 14.18.0

---

playbook/app/pb_kits/playbook/pb_date_picker/docs/_date_picker_error.html.erb
playbook/app/pb_kits/playbook/pb_dropdown/docs/_dropdown_error.html.erb
playbook/app/pb_kits/playbook/pb_phone_number_input/docs/_phone_number_input_validation.html.erb
playbook/app/pb_kits/playbook/pb_select/docs/_select_error.html.erb
playbook/app/pb_kits/playbook/pb_text_input/docs/_text_input_error.html.erb
playbook/app/pb_kits/playbook/pb_textarea/docs/_textarea_error.html.erb
playbook/app/pb_kits/playbook/pb_typeahead/docs/_typeahead_error_state.html.erb

[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2044)
1. Go to '...'

[PLAY-2044] Add "triangle-exclamation" icon to Error State docs - Rails

---

playbook/package.json
yarn.lock

[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-1902)
Dependency update:
Updating @types/react-highlight-words from 0.16.5 to 0.20.0

[PLAY-1902] Dependency update/upgrade: @types/react-highlight-words

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version bump 14.19.0

---

playbook/CHANGELOG.md

Update CHANGELOG.md 14.19.0

---

playbook-website/Gemfile
playbook-website/Gemfile.lock

[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2093)
Upgrades Puma dependency for playbook-website

[PLAY-2093] Playbook Website: upgrade Puma dependency

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump 14.20.0

---

playbook/CHANGELOG.md

Update CHANGELOG.md 14.20.0

---

playbook/app/pb_kits/playbook/pb_draggable/context/index.tsx

[PLAY-2211](https://runway.powerhrg.com/backlog_items/PLAY-2211)
Revert [PBNTR-933](https://runway.powerhrg.com/backlog_items/PBNTR-933) for Tempo.

[PLAY-2211] Draggable Kit: Fixes bug for cross container drag between 2 tables

---

playbook/CHANGELOG.md

Update CHANGELOG.md 14.21.0

---

playbook/CHANGELOG.md

Update CHANGELOG.md with patch

---

playbook/app/pb_kits/playbook/pb_section_separator/docs/_description.md

[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-1996)
1. Go to '...'

[PLAY-1966] Section Separator kit: Add Documentation for Width Requirement

---

playbook-website/app/views/patterns/custom_user_display/index.html.erb

Fix spelling

---

playbook-website/app/javascript/components/HomepageHero/Pages/SmallScreen.tsx
playbook-website/app/javascript/components/HomepageHero/Pages/Welcome.tsx
playbook-website/app/javascript/components/HomepageHero/index.tsx

[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2227)
1. Go to '...'

[PLAY-2227] Playbook Website: Homepage isn't displaying correctly on Chrome

---

playbook-website/package.json
playbook/app/pb_kits/playbook/pb_contact/contact.test.js
playbook/app/pb_kits/playbook/pb_filter/filter.test.js
yarn.lock

Runway https://runway.powerhrg.com/backlog_items/PLAY-2179
Icons update https://github.com/powerhome/playbook-icons/pull/42
New icons are added to playbook icons this is a version bump 
1. Go to '...'

[PLAY-2179] Update playbook icons

---

playbook/app/pb_kits/playbook/pb_table/_table.tsx
playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_columns.jsx
playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_columns_react.md
playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_left_columns.jsx
playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_left_columns_react.md
playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_right_columns.jsx
playbook/app/pb_kits/playbook/pb_table/docs/_table_sticky_right_columns_react.md

Reverts powerhome/playbook#4804

Revert "Revert "[PLAY-2256] Table kit: sticky_left_column and sticky_right_column depends on id attribute - React Only""

---

playbook/app/pb_kits/playbook/pb_phone_number_input/_phone_number_input.tsx

[PLAY-2132](https://runway.powerhrg.com/backlog_items/PLAY-2132) adds a "hasTyped" check within the Phone Number Input kits validationErrors checks so that interacting with the input by clicking into focus and clicking away or interacting with the country selection dropdown does NOT trigger validation/errors before a user actually types in the input. A few additional changes have been added to address typescript errors that popped up with the addition of the hasTyped check.
No validation after selecting a country from the dropdown and focus has moved from input
Validation appears once type in input (after click away that removes focus from …

[PLAY-2132] Phone Number Input kit: If selecting a country prior to entering a phone number, the "too short" validation appears

---

playbook-website/app/controllers/patterns_controller.rb
playbook-website/app/javascript/entrypoints/patterns.js
playbook-website/app/views/patterns/table_filter_card/index.html.erb
playbook-website/app/views/patterns/table_filter_card/index.jsx
playbook-website/config/patterns.yml

[PLAY-2166](https://runway.powerhrg.com/backlog_items/PLAY-2166) adds a new Pattern to our Patterns section. The "Table Filter Card" pattern contains the common Filter + Section Separator + Card inside a Card / Flex with responsive props - this is a common pattern all throughout Nitro including in our template pages.
Includes responsive Title (commit 1 included pagination bars but this required extra setup and code to work so removed - veering into template territory).
1. Go to the Patterns homepage ([../patterns](https://pr4936.playbook.beta.px.powerapp.cloud/patterns/)) in the review …

[PLAY-2166] Patterns: Filter + SectionSeparator + Table inside Card/Flex

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump to 14.24.0

---

playbook/CHANGELOG.md

Update CHANGELOG.md for 14.24.0

---

playbook/package.json
yarn.lock

Removes FA free from playbook-ui

[PLAY-2374] Remove Fontawesome Free from Playbook

---

playbook-website/Gemfile.lock
playbook/Gemfile.lock
playbook/lib/playbook/version.rb
playbook/package.json

Version Bump to 14.25.0

---

playbook-website/app/controllers/pages_controller.rb
playbook-website/app/javascript/components/MainSidebar/NavComponents/KitsNavComponent.tsx
playbook-website/app/javascript/components/MainSidebar/NavComponents/OtherNavComponent.tsx
playbook-website/app/javascript/components/MainSidebar/TopLevelNavItems.tsx
playbook-website/app/javascript/components/MainSidebar/index.tsx
playbook-website/app/javascript/components/Website/index.tsx
playbook-website/app/javascript/components/Website/src/components/KitCard/index.tsx
playbook-website/app/javascript/components/Website/src/components/LiveExamples/LiveExampleReact.tsx
playbook-website/app/javascript/components/Website/src/components/LiveExamples/ThirdPartyLoaders/highchartsLoader.tsx
playbook-website/app/javascript/components/Website/src/components/LiveExamples/ThirdPartyLoaders/index.ts
playbook-website/app/javascript/components/Website/src/components/LiveExamples/ThirdPartyLoaders/maplibreLoader.tsx
playbook-website/app/javascript/components/Website/src/components/LiveExamples/ThirdPartyLoaders/tiptapLoader.tsx
playbook-website/app/javascript/components/Website/src/components/LiveExamples/ThirdPartyLoaders/utilities.ts
playbook-website/app/javascript/components/Website/src/components/PageContainer/index.tsx
playbook-website/app/javascript/components/Website/src/layouts/LayoutRight.tsx
playbook-website/app/javascript/components/Website/src/pages/CategoryShow/index.tsx
playbook-website/app/javascript/components/Website/src/pages/CategoryShow/styles.scss
playbook-website/app/javascript/components/Website/src/pages/ComponentList.tsx
playbook-website/app/javascript/components/Website/src/pages/KitShow/index.tsx
playbook-website/app/javascript/components/app.tsx
playbook-website/app/javascript/site_styles/main.scss
playbook-website/app/javascript/site_styles/website_new.scss
playbook-website/app/views/layouts/application_beta.html.erb
playbook-website/config/routes.rb
playbook-website/package.json
yarn.lock

[Runway Story](https://runway.powerhrg.com/backlog_items/PLAY-2415)
[Gist](https://gist.github.com/nidaqg/44343d4017e9d15509d8c20e1e597857)
- The spike is shippable after we test to make sure legacy view is not broken in any way
- Go to https://pr5100.playbook.beta.px.powerapp.cloud/beta/kits to see beta view
- I've created a beta prop for the sidebar so it renders the beta routes when on the beta pages, so you can see that the sidebar stays on the page when you navigate. 
- The 'active' state etc is not set up yet and routes for anything outside of 'components' will give 404 since those pages do not exist on the beta route yet. 
- The kit show and category show pages are accurate, we just need to get …

[PLAY-2415] Playbook Website: Set up scaffold for React Views
